### ISSUE TITLE
bug: frontend panic when querying pg internal tables

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#10026]
### Describe the bug

Frontend panic

### To Reproduce

```
create table t (id bigint, name varchar);

SELECT n.nspname,c.relname,a.attname,a.atttypid,a.attnotnull OR (t.typtype = 'd' AND t.typnotnull) AS attnotnull,a.atttypmod,a.attlen,t.typtypmod,a.attnum,null as attidentity,null as attgenerated,pg_catalog.pg_get_expr(def.adbin, def.adrelid) AS adsrc,dsc.description,t.typbasetype,t.typtype  FROM pg_catalog.pg_namespace n  JOIN pg_catalog.pg_class c ON (c.relnamespace = n.oid)  JOIN pg_catalog.pg_attribute a ON (a.attrelid=c.oid)  JOIN pg_catalog.pg_type t ON (a.atttypid = t.oid)  LEFT JOIN pg_catalog.pg_attrdef def ON (a.attrelid=def.adrelid AND a.attnum = def.adnum)  LEFT JOIN pg_catalog.pg_description dsc ON (c.oid=dsc.objoid AND a.attnum = dsc.objsubid)  LEFT JOIN pg_catalog.pg_class dc ON (dc.oid=dsc.classoid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dc.relnamespace=dn.oid AND dn.nspname='pg_catalog')  WHERE c.relkind in ('r','p','v','f','m') and a.attnum > 0 AND NOT a.attisdropped  AND n.nspname LIKE 'public' AND c.relname LIKE 't' ORDER BY nspname,c.relname,attnum;
```

### Expected behavior

Not panic.

### Additional context

Raised from trino postgresql client test.

Logs:
```
thread 'risingwave-main' panicked at 'index out of bounds: the len is 7 but the index is 7', /Users/william/repo/risingwave/src/common/src/row/owned_row.rs:108:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panicking.rs:162:5
   3: <risingwave_common::row::owned_row::OwnedRow as core::ops::index::Index<usize>>::index
             at ./src/common/src/row/owned_row.rs:35:10
   4: <risingwave_common::row::owned_row::OwnedRow as risingwave_common::row::Row>::datum_at
             at ./src/common/src/row/owned_row.rs:108:9
   5: risingwave_batch::executor::sys_row_seq_scan::SysRowSeqScanExecutor::do_executor::{{closure}}::{{closure}}::{{closure}}
             at ./src/batch/src/executor/sys_row_seq_scan.rs:117:38
   6: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:84:28
   7: core::iter::traits::iterator::Iterator::fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:2481:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:124:9
   9: core::iter::traits::iterator::Iterator::for_each
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:856:9
  10: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/mod.rs:2844:17
  11: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_extend.rs:26:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_from_iter.rs:33:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/mod.rs:2712:9
  15: core::iter::traits::iterator::Iterator::collect
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:1895:9
  16: itertools::Itertools::collect_vec
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:9
  17: risingwave_batch::executor::sys_row_seq_scan::SysRowSeqScanExecutor::do_executor::{{closure}}::{{closure}}
             at ./src/batch/src/executor/sys_row_seq_scan.rs:114:30
  18: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:84:28
  19: core::iter::traits::iterator::Iterator::fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:2481:21
  20: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:124:9
  21: core::iter::traits::iterator::Iterator::for_each
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:856:9
  22: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/mod.rs:2844:17
  23: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_extend.rs:26:9
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/spec_from_iter.rs:33:9
  26: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/mod.rs:2712:9
  27: core::iter::traits::iterator::Iterator::collect
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:1895:9
  28: itertools::Itertools::collect_vec
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:9
  29: risingwave_batch::executor::sys_row_seq_scan::SysRowSeqScanExecutor::do_executor::{{closure}}
             at ./src/batch/src/executor/sys_row_seq_scan.rs:111:29
  30: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  31: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  32: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  33: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  34: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.4.1/src/future.rs:118:19
  35: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  36: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  37: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:73:17
  38: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  39: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  40: risingwave_batch::executor::filter::FilterExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/filter.rs:53:5
  41: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  43: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  44: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  45: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.4.1/src/future.rs:118:19
  46: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  47: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  48: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:73:17
  49: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  50: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  51: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
  52: <futures_util::stream::stream::fuse::Fuse<S> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/fuse.rs:53:27
  53: <futures_util::stream::stream::buffered::Buffered<St> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/buffered.rs:66:19
  54: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  55: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  56: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  57: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.4.1/src/future.rs:118:19
  58: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  59: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  60: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:73:17
  61: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  62: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  63: risingwave_batch::executor::join::hash_join::HashJoinExecutor<K>::do_execute::{{closure}}
             at ./src/batch/src/executor/join/hash_join.rs:223:5
  64: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  65: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  66: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  67: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  68: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.4.1/src/future.rs:118:19
  69: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  70: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  71: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:73:17
  72: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  73: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  74: risingwave_batch::executor::join::hash_join::HashJoinExecutor<K>::do_inner_join::{{closure}}
             at ./src/batch/src/executor/join/hash_join.rs:326:5
  75: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  76: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  77: risingwave_batch::executor::join::hash_join::HashJoinExecutor<K>::do_execute::{{closure}}
             at ./src/batch/src/executor/join/hash_join.rs:223:5
  78: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  79: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  80: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  81: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  82: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.4.1/src/future.rs:118:19
  83: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  84: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  85: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:73:17
  86: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  87: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/william/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by TennyZhuang** [comment]
Minimal reproduce:

```sql
create table t (id bigint, name varchar);
select "atttypmod" from pg_attribute;
```
