### ISSUE TITLE
panic "entered unreachable code: Parameter should not appear here" when running a query with parameter

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#10062]
### Describe the bug

```
thread 'risingwave-main' panicked at 'internal error: entered unreachable code: Parameter should not appear here. It will be replaced by a literal before this step.', src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs:46:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panicking.rs:67:14
   2: <risingwave_frontend::optimizer::plan_expr_rewriter::const_eval_rewriter::ConstEvalRewriter as risingwave_frontend::expr::expr_rewriter::ExprRewriter>::rewrite_expr
             at ./src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs:46:43
   3: risingwave_frontend::expr::expr_rewriter::ExprRewriter::rewrite_function_call::{{closure}}
             at ./src/frontend/src/expr/expr_rewriter.rs:44:25
   4: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:91:28
   5: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:2303:21
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:117:9
   7: <I as alloc::vec::in_place_collect::SpecInPlaceCollect<T,I>>::collect_in_place
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/in_place_collect.rs:258:13
   8: alloc::vec::in_place_collect::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/in_place_collect.rs:182:28
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/vec/mod.rs:2712:9
  10: core::iter::traits::iterator::Iterator::collect
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:1895:9
  11: risingwave_frontend::expr::expr_rewriter::ExprRewriter::rewrite_function_call
             at ./src/frontend/src/expr/expr_rewriter.rs:42:22
  12: <risingwave_frontend::optimizer::plan_expr_rewriter::const_eval_rewriter::ConstEvalRewriter as risingwave_frontend::expr::expr_rewriter::ExprRewriter>::rewrite_expr
             at ./src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs:39:50
  13: risingwave_frontend::utils::condition::Condition::rewrite_expr::{{closure}}
             at ./src/frontend/src/utils/condition.rs:837:29
  14: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/adapters/map.rs:91:28
  15: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/iter/traits/iterator.rs:2303:21
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
```

### To Reproduce

1. risedev d full
2. run the following SQL:
```
SELECT c.oid,c.*,t.relname as tabrelname,rt.relnamespace as refnamespace,d.description, null as consrc_copy
FROM pg_catalog.pg_constraint c
INNER JOIN pg_catalog.pg_class t ON t.oid=c.conrelid
LEFT OUTER JOIN pg_catalog.pg_class rt ON rt.oid=c.confrelid
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0 AND d.classoid='pg_constraint'::regclass
WHERE c.conrelid=$1
ORDER BY c.oid;
```

### Expected behavior

Should be an error instead of a panic

**Comment by TennyZhuang** [comment]
What's $1 in your SQL?

**Comment by hzxa21** [comment]
> What's $1 in your SQL?

It is literally $1. This is not a prepared statement or a valid parameterized SQL. We should throw an error instead of panic.

**Comment by BugenZhao** [comment]
Simply `select $1` will also panic the frontend. I often use this query to immediately trigger a panic in the cluster. 😄

**Comment by BugenZhao** [comment]
The parameter seems to be meaningful only after we support prepared statements in simple query mode. #21777
