### ISSUE TITLE
JDBC sink: multiple sink to the same destination table could result in deadlock

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#10117]
### Describe the bug

Currently, we can create multiple sinks to the same destination table, which could result in deadlocks in the downstream database.

```
2023-06-01 15:33:54,088 ERROR [grpc-default-executor-2] connector.SinkStreamObserver:175 - sink task error:
java.lang.RuntimeException: io.grpc.StatusRuntimeException: INTERNAL: Error when exec 40001, message Lock wait timeout exceeded; try restarting transaction
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:320) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:130) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:33) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.49.0.jar:1.49.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Error when exec 40001, message Lock wait timeout exceeded; try restarting transaction
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.49.0.jar:1.49.0]
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:312) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        ... 11 more
2023-06-01 15:33:54,088 ERROR [grpc-default-executor-7] connector.SinkStreamObserver:175 - sink task error:
java.lang.RuntimeException: io.grpc.StatusRuntimeException: INTERNAL: Error when exec 40001, message Lock wait timeout exceeded; try restarting transaction
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:320) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:130) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:33) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [grpc-stub-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.49.0.jar:1.49.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [grpc-core-1.49.0.jar:1.49.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?

```

### To Reproduce

```
statement ok
CREATE TABLE IF NOT EXISTS rw_types (
    id BIGINT PRIMARY KEY,
    varchar_column VARCHAR,
    text_column TEXT,
    integer_column INTEGER,
    smallint_column SMALLINT,
    bigint_column BIGINT,
    decimal_column DECIMAL,
    real_column REAL,
    double_column DOUBLE PRECISION,
    boolean_column BOOLEAN,
    date_column DATE,
    time_column TIME,
    timestamp_column TIMESTAMP,
    interval_column INTERVAL,
    jsonb_column JSONB,
    array_column VARCHAR[],
    array_column2 FLOAT[]
);

statement ok
CREATE SINK IF NOT EXISTS s2_postgres FROM rw_types WITH (
    connector='jdbc',
    jdbc.url='jdbc:postgresql://localhost:8432/mydb?user=myuser&password=123456',
    table.name='t_types',
    type='upsert'
);

statement ok
CREATE SINK IF NOT EXISTS s2_mysql FROM rw_types WITH (
    connector='jdbc',
    jdbc.url='jdbc:mysql://localhost:8306/mydb?user=root&password=123456',
    table.name='t_types',
    type='upsert'
);

statement ok
CREATE SINK IF NOT EXISTS s3_mysql FROM rw_types WITH (
    connector='jdbc',
    jdbc.url='jdbc:mysql://localhost:8306/mydb?user=root&password=123456',
    table.name='t_types',
    type='upsert'
);

statement ok
CREATE SINK IF NOT EXISTS s3_postgres FROM rw_types WITH (
    connector='jdbc',
    jdbc.url='jdbc:postgresql://localhost:8432/mydb?user=myuser&password=123456',
    table.name='t_types',
    type='upsert'
);

statement ok
INSERT INTO rw_types (id, varchar_column, text_column, integer_column, smallint_column, bigint_column, decimal_column, real_column, double_column, boolean_column, date_column, time_column, timestamp_column, interval_column, jsonb_column, array_column, array_column2) VALUES
    (1, 'Varcharvalue1', 'Textvalue1', 123, 456, 789, 12.34, 56.78, 90.12, TRUE, '2023-05-22', '12:34:56', '2023-05-22 12:34:56', '1 day', '{"key": "value"}', ARRAY['Value 1', 'Value 2'], '{12.345,56.789}'),
    (2, 'Varcharvalue2', 'Textvalue2', 234, 567, 890, 23.45, 67.89, 01.23, FALSE, '2023-05-23', '23:45:01', '2023-05-23 23:45:01', '2 days', '{"key": "value2"}', ARRAY['Value 3', 'Value 4'], '{43.21,65.432}');
```

### Expected behavior

Report error when there exists a Sink to the same destination table.

**Comment by StrikeW** [comment]
cc @wenym1

**Comment by tabVersion** [comment]
Do you think we gonna do a check to prevent multiple sink to the same table? eg distinct on `(host, port, database, table_name)`

**Comment by StrikeW** [comment]
> Do you think we gonna do a check to prevent multiple sink to the same table? eg distinct on `(host, port, database, table_name)`

Yes. For better user experience

**Comment by yezizp2012** [comment]
I think you can add a validation for `create_sink` in meta like what we did for other duplicate check, i.e.:
```rust
    pub fn check_sink_target_duplicated(&self, sink: &Sink) -> MetaResult<()> {
        if self.sinks.values().any(|x| {
            todo!("check target: (host, port, database, table_name)")
        }) {
            Err(MetaError::catalog_duplicated("sink target", &sink.name))
        } else {
            Ok(())
        }
    }
```

**Comment by fuyufjh** [comment]
-1. I don't think RisingWave should do such checks.

Can you please take a look on Flink? If they don't have such thing, neither for us.

**Comment by StrikeW** [comment]
>Furthermore, you can hardly prevent this at all. User can create a view on table and insert into the view, for example.

I don't get this point. IMO we only need to check if the sink destination is duplicated to prevent multiple writer for a pk. No matter the sink source is a table or a view.

>Can you please take a look on Flink? If they don't have such thing, neither for us.

Will check it.

**Comment by fuyufjh** [comment]
> IMO we only need to check if the sink destination is duplicated to prevent multiple writer for a pk. No matter the sink source is a table or a view.

I mean, you can actually do this in Postgres:

```
test=# create table t1 (k int, v int, primary key (k));
CREATE TABLE
test=# create view v1 as select * from t1 where k < 50;
CREATE VIEW
test=# insert into v1 values (20, 20);
INSERT 0 1
```

I just want to examplify that "you can hardly prevent this at all, so don't do it"

**Comment by StrikeW** [comment]
Got it. Only doing the check on the RW side cannot ensure there are no multiple writers.

**Comment by StrikeW** [comment]
Flink doesn't do this check. It can create multiple tables sink to the same downstream table.
