### ISSUE TITLE
bug(connector): CDC tables block Meta node from starting up when new column was added to external table  

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10159]
### Describe the bug

CDC tables block Meta node from starting up when new column was added to external table.

### To Reproduce

In Postgres:

```
test=# CREATE TABLE shipments (
   shipment_id integer,
   order_id integer,
   origin varchar,
   destination varchar,
   is_arrived boolean,
   PRIMARY KEY (shipment_id)
);
CREATE TABLE
```

In RisingWave:

```
dev=> CREATE TABLE shipments (
   shipment_id integer,
   order_id integer,
   origin string,
   destination string,
   is_arrived boolean,
   PRIMARY KEY (shipment_id)
) WITH (
connector = 'postgres-cdc',
hostname = '127.0.0.1',
port = '5432',
username = 'eric',
password = '',
database.name = 'test',
schema.name = 'public',
table.name = 'shipments',
slot.name = 'shipments'
);
CREATE_TABLE
```

In Postgres:

```
test=# alter table shipments add column new_col_1 varchar;
ALTER TABLE
```

Restart RisingWave:

```
thread 'risingwave-main' panicked at 'called `Result::unwrap()` on an `Err` value: source cannot pass validation: INVALID_ARGUMENT: The number of columns mismatch
```

<details>
  <summary>Backtrace</summary>
  
```
  backtrace of `MetaError`:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/backtrace.rs:332:13
   3: <risingwave_meta::error::MetaError as core::convert::From<risingwave_meta::error::MetaErrorInner>>::from
             at ./src/meta/src/error.rs:78:33
   4: <T as core::convert::Into<U>>::into
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/convert/mod.rs:717:9
   5: <risingwave_meta::error::MetaError as core::convert::From<anyhow::Error>>::from
             at ./src/meta/src/error.rs:171:9
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/result.rs:1961:27
   7: risingwave_meta::stream::source_manager::ConnectorSourceWorker::create::{{closure}}
             at ./src/meta/src/stream/source_manager.rs:96:26
   8: risingwave_meta::stream::source_manager::SourceManager<S>::create_source_worker::{{closure}}
             at ./src/meta/src/stream/source_manager.rs:701:10
   9: risingwave_meta::stream::source_manager::SourceManager<S>::new::{{closure}}
             at ./src/meta/src/stream/source_manager.rs:517:18
  10: risingwave_meta::rpc::server::start_service_as_election_leader::{{closure}}
             at ./src/meta/src/rpc/server.rs:415:10
  11: risingwave_meta::rpc::server::rpc_serve_with_store::{{closure}}::{{closure}}
             at ./src/meta/src/rpc/server.rs:271:10
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/future/future.rs:125:9
  13: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  14: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  15: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  16: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  17: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panic/unwind_safe.rs:271:9
  19: std::panicking::try::do_call
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:485:40
  20: ___rust_try
  21: std::panicking::try
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:449:19
  22: std::panic::catch_unwind
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panic.rs:142:14
  23: tokio::runtime::task::harness::poll_future
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  24: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  25: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  26: tokio::runtime::task::raw::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  27: tokio::runtime::task::raw::RawTask::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  28: tokio::runtime::task::LocalNotified<S>::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  30: tokio::runtime::coop::with_budget
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  31: tokio::runtime::coop::budget
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  33: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  34: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  37: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
  39: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  40: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  42: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:485:40
  46: ___rust_try
  47: std::panicking::try
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:449:19
  48: std::panic::catch_unwind
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panic.rs:142:14
  49: tokio::runtime::task::harness::poll_future
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  51: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  52: tokio::runtime::task::raw::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  53: tokio::runtime::task::raw::RawTask::poll
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  54: tokio::runtime::task::UnownedTask<S>::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
  55: tokio::runtime::blocking::pool::Task::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
  56: tokio::runtime::blocking::pool::Inner::run
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
  57: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/eric/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
  58: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/sys_common/backtrace.rs:135:18
  59: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/thread/mod.rs:529:17
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panic/unwind_safe.rs:271:9
  61: std::panicking::try::do_call
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:485:40
  62: ___rust_try
  63: std::panicking::try
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:449:19
  64: std::panic::catch_unwind
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panic.rs:142:14
  65: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/thread/mod.rs:528:30
  66: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/ops/function.rs:250:5
  67: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/boxed.rs:1985:9
  68: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/alloc/src/boxed.rs:1985:9
  69: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/sys/unix/thread.rs:108:17
  70: __pthread_deallocate

```

</details>

### Expected behavior

The Meta node should starts and the connector should continue to consume the data although missing the new column.

**Comment by fuyufjh** [comment]
> Currently, the connector node will check if source schema is the same as the upstream schema exactly.

Yeah. I am considering allowing the definition to cover a subset of source columns, for example: given source columns `a,b,c`, allow users to define only `a,b` in RisingWave.

What do you think? @StrikeW @tabVersion

**Comment by tabVersion** [comment]
> > Currently, the connector node will check if source schema is the same as the upstream schema exactly.
> 
> Yeah. I am considering allowing the definition to cover a subset of source columns, for example: given source columns `a,b,c`, allow users to define only `a,b` in RisingWave.
> 
> What do you think? @StrikeW @tabVersion

+1. But the user-defined columns must contains all downstream pks

**Comment by StrikeW** [comment]
I think it is ok and pk columns must be covered.

**Comment by StrikeW** [comment]
> Yeah. I am considering allowing the definition to cover a subset of source columns, for example: given source columns a,b,c, allow users to define only a,b in RisingWave.

BTW if we allow creating a table with a subset of columns, then we need to consider allowing alter the table with unsubscribed columns. For example alter from (a,b) to (a,b,c) in your case. https://github.com/risingwavelabs/risingwave/issues/9966
