### ISSUE TITLE
 pipeline.ChangeEventSourceCoordinator:113 - Change event source executor was interrupted

### ISSUE THREAD

**Issue by findpather** [risingwavelabs/risingwave#10154]
### Describe the bug

2023-06-05 00:50:34,424 WARN  [debezium-mysqlconnector-RW_CDC_mdpipub.submission_manuscript_academic_editors-change-event-source-coordinator] source.AbstractSnapshotChangeEventSource:80 - Snapshot was interrupted before completion
2023-06-05 00:50:34,424 INFO  [debezium-mysqlconnector-RW_CDC_mdpipub.submission_manuscript_academic_editors-change-event-source-coordinator] source.AbstractSnapshotChangeEventSource:88 - Snapshot - Final stage
2023-06-05 00:50:34,425 WARN  [debezium-mysqlconnector-RW_CDC_mdpipub.submission_manuscript_academic_editors-change-event-source-coordinator] pipeline.ChangeEventSourceCoordinator:113 - Change event source executor was interrupted
java.lang.InterruptedException: Interrupted while reading structure of schema [amazon, books, encyclopedia, jams-ucl, logs, mailsdb, mdpiapi, mdpicn, mdpicn_staging, mdpiconv, mdpipub, mrs, mrs3.0, new_books, new_encyclopedia, oai2, reviewers, scifo, sciforum, sciforum_demo, sciforum_demo_mdpipub, sciprints, sciprofile, scipub, susy_saas_books, wordpress, wsforum]
        at io.debezium.connector.mysql.MySqlSnapshotChangeEventSource.readTableStructure(MySqlSnapshotChangeEventSource.java:346) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.connector.mysql.MySqlSnapshotChangeEventSource.readTableStructure(MySqlSnapshotChangeEventSource.java:46) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:116) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

### To Reproduce

mysql-cdc mode, data synchronization error, can not see the problem.

**Comment by StrikeW** [comment]
Hi @findpather, could you please provide your `CREATE TABLE` SQL and the log file of the connector node and compute node?

**Comment by StrikeW** [comment]
> Hi @findpather, could you please provide your `CREATE TABLE` SQL and all the log files in the `.risingwave/log` folder?

Hi, I have tried to reproduce your problem. But I cannot make it. Besides the log file, it would be helpful if you can provide more details about the problem. For example, the operations you have done before the error comes out.

**Comment by StrikeW** [comment]
Close as no activity for a long time.
