### ISSUE TITLE
nexmark q21 leads to meta node restarting all the time

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#10297]
### Describe the bug

The nexmark q21 leads to meta node restarts in last night's two daily performance test pipeline jobs.
![image](https://github.com/risingwavelabs/risingwave/assets/35356271/b82f774d-4257-4bec-8976-de5108e62f58)

[Buildkite Job](https://buildkite.com/risingwave-test/nexmark-benchmark/builds/1258#0188b05c-d100-4faa-87f5-73c8069e88f6)
[Meta node log during q21](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/explore?left=%7B%22datasource%22:%22Logging(tenant):%20test-useast1-eks-a%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22nexmark-bs-stateful-15-105-affinity-daily-20230612%5C%22,container%3D%5C%22meta%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%221686598084000%22,%22to%22:%221686598505000%22%7D%7D&orgId=1)
```
thread 'risingwave-main' panicked at 'compaction group 5 does not exist', src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:157:32
```

[Grafana during q21](https://g-2927a1b4d9.grafana-workspace.us-east-1.amazonaws.com/d/EpkBw5W4k/risingwave_test_dashboard?orgId=1&from=1686598084000&to=1686598505000&var-namespace=nexmark-bs-stateful-15-105-affinity-daily-20230612)

**Comment by cyliu0** [comment]
By the way. It's reproducible. It happened twice in two different testbeds.

**Comment by fuyufjh** [comment]
<details>
<summary>Stacktrace</summary>

```
thread 'risingwave-main' panicked at 'compaction group 5 does not exist', src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:157:32
--
  |   | stack backtrace:
  |   | 0:     0x55e9bb237f1c - std::backtrace_rs::backtrace::libunwind::trace::hc317256c0daecb22
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
  |   | 1:     0x55e9bb237f1c - std::backtrace_rs::backtrace::trace_unsynchronized::h85008105ccd95ba6
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
  |   | 2:     0x55e9bb237f1c - std::sys_common::backtrace::_print_fmt::hb6e7cbe31fecc91c
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:65:5
  |   | 3:     0x55e9bb237f1c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53097d3751045778
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:44:22
  |   | 4:     0x55e9b58bb90f - core::fmt::rt::Argument::fmt::hdbe0b5dfb2c09e86
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/fmt/rt.rs:138:9
  |   | 5:     0x55e9b58bb90f - core::fmt::write::h4ae17c68778671a0
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/fmt/mod.rs:1094:21
  |   | 6:     0x55e9bb23339f - std::io::Write::write_fmt::hfd7c55e775c6dc60
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/io/mod.rs:1713:15
  |   | 7:     0x55e9bb237d25 - std::sys_common::backtrace::_print::h81eabb0036b692a0
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:47:5
  |   | 8:     0x55e9bb237d25 - std::sys_common::backtrace::print::h1b1f4d1a23fac3fd
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:34:9
  |   | 9:     0x55e9bb239297 - std::panicking::default_hook::{{closure}}::hc17d2bd8f3da442c
  |   | 10:     0x55e9bb2390a4 - std::panicking::default_hook::h3a32a9336113ba96
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:288:9
  |   | 11:     0x55e9babb31cb - call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1999:9
  |   | 12:     0x55e9babb31cb - {closure#0}
  |   | at /risingwave/src/utils/runtime/src/lib.rs:120:9
  |   | 13:     0x55e9babb31cb - {closure#0}<risingwave_rt::set_panic_hook::{closure_env#0}>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:234:47
  |   | 14:     0x55e9bb2398b2 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4413820818220cb9
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1999:9
  |   | 15:     0x55e9bb2398b2 - std::panicking::rust_panic_with_hook::h90e4d15277396259
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:709:13
  |   | 16:     0x55e9bb239654 - std::panicking::begin_panic_handler::{{closure}}::h2b743ea215b7c408
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:597:13
  |   | 17:     0x55e9bb2382f6 - std::sys_common::backtrace::__rust_end_short_backtrace::h895d390908a90650
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:151:18
  |   | 18:     0x55e9bb2393e2 - rust_begin_unwind
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
  |   | 19:     0x55e9b58b8563 - core::panicking::panic_fmt::h1cc8517ae3119d0e
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
  |   | 20:     0x55e9b98c8691 - {closure#0}
  |   | at /risingwave/src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:157:32
  |   | 21:     0x55e9b98c8691 - unwrap_or_else<&risingwave_pb::hummock::hummock_version::Levels, risingwave_hummock_sdk::compaction_group::hummock_version_ext::{impl#0}::get_compaction_group_levels::{closure_env#0}>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:979:21
  |   | 22:     0x55e9b98c8691 - get_compaction_group_levels
  |   | at /risingwave/src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:157:14
  |   | 23:     0x55e9ba69a2ef - trigger_sst_stat
  |   | at /risingwave/src/meta/src/hummock/metrics_utils.rs:144:32
  |   | 24:     0x55e9ba428d61 - {async_fn#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>
  |   | at /risingwave/src/meta/src/hummock/manager/mod.rs:1404:9
  |   | 25:     0x55e9ba30d1e0 - {async_fn#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>
  |   | at /risingwave/src/meta/src/hummock/manager/mod.rs:1043:14
  |   | 26:     0x55e9ba30d1e0 - {async_fn#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>
  |   | at /risingwave/src/meta/src/hummock/manager/mod.rs:1037:53
  |   | 27:     0x55e9ba25fc38 - {async_block#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>
  |   | at /risingwave/src/meta/src/hummock/manager/mod.rs:388:26
  |   | 28:     0x55e9ba25fc38 - poll<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  |   | 29:     0x55e9ba103132 - {closure#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  |   | 30:     0x55e9ba103132 - with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  |   | 31:     0x55e9b9ad4919 - poll<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  |   | 32:     0x55e9b99e0d3b - {closure#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  |   | 33:     0x55e9b99e0d3b - call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  |   | 34:     0x55e9b99e0d3b - do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>, core::task::poll::Poll<()>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  |   | 35:     0x55e9b99e0d3b - try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  |   | 36:     0x55e9b99e0d3b - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>, core::task::poll::Poll<()>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  |   | 37:     0x55e9b99e0d3b - poll_future<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  |   | 38:     0x55e9b99e0d3b - poll_inner<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  |   | 39:     0x55e9b99e0d3b - poll<tracing::instrument::Instrumented<risingwave_meta::hummock::manager::{impl#0}::start_compaction_heartbeat::{async_fn#0}::{async_block_env#0}<risingwave_meta::storage::etcd_meta_store::EtcdMetaStore>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  |   | 40:     0x55e9bb2cd68f - poll
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  |   | 41:     0x55e9bb2cd68f - run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  |   | 42:     0x55e9bb2cd68f - {closure#0}
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:487:26
  |   | 43:     0x55e9bb2cd68f - with_budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  |   | 44:     0x55e9bb2cd68f - budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  |   | 45:     0x55e9bb2cd68f - run_task
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  |   | 46:     0x55e9bb2ccbc3 - run
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  |   | 47:     0x55e9bb2c6fdd - {closure#0}
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  |   | 48:     0x55e9bb2c6fdd - set<tokio::runtime::scheduler::multi_thread::worker::Context, tokio::runtime::scheduler::multi_thread::worker::run::{closure_env#0}, ()>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  |   | 49:     0x55e9bb2cc638 - run
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  |   | 50:     0x55e9bb2b5d9c - {closure#0}
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  |   | 51:     0x55e9bb2b5d9c - poll<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}, ()>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
  |   | 52:     0x55e9bb2b5d9c - poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  |   | 53:     0x55e9bb2bc70d - {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  |   | 54:     0x55e9bb2bc70d - with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  |   | 55:     0x55e9bb2bc70d - poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  |   | 56:     0x55e9bb29ec6f - {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  |   | 57:     0x55e9bb29ec6f - call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  |   | 58:     0x55e9bb29ec6f - do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  |   | 59:     0x55e9bb29ec6f - try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  |   | 60:     0x55e9bb29ec6f - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  |   | 61:     0x55e9bb29ec6f - poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  |   | 62:     0x55e9bb29ec6f - poll_inner<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  |   | 63:     0x55e9bb29ec6f - poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  |   | 64:     0x55e9bb29d7cf - poll
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  |   | 65:     0x55e9bb29d7cf - run<tokio::runtime::blocking::schedule::BlockingSchedule>
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
  |   | 66:     0x55e9bb29d7cf - run
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
  |   | 67:     0x55e9bb29d7cf - run
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
  |   | 68:     0x55e9bb2bd2a6 - {closure#0}
  |   | at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
  |   | 69:     0x55e9bb2bd2a6 - __rust_begin_short_backtrace<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:135:18
  |   | 70:     0x55e9bb2aa082 - {closure#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/thread/mod.rs:529:17
  |   | 71:     0x55e9bb2aa082 - call_once<(), std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  |   | 72:     0x55e9bb2aa082 - do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  |   | 73:     0x55e9bb2aa082 - try<(), core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  |   | 74:     0x55e9bb2aa082 - catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<std::thread::{impl#0}::spawn_unchecked_::{closure#1}::{closure_env#0}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>>, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  |   | 75:     0x55e9bb2aa082 - {closure#1}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/thread/mod.rs:528:30
  |   | 76:     0x55e9bb2aa082 - call_once<std::thread::{impl#0}::spawn_unchecked_::{closure_env#1}<tokio::runtime::blocking::pool::{impl#6}::spawn_thread::{closure_env#0}, ()>, ()>
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:250:5
  |   | 77:     0x55e9bb23f625 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0716d70b901d1398
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1985:9
  |   | 78:     0x55e9bb23f625 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7c11e50091aab2e1
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1985:9
  |   | 79:     0x55e9bb23f625 - std::sys::unix::thread::Thread::new::thread_start::h3ae99d1c2785d9c6
  |   | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys/unix/thread.rs:108:17
  |   | 80:     0x7f666dd6fb43 - <unknown>
  |   | 81:     0x7f666de01a00 - <unknown>
  |   | 82:                0x0 - <unknown>


```
</details>

```
* d08eacb79f - fix: clean dropped executor cache metrics (#10288) (17 hours ago) <Yuhao Su>
* c2de78ee7a - chore: make risedev tasks more readable (#10279) (17 hours ago) <xxchan>
* 5c5420cdac - feat: add missing columns in information_schema.columns and add current_setting func (#10269) (18 hours ago) <August>
* 3d54df99e9 - fix(ci): maven bump in release script (#10287) (20 hours ago) <Huangjw>
* 90e7fcd5c1 - refactor(object store): unify s3 compatible storage and s3 backend (#10138) (21 hours ago) <congyi wang>
* dd5c41b0d4 - fix: support default `NOW()` (#10086) (22 hours ago) <Clearlove>
* 893f11c4a2 - chore(storage): handle metrics update when the value is zero or cg be removed (#10196) (22 hours ago) <Li0k>
* 17e210afc4 - feat(docker): add docker compose file for gcs (#10185) (23 hours ago) <congyi wang>
* d55bfe5236 - refactor(plan_node_fmt): 7 more impls for `Distill` (#10281) (23 hours ago) <Tesla Zhang>
* 5affde8dfd - fix(expr): `array_length` and `cardinality` returns int32 as in PostgreSQL (#10267) (25 hours ago) <xiangjinwu>
* 9a18ec0b6c - chore(sqlsmith): disable deterministic tests being run per PR (#10284) (34 hours ago) <Noel Kwan>
```

Any ideas? cc. @wcy-fdu @Li0k

**Comment by wcy-fdu** [comment]
@Little-Wallace  @Li0k  PTAL❤️

**Comment by Li0k** [comment]
I will do a quick fix
