### ISSUE TITLE
Compute node down at ANY(arrary) condition query

### ISSUE THREAD

**Issue by curiosityyy** [risingwavelabs/risingwave#10485]
### Describe the bug

Running the below query will make the compute node down.

### Error message/log

```text
WITH user_event_array AS (
  SELECT user_id, array_agg(event_type_id) as event_array
  FROM prod_trigger_event
  GROUP BY user_id
)
SELECT * from user_event_array
WHERE '1' = ANY(event_array) and '2' = ANY(event_array);

thread 'risingwave-batch-tasks' panicked at 'assertion failed: `(left == right)`
  left: `2697`,
 right: `2562`', /risingwave/src/common/src/array/data_chunk.rs:72:13
stack backtrace:
  
  22:     0x559d73c9d749 - new<usize>
                               at /risingwave/src/common/src/array/data_chunk.rs:72:13
  23:     0x559d73d3d69c - {async_block#0}
                               at /risingwave/src/expr/src/expr/expr_some_all.rs:145:26
  24:     0x559d73d3f80a - poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<risingwave_common::array::ArrayImpl>, risingwave_expr::error::ExprError>> + core::marker::Send), alloc::alloc::Global>>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/future/future.rs:125:9
  25:     0x559d73d3f80a - {async_block#0}<risingwave_expr::expr::expr_some_all::SomeAllExpression>
                               at /risingwave/src/expr/src/expr/mod.rs:97:36
  26:     0x559d73d8b060 - poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<risingwave_common::array::ArrayImpl>, risingwave_expr::error::ExprError>> + core::marker::Send), alloc::alloc::Global>>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/future/future.rs:125:9
  27:     0x559d73d8b060 - {async_block#0}
                               at /risingwave/src/expr/src/expr/expr_binary_nullable.rs:69:57
  28:     0x559d71bb8a5f - poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<alloc::sync::Arc<risingwave_common::array::ArrayImpl>, risingwave_expr::error::ExprError>> + core::marker::Send), alloc::alloc::Global>>
                               at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/future/future.rs:125:9
  29:     0x559d71bb8a5f - {generator#0}
                               at /risingwave/src/batch/src/executor/filter.rs:61:57
  30:     0x559d71bb8a5f - poll_next<risingwave_batch::executor::filter::{impl#1}::do_execute::{generator_env#0}, risingwave_common::array::data_chunk::DataChunk, risingwave_common::error::RwError>
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  31:     0x559d7188ee1b - poll_next<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_common::error::RwError>> + core::marker::Send), alloc::alloc::Global>>
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9

                                                                              QUERY PLAN                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BatchExchange { order: [], dist: Single }
 └─BatchFilter { predicate: Some(('1':Varchar = array_agg(prod_trigger_event.event_type_id))) AND Some(('2':Varchar = array_agg(prod_trigger_event.event_type_id))) }
   └─BatchHashAgg { group_key: [prod_trigger_event.user_id], aggs: [array_agg(prod_trigger_event.event_type_id)] }
     └─BatchExchange { order: [], dist: HashShard(prod_trigger_event.user_id) }
       └─BatchScan { table: prod_trigger_event, columns: [event_type_id, user_id] }
(5 rows)

dev=> describe prod_trigger_event;
     Name      |          Type           
---------------+-------------------------
 app_type      | varchar
 event_type_id | varchar
 event_value   | varchar
 timestamp     | varchar
 user_id       | varchar
 primary key   | prod_event_json._row_id
(6 rows)




           Name            |                                                                                                                                                                  Create Sql                                                                                                                                                                  
---------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 public.prod_trigger_event | CREATE MATERIALIZED VIEW prod_trigger_event AS SELECT event_json ->> 'app_type' AS app_type, event_json ->> 'event_type_id' AS event_type_id, event_json ->> 'event_value' AS event_value, event_json ->> 'timestamp' AS timestamp, event_json ->> 'userId' AS user_id FROM prod_event_json WHERE event_json ->> 'event_type_id' IS NOT NULL
(1 row)
```

**Comment by BugenZhao** [comment]
Will fix this in #10520.
