### ISSUE TITLE
`create table XXX as select * from Source` panics

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10500]
### Describe the bug

```
dev=> CREATE SOURCE source (
anything varchar
) 
WITH (
connector='kafka',
topic='empty_topic',                                                                                                                                   properties.bootstrap.server='127.0.0.1:29092',
) ROW FORMAT json;

dev=> create table table as select anything from source;
ERROR:  QueryError: internal error: BatchError: internal error: error reading a body from connection: stream closed because of a broken pipe
```

```
486 2023-06-23T10:23:29.169816Z  INFO risingwave_connector::source::kafka::private_link: [consumer] rewrite map None
 487 thread 'risingwave-batch-tasks' panicked at 'assertion failed: offset < data_chunk.capacity()', src/common/src/util/chunk_coalesce.rs:280:9
 488 stack backtrace:
 489    0: rust_begin_unwind
 490              at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/std/src/panicking.rs:578:5
 491    1: core::panicking::panic_fmt
 492              at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panicking.rs:67:14
 493    2: core::panicking::panic
 494              at /rustc/c373194cb6d882dc455a588bcc29c92a96b50252/library/core/src/panicking.rs:117:5
 495    3: risingwave_common::util::chunk_coalesce::SlicedDataChunk::with_offset_checked
 496              at ./src/common/src/util/chunk_coalesce.rs:280:9
 497    4: risingwave_common::util::chunk_coalesce::SlicedDataChunk::new_checked
 498              at ./src/common/src/util/chunk_coalesce.rs:276:9
 499    5: risingwave_common::util::chunk_coalesce::DataChunkBuilder::append_chunk
 500              at ./src/common/src/util/chunk_coalesce.rs:129:29
 501    6: risingwave_batch::executor::insert::InsertExecutor::do_execute::{{closure}}
 502              at ./src/batch/src/executor/insert.rs:163:26

```

**Comment by BugenZhao** [comment]
```
 501    6: risingwave_batch::executor::insert::InsertExecutor::do_execute::{{closure}}
 502              at ./src/batch/src/executor/insert.rs:163:26
```

There should be no coverage on `InsertExecutor` for this query. Are there any concurrent queries running?

**Comment by lmatz** [comment]
I just reproduced locally:

```
2023-06-25T14:19:35.331897+08:00 DEBUG risingwave_batch::executor::generic_exchange: Exchange source Local(LocalExchangeSource { task_output_id: TaskOutputId { query_id: "c10c541b-3cc1-4794-b939-9d967ce42b6f", stage_id: 2, task_id: 0, output_id: 0 } }) output empty chunk.
thread 'risingwave-batch-tasks' panicked at 'assertion failed: offset < data_chunk.capacity()', src/common/src/util/chunk_coalesce.rs:280:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:117:5
   3: risingwave_common::util::chunk_coalesce::SlicedDataChunk::with_offset_checked
             at ./src/common/src/util/chunk_coalesce.rs:280:9
   4: risingwave_common::util::chunk_coalesce::SlicedDataChunk::new_checked
             at ./src/common/src/util/chunk_coalesce.rs:276:9
   5: risingwave_common::util::chunk_coalesce::DataChunkBuilder::append_chunk
             at ./src/common/src/util/chunk_coalesce.rs:129:29
   6: risingwave_batch::executor::insert::InsertExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/insert.rs:163:26
   7: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
   9: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  10: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  13: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  14: <risingwave_batch::executor::manager::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/manager.rs:66:17
  15: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-stream-0.3.5/src/async_stream.rs:56:13
  16: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  17: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  18: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  19: risingwave_batch::task::task_execution::BatchTaskExecution<C>::run::{{closure}}::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/select.rs:524:49
  20: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  21: risingwave_batch::task::task_execution::BatchTaskExecution<C>::run::{{closure}}
             at ./src/batch/src/task/task_execution.rs:513:13
  22: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  23: risingwave_batch::task::task_execution::BatchTaskExecution<C>::async_execute::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/batch/src/task/task_execution.rs:400:22
  24: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.1.0/src/task.rs:2365:19
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:296:9
  26: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  28: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  29: ___rust_try
  30: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  31: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  32: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  33: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:348:35
  34: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:233:19
  35: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:345:13
  36: risingwave_batch::task::task_execution::BatchTaskExecution<C>::async_execute::{{closure}}::{{closure}}
             at ./src/batch/src/task/task_execution.rs:407:73
  37: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  38: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  40: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  41: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  43: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  44: ___rust_try
  45: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  46: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  47: tokio::runtime::task::harness::poll_future
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  48: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  49: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  50: tokio::runtime::task::raw::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  51: tokio::runtime::task::raw::RawTask::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  52: tokio::runtime::task::LocalNotified<S>::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  53: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  54: tokio::runtime::coop::with_budget
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  55: tokio::runtime::coop::budget
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  56: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  57: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  58: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  59: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  60: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  61: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  62: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
  63: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  64: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  65: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  66: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  67: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  68: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  69: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  70: ___rust_try
  71: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  72: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  73: tokio::runtime::task::harness::poll_future
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  74: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  75: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  76: tokio::runtime::task::raw::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  77: tokio::runtime::task::raw::RawTask::poll
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  78: tokio::runtime::task::UnownedTask<S>::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
  79: tokio::runtime::blocking::pool::Task::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
  80: tokio::runtime::blocking::pool::Inner::run
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
  81: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Only these two queries, one create source one create table

**Comment by st1page** [comment]
IIRC, `CREATE TABLE AS` should be an internal feature just for our test. and do we use private links during test?

**Comment by lmatz** [comment]
no private link, I start a local Kafka cluster on my Mac without any configuration

**Comment by lmatz** [comment]
> CREATE TABLE AS should be an internal feature just for our test. 

Yes, we disable it in production/release, it is a bug reported from the slack community

**Comment by chenzl25** [comment]
Currently, we have a better error when users want to create a table as select * from source. 
```
QueryError: Scheduler error: Unsupported to query directly from this source
```
