### ISSUE TITLE
Using bytea as primary key causes panic

### ISSUE THREAD

**Issue by wugouzi** [risingwavelabs/risingwave#10577]
### Error message/log

```text
thread 'risingwave-compaction' panicked at 'assertion failed: self.remaining() >= 1', /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/buf/buf_impl.rs:289:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:117:5
   3: bytes::buf::buf_impl::Buf::get_u8
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/buf/buf_impl.rs:289:9
   4: memcomparable::de::MaybeFlip<B>::get_u8
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memcomparable-0.2.0/src/de.rs:93:21
   5: memcomparable::de::Deserializer<B>::skip_bytes
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memcomparable-0.2.0/src/de.rs:158:19
   6: risingwave_common::util::memcmp_encoding::calculate_encoded_size_inner
             at ./src/common/src/util/memcmp_encoding.rs:170:32
   7: risingwave_common::util::memcmp_encoding::calculate_encoded_size
             at ./src/common/src/util/memcmp_encoding.rs:120:5
   8: risingwave_common::util::row_serde::OrderedRowSerde::deserialize_prefix_len
             at ./src/common/src/util/row_serde.rs:104:17
   9: <risingwave_storage::filter_key_extractor::SchemaFilterKeyExtractor as risingwave_storage::filter_key_extractor::FilterKeyExtractor>::extract
             at ./src/storage/src/filter_key_extractor.rs:147:36
  10: risingwave_storage::filter_key_extractor::FilterKeyExtractorImpl::extract
             at ./src/storage/src/filter_key_extractor.rs:65:54
  11: <risingwave_storage::filter_key_extractor::MultiFilterKeyExtractor as risingwave_storage::filter_key_extractor::FilterKeyExtractor>::extract
             at ./src/storage/src/filter_key_extractor.rs:221:9
  12: risingwave_storage::filter_key_extractor::FilterKeyExtractorImpl::extract
             at ./src/storage/src/filter_key_extractor.rs:65:54
  13: risingwave_storage::hummock::sstable::builder::SstableBuilder<W,F>::add::{{closure}}
             at ./src/storage/src/hummock/sstable/builder.rs:244:27
  14: risingwave_storage::hummock::sstable::multi_builder::CapacitySplitTableBuilder<F>::add_full_key::{{closure}}
             at ./src/storage/src/hummock/sstable/multi_builder.rs:258:55
  15: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:87:36
  16: risingwave_storage::hummock::compactor::Compactor::compact_and_build_sst::{{closure}}
             at ./src/storage/src/hummock/compactor/mod.rs:807:18
  17: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:87:36
  18: risingwave_storage::hummock::compactor::Compactor::compact_key_range_impl::{{closure}}
             at ./src/storage/src/hummock/compactor/mod.rs:1029:10
  19: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:87:36
  20: risingwave_storage::hummock::compactor::Compactor::compact_key_range::{{closure}}
             at ./src/storage/src/hummock/compactor/mod.rs:909:18
  21: risingwave_storage::hummock::compactor::shared_buffer_compact::SharedBufferCompactRunner::run::{{closure}}
             at ./src/storage/src/hummock/compactor/shared_buffer_compact.rs:461:14
  22: risingwave_storage::hummock::compactor::shared_buffer_compact::compact_shared_buffer::{{closure}}::{{closure}}
             at ./src/storage/src/hummock/compactor/shared_buffer_compact.rs:213:18
  23: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  24: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  26: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  27: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  29: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  30: ___rust_try
  31: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  32: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  33: tokio::runtime::task::harness::poll_future
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  34: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  35: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  36: tokio::runtime::task::raw::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  37: tokio::runtime::task::raw::RawTask::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  38: tokio::runtime::task::LocalNotified<S>::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  39: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  40: tokio::runtime::coop::with_budget
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  41: tokio::runtime::coop::budget
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  42: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  43: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  44: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  45: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  46: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  47: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  48: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
  49: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  50: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  51: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  52: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  53: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  54: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  55: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  56: ___rust_try
  57: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  58: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  59: tokio::runtime::task::harness::poll_future
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  60: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  61: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  62: tokio::runtime::task::raw::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  63: tokio::runtime::task::raw::RawTask::poll
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  64: tokio::runtime::task::UnownedTask<S>::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
  65: tokio::runtime::blocking::pool::Task::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
  66: tokio::runtime::blocking::pool::Inner::run
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
  67: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/wu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
```

### To Reproduce

``` sql
CREATE TABLE bytes(i bytea primary key, id int);
INSERT INTO bytes VALUES ('fgh', 3);
```
and wait for 3-5s.

**Comment by st1page** [comment]
```
                                             QUERY PLAN                                             
----------------------------------------------------------------------------------------------------
 Fragment 0
 StreamMaterialize { columns: [i, id], stream_key: [i], pk_columns: [i], pk_conflict: "Overwrite" }
 ├── materialized table: 4294967294
 └── StreamExchange Hash([0]) from 1
 
 Fragment 1
 StreamDml { columns: [i, id] }
 └── StreamSource
 
 Table 4294967294
 ├── columns: [ i, id ]
 ├── primary key: [ $0 ASC ]
 ├── value indices: [ 0, 1 ]
 ├── distribution key: [ 0 ]
 └── read pk prefix len hint: 1
```
