### ISSUE TITLE
panicked at `assertion failed: (left == right)`, not same schema

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#10691]
### Describe the bug

https://buildkite.com/risingwavelabs/pull-request/builds/26630#01891a20-5d1b-4abe-9b05-af330549cdb9

```
---- START -- Failing SQL setup code: CREATE TABLE supplier (     s_suppkey INTEGER,     s_name VARCHAR,     s_address VARCHAR,     s_nationkey INTEGER,     s_phone VARCHAR,     s_acctbal NUMERIC,     s_comment VARCHAR,     PRIMARY KEY (s_suppkey) ); CREATE TABLE part (     p_partkey INTEGER,     p_name VARCHAR,     p_mfgr VARCHAR,     p_brand VARCHAR,     p_type VARCHAR,     p_size INTEGER,     p_container VARCHAR,     p_retailprice NUMERIC,     p_comment VARCHAR,     PRIMARY KEY (p_partkey) ); CREATE TABLE partsupp (     ps_partkey INTEGER,     ps_suppkey INTEGER,     ps_availqty INTEGER,     ps_supplycost NUMERIC,     ps_comment VARCHAR,     PRIMARY KEY (ps_partkey, ps_suppkey) ); CREATE TABLE customer (     c_custkey INTEGER,     c_name VARCHAR,     c_address VARCHAR,     c_nationkey INTEGER,     c_phone VARCHAR,     c_acctbal NUMERIC,     c_mktsegment VARCHAR,     c_comment VARCHAR,     PRIMARY KEY (c_custkey) ); CREATE TABLE orders (     o_orderkey BIGINT,     o_custkey INTEGER,     o_orderstatus VARCHAR,     o_totalprice NUMERIC,     o_orderdate DATE,     o_orderpriority VARCHAR,     o_clerk VARCHAR,     o_shippriority INTEGER,     o_comment VARCHAR,     PRIMARY KEY (o_orderkey) ); CREATE TABLE lineitem (     l_orderkey BIGINT,     l_partkey INTEGER,     l_suppkey INTEGER,     l_linenumber INTEGER,     l_quantity NUMERIC,     l_extendedprice NUMERIC,     l_discount NUMERIC,     l_tax NUMERIC,     l_returnflag VARCHAR,     l_linestatus VARCHAR,     l_shipdate DATE,     l_commitdate DATE,     l_receiptdate DATE,     l_shipinstruct VARCHAR,     l_shipmode VARCHAR,     l_comment VARCHAR,     PRIMARY KEY (l_orderkey, l_linenumber) ); CREATE TABLE nation (     n_nationkey INTEGER,     n_name VARCHAR,     n_regionkey INTEGER,     n_comment VARCHAR,     PRIMARY KEY (n_nationkey) ); CREATE TABLE region (     r_regionkey INTEGER,     r_name VARCHAR,     r_comment VARCHAR,     PRIMARY KEY (r_regionkey) ); CREATE TABLE person (     id BIGINT,     name VARCHAR,     email_address VARCHAR,     credit_card VARCHAR,     city VARCHAR,     state VARCHAR,     date_time TIMESTAMP,     extra VARCHAR,     PRIMARY KEY (id) ); CREATE TABLE auction (     id BIGINT,     item_name VARCHAR,     description VARCHAR,     initial_bid BIGINT,     reserve BIGINT,     date_time TIMESTAMP,     expires TIMESTAMP,     seller BIGINT,     category BIGINT,     extra VARCHAR,     PRIMARY KEY (id) ); CREATE TABLE bid (     auction BIGINT,     bidder BIGINT,     price BIGINT,     channel VARCHAR,     url VARCHAR,     date_time TIMESTAMP,     extra VARCHAR ); CREATE TABLE alltypes1 (     c1 boolean,     c2 smallint,     c3 integer,     c4 bigint,     c5 real,     c6 double precision,     c7 numeric,     c8 date,     c9 varchar,     c10 time without time zone,     c11 timestamp without time zone,     -- TODO(Noel): Many timestamptz expressions are unsupported in RW, leave this out for now.     -- c12 timestamp with time zone,     c13 interval,     c14 struct < a integer >,     c15 integer [],     c16 varchar [] ); CREATE TABLE alltypes2 (     c1 boolean,     c2 smallint,     c3 integer,     c4 bigint,     c5 real,     c6 double precision,     c7 numeric,     c8 date,     c9 varchar,     c10 time without time zone,     c11 timestamp without time zone,     -- TODO(Noel): Many timestamptz expressions are unsupported in RW, leave this out for now.     -- c12 timestamp with time zone,     c13 interval,     c14 struct < a integer >,     c15 integer [],     c16 varchar [] );CREATE MATERIALIZED VIEW m0 AS SELECT tumble_0.c1 AS col_0, hop_2.c13 AS col_1, DATE '2023-07-03' AS col_2 FROM (tumble(alltypes1, alltypes1.c11, INTERVAL '2') AS tumble_0 JOIN hop(alltypes1, alltypes1.c11, INTERVAL '26', INTERVAL '442') AS hop_1 ON tumble_0.c5 = hop_1.c5 AND true) JOIN hop(alltypes1, alltypes1.c11, INTERVAL '85', INTERVAL '765') AS hop_2 ON hop_1.c11 = hop_2.c11 AND hop_2.c1 GROUP BY tumble_0.c14, hop_2.c13, tumble_0.c15, tumble_0.c1, hop_1.c13, hop_2.c15, tumble_0.c11, hop_2.c10, hop_1.c3, hop_2.c2, hop_2.c14, hop_2.c5, tumble_0.c6, tumble_0.c9, hop_1.c7, hop_2.c9;CREATE MATERIALIZED VIEW m1 AS SELECT CAST(true AS INT) AS col_0 FROM lineitem AS t_0 FULL JOIN orders AS t_1 ON t_0.l_comment = t_1.o_orderpriority AND true AND t_0.l_linenumber = t_1.o_custkey AND t_0.l_linenumber = t_1.o_shippriority AND t_0.l_linestatus = t_1.o_clerk AND t_0.l_shipmode = t_1.o_orderpriority AND t_0.l_returnflag = t_1.o_orderpriority AND t_0.l_shipmode = t_1.o_clerk AND t_0.l_shipdate = t_1.o_orderdate AND t_0.l_shipinstruct = t_1.o_orderstatus AND t_0.l_suppkey = t_1.o_custkey AND t_0.l_linestatus = t_1.o_comment AND t_0.l_shipinstruct = t_1.o_comment AND t_0.l_linestatus = t_1.o_orderpriority AND t_0.l_commitdate = t_1.o_orderdate AND t_0.l_comment = t_1.o_comment AND t_0.l_comment = t_1.o_clerk AND t_0.l_comment = t_1.o_orderstatus AND t_0.l_partkey = t_1.o_shippriority AND t_0.l_returnflag = t_1.o_clerk AND t_0.l_discount = t_1.o_totalprice AND t_0.l_receiptdate = t_1.o_orderdate AND t_0.l_shipmode = t_1.o_comment AND t_0.l_shipmode = t_1.o_orderstatus AND t_0.l_quantity = t_1.o_totalprice AND t_0.l_linestatus = t_1.o_orderstatus AND t_0.l_tax = t_1.o_totalprice AND t_0.l_partkey = t_1.o_custkey AND t_0.l_shipinstruct = t_1.o_orderpriority AND t_0.l_orderkey = t_1.o_orderkey AND t_0.l_extendedprice = t_1.o_totalprice GROUP BY t_0.l_tax, t_0.l_shipdate, t_0.l_extendedprice, t_0.l_orderkey, t_1.o_custkey, t_1.o_orderpriority, t_0.l_shipinstruct, t_0.l_partkey, t_0.l_shipmode, t_0.l_linenumber, t_0.l_discount HAVING true;CREATE MATERIALIZED VIEW m2 AS SELECT (DATE '2023-07-03') AS col_0, t_4.c7 AS col_1, (FLOAT '988') AS col_2 FROM ((WITH with_0 AS (WITH with_1 AS (SELECT t_2.ps_comment AS col_0, string_agg(t_2.ps_comment, ('eW0IpillyU')) FILTER(WHERE false) AS col_1 FROM partsupp AS t_2 WHERE true GROUP BY t_2.ps_availqty, t_2.ps_comment HAVING true) SELECT (REAL '968') AS col_0, (INTERVAL '3600') AS col_1 FROM with_1) SELECT (BIGINT '808') AS col_0, (BIGINT '130') AS col_1 FROM with_0 WHERE false) AS sq_3 RIGHT JOIN alltypes2 AS t_4 ON sq_3.col_1 = t_4.c4 AND true) LEFT JOIN nation AS t_5 ON t_4.c3 = t_5.n_regionkey GROUP BY t_4.c8, t_4.c7, t_4.c13, t_4.c4, t_5.n_name, t_4.c6, t_4.c10 HAVING false;CREATE MATERIALIZED VIEW m3 AS SELECT t_0.s_phone AS col_0, tumble_1.c4 AS col_1 FROM supplier AS t_0 RIGHT JOIN tumble(alltypes1, alltypes1.c11, INTERVAL '2') AS tumble_1 ON t_0.s_name = tumble_1.c9 AND true AND t_0.s_address = tumble_1.c9 AND t_0.s_acctbal = tumble_1.c7 WHERE (tumble_1.c6 = tumble_1.c6) GROUP BY t_0.s_phone, tumble_1.c9, tumble_1.c4, tumble_1.c3, t_0.s_name, t_0.s_address;CREATE MATERIALIZED VIEW m4 AS SELECT hop_2.c3 AS col_0, hop_2.c3 AS col_1 FROM hop(alltypes2, alltypes2.c11, INTERVAL '94', INTERVAL '1598') AS hop_2 GROUP BY hop_2.c16, hop_2.c3 HAVING false;CREATE MATERIALIZED VIEW m5 AS SELECT t_0.description AS col_0 FROM auction AS t_0 LEFT JOIN supplier AS t_1 ON t_0.item_name = t_1.s_address WHERE CAST((char_length(t_1.s_name)) AS BOOLEAN) GROUP BY t_0.extra, t_1.s_nationkey, t_0.item_name, t_0.description;CREATE MATERIALIZED VIEW m6 AS SELECT t_0.p_size AS col_0, string_agg(tumble_5.c9, tumble_5.c9) FILTER(WHERE true) AS col_1, min((TIMESTAMP '2023-07-03 05:10:24')) AS col_2 FROM (part AS t_0 JOIN (SELECT t_3.c_acctbal AS col_0 FROM customer AS t_3 WHERE true GROUP BY t_3.c_nationkey, t_3.c_custkey, t_3.c_acctbal HAVING false) AS sq_4 ON t_0.p_retailprice = sq_4.col_0 AND true) LEFT JOIN tumble(alltypes2, alltypes2.c11, INTERVAL '3') AS tumble_5 ON t_0.p_type = tumble_5.c9 AND true WHERE tumble_5.c1 GROUP BY t_0.p_comment, tumble_5.c13, t_0.p_size HAVING false;CREATE MATERIALIZED VIEW m7 AS SELECT (TIMESTAMP '2023-07-03 05:09:09') AS col_0, 'K3ltDM58rB' AS col_1, TIME '05:08:50' AS col_2, hop_0.auction AS col_3 FROM hop(bid, bid.date_time, INTERVAL '1', INTERVAL '13') AS hop_0 WHERE false GROUP BY hop_0.auction, hop_0.extra, hop_0.date_time HAVING false;CREATE MATERIALIZED VIEW m8 AS WITH with_0 AS (SELECT (- sq_4.col_0) AS col_0, sq_4.col_0 AS col_1, (SMALLINT '202') AS col_2 FROM (SELECT hop_2.c2 AS col_0, hop_2.c15 AS col_1 FROM (hop(bid, bid.date_time, INTERVAL '60', INTERVAL '780') AS hop_1 FULL JOIN hop(alltypes1, alltypes1.c11, INTERVAL '96', INTERVAL '864') AS hop_2 ON hop_1.auction = hop_2.c4 AND true) RIGHT JOIN m1 AS t_3 ON hop_2.c3 = t_3.col_0 GROUP BY hop_2.c15, hop_2.c2, hop_1.channel, hop_2.c1 HAVING hop_2.c1) AS sq_4 WHERE ('QXBrA97IKg' LIKE 'KYyZ16c2PQ') GROUP BY sq_4.col_0) SELECT ARRAY[(BIGINT '269'), (BIGINT '23'), (BIGINT '746')] AS col_0 FROM with_0 WHERE CAST(((SMALLINT '595') % (INT '659914986')) AS BOOLEAN);CREATE MATERIALIZED VIEW m9 AS SELECT (t_1.n_nationkey + t_0.p_partkey) AS col_0, t_0.p_name AS col_1 FROM part AS t_0 JOIN nation AS t_1 ON t_0.p_brand = t_1.n_name AND true AND t_0.p_container = t_1.n_name AND t_0.p_mfgr = t_1.n_comment AND t_0.p_partkey = t_1.n_regionkey WHERE ((FLOAT '143') < (REAL '264')) GROUP BY t_0.p_name, t_1.n_nationkey, t_0.p_mfgr, t_0.p_partkey;CREATE MATERIALIZED VIEW m10 AS WITH with_0 AS (SELECT CAST(false AS INT) AS col_0, tumble_3.col_0 AS col_1, (((SMALLINT '993') - (SMALLINT '32767')) + tumble_3.col_0) AS col_2, (INT '0') AS col_3 FROM tumble(m6, m6.col_2, INTERVAL '16') AS tumble_3 WHERE true GROUP BY tumble_3.col_0 HAVING true) SELECT TIME '05:10:24' AS col_0, 'Ua0rBjeobm' AS col_1 FROM with_0;CREATE MATERIALIZED VIEW m11 AS SELECT '8DUUKITyED' AS col_0, t_2.c_custkey AS col_1, ('tVMGmm04BL') AS col_2, 'YtGKWNPSCX' AS col_3 FROM (partsupp AS t_0 JOIN m5 AS t_1 ON t_0.ps_comment = t_1.col_0) FULL JOIN customer AS t_2 ON t_1.col_0 = t_2.c_phone AND true WHERE true GROUP BY t_2.c_custkey, t_2.c_phone, t_2.c_comment, t_0.ps_comment HAVING false;CREATE MATERIALIZED VIEW m12 AS SELECT TIME '05:09:50' AS col_0 FROM tumble(m6, m6.col_2, INTERVAL '19') AS tumble_0 JOIN m10 AS t_1 ON tumble_0.col_1 = t_1.col_1 WHERE ((FLOAT '968') <= (FLOAT '0')) GROUP BY t_1.col_0, tumble_0.col_0;CREATE MATERIALIZED VIEW m13 AS SELECT t_0.n_name AS col_0, t_0.n_name AS col_1 FROM nation AS t_0 GROUP BY t_0.n_comment, t_0.n_name HAVING true;CREATE MATERIALIZED VIEW m14 AS SELECT tumble_0.c4 AS col_0, tumble_0.c7 AS col_1 FROM tumble(alltypes2, alltypes2.c11, INTERVAL '10') AS tumble_0 JOIN m3 AS t_1 ON tumble_0.c4 = t_1.col_1 AND tumble_0.c1 GROUP BY tumble_0.c6, tumble_0.c4, tumble_0.c7, tumble_0.c10, tumble_0.c14, tumble_0.c9 HAVING max((tumble_0.c3 <> (INT '511')));CREATE MATERIALIZED VIEW m15 AS SELECT t_2.n_name AS col_0, tumble_0.c7 AS col_1 FROM (tumble(alltypes1, alltypes1.c11, INTERVAL '8') AS tumble_0 FULL JOIN tumble(alltypes1, alltypes1.c11, INTERVAL '16') AS tumble_1 ON tumble_0.c13 = tumble_1.c13 AND tumble_1.c1) FULL JOIN nation AS t_2 ON tumble_0.c3 = t_2.n_nationkey AND tumble_0.c1 WHERE tumble_1.c1 GROUP BY tumble_1.c7, tumble_0.c2, t_2.n_comment, tumble_1.c1, tumble_0.c7, tumble_1.c3, t_2.n_name;CREATE MATERIALIZED VIEW m16 AS SELECT ((SMALLINT '547') <> (BIGINT '230')) AS col_0, t_0.c1 AS col_1, true AS col_2, t_0.c1 AS col_3 FROM alltypes2 AS t_0 RIGHT JOIN tumble(alltypes1, alltypes1.c11, INTERVAL '19') AS tumble_1 ON t_0.c5 = tumble_1.c5 AND true AND t_0.c15 = tumble_1.c15 AND t_0.c3 = tumble_1.c3 GROUP BY t_0.c1 HAVING t_0.c1;CREATE MATERIALIZED VIEW m17 AS SELECT t_7.col_1 AS col_0, 'yLsCchzBdN' AS col_1 FROM m6 AS t_7 GROUP BY t_7.col_1 HAVING true;CREATE MATERIALIZED VIEW m18 AS SELECT t_0.col_1 AS col_0, t_0.col_1 AS col_1 FROM m16 AS t_0 LEFT JOIN m0 AS t_1 ON t_0.col_0 = t_1.col_0 AND true WHERE t_0.col_1 GROUP BY t_0.col_1 HAVING t_0.col_1;CREATE MATERIALIZED VIEW m19 AS WITH with_0 AS (SELECT t_3.p_comment AS col_0 FROM part AS t_3 WHERE true GROUP BY t_3.p_retailprice, t_3.p_comment, t_3.p_brand) SELECT ((FLOAT '277') + (REAL '715')) AS col_0, (BIGINT '467') AS col_1, TIME '05:08:57' AS col_2 FROM with_0;
```

```
-- Failing SQL query: CREATE MATERIALIZED VIEW stream_query AS SELECT (ARRAY['1hvDa1hd7X', 'CQCu6JYZuv', 'EVuoDmDhpZ', 'iig7iCqJxC']) AS col_0, hop_2.c7 AS col_1, t_1.r_regionkey AS col_2, hop_2.c15 AS col_3 FROM (tumble(m7, m7.col_0, INTERVAL '1') AS tumble_0 LEFT JOIN region AS t_1 ON tumble_0.col_1 = t_1.r_comment AND true AND tumble_0.col_1 = t_1.r_name) FULL JOIN hop(alltypes1, alltypes1.c11, INTERVAL '89', INTERVAL '267') AS hop_2 ON t_1.r_name = hop_2.c9 WHERE EXISTS (SELECT CAST(NULL AS STRUCT<a REAL, b SMALLINT>) AS col_0, hop_2.c3 AS col_1, hop_2.c10 AS col_2 FROM (WITH with_3 AS (SELECT max(tumble_5.c10) AS col_0, CAST(NULL AS STRUCT<a INT>) AS col_1, ARRAY[TIMESTAMP '2023-07-03 05:09:52', TIMESTAMP '2023-07-03 05:08:57', TIMESTAMP '2023-07-03 05:10:01', TIMESTAMP '2023-07-03 05:08:53'] AS col_2, tumble_5.c14 AS col_3 FROM hop(m7, m7.col_0, INTERVAL '78', INTERVAL '390') AS hop_4 LEFT JOIN tumble(alltypes1, alltypes1.c11, INTERVAL '1') AS tumble_5 ON hop_4.col_1 = tumble_5.c9 AND tumble_5.c1 GROUP BY tumble_5.c6, tumble_5.c7, tumble_5.c14, tumble_5.c16, tumble_5.c9, tumble_5.c10, tumble_5.c1, hop_4.col_0 HAVING tumble_5.c1) SELECT TIMESTAMP '2023-07-03 05:09:55' AS col_0 FROM with_3) AS sq_6 WHERE (hop_2.c2 > (INT '88')) GROUP BY tumble_0.col_0, hop_2.c3, t_1.r_comment, hop_2.c10, hop_2.c2, tumble_0.col_1, tumble_0.col_3, hop_2.c5, tumble_0.col_2, hop_2.c7) GROUP BY hop_2.c7, hop_2.c11, t_1.r_regionkey, tumble_0.col_1, hop_2.c15, t_1.r_comment;
```

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`   left: `Schema { fields: [m7.col_0:Timestamp, m7.col_1:Varchar, m7.col_2:Time, m7.col_3:Int64, region.r_comment:Varchar, alltypes1.c2:Int16, alltypes1.c3:Int32, alltypes1.c5:Float32, alltypes1.c7:Decimal, alltypes1.c10:Time, m7.col_0:Timestamp, m7.col_1:Varchar, m7.col_2:Time, m7.col_3:Int64, m7.bid.date_time:Timestamp, m7.bid.extra:Varchar, window_start:Timestamp, window_end:Timestamp, alltypes1.c1:Boolean, alltypes1.c2:Int16, alltypes1.c3:Int32, alltypes1.c4:Int64, alltypes1.c5:Float32, alltypes1.c6:Float64, alltypes1.c7:Decimal, alltypes1.c8:Date, alltypes1.c9:Varchar, alltypes1.c10:Time, alltypes1.c11:Timestamp, alltypes1.c13:Interval, alltypes1.c14:Struct(StructType { field_names: ["a"], field_types: [Int32] }), alltypes1.c15:List(Int32), alltypes1.c16:List(Varchar), alltypes1._row_id:Serial, $expr10150:Timestamp, $expr10151:Timestamp] }`,  right: `Schema { fields: [m7.col_0:Timestamp, m7.col_1:Varchar, m7.col_2:Time, m7.col_3:Int64, region.r_comment:Varchar, alltypes1.c2:Int16, alltypes1.c3:Int32, alltypes1.c5:Float32, alltypes1.c7:Decimal, alltypes1.c10:Time, alltypes1.c6:Float64, alltypes1.c7:Decimal, alltypes1.c14:Struct(StructType { field_names: ["a"], field_types: [Int32] }), alltypes1.c16:List(Varchar), alltypes1.c9:Varchar, alltypes1.c10:Time, alltypes1.c1:Boolean, m7.col_0:Timestamp] }`', src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs:188:9 stack backtrace:    0: rust_begin_unwind              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5    1: core::panicking::panic_fmt              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14    2: core::panicking::assert_failed_inner    3: core::panicking::assert_failed              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:228:5    4: <risingwave_frontend::optimizer::rule::apply_join_transpose_rule::ApplyJoinTransposeRule as risingwave_frontend::optimizer::rule::Rule>::apply              at /risingwave/src/frontend/src/optimizer/rule/apply_join_transpose_rule.rs:188:9    5: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_node              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:53:36    6: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:76:24    7: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:68:29    8: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:305:13    9: core::option::Option<T>::map              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:1075:29   10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:103:26   11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:26:32   12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9   13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9   14: core::iter::traits::iterator::Iterator::collect              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9   15: itertools::Itertools::collect_vec              at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:9   16: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:65:22   17: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:77:17   18: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:68:29   19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:305:13   20: core::option::Option<T>::map              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:1075:29   21: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:103:26   22: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:26:32   23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9   24: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9   25: core::iter::traits::iterator::Iterator::collect              at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9   26: itertools::Itertools::collect_vec              at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:9   27: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:65:22   28: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:77:17   29: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}              at /risingwave/src/frontend/src/optimizer/heuristic_optimizer.rs:68:29
```

**Comment by chenzl25** [comment]
The panic is already fixed. However, we lack the ability to untest correlated query within `HopWindow`.
