### ISSUE TITLE
pgwire panics if error message contains '\0' (e.g., parsing parameter in text format)

### ISSUE THREAD

**Issue by JuchangGit** [risingwavelabs/risingwave#10827]
### Describe the bug

我试图将[]byte类型插入到表integer类型的字段时发生了严重的错误，导致frontend-node-0节点直接终止

### Error message/log

```text
2023-07-07T07:53:41.041312114Z  thread 'risingwave-main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "string contains embedded null" }', src/utils/pgwire/src/pg_message.rs:706:6
2023-07-07T07:53:41.041323268Z  stack backtrace:
2023-07-07T07:53:41.384059553Z     0: rust_begin_unwind
2023-07-07T07:53:41.384080003Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
2023-07-07T07:53:41.384082791Z     1: core::panicking::panic_fmt
2023-07-07T07:53:41.384084855Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
2023-07-07T07:53:41.384090290Z     2: core::result::unwrap_failed
2023-07-07T07:53:41.384093160Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1651:5
2023-07-07T07:53:41.384263801Z     3: core::result::Result<T,E>::unwrap
2023-07-07T07:53:41.384270984Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1076:23
2023-07-07T07:53:41.384276608Z     4: pgwire::pg_message::write_err_or_notice
2023-07-07T07:53:41.384279624Z               at ./risingwave/src/utils/pgwire/src/pg_message.rs:693:5
2023-07-07T07:53:41.384540306Z     5: pgwire::pg_message::BeMessage::write
2023-07-07T07:53:41.384551621Z               at ./risingwave/src/utils/pgwire/src/pg_message.rs:622:17
2023-07-07T07:53:41.393801541Z     6: pgwire::pg_protocol::Conn<S>::write_no_flush
2023-07-07T07:53:41.399018230Z     7: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
2023-07-07T07:53:41.399031367Z               at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:204:25
2023-07-07T07:53:41.399034010Z     8: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
2023-07-07T07:53:41.399036236Z               at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:160:30
2023-07-07T07:53:41.399051912Z     9: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
2023-07-07T07:53:41.399059258Z               at ./risingwave/src/utils/pgwire/src/pg_server.rs:173:45
2023-07-07T07:53:41.399125352Z    10: pgwire::pg_server::handle_connection::{{closure}}
2023-07-07T07:53:41.399133940Z               at ./risingwave/src/utils/pgwire/src/pg_server.rs:158:1
2023-07-07T07:53:41.399148341Z    11: <F as futures_core::future::TryFuture>::try_poll
2023-07-07T07:53:41.399156869Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
2023-07-07T07:53:41.399203390Z    12: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
2023-07-07T07:53:41.399209307Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_future/into_future.rs:34:9
2023-07-07T07:53:41.399230958Z    13: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
2023-07-07T07:53:41.399244527Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/map.rs:55:37
2023-07-07T07:53:41.399335723Z    14: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
2023-07-07T07:53:41.399364731Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
2023-07-07T07:53:41.399368997Z    15: <futures_util::future::try_future::InspectErr<Fut,F> as core::future::future::Future>::poll
2023-07-07T07:53:41.399392153Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
2023-07-07T07:53:41.399406283Z    16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
2023-07-07T07:53:41.399415197Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
2023-07-07T07:53:41.399458344Z    17: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
2023-07-07T07:53:41.399463688Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
2023-07-07T07:53:41.399479237Z    18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2023-07-07T07:53:41.399483614Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
2023-07-07T07:53:41.410702279Z    19: tokio::runtime::task::core::Core<T,S>::poll
2023-07-07T07:53:41.410717676Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
2023-07-07T07:53:41.418645008Z    20: tokio::runtime::task::harness::poll_future::{{closure}}
2023-07-07T07:53:41.418659757Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
2023-07-07T07:53:41.418664029Z    21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2023-07-07T07:53:41.418669436Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
2023-07-07T07:53:41.418672868Z    22: std::panicking::try::do_call
2023-07-07T07:53:41.418676592Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
2023-07-07T07:53:41.418680645Z    23: std::panicking::try
2023-07-07T07:53:41.418695404Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
2023-07-07T07:53:41.418707380Z    24: std::panic::catch_unwind
2023-07-07T07:53:41.418718872Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
2023-07-07T07:53:41.418726692Z    25: tokio::runtime::task::harness::poll_future
2023-07-07T07:53:41.418735517Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
2023-07-07T07:53:41.418756819Z    26: tokio::runtime::task::harness::Harness<T,S>::poll_inner
2023-07-07T07:53:41.418769862Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
2023-07-07T07:53:41.418790709Z    27: tokio::runtime::task::harness::Harness<T,S>::poll
2023-07-07T07:53:41.418800161Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
2023-07-07T07:53:41.419223019Z    28: tokio::runtime::task::raw::RawTask::poll
2023-07-07T07:53:41.419256668Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
2023-07-07T07:53:41.419259931Z    29: tokio::runtime::task::LocalNotified<S>::run
2023-07-07T07:53:41.419261940Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
2023-07-07T07:53:41.419292456Z    30: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
2023-07-07T07:53:41.419298814Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:464:18
2023-07-07T07:53:41.419302293Z    31: tokio::runtime::coop::with_budget
2023-07-07T07:53:41.419306196Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
2023-07-07T07:53:41.419310739Z    32: tokio::runtime::coop::budget
2023-07-07T07:53:41.419320955Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
2023-07-07T07:53:41.419336087Z    33: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
2023-07-07T07:53:41.419345919Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
2023-07-07T07:53:41.419501622Z    34: tokio::runtime::scheduler::multi_thread::worker::Context::run
2023-07-07T07:53:41.419506513Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
2023-07-07T07:53:41.420097267Z    35: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
2023-07-07T07:53:41.420107756Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
2023-07-07T07:53:41.420120120Z    36: tokio::macros::scoped_tls::ScopedKey<T>::set
2023-07-07T07:53:41.420138976Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
2023-07-07T07:53:41.420167778Z    37: tokio::runtime::scheduler::multi_thread::worker::run
2023-07-07T07:53:41.420179139Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
2023-07-07T07:53:41.420728934Z    38: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
2023-07-07T07:53:41.420737055Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
2023-07-07T07:53:41.420739367Z    39: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
2023-07-07T07:53:41.420741362Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
2023-07-07T07:53:41.420769091Z    40: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
2023-07-07T07:53:41.420778178Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
2023-07-07T07:53:41.421226692Z    41: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
2023-07-07T07:53:41.421239869Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
2023-07-07T07:53:41.421258590Z    42: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
2023-07-07T07:53:41.421266876Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
2023-07-07T07:53:41.421291680Z    43: tokio::runtime::task::core::Core<T,S>::poll
2023-07-07T07:53:41.421300690Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
2023-07-07T07:53:41.421639023Z    44: tokio::runtime::task::harness::poll_future::{{closure}}
2023-07-07T07:53:41.421651909Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
2023-07-07T07:53:41.421693602Z    45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2023-07-07T07:53:41.421702372Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
2023-07-07T07:53:41.421715321Z    46: std::panicking::try::do_call
2023-07-07T07:53:41.421722150Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
2023-07-07T07:53:41.421735967Z    47: std::panicking::try
2023-07-07T07:53:41.421750182Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
2023-07-07T07:53:41.421754313Z    48: std::panic::catch_unwind
2023-07-07T07:53:41.421785634Z               at ./rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
2023-07-07T07:53:41.421794838Z    49: tokio::runtime::task::harness::poll_future
2023-07-07T07:53:41.421798136Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
2023-07-07T07:53:41.421808152Z    50: tokio::runtime::task::harness::Harness<T,S>::poll_inner
2023-07-07T07:53:41.421818515Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
2023-07-07T07:53:41.421840557Z    51: tokio::runtime::task::harness::Harness<T,S>::poll
2023-07-07T07:53:41.421868506Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
2023-07-07T07:53:41.422268550Z    52: tokio::runtime::task::raw::RawTask::poll
2023-07-07T07:53:41.422275591Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
2023-07-07T07:53:41.422288647Z    53: tokio::runtime::task::UnownedTask<S>::run
2023-07-07T07:53:41.422315304Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
2023-07-07T07:53:41.422322427Z    54: tokio::runtime::blocking::pool::Task::run
2023-07-07T07:53:41.422335536Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
2023-07-07T07:53:41.422339135Z    55: tokio::runtime::blocking::pool::Inner::run
2023-07-07T07:53:41.422348486Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
2023-07-07T07:53:41.422401094Z    56: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
2023-07-07T07:53:41.422413175Z               at ./root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
2023-07-07T07:53:41.473299064Z  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

--1.创建表
```
create table test1(
id integer,
name varchar,
age smallint,
photo bytea);
```
--2.插入数据
```
insert into test1 values(1,'张三',29,'jfdj');
```
--3.查询数据
```
dev=> select * from test1;
 id | name | age |   photo    
----+------+-----+------------
  1 | 张三 |  29 | \x6a66646a
```
--4.go代码操作
```
var id []byte
	var name string
	var age []byte
	var photo string
	err = dbpool.QueryRow(context.Background(), "select id,name,age,photo from test1").Scan(&id, &name, &age, &photo)
	if err != nil {
		fmt.Fprintf(os.Stderr, "QueryRow failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println(id, "\t", name, "\t", age, "\t", photo)

	ct, err2 := dbpool.Exec(context.Background(), "insert into test1 values($1,'王五2',30,$2)", id, photo)
	if err2 != nil {
		fmt.Println("dbpool.Exec ERROR:", err2)
		return
	}
	fmt.Println("ct=", ct)
```
--5.go代码运行输出
```
PS D:\GoCode\pg_test1> go run main.go
[0 0 0 1]        张三    [0 29]          jfdj
dbpool.Exec ERROR: read tcp 58.206.163.80:50737->58.206.163.221:4566: wsarecv: An existing connection was forcibly closed by the remote host.
PS D:\GoCode\pg_test1>
```

### How did you deploy RisingWave?

[root@cernet2 docker]# cat docker-compose.yml 
---
version: "3"
services:
  compactor-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compactor-node
      - "--listen-addr"
      - "0.0.0.0:6660"
      - "--advertise-addr"
      - "compactor-0:6660"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1260"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "6660"
      - "1260"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compactor-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/6660
      interval: 1s
      timeout: 5s
      retries: 5
  compute-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - compute-node
      - "--listen-addr"
      - "0.0.0.0:5688"
      - "--advertise-addr"
      - "compute-node-0:5688"
      - "--prometheus-listener-addr"
      - "0.0.0.0:1222"
      - "--metrics-level"
      - "1"
      - "--meta-address"
      - "http://meta-node-0:5690"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5688"
      - "1222"
    ports: []
    depends_on:
      - meta-node-0
      - minio-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: compute-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5688
      interval: 1s
      timeout: 5s
      retries: 5
  etcd-0:
    image: "quay.io/coreos/etcd:v3.5.7"
    command:
      - /usr/local/bin/etcd
      - "--listen-client-urls"
      - "http://0.0.0.0:2388"
      - "--advertise-client-urls"
      - "http://etcd-0:2388"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2389"
      - "--initial-advertise-peer-urls"
      - "http://etcd-0:2389"
      - "--listen-metrics-urls"
      - "http://0.0.0.0:2379"
      - "--name"
      - risedev-meta
      - "--max-txn-ops"
      - "999999"
      - "--max-request-bytes"
      - "10485760"
      - "--auto-compaction-mode"
      - periodic
      - "--auto-compaction-retention"
      - 1m
      - "--snapshot-count"
      - "10000"
    expose:
      - "2388"
    ports:
      - "2388:2388"
      - "2389:2389"
    depends_on: []
    volumes:
      - "etcd-0:/etcd-data"
    environment: {}
    container_name: etcd-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/2388
      interval: 1s
      timeout: 5s
      retries: 5
  frontend-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - frontend-node
      - "--listen-addr"
      - "0.0.0.0:4566"
      - "--meta-addr"
      - "http://meta-node-0:5690"
      - "--advertise-addr"
      - "frontend-node-0:4566"
      - "--config-path"
      - /risingwave.toml
      - "--prometheus-listener-addr"
      - "0.0.0.0:2222"
      - "--metrics-level"
      - "1"
    expose:
      - "4566"
    ports:
      - "4566:4566"
    depends_on:
      - meta-node-0
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: frontend-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/4566
      interval: 1s
      timeout: 5s
      retries: 5
  grafana-0:
    image: "grafana/grafana-oss:latest"
    command: []
    expose:
      - "3001"
    ports:
      - "3001:3001"
    depends_on: []
    volumes:
      - "grafana-0:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana-risedev-datasource.yml:/etc/grafana/provisioning/datasources/grafana-risedev-datasource.yml"
      - "./grafana-risedev-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-risedev-dashboard.yml"
      - "./dashboards:/dashboards"
    environment: {}
    container_name: grafana-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/3001
      interval: 1s
      timeout: 5s
      retries: 5
  meta-node-0:
    image: "ghcr.io/risingwavelabs/risingwave:latest"
    command:
      - meta-node
      - "--listen-addr"
      - "0.0.0.0:5690"
      - "--advertise-addr"
      - "meta-node-0:5690"
      - "--dashboard-host"
      - "0.0.0.0:5691"
      - "--prometheus-host"
      - "0.0.0.0:1250"
      - "--backend"
      - etcd
      - "--etcd-endpoints"
      - "etcd-0:2388"
      - "--connector-rpc-endpoint"
      - "connector-node:50051"
      - "--state-store"
      - "hummock+minio://hummockadmin:hummockadmin@minio-0:9301/hummock001"
      - "--data-directory"
      - "hummock_001"
      - "--config-path"
      - /risingwave.toml
    expose:
      - "5690"
      - "1250"
      - "5691"
    ports:
      - "5690:5690"
      - "5691:5691"
    depends_on:
      - "etcd-0"
    volumes:
      - "./risingwave.toml:/risingwave.toml"
    environment:
      RUST_BACKTRACE: "1"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: meta-node-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/5690
      interval: 1s
      timeout: 5s
      retries: 5
  minio-0:
    image: "quay.io/minio/minio:latest"
    command:
      - server
      - "--address"
      - "0.0.0.0:9301"
      - "--console-address"
      - "0.0.0.0:9400"
      - /data
    expose:
      - "9301"
      - "9400"
    ports:
      - "9301:9301"
      - "9400:9400"
    depends_on: []
    volumes:
      - "minio-0:/data"
    entrypoint: "

      /bin/sh -c '

      set -e

      mkdir -p \"/data/hummock001\"

      /usr/bin/docker-entrypoint.sh \"$$0\" \"$$@\"

      '"
    environment:
      MINIO_CI_CD: "1"
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_PROMETHEUS_URL: "http://prometheus-0:9500"
      MINIO_ROOT_PASSWORD: hummockadmin
      MINIO_ROOT_USER: hummockadmin
    container_name: minio-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9301
      interval: 1s
      timeout: 5s
      retries: 5
  prometheus-0:
    image: "prom/prometheus:latest"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=0.0.0.0:9500"
      - "--storage.tsdb.retention.time=30d"
    expose:
      - "9500"
    ports:
      - "9500:9500"
    depends_on: []
    volumes:
      - "prometheus-0:/prometheus"
      - "./prometheus.yaml:/etc/prometheus/prometheus.yml"
    environment: {}
    container_name: prometheus-0
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9500
      interval: 1s
      timeout: 5s
      retries: 5
  connector-node:
    image: ghcr.io/risingwavelabs/risingwave:latest
    entrypoint: "/risingwave/bin/connector-node/start-service.sh"
    ports:
      - 50051
      - 50052
    container_name: connector-node
  message_queue:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    command:
      - redpanda
      - start
      - "--smp"
      - "1"
      - "--reserve-memory"
      - 0M
      - "--memory"
      - 4G
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--check=false"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://message_queue:29092,OUTSIDE://localhost:9092"
    expose:
      - "29092"
      - "9092"
      - "9644"
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9644:9644"
      - "8081:8081"
    depends_on: []
    volumes:
      - "message_queue:/var/lib/redpanda/data"
    environment: {}
    container_name: message_queue
    healthcheck:
      test:
        - CMD
        - printf
        - ""
        - /dev/tcp/127.0.0.1/9092
      interval: 1s
      timeout: 5s
      retries: 5
volumes:
  etcd-0:
    external: false
  grafana-0:
    external: false
  minio-0:
    external: false
  prometheus-0:
    external: false
  message_queue:
    external: false
[root@cernet2 docker]# 

### The version of RisingWave

dev=> select version();
                                     version                                      
----------------------------------------------------------------------------------
 PostgreSQL 8.3-RisingWave-1.0.0-alpha (2e0614c405c169899c98617f5d2944646341de02)

[root@cernet2 docker]# docker images
REPOSITORY                                 TAG                                 IMAGE ID       CREATED         SIZE
ghcr.io/risingwavelabs/risingwave          latest                              038734b58dd6   4 days ago      2.8GB

### Additional context

![image](https://github.com/risingwavelabs/risingwave/assets/34911052/321e7f17-d8a3-47ec-912f-45191c9e1b55)

**Comment by fuyufjh** [comment]
Thanks for the feedback!

@xiangjinwu Can you please take a look? Feel free to reassign

**Comment by xiangjinwu** [comment]
The panic happens because rust `str` allows `'\0'` but PostgreSQL wire protocol (using C null-terminated string) disallows it. This can be fixed in several layers:
* The frontend should not panic when it encounters problems during transmission over one connection. It should just reset/close this connection. #11084
* The transmission layer should be able to handle the difference between rust and c string. The `\0` char can be skipped or replaced by U+2400 (␀). This is not implemented because it incurs extra runtime cost and hides the problem deeper.
* The generated error message should not contain `\0` char. Furthermore, it should not contain user input without sanitization. In this case, the error is generated [here](https://github.com/risingwavelabs/risingwave/blob/v1.0.0/src/common/src/types/mod.rs#L889) when parsing an int32-typed parameter declared to be in text format (1-byte ascii 0x31) but actually sent in binary format (4-byte [0 0 0 1]). The parameter parsing implementation will be fixed when it is unified with cast-from-string #8669

I was not able to repro with the exact steps, because passing [0 0 0 1] as int32 is directly rejected by pgx v4.18.1 client library before it is sent to risingwave:
```
[0 0 0 1] 	 张三 	 [0 29] 	 jfdj
dbpool.Exec ERROR: cannot convert [0 0 0 1] to Int4
```

So in practice, a good client library would not send such invalid request. But when it did, we would not panic after any one of the fixes above.
