### ISSUE TITLE
panic during psycopg2 library testing

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#10935]
### Describe the bug

Risingwave paniced during execution of query using psycopg2 (python) library

```
>       cursor.execute("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sample_table');")
E       psycopg2.OperationalError: server closed the connection unexpectedly
E       	This probably means the server terminated abnormally
E       	before or while processing the request.

test_database.py:55: OperationalError
```

[Screencast from 13-07-23 04:00:16 PM IST.webm](https://github.com/risingwavelabs/risingwave/assets/70817539/86ff81ef-0bd4-4208-9503-5996cf292eac)

### Error message/log

```text
frontend-node-0  | thread 'risingwave-main' panicked at 'internal error: entered unreachable code', src/frontend/src/scheduler/distributed/stage.rs:914:21
frontend-node-0  | stack backtrace:
compute-node-0   | 2023-07-13T09:52:07.788890Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 4719032845860864 is sealed
frontend-node-0  |    0: rust_begin_unwind
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
frontend-node-0  |    1: core::panicking::panic_fmt
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
frontend-node-0  |    2: core::panicking::panic
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:114:5
frontend-node-0  |    3: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:914:21
frontend-node-0  |    4: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:949:25
frontend-node-0  |    5: core::iter::adapters::map::map_fold::{{closure}}
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
frontend-node-0  |    6: core::iter::traits::iterator::Iterator::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
frontend-node-0  |    7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
frontend-node-0  |    8: core::iter::traits::iterator::Iterator::for_each
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
frontend-node-0  |    9: alloc::vec::Vec<T,A>::extend_trusted
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
frontend-node-0  |   10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
frontend-node-0  |   11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
frontend-node-0  |   12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
frontend-node-0  |   13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
frontend-node-0  |   14: core::iter::traits::iterator::Iterator::collect
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
frontend-node-0  |   15: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:951:22
frontend-node-0  |   16: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:949:25
frontend-node-0  |   17: core::iter::adapters::map::map_fold::{{closure}}
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
frontend-node-0  |   18: core::iter::traits::iterator::Iterator::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
frontend-node-0  |   19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
frontend-node-0  |   20: core::iter::traits::iterator::Iterator::for_each
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
frontend-node-0  |   21: alloc::vec::Vec<T,A>::extend_trusted
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
frontend-node-0  |   22: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
frontend-node-0  |   23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
frontend-node-0  |   24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
frontend-node-0  |   25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
frontend-node-0  |   26: core::iter::traits::iterator::Iterator::collect
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
frontend-node-0  |   27: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:951:22
frontend-node-0  |   28: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:949:25
frontend-node-0  |   29: core::iter::adapters::map::map_fold::{{closure}}
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
frontend-node-0  |   30: core::iter::traits::iterator::Iterator::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
frontend-node-0  |   31: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
frontend-node-0  |   32: core::iter::traits::iterator::Iterator::for_each
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
frontend-node-0  |   33: alloc::vec::Vec<T,A>::extend_trusted
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
frontend-node-0  |   34: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
frontend-node-0  |   35: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
frontend-node-0  |   36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
frontend-node-0  |   37: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
frontend-node-0  |   38: core::iter::traits::iterator::Iterator::collect
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
frontend-node-0  |   39: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:951:22
frontend-node-0  |   40: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:949:25
frontend-node-0  |   41: core::iter::adapters::map::map_fold::{{closure}}
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
frontend-node-0  |   42: core::iter::traits::iterator::Iterator::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
frontend-node-0  |   43: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
frontend-node-0  |   44: core::iter::traits::iterator::Iterator::for_each
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
frontend-node-0  |   45: alloc::vec::Vec<T,A>::extend_trusted
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
frontend-node-0  |   46: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
frontend-node-0  |   47: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
frontend-node-0  |   48: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
frontend-node-0  |   49: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
frontend-node-0  |   50: core::iter::traits::iterator::Iterator::collect
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
frontend-node-0  |   51: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:951:22
frontend-node-0  |   52: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:949:25
frontend-node-0  |   53: core::iter::adapters::map::map_fold::{{closure}}
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
frontend-node-0  |   54: core::iter::traits::iterator::Iterator::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
frontend-node-0  |   55: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
frontend-node-0  |   56: core::iter::traits::iterator::Iterator::for_each
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
frontend-node-0  |   57: alloc::vec::Vec<T,A>::extend_trusted
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
frontend-node-0  |   58: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
frontend-node-0  |   59: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
frontend-node-0  |   60: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
frontend-node-0  |   61: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
frontend-node-0  |   62: core::iter::traits::iterator::Iterator::collect
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
frontend-node-0  |   63: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:951:22
frontend-node-0  |   64: risingwave_frontend::scheduler::distributed::stage::StageRunner::create_plan_fragment
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:852:13
frontend-node-0  |   65: risingwave_frontend::scheduler::distributed::stage::StageRunner::schedule_tasks_for_root::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:556:29
frontend-node-0  |   66: risingwave_frontend::scheduler::distributed::stage::StageRunner::schedule_tasks_for_all::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:636:54
frontend-node-0  |   67: risingwave_frontend::scheduler::distributed::stage::StageRunner::run::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:306:65
frontend-node-0  |   68: risingwave_frontend::scheduler::distributed::stage::StageExecution::start::{{closure}}::{{closure}}
frontend-node-0  |              at ./risingwave/src/frontend/src/scheduler/distributed/stage.rs:221:56
frontend-node-0  |   69: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
frontend-node-0  |   70: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
frontend-node-0  |   71: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
frontend-node-0  |   72: tokio::runtime::task::core::Core<T,S>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
frontend-node-0  |   73: tokio::runtime::task::harness::poll_future::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
frontend-node-0  |   74: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
frontend-node-0  |   75: std::panicking::try::do_call
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
frontend-node-0  |   76: std::panicking::try
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
frontend-node-0  |   77: std::panic::catch_unwind
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
frontend-node-0  |   78: tokio::runtime::task::harness::poll_future
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
frontend-node-0  |   79: tokio::runtime::task::harness::Harness<T,S>::poll_inner
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
frontend-node-0  |   80: tokio::runtime::task::harness::Harness<T,S>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
frontend-node-0  |   81: tokio::runtime::task::raw::RawTask::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
frontend-node-0  |   82: tokio::runtime::task::LocalNotified<S>::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
frontend-node-0  |   83: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
frontend-node-0  |   84: tokio::runtime::coop::with_budget
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
frontend-node-0  |   85: tokio::runtime::coop::budget
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
frontend-node-0  |   86: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
frontend-node-0  |   87: tokio::runtime::scheduler::multi_thread::worker::Context::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
frontend-node-0  |   88: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
frontend-node-0  |   89: tokio::macros::scoped_tls::ScopedKey<T>::set
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
frontend-node-0  |   90: tokio::runtime::scheduler::multi_thread::worker::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
frontend-node-0  |   91: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
frontend-node-0  |   92: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
frontend-node-0  |   93: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
frontend-node-0  |   94: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
frontend-node-0  |   95: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
frontend-node-0  |   96: tokio::runtime::task::core::Core<T,S>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
frontend-node-0  |   97: tokio::runtime::task::harness::poll_future::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
frontend-node-0  |   98: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
frontend-node-0  |   99: std::panicking::try::do_call
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
frontend-node-0  |  100: std::panicking::try
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
frontend-node-0  |  101: std::panic::catch_unwind
frontend-node-0  |              at ./rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
frontend-node-0  |  102: tokio::runtime::task::harness::poll_future
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
frontend-node-0  |  103: tokio::runtime::task::harness::Harness<T,S>::poll_inner
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
frontend-node-0  |  104: tokio::runtime::task::harness::Harness<T,S>::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
frontend-node-0  |  105: tokio::runtime::task::raw::RawTask::poll
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
frontend-node-0  |  106: tokio::runtime::task::UnownedTask<S>::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
frontend-node-0  |  107: tokio::runtime::blocking::pool::Task::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
frontend-node-0  |  108: tokio::runtime::blocking::pool::Inner::run
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
frontend-node-0  |  109: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
frontend-node-0  |              at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
frontend-node-0  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
frontend-node-0 exited with code 139
compute-node-0   | 2023-07-13T09:52:08.789592Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 4719032911724544 is sealed
meta-node-0      | 2023-07-13T09:52:08.790089Z  WARN risingwave_meta::manager::notification: Failed to notify Frontend WorkerKey(HostAddress { host: "frontend-node-0", port: 4566 }): channel close
```

### To Reproduce

First create a table 
`CREATE TABLE sample_table;
`
Then execute this query to check if table exists
`SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sample_table');`

### Expected behavior

 ?column? 
----------
 t
(1 row)

### How did you deploy RisingWave?

git clone https://github.com/risingwavelabs/risingwave.git
cd risingwave/docker
docker compose up

### The version of RisingWave

```
                                      version                                      
-----------------------------------------------------------------------------------
 PostgreSQL 13.9-RisingWave-0.2.0-alpha (c683098c18d2cc41ced29ca57a0cf6462bc71818)
(1 row)
```

**Comment by zwang28** [comment]
The panic is from frontend, and cannot be reproduced locally via
```
CREATE TABLE sample_table; 
SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'sample_table');
```

**Comment by zwang28** [comment]
Frontend did use a very old kernel version `c683098c18d2cc41ced29ca57a0cf6462bc71818 ` (it's created on March), according to the `version()` provided by reporter. 

I suspect there are tests incorrectly performed over old kernel version.. @lmatz @huangjw806

**Comment by lmatz** [comment]
> If old container with old latest tagged image is reused by mistake sometimes during tests, I suspect there can be tests incorrectly performed over old kernel version..

True, 

A while ago, I supported running a certain version for tests such as integration tests (which uses `docker-compose.yml`) on Buildkite, @huangjw806 probably we can also make daily integration tests and any other tests that use `docker-compose.yml` to use a specified version.

For other tests such as longevity and performance tests, the version is explicitly specified via Buildkite.


@abhyuday26  please use `1.0` or the latest nightly image to test, you can find here:
https://github.com/risingwavelabs/risingwave/pkgs/container/risingwave/versions

**Comment by zwang28** [comment]
Confirmed the issue is only reproducible in old version `c683098c18d2cc41ced29ca57a0cf6462bc71818 `.
