### ISSUE TITLE
UDF panics on wrong/malicious get_flight_info

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#11022]
### Describe the bug

run a flight service with this impl
```rust
    async fn get_flight_info(
        &self,
        _request: Request<FlightDescriptor>,
    ) -> Result<Response<FlightInfo>, Status> {
        let schema =
            arrow_schema::Schema::new(vec![Field::new("a", arrow_schema::DataType::Int32, false)]);
        let schema: SchemaResult = SchemaAsIpc::new(&schema, &IpcWriteOptions::default())
            .try_into()
            .unwrap();

        let info = FlightInfo {
            schema: schema.schema,
            total_records: 2, // WRONG VALUE
            ..Default::default()
        };
        Ok(Response::new(info))
    }
```

### Error message/log

```text
thread 'risingwave-main' panicked at 'assertion failed: mid <= self.len()', /Users/xxchan/Projects/risingwave/src/udf/src/external.rs:50:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:117:5
   3: core::slice::<impl [T]>::split_at
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/slice/mod.rs:1863:9
   4: risingwave_udf::external::ArrowFlightUdfClient::check::{{closure}}
             at ./src/udf/src/external.rs:50:45
   5: risingwave_frontend::handler::create_function::handle_create_function::{{closure}}
             at ./src/frontend/src/handler/create_function.rs:144:10
```

### Additional context

https://github.com/risingwavelabs/risingwave/issues/9002

**Comment by fuyufjh** [comment]
Ping @wangrunji0408
