### ISSUE TITLE
Bug(sink): Create iceberg sink error.

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave#11091]
### Describe the bug

1. create table in iceberg
`create table demo.demo_db.demo_test(user_id string, target_id string, event_timestamp string) TBLPROPERTIES ('format-version'='2');`
2. create source;
    `CREATE source user_behaviors (
    user_id VARCHAR,
    target_id VARCHAR,
    target_type VARCHAR,
    event_timestamp VARCHAR,
    behavior_type VARCHAR,
    parent_target_type VARCHAR,
    parent_target_id VARCHAR,
) WITH (
    connector = 'datagen',
     fields.seq_id.kind = 'sequence',
     fields.seq_id.start = '1',
     fields.seq_id.end = '10000000',
     fields.user_id.kind = 'random',
     fields.user_id.min = '1',
     fields.user_id.max = '10000000',
     fields.user_name.kind = 'random',
     fields.user_name.length = '10',
     datagen.rows.per.second = '20000'
) FORMAT PLAIN ENCODE JSON;` 
3. create mv;
 `CREATE MATERIALIZED VIEW bhv_mv AS
SELECT
    user_id,
    target_id,
    event_timestamp
FROM
    user_behaviors;`
4. create sink;
`CREATE SINK s6 from bhv_mv WITH (
     connector = 'iceberg',
    type = 'append-only',
    warehouse.path = 's3://iceberg',
    s3.endpoint = 'http://127.0.0.1:9301',
    s3.access.key = 'hummockadmin',
    s3.secret.key = 'hummockadmin',
    database.name='demo_db',
    table.name='demo_test'
);`
error:
```
thread 'risingwave-streaming-actor' panicked at 'index 3 out of bounds for row of length 1', /Users/xinhaoxu/xxhx/singuarity/risingwave/src/common/src/row/project.rs:62:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: risingwave_common::row::project::Project<R>::new
             at ./src/common/src/row/project.rs:62:13
   3: risingwave_common::row::RowExt::project
             at ./src/common/src/row/mod.rs:153:20
   4: risingwave_stream::executor::backfill::utils::mark_chunk_inner::{{closure}}
             at ./src/stream/src/executor/backfill/utils.rs:170:19
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:305:13
   6: core::option::Option<T>::map
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/option.rs:1075:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:103:26
   8: risingwave_stream::executor::backfill::utils::mark_chunk_inner
             at ./src/stream/src/executor/backfill/utils.rs:168:14
   9: risingwave_stream::executor::backfill::utils::mark_chunk
             at ./src/stream/src/executor/backfill/utils.rs:112:5
  10: risingwave_stream::executor::backfill::no_shuffle_backfill::BackfillExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/backfill/no_shuffle_backfill.rs:278:49
  11: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  12: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  13: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  14: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  15: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  16: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:124:23
  17: risingwave_stream::executor::wrapper::trace::instrument_await_tree::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:100:10
  18: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  19: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:24:1
  20: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  21: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  22: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  23: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  24: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_check.rs:31:44
  25: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  26: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  27: <S as futures_core::stream::TryStream>::try_poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:196:9
  28: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/mod.rs:1068:9
  29: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/try_stream/try_next.rs:32:9
  30: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:348:35
  31: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:233:19
  32: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:345:13
  33: risingwave_common::util::epoch::task_local::scope::{{closure}}
             at ./src/common/src/util/epoch.rs:181:47
  34: risingwave_stream::executor::wrapper::epoch_provide::epoch_provide::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_provide.rs:31:59
  35: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  36: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  37: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  38: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  39: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  40: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:46:69
  41: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  42: risingwave_stream::executor::wrapper::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/wrapper/update_check.rs:27:1
  43: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  44: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  45: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  46: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./src/stream/src/executor/dispatch.rs:258:9
  47: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.6/src/lib.rs:463:33
  48: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  49: <&mut S as futures_core::stream::Stream>::poll_next
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:104:9
  50: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/git/checkouts/tokio-968c02b7a1a41bea/ab251ad/tokio-stream/src/stream_ext/next.rs:42:9
  51: <tokio_stream::stream_ext::try_next::TryNext<St> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/git/checkouts/tokio-968c02b7a1a41bea/ab251ad/tokio-stream/src/stream_ext/try_next.rs:43:9
  52: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  53: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/future.rs:124:23
  54: risingwave_stream::executor::actor::Actor<C>::run_consumer::{{closure}}
             at ./src/stream/src/executor/actor.rs:190:18
  55: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/maybe_done.rs:68:48
  56: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/join.rs:126:24
  57: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/future/poll_fn.rs:58:9
  58: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:154:9
  59: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:654:51
  60: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:348:35
  61: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:233:19
  62: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:345:13
  63: await_tree::registry::TreeRoot::instrument::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.1.1/src/registry.rs:51:45
  64: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/either.rs:109:32
  65: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.1.0/src/task.rs:2365:19
  66: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  67: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  68: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  69: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  70: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  71: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  72: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  73: ___rust_try
  74: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  75: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  76: tokio::runtime::task::harness::poll_future
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  77: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  78: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  79: tokio::runtime::task::raw::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
  80: tokio::runtime::task::raw::RawTask::poll
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  81: tokio::runtime::task::LocalNotified<S>::run
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  82: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  83: tokio::runtime::coop::with_budget
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  84: tokio::runtime::coop::budget
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  85: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  86: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  87: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  88: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  89: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  90: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/xinhaoxu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by xxhZs** [comment]
May be related https://github.com/risingwavelabs/risingwave/pull/10266

**Comment by fuyufjh** [comment]
Any updates?

**Comment by liurenjie1024** [comment]
I'll try later.

**Comment by liurenjie1024** [comment]
No longer happens. Feel free to open it when happens again.
