### ISSUE TITLE
bug(frontend): panicked at unreachable code: CorrelatedInputRef

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11290]
### Describe the bug

```sql
CREATE TABLE data (
    id INT PRIMARY KEY,
    author JSONB ,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    reactions JSONB[]
);

-- panicked
SELECT
'discord-' || id AS doc_id,
(author->>'id'):: text AS author_id,
timestamp AS created_at,
(SELECT SUM((r->'count')::integer) FROM UNNEST (reactions) r) AS cnt
FROM data raw
```

```
ERROR:  Panicked when processing: internal error: entered unreachable code: CorrelatedInputRef CorrelatedInputRef { index: 3, correlated_id: 0 } has not been decorrelated.
```

### Error message/log

```text
thread 'risingwave-main' panicked at 'internal error: entered unreachable code: CorrelatedInputRef CorrelatedInputRef { index: 3, correlated_id: 0 } has not been decorrelated', src/frontend/src/expr/correlated_input_ref.rs:84:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: <risingwave_frontend::expr::correlated_input_ref::CorrelatedInputRef as risingwave_frontend::expr::Expr>::to_expr_proto
             at ./src/frontend/src/expr/correlated_input_ref.rs:84:9
   3: <risingwave_frontend::expr::ExprImpl as risingwave_frontend::expr::Expr>::to_expr_proto
             at ./src/frontend/src/expr/mod.rs:107:45
   4: risingwave_frontend::expr::table_function::TableFunction::to_protobuf::{{closure}}
             at ./src/frontend/src/expr/table_function.rs:85:44
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
   9: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  15: itertools::Itertools::collect_vec
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.10.5/src/lib.rs:1985:14
  16: risingwave_frontend::expr::table_function::TableFunction::to_protobuf
             at ./src/frontend/src/expr/table_function.rs:85:63
  17: <risingwave_frontend::optimizer::plan_node::batch_table_function::BatchTableFunction as risingwave_frontend::optimizer::plan_node::to_prost::ToBatchPb>::to_batch_prost_body
             at ./src/frontend/src/optimizer/plan_node/batch_table_function.rs:69:34
  18: <risingwave_frontend::scheduler::plan_fragmenter::ExecutionPlanNode as core::convert::From<risingwave_frontend::optimizer::plan_node::PlanRef>>::from
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:107:19
  19: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::visit_node
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:831:47
  20: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::visit_node
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:834:21
  21: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::visit_node
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:834:21
  22: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::visit_node
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:834:21
  23: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::visit_node
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:834:21
  24: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::new_stage
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:815:9
  25: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::split_into_stage
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:168:26
  26: risingwave_frontend::scheduler::plan_fragmenter::BatchPlanFragmenter::new
             at ./src/frontend/src/scheduler/plan_fragmenter.rs:162:9
  27: risingwave_frontend::handler::query::gen_batch_plan_fragmenter
             at ./src/frontend/src/handler/query.rs:285:27
  28: risingwave_frontend::handler::query::handle_query::{{closure}}
             at ./src/frontend/src/handler/query.rs:64:9
  29: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:359:88
  30: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9
  31: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session>::run_one_query::{{closure}}
             at ./src/frontend/src/session.rs:947:28
  32: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg_one_stmt::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:447:14
  33: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  34: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:429:18
  35: pgwire::pg_protocol::PgProtocol<S,SM>::process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:387:65
  36: pgwire::pg_protocol::PgProtocol<S,SM>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:256:88
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:296:9
  38: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  40: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  41: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  42: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  43: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  44: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:348:35
  45: tokio::task::task_local::LocalKey<T>::scope_inner
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:233:19
  46: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:345:13
  47: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:186:14
  48: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:177:30
  49: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:176:45
  50: pgwire::pg_server::handle_connection::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:161:1
  51: <F as futures_core::future::TryFuture>::try_poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
  52: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_future/into_future.rs:34:9
  53: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/map.rs:55:37
  54: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
  55: <futures_util::future::try_future::InspectErr<Fut,F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
  56: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  57: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  58: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  59: tokio::runtime::task::core::Core<T,S>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  60: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  61: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  62: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  63: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  64: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  65: tokio::runtime::task::harness::poll_future
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  66: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  67: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  68: tokio::runtime::task::raw::RawTask::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  69: tokio::runtime::task::LocalNotified<S>::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
  70: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:464:18
  71: tokio::runtime::coop::with_budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
  72: tokio::runtime::coop::budget
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
  73: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  74: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  75: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  76: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
  77: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  78: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  79: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
  80: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  81: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  82: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  83: tokio::runtime::task::core::Core<T,S>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  84: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  85: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  86: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  87: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  88: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  89: tokio::runtime::task::harness::poll_future
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  90: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  91: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  92: tokio::runtime::task::raw::RawTask::poll
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
  93: tokio::runtime::task::UnownedTask<S>::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
  94: tokio::runtime::blocking::pool::Task::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
  95: tokio::runtime::blocking::pool::Inner::run
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
  96: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
```


### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

**Comment by chenzl25** [comment]
After these 3 PRs, we support this correlated subquery!
https://github.com/risingwavelabs/risingwave/pull/11422
https://github.com/risingwavelabs/risingwave/pull/11404
https://github.com/risingwavelabs/risingwave/pull/11390
