### ISSUE TITLE
`array[]::STRUCT<s1_c1_integer INT>[]` doesn't work properly

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#11352]
### Describe the bug

```
dev=> select array[]::STRUCT<s1_c1_integer INT>[];
ERROR:  Panicked when processing: called `Result::unwrap()` on an `Err` value: UnsupportedFunction("cast(varchar) -> struct").
This is a bug. We would appreciate a bug report at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Fbug&template=bug_report.yml
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

### Error message/log

```text
thread 'risingwave-main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedFunction("cast(varchar) -> struct")', src/expr/src/vector_op/cast.rs:390:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1076:23
   4: risingwave_expr::vector_op::cast::list_cast
             at ./src/expr/src/vector_op/cast.rs:385:16
   5: risingwave_expr::vector_op::cast::build_cast_list_to_list::{{closure}}
             at ./src/expr/src/vector_op/cast.rs:375:18
   6: <risingwave_expr::expr::template::UnaryExpression<IA1,OA,F> as risingwave_expr::expr::Expression>::eval_row::{{closure}}
             at ./src/expr/src/expr/template.rs:364:1
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9
   8: risingwave_frontend::expr::ExprImpl::eval_row::{{closure}}
             at ./src/frontend/src/expr/mod.rs:309:41
   9: futures_util::future::future::FutureExt::now_or_never
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:605:15
  10: risingwave_frontend::expr::ExprImpl::try_fold_const
             at ./src/frontend/src/expr/mod.rs:320:13
  11: <risingwave_frontend::optimizer::plan_expr_rewriter::const_eval_rewriter::ConstEvalRewriter as risingwave_frontend::expr::expr_rewriter::ExprRewriter>::rewrite_expr
             at ./src/frontend/src/optimizer/plan_expr_rewriter/const_eval_rewriter.rs:27:31
  12: <risingwave_frontend::optimizer::plan_node::logical_values::LogicalValues as risingwave_frontend::optimizer::plan_node::expr_rewritable::ExprRewritable>::rewrite_exprs::{{closure}}::{{closure}}
             at ./src/frontend/src/optimizer/plan_node/logical_values.rs:126:30
  13: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
  14: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
  16: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
  17: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  18: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  19: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  21: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  22: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  23: <risingwave_frontend::optimizer::plan_node::logical_values::LogicalValues as risingwave_frontend::optimizer::plan_node::expr_rewritable::ExprRewritable>::rewrite_exprs::{{closure}}
             at ./src/frontend/src/optimizer/plan_node/logical_values.rs:124:17
  24: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
  25: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
  26: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
  27: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
  28: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  29: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  30: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  31: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  32: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  33: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  34: <risingwave_frontend::optimizer::plan_node::logical_values::LogicalValues as risingwave_frontend::optimizer::plan_node::expr_rewritable::ExprRewritable>::rewrite_exprs
             at ./src/frontend/src/optimizer/plan_node/logical_values.rs:120:20
  35: <risingwave_frontend::optimizer::plan_node::batch_values::BatchValues as risingwave_frontend::optimizer::plan_node::expr_rewritable::ExprRewritable>::rewrite_exprs
             at ./src/frontend/src/optimizer/plan_node/batch_values.rs:108:13
  36: <risingwave_frontend::optimizer::plan_node::PlanRef as risingwave_frontend::optimizer::plan_node::expr_rewritable::ExprRewritable>::rewrite_exprs
             at ./src/frontend/src/optimizer/plan_node/expr_rewritable.rs:42:13
  37: <risingwave_frontend::optimizer::plan_node::PlanRef as risingwave_frontend::optimizer::plan_node::RewriteExprsRecursive>::rewrite_exprs_recursive
             at ./src/frontend/src/optimizer/plan_node/mod.rs:211:19
  38: risingwave_frontend::optimizer::const_eval_exprs
             at ./src/frontend/src/optimizer/mod.rs:570:16
  39: risingwave_frontend::optimizer::PlanRoot::gen_batch_plan
             at ./src/frontend/src/optimizer/mod.rs:194:16
  40: risingwave_frontend::handler::query::gen_batch_query_plan
             at ./src/frontend/src/handler/query.rs:175:22
  41: risingwave_frontend::handler::query::gen_batch_plan_by_statement
             at ./src/frontend/src/handler/query.rs:109:5
  42: risingwave_frontend::handler::query::handle_query::{{closure}}
             at ./src/frontend/src/handler/query.rs:63:27
  43: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:380:88
  44: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9
  45: <&mut F as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:113:9
  46: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/time/timeout.rs:202:33
  47: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session>::run_one_query::{{closure}}
             at ./src/frontend/src/session.rs:938:88
  48: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg_one_stmt::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:447:14
  49: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  50: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:429:18
  51: pgwire::pg_protocol::PgProtocol<S,SM>::process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:387:65
  52: pgwire::pg_protocol::PgProtocol<S,SM>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:256:88
  53: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:296:9
  54: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  55: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  56: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  57: ___rust_try
  58: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  59: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  60: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  61: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:348:35
  62: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:233:19
  63: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/task/task_local.rs:345:13
  64: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:186:14
  65: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:177:30
  66: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:176:45
  67: pgwire::pg_server::handle_connection::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:161:1
  68: <F as futures_core::future::TryFuture>::try_poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/future.rs:82:9
  69: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/try_future/into_future.rs:34:9
  70: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/map.rs:55:37
  71: <futures_util::future::future::Inspect<Fut,F> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
  72: <futures_util::future::try_future::InspectErr<Fut,F> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:91:13
  73: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  75: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
  78: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  81: ___rust_try
  82: std::panicking::try
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  83: std::panic::catch_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  84: tokio::runtime::task::harness::poll_future
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
  85: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
  86: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
  87: tokio::runtime::task::raw::poll
             at /Users/liuchengyou/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:255:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-08-01T14:25:16.246263+08:00 ERROR pgwire::pg_protocol: error when process message error=Panicked when processing: called `Result::unwrap()` on an `Err` value: UnsupportedFunction("cast(varchar) -> struct").
This is a bug. We would appreciate a bug report at https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Fbug&template=bug_report.yml
```

**Comment by xiangjinwu** [comment]
The error refers to #7369, which is generally not useful except the special case here. I will attempt a fix without that.
