### ISSUE TITLE
bug: null value of timestamp is not well handled in pgwire

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#11392]
### Describe the bug

The java program below returned this error:
```
org.postgresql.util.PSQLException: ERROR: ParseError: internal error: Unsupported oid 0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at DatabaseTest.main(DatabaseTest.java:29)
```

### Error message/log

```text
2023-08-02T19:18:23.143837+08:00 ERROR pgwire::pg_protocol: error when process message error=ParseError: internal error: Unsupported oid 0
thread 'risingwave-main' panicked at 'range end out of bounds: 18446744073709551615 <= 2', /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:261:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
   2: bytes::bytes::Bytes::slice
             at /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:261:9
   3: <bytes::bytes::Bytes as bytes::buf::buf_impl::Buf>::copy_to_bytes
             at /Users/wutao/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.4.0/src/bytes.rs:565:23
   4: pgwire::pg_message::FeBindMessage::parse::{{closure}}
             at ./src/utils/pgwire/src/pg_message.rs:180:17
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:84:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:2481:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/adapters/map.rs:124:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:856:9
   9: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2843:17
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_extend.rs:26:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/vec/mod.rs:2711:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/iter/traits/iterator.rs:1895:9
  15: pgwire::pg_message::FeBindMessage::parse
             at ./src/utils/pgwire/src/pg_message.rs:177:22
  16: pgwire::pg_message::FeMessage::read::{{closure}}
             at ./src/utils/pgwire/src/pg_message.rs:274:21
  17: pgwire::pg_protocol::PgStream<S>::read::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:833:40
  18: pgwire::pg_protocol::Conn<S>::read::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:925:38
  19: pgwire::pg_protocol::PgProtocol<S,SM>::read_message::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:274:60
```

### To Reproduce

```java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DatabaseTest {
    public static void main(String[] args) {

        String url = "jdbc:postgresql://localhost:4566/dev"; // Replace with your url
        String user = "root"; // Replace with your username
        String password = ""; // Replace with your password

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            // Create table
            String createTableQuery = "CREATE TABLE IF NOT EXISTS t (v TIMESTAMP)";

            PreparedStatement createTableStatement = connection.prepareStatement(createTableQuery);
            createTableStatement.execute();

            // Insert into table
            String insertQuery = "INSERT INTO t (v) VALUES (?) ";

            PreparedStatement insertStatement = connection.prepareStatement(insertQuery);

            // Fill in the placeholders
            insertStatement.setTimestamp(1, null);

            insertStatement.execute();

        } catch (SQLException e) {
            System.out.println("Error while interacting with the database");
            e.printStackTrace();
        }
    }
}
```

**Comment by ZENOTME** [comment]
I will take a look later.
