### ISSUE TITLE
bug(meta): deterministic test failure: assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11792]
### Describe the bug

https://buildkite.com/risingwavelabs/main/builds/5363#018a02c1-2a99-4236-891a-866aa696a68a

Panicked at:

https://github.com/risingwavelabs/risingwave/blob/88a4daca851bf23bea68065426779aeea105bd8d/src/meta/src/stream/stream_manager.rs#L942

### Error message/log

```text
[2K_bk;t=1692263511558[31;1m        FAIL[0m [   0.706s] [35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m

_bk;t=1692263511558

_bk;t=1692263511558[31;1m--- [0m[31;1mSTDOUT:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692263511558

_bk;t=1692263511558running 1 test

_bk;t=1692263511558test is runner,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558test is drop,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558test stream::stream_manager::tests::test_drop_materialized_view ... FAILED

_bk;t=1692263511558

_bk;t=1692263511558failures:

_bk;t=1692263511558

_bk;t=1692263511558failures:

_bk;t=1692263511558    stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692263511558

_bk;t=1692263511558test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 116 filtered out; finished in 0.66s

_bk;t=1692263511558

_bk;t=1692263511558[0m

_bk;t=1692263511559[31;1m--- [0m[31;1mSTDERR:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692263511559thread '<unnamed>' panicked at 'assertion failed: `(left == right)`

_bk;t=1692263511559  left: `0`,

_bk;t=1692263511559 right: `4`', src/meta/src/stream/stream_manager.rs:942:9

_bk;t=1692263511559stack backtrace:

_bk;t=1692263511559   0: rust_begin_unwind

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5

_bk;t=1692263511559   1: core::panicking::panic_fmt

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14

_bk;t=1692263511559   2: core::panicking::assert_failed_inner

_bk;t=1692263511559   3: core::panicking::assert_failed

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:228:5

_bk;t=1692263511559   4: risingwave_meta::stream::stream_manager::tests::test_drop_materialized_view::{{closure}}::{{closure}}

_bk;t=1692263511559             at ./src/stream/stream_manager.rs:942:9

_bk;t=1692263511559   5: madsim::sim::task::Executor::block_on::{{closure}}::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:230:32

_bk;t=1692263511559   6: <core::pin::Pin<P> as core::future::future::Future>::poll

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9

_bk;t=1692263511559   7: async_task::raw::RawTask<F,T,S,M>::run

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17

_bk;t=1692263511559   8: async_task::runnable::Runnable<M>::run

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18

_bk;t=1692263511559   9: madsim::sim::task::Executor::run_all_ready::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:50

_bk;t=1692263511559  10: std::panicking::try::do_call

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40

_bk;t=1692263511559  11: __rust_try

_bk;t=1692263511559  12: std::panicking::try

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19

_bk;t=1692263511559  13: std::panic::catch_unwind

_bk;t=1692263511559             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14

_bk;t=1692263511559  14: madsim::sim::task::Executor::run_all_ready

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:17

_bk;t=1692263511559  15: madsim::sim::task::Executor::block_on

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:238:13

_bk;t=1692263511559  16: madsim::sim::runtime::Runtime::block_on

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:9

_bk;t=1692263511559  17: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692263511559             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/builder.rs:128:35

_bk;t=1692263511559note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

_bk;t=1692263511559context: node=0 "main", task=320 (spawned at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:19)

_bk;t=1692263511559note: run with `MADSIM_TEST_SEED=1692263510861490596` environment variable to reproduce this error

_bk;t=1692263511559[0m

_bk;t=1692263511559[32;1m     Running[0m [ 00:00:04] [=>]  692/992 : [1m16[0m running, [1m692[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692263511559[31;1m     Running[0m [ 00:00:04] [=>]  692/992 : [1m16[0m running, [1m692[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692263511559[31;1m     Running[0m [ 00:00:04] []  693/992 : [1m15[0m running, [1m692[0m [32;1mpassed[0m, [1m1[0m [31;1mfailed[0m, [1m12[0m [33;1mskipped[0m     [1A
[2K_bk;t=1692263511560[1B
[2K_bk;t=1692263511560[1A[32;1m        PASS[0m [   0.356s] [35;1mrisingwave_storage[0m [36mhummock::conflict_detector::test[0m[36m::[0m[34;1mtest_write_to_archived_epoch[0m
```

**Comment by fuyufjh** [comment]
Found another failure with different error:

https://buildkite.com/risingwavelabs/main/builds/5358#018a0280-4fd9-40bd-abb7-e40edaf5b39b

```
_bk;t=1692259267423[32;1m     Running[0m [ 00:00:04] [=>]  707/992 : [1m16[0m running, [1m707[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692259267423[32;1m     Running[0m [ 00:00:04] [=>]  708/992 : [1m15[0m running, [1m708[0m [32;1mpassed[0m, [1m12[0m [33;1mskipped[0m     
[2K_bk;t=1692259267503[31;1m        FAIL[0m [   1.038s] [35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m

_bk;t=1692259267503

_bk;t=1692259267503[31;1m--- [0m[31;1mSTDOUT:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692259267503

_bk;t=1692259267503running 1 test

_bk;t=1692259267503test is runner,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692259267503test is drop,stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692259267503test stream::stream_manager::tests::test_drop_materialized_view ... FAILED

_bk;t=1692259267503

_bk;t=1692259267503failures:

_bk;t=1692259267503

_bk;t=1692259267503failures:

_bk;t=1692259267503    stream::stream_manager::tests::test_drop_materialized_view

_bk;t=1692259267503

_bk;t=1692259267503test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 116 filtered out; finished in 0.99s

_bk;t=1692259267503

_bk;t=1692259267503[0m

_bk;t=1692259267503[31;1m--- [0m[31;1mSTDERR:              [0m[35;1mrisingwave_meta[0m [36mstream::stream_manager::tests[0m[36m::[0m[34;1mtest_drop_materialized_view[0m[31;1m ---[0m

_bk;t=1692259267503thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', src/meta/src/stream/stream_manager.rs:715:79

_bk;t=1692259267503stack backtrace:

_bk;t=1692259267503   0: rust_begin_unwind

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5

_bk;t=1692259267503   1: core::panicking::panic_fmt

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14

_bk;t=1692259267503   2: core::result::unwrap_failed

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1651:5

_bk;t=1692259267503   3: core::result::Result<T,E>::unwrap

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1076:23

_bk;t=1692259267503   4: risingwave_meta::stream::stream_manager::tests::MockServices::start::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692259267503             at ./src/stream/stream_manager.rs:715:61

_bk;t=1692259267503   5: <core::pin::Pin<P> as core::future::future::Future>::poll

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9

_bk;t=1692259267503   6: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/fuse.rs:84:26

_bk;t=1692259267503   7: <&mut F as core::future::future::Future>::poll

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:113:9

_bk;t=1692259267503   8: <core::pin::Pin<P> as core::future::future::Future>::poll

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9

_bk;t=1692259267503   9: futures_util::future::future::FutureExt::poll_unpin

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9

_bk;t=1692259267503  10: madsim_tonic::sim::transport::server::Router<L>::serve_with_shutdown::{{closure}}::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/select_mod.rs:331:13

_bk;t=1692259267503  11: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:294:13

_bk;t=1692259267503  12: madsim_tonic::sim::transport::server::Router<L>::serve_with_shutdown::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/select_mod.rs:331:13

_bk;t=1692259267503  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/poll_fn.rs:56:9

_bk;t=1692259267503  14: madsim_tonic::sim::transport::server::Router<L>::serve_with_shutdown::{{closure}}::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-tonic-0.3.1+0.9.2/src/transport/server.rs:213:38

_bk;t=1692259267503  15: madsim_tonic::sim::transport::server::Router<L>::serve_with_shutdown::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-tonic-0.3.1+0.9.2/src/transport/server.rs:202:5

_bk;t=1692259267503  16: risingwave_meta::stream::stream_manager::tests::MockServices::start::{{closure}}::{{closure}}

_bk;t=1692259267503             at ./src/stream/stream_manager.rs:716:22

_bk;t=1692259267503  17: madsim::sim::task::Spawner::spawn_inner::{{closure}}::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:629:28

_bk;t=1692259267503  18: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:455:26

_bk;t=1692259267503  19: <core::pin::Pin<P> as core::future::future::Future>::poll

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/future/future.rs:125:9

_bk;t=1692259267503  20: async_task::raw::RawTask<F,T,S,M>::run

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17

_bk;t=1692259267503  21: async_task::runnable::Runnable<M>::run

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18

_bk;t=1692259267503  22: madsim::sim::task::Executor::run_all_ready::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:50

_bk;t=1692259267503  23: std::panicking::try::do_call

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40

_bk;t=1692259267503  24: __rust_try

_bk;t=1692259267503  25: std::panicking::try

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19

_bk;t=1692259267503  26: std::panic::catch_unwind

_bk;t=1692259267503             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14

_bk;t=1692259267503  27: madsim::sim::task::Executor::run_all_ready

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:17

_bk;t=1692259267503  28: madsim::sim::task::Executor::block_on

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:238:13

_bk;t=1692259267503  29: madsim::sim::runtime::Runtime::block_on

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:9

_bk;t=1692259267503  30: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}

_bk;t=1692259267503             at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/builder.rs:128:35

_bk;t=1692259267503note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

_bk;t=1692259267503context: node=0 "main", task=981 (spawned at src/meta/src/stream/stream_manager.rs:712:31)

_bk;t=1692259267503note: run with `MADSIM_TEST_SEED=1692259266474591907` environment variable to reproduce this error

_bk;t=1692259267503[0m


```

**Comment by yezizp2012** [comment]
The first assertion might be cause by `bootstrap_recovery`, which is actually should not be triggered when `enable_recovery` option is false. Not sure if it's the root cause as well for the second one.

**Comment by BugenZhao** [comment]
> which is actually should not be triggered when `enable_recovery` option is false

Oops, this got changed after https://github.com/risingwavelabs/risingwave/pull/10907#discussion_r1263425283.
