### ISSUE TITLE
bug(storage): can_concat assertion failed

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#11864]
### Describe the bug

The deterministic integration test failed due to `can_concat` assertion.

```
failures:
--
  | sink::basic::test_sink_decouple_basic
  |  
  | test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 74 filtered out; finished in 6.19s
  |  
  |  
  | --- STDERR:              risingwave_simulation::integration_tests sink::basic::test_sink_decouple_basic ---
  | thread '<unnamed>' panicked at 'assertion failed: can_concat(&operand.table_infos)', src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:1038:5
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
  | 1: core::panicking::panic_fmt
  | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
  | 2: core::panicking::panic
  | at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:117:5
  | 3: risingwave_hummock_sdk::compaction_group::hummock_version_ext::level_insert_ssts
  | at /risingwave/src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:1038:5
  | 4: <risingwave_pb::hummock::hummock_version::Levels as risingwave_hummock_sdk::compaction_group::hummock_version_ext::HummockLevelsExt>::apply_compact_ssts
  | at /risingwave/src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:694:17
  | 5: <risingwave_pb::hummock::HummockVersion as risingwave_hummock_sdk::compaction_group::hummock_version_ext::HummockVersionUpdateExt>::apply_version_delta
  | at /risingwave/src/storage/hummock_sdk/src/compaction_group/hummock_version_ext.rs:562:17
  | 6: risingwave_meta::hummock::manager::HummockManager<S>::report_compact_task_impl::{{closure}}
  | at /risingwave/src/meta/src/hummock/manager/mod.rs:1242:17
  | 7: risingwave_meta::hummock::manager::HummockManager<S>::report_compact_task::{{closure}}
  | at /risingwave/src/meta/src/hummock/manager/mod.rs:1120:14
  | 8: risingwave_meta::hummock::manager::HummockManager<S>::compaction_event_loop::{{closure}}::{{closure}}
  | at /risingwave/src/meta/src/hummock/manager/mod.rs:2586:41
```

https://buildkite.com/risingwavelabs/pull-request/builds/30177#018a25db-4116-4b95-bac6-9648e1d90d7a

**Comment by zwang28** [comment]
@Little-Wallace Could you please take a look?

**Comment by Little-Wallace** [comment]
A bad news.... 
I'll take a look for this bug

**Comment by wenym1** [comment]
Same In my PR.

https://buildkite.com/risingwavelabs/pull-request/builds/30178#018a25e4-d159-4e7c-8d53-e2cd4d20f36b

**Comment by fuyufjh** [comment]
Again https://buildkite.com/risingwavelabs/main-cron/builds/804#018a42e6-479a-4013-85e9-9464ba19fec1/161-1398

**Comment by hzxa21** [comment]
@Little-Wallace I think this has been fixed?

**Comment by Little-Wallace** [comment]
> @Little-Wallace I think this has been fixed?

Yes
