### ISSUE TITLE
bug: panic on memory dump

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12254]
### Describe the bug

```
thread 'risingwave-main' panicked at src/compute/src/memory_management/policy.rs:132:58:
called `Result::unwrap()` on an `Err` value: Attempt to read or write `void` value, or attempt to write read-only value.
stack backtrace:
   0:     0x55bb8bb06bd7 - std::backtrace_rs::backtrace::libunwind::trace::h75b30c0cd68bc7af
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55bb8bb06bd7 - std::backtrace_rs::backtrace::trace_unsynchronized::h87a4581e60db2a55
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bb8bb06bd7 - std::sys_common::backtrace::_print_fmt::hb61bbd4cad6c8d05
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55bb8bb06bd7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h78c87721a2fe0851
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55bb8569ae9c - core::fmt::rt::Argument::fmt::h3a1f78153a55cf27
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/core/src/fmt/rt.rs:138:9
   5:     0x55bb8569ae9c - core::fmt::write::h78df6aa1c7979fcd
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/core/src/fmt/mod.rs:1094:21
   6:     0x55bb8bb0151e - std::io::Write::write_fmt::h51abcfccd2bfcce9
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/io/mod.rs:1714:15
   7:     0x55bb8bb069b4 - std::sys_common::backtrace::_print::h900c04ec6229a3eb
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55bb8bb069b4 - std::sys_common::backtrace::print::heb918b083479ba12
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55bb8bb0847b - std::panicking::panic_hook_with_disk_dump::{{closure}}::h308105f13195c33c
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/panicking.rs:280:22
  10:     0x55bb8bb08136 - std::panicking::panic_hook_with_disk_dump::h2f5bad6440ca252c
                               at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/panicking.rs:314:9
```

**Comment by fuyufjh** [comment]
Hmmm...
 https://github.com/jemalloc/jemalloc/blob/54eaed1d8b56b1aa528be3bdd1877e59c56fa90c/src/ctl.c#L3310
