### ISSUE TITLE
Create conflict database.source.name in source/sink

### ISSUE THREAD

**Issue by QuantumBear** [risingwavelabs/risingwave#12301]
### Describe the bug

cdc source from mysql5, then sink to mysql 8. Fail to create sink.

```
(base) ➜  sql git:(main) ✗ psql -h myip  -p  31146  -d dev -U root < sink.sql
ERROR:  QueryError: internal error: failed to finish command: channel closed
(base) ➜  sql git:(main) ✗ psql -h myip  -p  31146  -d dev -U root < sink.sql
ERROR:  QueryError: internal error: Service unavailable: The cluster is starting or recovering
```

### Error message/log

```text
2023-09-14 06:25:05,562 ERROR [rw-dbz-engine-runner-6178] core.DbzCdcEngineRunner:55 - engine#6178 terminated with error. message: Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config: {connector.class=io.debezium.connector.mysql.MySqlConnector, max.queue.size=8192, provide.transaction.metadata=false, include.schema.changes=false, decimal.handling.mode=string, offset.storage.file.filename=, converters=datetime, interval.handling.mode=string, datetime.type=com.risingwave.connector.cdc.debezium.converters.DatetimeTypeConverter, value.converter=org.apache.kafka.connect.json.JsonConverter, key.converter=org.apache.kafka.connect.json.JsonConverter, database.user=willing, offset.storage=com.risingwave.connector.cdc.debezium.internal.ConfigurableOffsetBackingStore, database.server.id=8571, time.precision.mode=adaptive_time_microseconds, database.server.name=RW_CDC_6178, offset.flush.timeout.ms=5000, offset.storage.risingwave.state.value={"sourcePartition":{"server":"RW_CDC_6178"},"sourceOffset":{"transaction_id":null,"ts_sec":1694599033,"file":"mysql-bin.000057","pos":8486973,"row":1,"server_id":1,"event":2}}, database.port=3306, offset.flush.interval.ms=60000, internal.key.converter=org.apache.kafka.connect.json.JsonConverter, database.hostname=172.30.10.10, database.password=********, name=172.30.10.10:3306:willing_base.scrm_progress, internal.value.converter=org.apache.kafka.connect.json.JsonConverter, max.batch.size=1024, table.include.list=willing_base.scrm_progress, snapshot.mode=schema_only_recovery, database.history=io.debezium.relational.history.MemoryDatabaseHistory, database.include.list=willing_base}
java.lang.RuntimeException: Unable to register the MBean 'debezium.mysql:type=connector-metrics,context=schema-history,server=RW_CDC_6178'
 at io.debezium.metrics.Metrics.register(Metrics.java:108) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.relational.history.DatabaseHistoryMetrics.started(DatabaseHistoryMetrics.java:95) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.relational.history.AbstractDatabaseHistory.start(AbstractDatabaseHistory.java:82) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:42) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.connector.mysql.MySqlDatabaseSchema.<init>(MySqlDatabaseSchema.java:93) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:93) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:133) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:760) [debezium-embedded-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:192) [debezium-embedded-1.9.7.Final.jar:1.9.7.Final]
 at com.risingwave.connector.source.core.DbzCdcEngine.run(DbzCdcEngine.java:54) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
 at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.InterruptedException: sleep interrupted
 at java.lang.Thread.sleep(Native Method) ~[?:?]
 at io.debezium.util.Metronome$1.pause(Metronome.java:57) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 at io.debezium.metrics.Metrics.register(Metrics.java:96) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
 ... 12 more
```
```


### To Reproduce

_No response_


### Expected behavior

_No response_


### How did you deploy RisingWave?

_No response_


### The version of RisingWave

```
dev=> select version();
                                  version
----------------------------------------------------------------------------
 PostgreSQL 9.5-RisingWave-1.2.0 (f27f085e4433eb4b3b9e8df61b3f94406f654d89)
(1 row)
```

### Additional context

_No response_

**Comment by StrikeW** [comment]
After checking the logs of the meta node, we found that the cluster continuously triggers recovery state, so it can't process the DDL request. Due to the incomplete log, the root cause of recovery cannot be decided yet. There are many gRPC errors in the log of meta and the connector node sees many “Connection broken detected, stop the engine” message.

A new issue found in the log is recorded in https://github.com/risingwavelabs/risingwave/issues/12313, we may fix the issue  and see whether continuous recovery still occur.

**Comment by hzxa21** [comment]
@StrikeW #12313 is marked as completed. Can you confirm that whether this issue is fixed?

**Comment by BugenZhao** [comment]
Some users are still encountering this in v2.3.0 after creating a considerable amount of tables from the same CDC source. The error message is also `Unable to register the MBean`.

**Comment by qccash** [comment]
"Unable to register the MBean" is caused by JmxUtils.registerMXBean "Unable to register metrics as an old set with the same name exists, retrying in {} (attempt {} out of {})",
and this is caused by same server name server=RW_CDC_{sourceId}.

It seems that SchemaHistoryMetrics hasn't been closed properly. If RisingWave tries to restore this source actor on the same node, it will trigger the MBean conflict error.

**Comment by qccash** [comment]
In my case, I didn't see the "engine{} stopped normally" log. A reasonable guess is that because debezium.embedded.shutdown.pause.before.interrupt.ms=1, the task didn't have enough time to complete close(). I'll try increasing this setting to see if it resolves the issue.
