### ISSUE TITLE
bug: tumble fails parallel e2e test

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#12429]
### Describe the bug

Since https://buildkite.com/risingwavelabs/main-cron/builds/849

```
thread 'risingwave-streaming-actor' panicked at src/expr/src/vector_op/tumble.rs:91:12:
attempt to subtract with overflow
stack backtrace:
thread 'risingwave-streaming-actor' panicked at src/expr/src/vector_op/tumble.rs:91:12:
attempt to subtract with overflow
2023-09-14T20:34:35.209033552Z DEBUG risingwave_stream::task::stream_manager: drop actors actors=[4964, 4965, 4966, 4967, 4976, 4977, 4978, 4979, 4988, 4989, 4990, 4991, 5000, 5001, 5002, 5003]
2023-09-14T20:34:35.249759635Z DEBUG risingwave_stream::task::stream_manager: drop actors actors=[5748, 5749, 5750, 5751, 5760, 5761, 5762, 5763]
thread 'risingwave-streaming-actor' panicked at src/expr/src/vector_op/tumble.rs:91:12:
attempt to subtract with overflow
thread 'risingwave-streaming-actor' panicked at src/expr/src/vector_op/tumble.rs:91:12:
attempt to subtract with overflow
   0: rust_begin_unwind
             at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/62ebe3a2b177d50ec664798d731b8a8d1a9120d1/library/core/src/panicking.rs:127:5
   3: get_window_start_with_offset
   4: get_window_start
             at ./src/expr/src/vector_op/tumble.rs:51:5
   5: tumble_start_timestamptz
             at ./src/expr/src/vector_op/tumble.rs:45:5
   6: {async_block#0}
             at ./src/expr/src/vector_op/tumble.rs:43:1
```

**Comment by zwang28** [comment]
@chenzl25 
Seem the newly added `temporal_join_watermark.slt` will fail.

**Comment by chenzl25** [comment]
I think it is related to another issue https://github.com/risingwavelabs/risingwave/issues/12300 
I am not sure if an append-only table with a watermark is well-supported. cc @st1page @yuhao-su

**Comment by chenzl25** [comment]
Since `temporal_join_watermark.slt` uses an append-only table to generate watermarks and temporal join won't modify the watermark value but a panic occurs on `tumble`. It seems the watermark value is unexpected.
