### ISSUE TITLE
Error internal error: Unsupported oid 0 Call getNextException to see other errors in the batch

### ISSUE THREAD

**Issue by luzongzhu** [risingwavelabs/risingwave#12482]
### Describe the bug

saphana to risingwave use apache seatunnel use postgresql jdbc 

### Error message/log

```text
Caused by: org.apache.seatunnel.connectors.seatunnel.jdbc.exception.JdbcConnectorException: ErrorCode:[COMMON-10], ErrorDescription:[Flush data operation that in sink connector failed]
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.flush(JdbcOutputFormat.java:136)
at org.apache.seatunnel.connectors.seatunnel.jdbc.sink.JdbcSinkWriter.prepareCommit(JdbcSinkWriter.java:88)
at org.apache.seatunnel.engine.server.task.flow.SinkFlowLifeCycle.received(SinkFlowLifeCycle.java:166)
... 15 more
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO public.ST_WORK_CENTER(HANDLE,CHANGE_STAMP,SITE,WORK_CENTER,ROUTER_BO,CAN_BE_RELEASED_TO,WC_CATEGORY,STATUS_BO,WC_TYPE,ASSIGNMENT_ENFORCEMENT,ERP_INTERNAL_ID,IS_ERP_WORK_CENTER,ERP_WORK_CENTER,ERP_CAPACITY_CATEGORY,PRODUCTION_SUPPLY_AREA,STANDARD_VALUE_KEY_BO) VALUES('WorkCenterBO:1101,D31-ZL',NULL,'1101','D31-ZL',NULL,'false','LEVEL4','StatusBO:1101,101','FABRICATION','NONE',NULL,'false',NULL,NULL,NULL,NULL) was aborted: ERROR: ParseError: internal error: Unsupported oid 0 Call getNextException to see other errors in the batch.
at org.postgresql.jdbc.BatchResultHandler.handleCompletion(BatchResultHandler.java:186)
at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:881)
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.FieldNamedPreparedStatement.executeBatch(FieldNamedPreparedStatement.java:533)
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.SimpleBatchStatementExecutor.executeBatch(SimpleBatchStatementExecutor.java:51)
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.executor.BufferedBatchStatementExecutor.executeBatch(BufferedBatchStatementExecutor.java:53)
at org.apache.seatunnel.connectors.seatunnel.jdbc.internal.JdbcOutputFormat.attemptFlush(JdbcOutputFormat.java:165)
a
```

**Comment by StrikeW** [comment]
Hi @luzongzhu, the stack trace doesn't shows any code related to the RisingWave codebase. Where you get this stack trace? Are you using the apache seatunnel to replica data into RisingWave?

**Comment by hzxa21** [comment]
Hi @luzongzhu , can you provide more information regarding to @StrikeW 's comment?

**Comment by StrikeW** [comment]
Closed due to inactive for a long time.
