### ISSUE TITLE
Support a method to reload a CDC table without recreating it

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#12753]
### Is your feature request related to a problem? Please describe.

When we try to recover a CDC table job, if the upstream binlog/wal file is missing, currently this job cannot be recovered. Right now, we can only drop the table and recreate it to do the full replication. However, the process of rebuilding a CDC table can be tedious, because there maybe many downstream stream jobs depends on the CDC table.

One of our customer request us to support a method to reload the CDC table without recreating it.

### Describe the solution you'd like
Some ideas:
- Trigger a full replication internally when we detect that upstream binlog file is missing in the recovery process, but how to detect the binlog file is missing? Need some investigatation
- Introduce a new SQL command, for example the `REFRESH` command to allow user to trigger a full replication for a specific CDC table. Mainly for operational scenario.

reference: 
DB2: https://www.ibm.com/docs/en/db2-for-zos/12?topic=statements-refresh-table
PG: https://www.postgresql.org/docs/current/sql-refreshmaterializedview.html

### Additional context

related: https://github.com/risingwavelabs/risingwave/issues/12313, https://github.com/risingwavelabs/risingwave/issues/14060

**Comment by BugenZhao** [comment]
This is somehow similar to Alter MV. IIUC, the main motivation is to preserve all downstream streaming jobs. Then the problem is, how to decide the changes that should be yielded to these downstream if there's already data loss?

- Delete all records in the RW table and re-synchronize with the upstream. Will result in a significant amount of downtime.
- Directly re-synchronize with the upstream and rely on the on-conflict handling to overwrite data. Will there be dirty data visible by users?
- Somehow find the "diff" to indicate the lost data. This introduces a brand-new job pattern and may require a complete design.

**Comment by liurenjie1024** [comment]
> Trigger a full replication internally when we detect that upstream binlog file is missing in the recovery process, but how to detect the binlog file is missing? Need some investigatation

By full replication you mean do full scan of source table?

**Comment by hzxa21** [comment]
> When we try to recover a CDC table job, if the upstream binlog/wal file is missing, currently this job cannot be recovered.

Why is the upstream binlog/wal file missing at the first place? Is this an expected situaion.

I guess this is due to binlog/WAL retention? Correct me if I am wrong, the job cannot be recovered only if the missing upstream binlog/WAL are "unconsumed" by RW. If this is the case, that means there is something unexpected happening in RW cluster causing lags in consuming the binlog/WAL files. That sounds rare to me and dropping & creating the cdc table sounds acceptable to me.

**Comment by hzxa21** [comment]
I tried to repro binlog missing via the following steps:
1. Use docker compose under integration test to create MySQL/RW pods and create sample tables and MVs.
2. Run the following command in MySQL:
```
mysql> show binary logs;
+---------------+-----------+-----------+
| Log_name      | File_size | Encrypted |
+---------------+-----------+-----------+
| binlog.000003 |       157 | No        |
+---------------+-----------+-----------+

mysql> purge binary logs before now();

# Reset to a number larger than the binlog idx saw above
mysql> reset master to 4
```

3. Check RW cluster and run batch query

Here are my findings:
1. RW cluster is still up after the binlog is cleaned.
2. Newly changes to the MySQL table won't reflected in RW table.
3. I saw the following errors in compute node:
```
2023-10-13 06:44:56,867 ERROR [blc-mysql:3306] mysql.MySqlStreamingChangeEventSource:1094 - Error during binlog processing. Last offset stored = {transaction_id=null, ts_sec=1697179409, file=binlog.000004, pos=1882, server_id=1, event=1}, binlog reader near position = binlog.000004/1882
2023-10-13 06:44:56,871 ERROR [blc-mysql:3306] pipeline.ErrorHandler:35 - Producer failure
io.debezium.DebeziumException: could not find next log; the first event 'binlog.000004' at 1042, the last event read from './binlog.000004' at 1882, the last byte read from './binlog.000004' at 1882. Error code: 1236; SQLSTATE: HY000.
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1194) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1239) [debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) [mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: could not find next log; the first event 'binlog.000004' at 1042, the last event read from './binlog.000004' at 1882, the last byte read from './binlog.000004' at 1882.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        ... 3 more
2023-10-13 06:44:56,872 INFO  [blc-mysql:3306] mysql.MySqlStreamingChangeEventSource:1210 - Stopped reading binlog after 0 events, last recorded offset: {transaction_id=null, ts_sec=1697179409, file=binlog.000004, pos=1882, server_id=1, event=1}
2023-10-13 06:44:57,112 INFO  [rw-dbz-engine-runner-1008] embedded.EmbeddedEngine:847 - Stopping the task and engine
2023-10-13 06:44:57,113 INFO  [rw-dbz-engine-runner-1008] common.BaseSourceTask:243 - Stopping down connector
2023-10-13T06:44:57.161128057Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 5239229393076224 is sealed
2023-10-13T06:44:57.16114017Z  INFO risingwave_storage::hummock::event_handler::uploader: epoch 5239229393076224 to seal has no data
2023-10-13 06:44:57,216 INFO  [debezium-mysqlconnector-RW_CDC_1008-change-event-source-coordinator] pipeline.ChangeEventSourceCoordinator:175 - Finished streaming
2023-10-13 06:44:57,222 INFO  [pool-5-thread-1] jdbc.JdbcConnection:962 - Connection gracefully closed
2023-10-13 06:44:57,225 ERROR [rw-dbz-engine-runner-1008] core.DbzCdcEngineRunner:83 - engine#1008 terminated with error. message: Error while trying to run connector class 'io.debezium.connector.mysql.MySqlConnector'
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
        at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:50) ~[debezium-core-1.9.7.Final.jar:1.9.7.Final]
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1239) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1079) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:631) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:932) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.debezium.DebeziumException: could not find next log; the first event 'binlog.000004' at 1042, the last event read from './binlog.000004' at 1882, the last byte read from './binlog.000004' at 1882. Error code: 1236; SQLSTATE: HY000.
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1194) ~[debezium-connector-mysql-1.9.7.Final.jar:1.9.7.Final]
        ... 5 more
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: could not find next log; the first event 'binlog.000004' at 1042, the last event read from './binlog.000004' at 1882, the last byte read from './binlog.000004' at 1882.
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1043) ~[mysql-binlog-connector-java-0.27.2.jar:0.27.2]
        ... 3 more
```

**Comment by StrikeW** [comment]
> This is somehow similar to Alter MV. IIUC, the main motivation is to preserve all downstream streaming jobs. Then the problem is, how to decide the changes that should be yielded to these downstream if there's already data loss?

Right now we should focus on the case that binlog file is deleted by the MySQL retention policy. In this case, the persisted source offset may have been purged by MySQL. So that the connector can't  be recovered correctly upon recovery, then cdc table would not sync with its upstream.

I found that Debezium can emit [heartbeat](https://debezium.io/documentation/reference/1.9/connectors/mysql.html#mysql-property-heartbeat-interval-ms) event to downstream. With the help with heartbeat events, we can update the source offset to keep it update to date with the upstream then offset can be reset successfully during the recovery. I will implement the support of heartbeat event first to solve the problem for our customer.

> Heartbeat messages are useful for monitoring whether the connector is receiving change events from the database. Heartbeat messages might help decrease the number of change events that need to be re-sent when a connector restarts.

**Comment by BugenZhao** [comment]
> > This is somehow similar to Alter MV. IIUC, the main motivation is to preserve all downstream streaming jobs. Then the problem is, how to decide the changes that should be yielded to these downstream if there's already data loss?

Did you accidentally reference this? 👀

**Comment by StrikeW** [comment]
> > > This is somehow similar to Alter MV. IIUC, the main motivation is to preserve all downstream streaming jobs. Then the problem is, how to decide the changes that should be yielded to these downstream if there's already data loss?
> 
> Did you accidentally reference this? 👀

No. Since I think the problem you mentioned is more general and complex, for example when the compute node crashed for a long time. But right now we can narrow the scope and assumes that **compute node won't be down for more than the expiration time of the binlog**, so that the connector can reset its offset upon recovery.
