### ISSUE TITLE
bug(panic): It should not have duplicate task label

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#12800]
### Describe the bug

CN panicked when running a batch query (the query was not provided)

### Error message/log

```text
thread 'risingwave-main' panicked at 'It should not have duplicate task label.: Msg("missing label values [\"1f6e5c02-09ba-4627-9084-dcf6f2fa28d2\", \"1\", \"1\"]")', src/batch/src/monitor/stats.rs:175:13
stack backtrace:
   0:     0x564f19543fec - std::backtrace_rs::backtrace::libunwind::trace::hc317256c0daecb22
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564f19543fec - std::backtrace_rs::backtrace::trace_unsynchronized::h85008105ccd95ba6
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564f19543fec - std::sys_common::backtrace::_print_fmt::hb6e7cbe31fecc91c
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564f19543fec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h53097d3751045778
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564f12dad12f - core::fmt::rt::Argument::fmt::hdbe0b5dfb2c09e86
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/fmt/rt.rs:138:9
   5:     0x564f12dad12f - core::fmt::write::h4ae17c68778671a0
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/fmt/mod.rs:1094:21
   6:     0x564f1953ee9f - std::io::Write::write_fmt::hfd7c55e775c6dc60
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/io/mod.rs:1713:15
   7:     0x564f19543df5 - std::sys_common::backtrace::_print::h81eabb0036b692a0
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x564f19543df5 - std::sys_common::backtrace::print::h1b1f4d1a23fac3fd
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x564f19545367 - std::panicking::default_hook::{{closure}}::hc17d2bd8f3da442c
  10:     0x564f19545174 - std::panicking::default_hook::h3a32a9336113ba96
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:288:9
  11:     0x564f18d1699b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hd5bc03d8316c426a
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1999:9
  12:     0x564f18d1699b - risingwave_rt::panic_hook::set_panic_hook::{{closure}}::h4323836ffebfaa73
                               at /risingwave/src/utils/runtime/src/panic_hook.rs:19:9
  13:     0x564f18d1699b - std::panicking::update_hook::{{closure}}::hdb9e2c8f81e8f2fb
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:234:47
  14:     0x564f19545982 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h4413820818220cb9
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1999:9
  15:     0x564f19545982 - std::panicking::rust_panic_with_hook::h90e4d15277396259
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:709:13
  16:     0x564f19545724 - std::panicking::begin_panic_handler::{{closure}}::h2b743ea215b7c408
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:597:13
  17:     0x564f195443c6 - std::sys_common::backtrace::__rust_end_short_backtrace::h895d390908a90650
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:151:18
  18:     0x564f195454b2 - rust_begin_unwind
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:593:5
  19:     0x564f12da9e13 - core::panicking::panic_fmt::h1cc8517ae3119d0e
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panicking.rs:67:14
  20:     0x564f12daa2c3 - core::result::unwrap_failed::h4c9088fd4642a5e0
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1651:5
  21:     0x564f13ca8531 - core::result::Result<T,E>::expect::h60d92a1ed143b8c7
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/result.rs:1033:23
  22:     0x564f13ca8531 - risingwave_batch::monitor::stats::BatchTaskMetrics::clean_metrics::hdc1f7cd0d3629ff8
                               at /risingwave/src/batch/src/monitor/stats.rs:175:13
  23:     0x564f13ca8531 - <risingwave_batch::monitor::stats::BatchTaskMetrics as prometheus::metrics::Collector>::collect::h9c600f0cea854895
                               at /risingwave/src/batch/src/monitor/stats.rs:202:9
  24:     0x564f134a0462 - prometheus::registry::RegistryCore::gather::h1d73b67115ddae70
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prometheus-0.13.3/src/registry.rs:123:23
  25:     0x564f134a0462 - prometheus::registry::Registry::gather::hfafe772562f333bb
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prometheus-0.13.3/src/registry.rs:276:9
  26:     0x564f145f6cd8 - risingwave_common_service::metrics_manager::MetricsManager::metrics_service::{{closure}}::h7abc90402c8a9247
                               at /risingwave/src/common/common_service/src/metrics_manager.rs:67:18
  27:     0x564f145f6cd8 - <hyper::proto::h1::dispatch::Server<S,hyper::body::body::Body> as hyper::proto::h1::dispatch::Dispatch>::poll_msg::h33cb3b6343f577e3
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:500:35
  28:     0x564f145f6cd8 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_write::h1040b593d1935c4a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:301:43
  29:     0x564f145f6cd8 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop::haec6147b67ae240b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:165:21
  30:     0x564f145f6cd8 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_inner::hd39c56b94124588c
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:141:16
  31:     0x564f145f6cd8 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::h6af829b526293267
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:120:28
  32:     0x564f1462714d - <hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T> as core::future::future::Future>::poll::h22fd4dd3d2dc8c07
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/proto/h1/dispatch.rs:433:9
  33:     0x564f1462714d - <hyper::server::conn::ProtoServer<T,B,S,E> as core::future::future::Future>::poll::h98e8bcaeef92ec84
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/conn.rs:986:50
  34:     0x564f1462714d - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::hf09e29bcee254ef1
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/conn.rs:1046:30
  35:     0x564f145c986b - <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll::h2d1dfb8285b0cb1a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.27/src/server/server.rs:763:36
  36:     0x564f14612b6f - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h2a7a8c2b615183de
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  37:     0x564f14612b6f - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::ha50754934a63b0d6
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/core.rs:334:17
  38:     0x564f14612b6f - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hfaf44e872931dc13
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/loom/std/unsafe_cell.rs:16:9
  39:     0x564f14612b6f - tokio::runtime::task::core::Core<T,S>::poll::h46a6f23f67f9a685
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/core.rs:323:30
  40:     0x564f1463931c - tokio::runtime::task::harness::poll_future::{{closure}}::h88003e544fb685ed
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:485:19
  41:     0x564f1463931c - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he16c782a66fdcfc5
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  42:     0x564f1463931c - std::panicking::try::do_call::hacda33c3ec4ed2df
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  43:     0x564f1463931c - std::panicking::try::hcc0d8e5d9032696f
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  44:     0x564f1463931c - std::panic::catch_unwind::hdcb629f05b642af6
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  45:     0x564f1463931c - tokio::runtime::task::harness::poll_future::h4b7b068ffaca0a68
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:473:18
  46:     0x564f1463931c - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h3545bd4fc3434b34
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:208:27
  47:     0x564f1463931c - tokio::runtime::task::harness::Harness<T,S>::poll::h5ebae32ca736f778
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:153:15
  48:     0x564f195e1686 - tokio::runtime::task::raw::RawTask::poll::haaef99745fcb600c
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/raw.rs:200:18
  49:     0x564f195e1686 - tokio::runtime::task::LocalNotified<S>::run::h5534f117cf9b6e6e
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/mod.rs:400:9
  50:     0x564f195e1686 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}::h40b22f42a97bda2d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:576:18
  51:     0x564f195e1686 - tokio::runtime::coop::with_budget::hba2a5ebff4bf055a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/coop.rs:107:5
  52:     0x564f195e1686 - tokio::runtime::coop::budget::hae9c80674f8b6f58
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/coop.rs:73:5
  53:     0x564f195e1686 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h0a37baffc361dabe
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  54:     0x564f195e0c5e - tokio::runtime::scheduler::multi_thread::worker::Context::run::h22024ffabd6d3d70
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  55:     0x564f195b6966 - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}::h56230bd78025b2a4
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  56:     0x564f195b6966 - tokio::runtime::context::scoped::Scoped<T>::set::hc1750e562874e6ab
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/context/scoped.rs:40:9
  57:     0x564f195e554e - tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::h3c8a48c6cdd7940d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  58:     0x564f195e554e - tokio::runtime::context::runtime::enter_runtime::h5f064be0fadf976d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/context/runtime.rs:65:16
  59:     0x564f195e04c0 - tokio::runtime::scheduler::multi_thread::worker::run::h71ac56486351761e
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  60:     0x564f169df331 - tokio::runtime::scheduler::multi_thread::worker::block_in_place::{{closure}}::{{closure}}::hf2f5ee254b8fba2d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:422:41
  61:     0x564f169df331 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hc06629f36e0dfe3d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/blocking/task.rs:42:21
  62:     0x564f169df331 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h4e9c8b6cf3c977af
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  63:     0x564f169ab3c9 - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::h54c3a042fe7751c2
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/core.rs:334:17
  64:     0x564f169ab3c9 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hbaf623c800f9a9e4
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/loom/std/unsafe_cell.rs:16:9
  65:     0x564f169ab3c9 - tokio::runtime::task::core::Core<T,S>::poll::he1e6c8b17f817d5b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/core.rs:323:30
  66:     0x564f166941ef - tokio::runtime::task::harness::poll_future::{{closure}}::h85e5514064c8111a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:485:19
  67:     0x564f166941ef - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h116ffc9096467005
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  68:     0x564f166941ef - std::panicking::try::do_call::h39ef2d1f19d86520
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  69:     0x564f166941ef - std::panicking::try::h8ad8704584b51f27
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  70:     0x564f166941ef - std::panic::catch_unwind::h8b65e59408a8caa0
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  71:     0x564f166941ef - tokio::runtime::task::harness::poll_future::h15b3d81cf751c7da
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:473:18
  72:     0x564f166941ef - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h7b15b5fe1415e1d0
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:208:27
  73:     0x564f166941ef - tokio::runtime::task::harness::Harness<T,S>::poll::hd88bf729d1139331
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/harness.rs:153:15
  74:     0x564f195ab4e6 - tokio::runtime::task::raw::RawTask::poll::haaef99745fcb600c
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/raw.rs:200:18
  75:     0x564f195ab4e6 - tokio::runtime::task::UnownedTask<S>::run::h2b9672bea653e901
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/task/mod.rs:437:9
  76:     0x564f195ab4e6 - tokio::runtime::blocking::pool::Task::run::hea90fb381d7d045b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/blocking/pool.rs:159:9
  77:     0x564f195ab4e6 - tokio::runtime::blocking::pool::Inner::run::h738f6cf4149c87a4
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/blocking/pool.rs:513:17
  78:     0x564f195ec1fb - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h315017ca3df1756f
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/blocking/pool.rs:471:13
  79:     0x564f195ec1fb - std::sys_common::backtrace::__rust_begin_short_backtrace::h76a0b4cf3c30a3f8
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys_common/backtrace.rs:135:18
  80:     0x564f195c7172 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hb8df74a97b136925
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/thread/mod.rs:529:17
  81:     0x564f195c7172 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h0dbe64f9a4737993
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/panic/unwind_safe.rs:271:9
  82:     0x564f195c7172 - std::panicking::try::do_call::hc098c079ed7d78f1
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:500:40
  83:     0x564f195c7172 - std::panicking::try::h6721df949e516bb1
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panicking.rs:464:19
  84:     0x564f195c7172 - std::panic::catch_unwind::hdf38a3baacd08d8d
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/panic.rs:142:14
  85:     0x564f195c7172 - std::thread::Builder::spawn_unchecked_::{{closure}}::h255b9c9b5d9e218f
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/thread/mod.rs:528:30
  86:     0x564f195c7172 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he471b1bc8eb6329f
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/core/src/ops/function.rs:250:5
  87:     0x564f1954b645 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0716d70b901d1398
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1985:9
  88:     0x564f1954b645 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7c11e50091aab2e1
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/alloc/src/boxed.rs:1985:9
  89:     0x564f1954b645 - std::sys::unix::thread::Thread::new::thread_start::h3ae99d1c2785d9c6
                               at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/sys/unix/thread.rs:108:17
  90:     0x7f01ce87db43 - start_thread
                               at ./nptl/pthread_create.c:442:8
  91:     0x7f01ce90ebb4 - clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
  92:                0x0 - <unknown>
```

**Comment by fuyufjh** [comment]
Duplicated #12489
