### ISSUE TITLE
bug: assertion failed: offset < data_chunk.capacity() in filter executor

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#13041]
### Describe the bug

panic found in customer cluster: assertion failed: offset < data_chunk.capacity(). Related sql:
```sql
SELECT  timestamp, event_type, event_id, connector_config_id, app_session_id, content_session_id, latitude ,longitude ,city ,country,country_code ,region,region_code ,postal_code,district ,continent ,continent_code ,timezone_offset ,timezone_name 
FROM xxx 
WHERE 
rw_kafka_timestamp  > now() - INTERVAL '1 MINUTE'
AND connector_config_id = 'yyy'
LIMIT 1000
```

### Error message/log

```text
thread 'risingwave-batch-tasks' panicked at 'assertion failed: offset < data_chunk.capacity()', src/common/src/util/chunk_coalesce.rs:286:9
...
  21:     0x5640edcbc67c - risingwave_common::util::chunk_coalesce::SlicedDataChunk::with_offset_checked::hf1886724cb59333d
                               at /risingwave/src/common/src/util/chunk_coalesce.rs:286:9
  22:     0x5640edcbc67c - risingwave_common::util::chunk_coalesce::SlicedDataChunk::new_checked::h2245da4073b854c5
                               at /risingwave/src/common/src/util/chunk_coalesce.rs:282:9
  23:     0x5640edcbc67c - risingwave_common::util::chunk_coalesce::DataChunkBuilder::append_chunk::h356f6e0175a76e03
                               at /risingwave/src/common/src/util/chunk_coalesce.rs:129:29
  24:     0x5640edcbc67c - risingwave_batch::executor::filter::FilterExecutor::do_execute::{{closure}}::ha005b63488da5889
                               at /risingwave/src/batch/src/executor/filter.rs:66:21
```

### To Reproduce

Unreproducible

### Expected behavior

No panic.

### How did you deploy RisingWave?

Deployed in their own cloud with our k8s operator.

### The version of RisingWave

v1.2.0

**Comment by zwang28** [comment]
reproduce

```
CREATE SOURCE clicks (
    click_id INTEGER,
    user_id INTEGER,
    created_at TIMESTAMP,
) WITH (
    connector = 'kafka',
    topic = 'temp',
    properties.bootstrap.server = 'localhost:29092',
    kafka.scan.startup.mode = 'earliest'
)  FORMAT PLAIN ENCODE JSON;

create view vv as select click_id, user_id, _rw_kafka_timestamp as rw_kafka_timestamp from clicks;

SELECT * FROM vv WHERE rw_kafka_timestamp > now() - INTERVAL '10' second and user_id=123 limit 1000;
```

**Comment by yezizp2012** [comment]
Related #10500 . It turns out to be caused by query on source.
