### ISSUE TITLE
bug: frontend crashes during `SELECT * FROM rw_functions`

### ISSUE THREAD

**Issue by Rossil2012** [risingwavelabs/risingwave#13454]
### Describe the bug

Querying `rw_functions` after `CREATE FUNCTION` causes frontend to crash.

### Error message/log

```text
2023-11-16T13:35:53.311323+08:00  INFO risingwave_rt::deadlock: parking lot deadlock detection enabled
2023-11-16T13:35:53.313978+08:00  INFO risingwave_frontend::session: Starting frontend node
2023-11-16T13:35:53.314017+08:00  INFO risingwave_frontend::session: > config: RwConfig { server: ServerConfig { heartbeat_interval_ms: 1000, connection_pool_size: 16, metrics_level: Info, telemetry_enabled: true, heap_profiling: HeapProfilingConfig { enable_auto: true, threshold_auto: 0.9, dir: "./" }, unrecognized: {} }, meta: MetaConfig { min_sst_retention_time_sec: 86400, full_gc_interval_sec: 86400, collect_gc_watermark_spin_interval_sec: 5, periodic_compaction_interval_sec: 60, vacuum_interval_sec: 30, vacuum_spin_interval_ms: 10, hummock_version_checkpoint_interval_sec: 30, min_delta_log_num_for_hummock_version_checkpoint: 10, max_heartbeat_interval_secs: 300, disable_recovery: false, enable_scale_in_when_recovery: false, meta_leader_lease_secs: 30, dangerous_max_idle_secs: None, default_parallelism: Full, enable_compaction_deterministic: false, enable_committed_sst_sanity_check: false, node_num_monitor_interval_sec: 10, backend: Mem, periodic_space_reclaim_compaction_interval_sec: 3600, periodic_ttl_reclaim_compaction_interval_sec: 1800, periodic_tombstone_reclaim_compaction_interval_sec: 600, periodic_split_compact_group_interval_sec: 180, move_table_size_limit: 10737418240, split_group_size_limit: 68719476736, unrecognized: {}, do_not_config_object_storage_lifecycle: false, partition_vnode_count: 64, table_write_throughput_threshold: 16777216, min_table_split_write_throughput: 4194304, compaction_task_max_heartbeat_interval_secs: 60, compaction_config: CompactionConfig { max_bytes_for_level_base: 536870912, max_bytes_for_level_multiplier: 5, max_compaction_bytes: 2147483648, sub_level_max_compaction_bytes: 134217728, level0_tier_compact_file_number: 6, target_file_size_base: 33554432, compaction_filter_mask: 6, max_sub_compaction: 4, level0_stop_write_threshold_sub_level_number: 300, level0_sub_level_compact_level_count: 3, level0_overlapping_sub_level_compact_level_count: 6, max_space_reclaim_bytes: 536870912, level0_max_compact_file_number: 96, tombstone_reclaim_ratio: 40, enable_emergency_picker: true } }, batch: BatchConfig { worker_threads_num: None, developer: BatchDeveloperConfig { connector_message_buffer_size: 16, output_channel_size: 64, chunk_size: 1024 }, distributed_query_limit: None, enable_barrier_read: false, unrecognized: {} }, streaming: StreamingConfig { in_flight_barrier_nums: 10000, actor_runtime_worker_threads_num: None, async_stack_trace: ReleaseVerbose, developer: StreamingDeveloperConfig { enable_executor_row_count: false, connector_message_buffer_size: 16, unsafe_extreme_cache_size: 10, chunk_size: 256, exchange_initial_permits: 2048, exchange_batched_permits: 256, exchange_concurrent_barriers: 1, dml_channel_initial_permits: 32768, hash_agg_max_dirty_groups_heap_size: 67108864 }, unique_user_stream_errors: 10, unrecognized: {} }, storage: StorageConfig { share_buffers_sync_parallelism: 1, share_buffer_compaction_worker_threads_number: 4, shared_buffer_capacity_mb: None, shared_buffer_flush_ratio: 0.8, imm_merge_threshold: 4, write_conflict_detection_enabled: true, block_cache_capacity_mb: None, high_priority_ratio_in_percent: None, meta_cache_capacity_mb: None, large_query_memory_usage_mb: None, disable_remote_compactor: false, share_buffer_upload_concurrency: 8, compactor_memory_limit_mb: None, compactor_max_task_multiplier: 1.5, compactor_memory_available_proportion: 0.8, sstable_id_remote_fetch_number: 10, data_file_cache: FileCacheConfig { dir: "", capacity_mb: 1024, file_capacity_mb: 64, device_align: 4096, device_io_size: 16384, flushers: 4, reclaimers: 4, recover_concurrency: 8, lfu_window_to_cache_size_ratio: 1, lfu_tiny_lru_capacity_ratio: 0.01, insert_rate_limit_mb: 0, reclaim_rate_limit_mb: 0, ring_buffer_capacity_mb: 256, catalog_bits: 6, compression: "none", unrecognized: {} }, meta_file_cache: FileCacheConfig { dir: "", capacity_mb: 1024, file_capacity_mb: 64, device_align: 4096, device_io_size: 16384, flushers: 4, reclaimers: 4, recover_concurrency: 8, lfu_window_to_cache_size_ratio: 1, lfu_tiny_lru_capacity_ratio: 0.01, insert_rate_limit_mb: 0, reclaim_rate_limit_mb: 0, ring_buffer_capacity_mb: 256, catalog_bits: 6, compression: "none", unrecognized: {} }, cache_refill: CacheRefillConfig { data_refill_levels: [], timeout_ms: 6000, concurrency: 10, unit: 64, threshold: 0.5, recent_filter_layers: 6, recent_filter_rotate_interval_ms: 10000, unrecognized: {} }, min_sst_size_for_streaming_upload: 33554432, max_sub_compaction: 4, max_concurrent_compaction_task_number: 16, max_preload_wait_time_mill: 0, max_version_pinning_duration_sec: 10800, object_store_streaming_read_timeout_ms: 600000, object_store_streaming_upload_timeout_ms: 600000, object_store_upload_timeout_ms: 3600000, object_store_read_timeout_ms: 3600000, object_store_keepalive_ms: Some(600000), object_store_recv_buffer_size: Some(2097152), object_store_send_buffer_size: None, object_store_nodelay: Some(true), object_store_req_retry_interval_ms: 20, object_store_req_retry_max_delay_ms: 10000, object_store_req_retry_max_attempts: 8, compactor_max_sst_key_count: 2097152, compact_iter_recreate_timeout_ms: 600000, compactor_max_sst_size: 536870912, enable_fast_compaction: true, max_preload_io_retry_times: 3, unrecognized: {}, mem_table_spill_threshold: 4194304 }, unrecognized: {} }
2023-11-16T13:35:53.314133+08:00  INFO risingwave_frontend::session: > debug assertions: on
2023-11-16T13:35:53.314143+08:00  INFO risingwave_frontend::session: > version: 1.3.0-alpha (unknown)
2023-11-16T13:35:53.314549+08:00  INFO risingwave_frontend::session: advertise addr is 127.0.0.1:4566
2023-11-16T13:35:53.314849+08:00  INFO risingwave_rpc_client::meta_client: register meta client using strategy: List(["http://127.0.0.1:5690"])
2023-11-16T13:35:53.318299+08:00  INFO risingwave_rpc_client::meta_client: Connect to meta server http://127.0.0.1:5690 successfully
2023-11-16T13:35:53.326023+08:00  INFO risingwave_frontend::session: Assigned worker node id 2
2023-11-16T13:35:53.332436+08:00 DEBUG risingwave_frontend::scheduler::worker_node_manager: Refresh worker nodes [WorkerNode { id: 1, r#type: ComputeNode, host: Some(HostAddress { host: "127.0.0.1", port: 5688 }), state: Running, parallel_units: [ParallelUnit { id: 0, worker_node_id: 1 }, ParallelUnit { id: 1, worker_node_id: 1 }, ParallelUnit { id: 2, worker_node_id: 1 }, ParallelUnit { id: 3, worker_node_id: 1 }], property: Some(Property { is_streaming: true, is_serving: true, is_unschedulable: false }), transactional_id: Some(0) }].
2023-11-16T13:35:53.332504+08:00 DEBUG risingwave_frontend::scheduler::worker_node_manager: Refresh streaming vnode mapping for fragments [].
2023-11-16T13:35:53.332546+08:00 DEBUG risingwave_frontend::scheduler::worker_node_manager: Refresh serving vnode mapping for fragments [].
2023-11-16T13:35:53.336791+08:00  INFO risingwave_frontend::session: Telemetry didn't start due to config
2023-11-16T13:35:53.336829+08:00  INFO risingwave_frontend::session: Health Check RPC Listener is set up on 127.0.0.1:6786
2023-11-16T13:35:53.33693+08:00  INFO risingwave_common_service::metrics_manager: Prometheus listener for Prometheus is set up on http://127.0.0.1:2222
2023-11-16T13:35:53.33743+08:00  INFO pgwire::pg_server: server started addr="127.0.0.1:4566"
2023-11-16T13:35:53.340223+08:00  INFO pgwire::pg_server: accept connection peer_addr=127.0.0.1:54982
2023-11-16T13:35:53.341906+08:00 ERROR pgwire::pg_server: error when reading message error=unexpected end of file
2023-11-16T13:35:58.21361+08:00  INFO pgwire::pg_server: accept connection peer_addr=127.0.0.1:54989
2023-11-16T13:35:58.227479+08:00  INFO risingwave_common::session_config: set config key=application_name val=["psql"]
2023-11-16T13:36:03.328019+08:00  INFO risingwave_frontend::scheduler::snapshot: unpin snapshot with RPC min_epoch=5431476955447296
2023-11-16T13:36:05.239417+08:00  INFO pgwire_query_log: mode=(simple query) session=0 status=ok time=12ms sql=CREATE FUNCTION test_func() RETURNS INT LANGUAGE python as echo_42 using link 'http://localhost:8816';
2023-11-16T13:36:13.32806+08:00  INFO risingwave_frontend::scheduler::snapshot: unpin snapshot with RPC min_epoch=5431477610938368
2023-11-16T13:36:15.747278+08:00 DEBUG local_execute{query_id="e34c87d3-69eb-42cc-91e1-47762d8db44e" epoch=BatchQueryEpoch { epoch: Some(Committed(5431477741944832)) }}: risingwave_frontend::scheduler::local: Starting to run query self.query.query_id=QueryId:e34c87d3-69eb-42cc-91e1-47762d8db44e self.sql=""
2023-11-16T13:36:15.74745+08:00 DEBUG local_execute{query_id="e34c87d3-69eb-42cc-91e1-47762d8db44e" epoch=BatchQueryEpoch { epoch: Some(Committed(5431477741944832)) }}: risingwave_frontend::scheduler::local: Local execution mode converts a plan with two stages
thread 'frontend-compute-threads' panicked at src/common/src/acl/mod.rs:86:18:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:127:5
   3: risingwave_common::acl::<impl core::convert::From<risingwave_common::acl::AclMode> for risingwave_pb::user::grant_privilege::Action>::from
             at ./src/common/src/acl/mod.rs:86:18
   4: <T as core::convert::Into<U>>::into
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/convert/mod.rs:757:9
   5: risingwave_frontend::user::user_privilege::available_prost_privilege::{{closure}}
             at ./src/frontend/src/user/user_privilege.rs:104:21
   6: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/ops/function.rs:305:13
   7: core::option::Option<T>::map
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/option.rs:1066:29
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/adapters/map.rs:103:26
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  10: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/spec_from_iter.rs:33:9
  11: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/mod.rs:2750:9
  12: core::iter::traits::iterator::Iterator::collect
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/traits/iterator.rs:2053:9
  13: itertools::Itertools::collect_vec
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.11.0/src/lib.rs:2154:9
  14: risingwave_frontend::user::user_privilege::available_prost_privilege
             at ./src/frontend/src/user/user_privilege.rs:101:19
  15: risingwave_frontend::catalog::system_catalog::get_acl_items
             at ./src/frontend/src/catalog/system_catalog/mod.rs:221:27
  16: risingwave_frontend::catalog::system_catalog::rw_catalog::rw_functions::<impl risingwave_frontend::catalog::system_catalog::SysCatalogReaderImpl>::read_rw_functions_info::{{closure}}::{{closure}}
             at ./src/frontend/src/catalog/system_catalog/rw_catalog/rw_functions.rs:79:29
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/ops/function.rs:305:13
  18: core::option::Option<T>::map
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/option.rs:1066:29
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/adapters/map.rs:103:26
  20: core::ops::function::FnOnce::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/ops/function.rs:250:5
  21: core::iter::adapters::flatten::and_then_or_clear
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/adapters/flatten.rs:709:13
  22: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/adapters/flatten.rs:477:36
  23: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/adapters/flatten.rs:52:9
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/spec_from_iter.rs:33:9
  26: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/vec/mod.rs:2750:9
  27: core::iter::traits::iterator::Iterator::collect
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/iter/traits/iterator.rs:2053:9
  28: itertools::Itertools::collect_vec
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.11.0/src/lib.rs:2154:9
  29: risingwave_frontend::catalog::system_catalog::rw_catalog::rw_functions::<impl risingwave_frontend::catalog::system_catalog::SysCatalogReaderImpl>::read_rw_functions_info
             at ./src/frontend/src/catalog/system_catalog/rw_catalog/rw_functions.rs:59:12
  30: <risingwave_frontend::catalog::system_catalog::SysCatalogReaderImpl as risingwave_common::catalog::SysCatalogReader>::read_table::{{closure}}
             at ./src/frontend/src/catalog/system_catalog/mod.rs:322:40
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/future/future.rs:125:9
  32: risingwave_batch::executor::sys_row_seq_scan::SysRowSeqScanExecutor::do_executor::{{closure}}
             at ./src/batch/src/executor/sys_row_seq_scan.rs:110:71
  33: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  34: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  35: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  36: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  37: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  38: futures_util::future::future::FutureExt::poll_unpin
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9
  39: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/select.rs:118:35
  40: <risingwave_batch::executor::managed::ManagedExecutor as risingwave_batch::executor::Executor>::execute::{{closure}}
             at ./src/batch/src/executor/managed.rs:61:82
  41: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  43: risingwave_frontend::scheduler::local::LocalQueryExecution::run_inner::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:102:5
  44: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  45: <tracing_futures::Instrumented<T> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-futures-0.2.5/src/lib.rs:342:9
  46: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
  47: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
  48: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  49: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  50: risingwave_frontend::scheduler::local::LocalQueryExecution::stream_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:153:56
  51: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  52: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  53: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  54: risingwave_frontend::scheduler::local::LocalQueryExecution::stream_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:169:77
  55: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  56: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  57: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  58: risingwave_frontend::scheduler::local::LocalQueryExecution::stream_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:170:63
  59: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  60: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  61: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  62: risingwave_frontend::scheduler::local::LocalQueryExecution::stream_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:171:71
  63: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  64: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  65: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  66: risingwave_frontend::scheduler::local::LocalQueryExecution::stream_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:172:73
  67: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  68: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  69: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  70: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  71: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  72: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
  73: std::panicking::try::do_call
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
  74: ___rust_try
  75: std::panicking::try
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
  76: std::panic::catch_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
  77: tokio::runtime::task::harness::poll_future
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  78: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  79: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  80: tokio::runtime::task::raw::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  81: tokio::runtime::task::raw::RawTask::poll
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  82: tokio::runtime::task::LocalNotified<S>::run
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  83: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:576:13
  84: tokio::runtime::coop::with_budget
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  85: tokio::runtime::coop::budget
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  86: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  87: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  88: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  89: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  90: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/rossil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  91: std::thread::local::LocalKey<T>::try_with
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:270:16
  92: std::thread::local::LocalKey<T>::with
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:246:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023年11月16日 星期四 05时36分16秒 UTC [risedev]: Program exited with 134
```

### To Reproduce

UDF:
```python
from risingwave.udf import udf, UdfServer


@udf(input_types=["INT"], result_type="INT")
def echo(inp) -> int:
    return inp

@udf(input_types=[], result_type="INT")
def echo_42() -> int:
    return 42

if __name__ == "__main__":
    server = UdfServer(location="localhost:8816")
    server.add_function(echo)
    server.add_function(echo_42)
    server.serve()
```

SQL:
```sql
CREATE FUNCTION test_func() RETURNS INT LANGUAGE python as echo_42 using link 'http://localhost:8816';
SELECT * FROM rw_functions;
```

### How did you deploy RisingWave?

Risedev

**Comment by Rossil2012** [comment]
cc @yezizp2012

**Comment by Rossil2012** [comment]
> Please remember to add an e2e test after the fix.

The bug occurs during e2e test of #13341. So we do not need an additional test for it.
