### ISSUE TITLE
Bug: panic on cancel creating cdc source job

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#13758]
### Describe the bug

```
thread 'risingwave-main' panicked at /Users/siyuan/workspace/acting/rust/risingwave/src/meta/src/manager/catalog/mod.rs:2456:9:
source must be in creating procedure
```

### Error message/log

```text
2023-12-01T11:32:09.633787+08:00 DEBUG risingwave_connector::source::cdc::enumerator: validate cdc source properties success
2023-12-01T11:32:09.633946+08:00  INFO risingwave_meta::stream::source_manager: spawning new watcher for source 1001
2023-12-01T11:32:09.634203+08:00 DEBUG risingwave_meta::rpc::ddl_controller: creating stream job id=1001
2023-12-01T11:32:09.635299+08:00  INFO risingwave_common::monitor::connection: monitoring connector hyper::client::connect::http::HttpConnector with type grpc-stream-client
2023-12-01T11:32:09.638687+08:00 DEBUG risingwave_meta::stream::stream_manager: update actors request_id="2eecba31-2819-4ef2-be57-febe423b9c64" actors=[1]
2023-12-01T11:32:09.639914+08:00 DEBUG risingwave_meta::stream::stream_manager: build actors request_id="707c9932-5102-423c-98d3-7fee5d67480a" actors=[1]
2023-12-01T11:32:09.643059+08:00  INFO risingwave_meta::stream::source_manager: new discovered splits fragment_id=1 new_discovered_splits={"1001"}
2023-12-01T11:32:14.312615+08:00  WARN risingwave_meta::barrier: Failed to complete epoch 5515924710621184: gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. }
  backtrace of `MetaError`:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/backtrace.rs:331:13
   3: <risingwave_meta::error::MetaError as core::convert::From<risingwave_meta::error::MetaErrorInner>>::from
             at ./src/meta/src/error.rs:114:33
   4: <T as core::convert::Into<U>>::into
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/convert/mod.rs:757:9
   5: <risingwave_meta::error::MetaError as core::convert::From<risingwave_rpc_client::error::RpcError>>::from
             at ./src/meta/src/error.rs:209:9
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/result.rs:1963:27
   7: risingwave_meta::barrier::GlobalBarrierManager::inject_barrier_inner::{{closure}}
             at ./src/meta/src/barrier/mod.rs:855:9
   8: risingwave_meta::barrier::GlobalBarrierManager::inject_barrier::{{closure}}
             at ./src/meta/src/barrier/mod.rs:782:73
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tracing-0.1.37/src/instrument.rs:272:9
  10: risingwave_meta::barrier::GlobalBarrierManager::handle_new_barrier::{{closure}}
             at ./src/meta/src/barrier/mod.rs:755:14
  11: risingwave_meta::barrier::GlobalBarrierManager::run::{{closure}}
             at ./src/meta/src/barrier/mod.rs:699:104
  12: risingwave_meta::barrier::GlobalBarrierManager::start::{{closure}}
             at ./src/meta/src/barrier/mod.rs:563:46
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/future/future.rs:125:9
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/core.rs:334:17
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  17: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/core.rs:323:13
  18: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
  21: ___rust_try
  22: std::panicking::try
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
  23: std::panic::catch_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
  24: tokio::runtime::task::harness::poll_future
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  25: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  26: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  27: tokio::runtime::task::raw::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  28: tokio::runtime::task::raw::RawTask::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  29: tokio::runtime::task::LocalNotified<S>::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  30: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:639:17
  31: tokio::runtime::coop::with_budget
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/coop.rs:107:5
  32: tokio::runtime::coop::budget
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/coop.rs:73:5
  33: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  35: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  36: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  37: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/context.rs:176:26
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:270:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/local.rs:246:9
  40: tokio::runtime::context::set_scheduler
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/context.rs:176:9
  41: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  42: tokio::runtime::context::runtime::enter_runtime
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  43: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  44: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  45: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  46: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tracing-0.1.37/src/instrument.rs:272:9
  47: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/core.rs:334:17
  48: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  49: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/core.rs:323:13
  50: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  51: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
  52: std::panicking::try::do_call
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
  53: ___rust_try
  54: std::panicking::try
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
  55: std::panic::catch_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
  56: tokio::runtime::task::harness::poll_future
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  59: tokio::runtime::task::raw::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  60: tokio::runtime::task::raw::RawTask::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  61: tokio::runtime::task::UnownedTask<S>::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  62: tokio::runtime::blocking::pool::Task::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  63: tokio::runtime::blocking::pool::Inner::run
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  64: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
  65: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/sys_common/backtrace.rs:154:18
  66: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/mod.rs:529:17
  67: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panic/unwind_safe.rs:271:9
  68: std::panicking::try::do_call
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:504:40
  69: ___rust_try
  70: std::panicking::try
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:468:19
  71: std::panic::catch_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panic.rs:142:14
  72: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/thread/mod.rs:528:30
  73: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/ops/function.rs:250:5
  74: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/boxed.rs:2007:9
  75: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/alloc/src/boxed.rs:2007:9
  76: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/sys/unix/thread.rs:108:17
  77: __pthread_joiner_wake

2023-12-01T11:32:14.596413+08:00  INFO failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::barrier::recovery: recovery start!
2023-12-01T11:32:14.596453+08:00 DEBUG failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::manager::catalog: creating_tables ids: []
2023-12-01T11:32:14.596604+08:00 DEBUG failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::barrier::recovery: clean dirty table fragments: {TableId { table_id: 1001 }}
2023-12-01T11:32:14.597038+08:00  INFO risingwave_meta::manager::sink_coordination::manager: sink manager worker start cleaning up
2023-12-01T11:32:14.597053+08:00  INFO risingwave_meta::manager::sink_coordination::manager: sink manager worker finished cleaning up
2023-12-01T11:32:14.597078+08:00  INFO failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::manager::sink_coordination::manager: successfully stop coordinator: None
2023-12-01T11:32:14.59709+08:00  INFO failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::barrier::recovery: recovering mview progress
2023-12-01T11:32:14.597144+08:00  INFO failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}: risingwave_meta::barrier::recovery: recovered mview progress
2023-12-01T11:32:14.597171+08:00 DEBUG risingwave_meta::stream::stream_manager: stream job failed id=TableId { table_id: 1001 }
thread 'risingwave-main' panicked at /Users/siyuan/workspace/acting/rust/risingwave/src/meta/src/manager/catalog/mod.rs:2456:9:
source must be in creating procedure
stack backtrace:
2023-12-01T11:32:14.597293+08:00 DEBUG failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}:recovery_attempt: risingwave_meta::barrier::recovery: start migrate actors.
2023-12-01T11:32:14.597309+08:00 DEBUG failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}:recovery_attempt: risingwave_meta::barrier::recovery: no expired workers, skipping.
2023-12-01T11:32:14.597399+08:00 DEBUG failure_recovery{err=gRPC request to stream service failed: Internal error: failed to send barrier to actor 1: SendError { .. } prev_epoch=5515924396703744}:recovery_attempt: risingwave_meta::barrier::recovery: force stop actors worker=1
   0: rust_begin_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:72:14
   2: risingwave_meta::manager::catalog::CatalogManager::cancel_create_source_procedure::{{closure}}
             at ./src/meta/src/manager/catalog/mod.rs:2456:9
   3: risingwave_meta::rpc::ddl_controller::DdlController::cancel_stream_job::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:831:22
   4: risingwave_meta::rpc::ddl_controller::DdlController::create_streaming_job_inner::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:547:26
   5: risingwave_meta::rpc::ddl_controller::DdlController::create_streaming_job::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:495:22
   6: risingwave_meta::rpc::ddl_controller::DdlController::run_command::{{closure}}::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:248:26
   7: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tracing-0.1.37/src/instrument.rs:272:9
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/future/future.rs:125:9
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/tracing-0.1.37/src/instrument.rs:272:9
  10: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}



```
```


### To Reproduce

_No response_

### Expected behavior

_No response_

### How did you deploy RisingWave?

_No response_

### The version of RisingWave

_No response_

### Additional context

_No response_

**Comment by yezizp2012** [comment]
I found that the in-memory tracking status might be cleared by `clean_dirty_tables` via `clear_creating_stream_jobs` during recovery, which results in panic of canceling other `CREATE` ddls that are not mviews. Cc @kwannoel ,  `clear_creating_stream_jobs` should not be called, removing it could fix this issue.

**Comment by kwannoel** [comment]
> I found that the in-memory tracking status might be cleared by `clean_dirty_tables` via `clear_creating_stream_jobs` during recovery, which results in panic of canceling other `CREATE` ddls that are not mviews. Cc @kwannoel , `clear_creating_stream_jobs` should not be called, removing it could fix this issue.

Hmm why should it not be called 🤔 . IIUC any in-memory stream jobs should be purged on recovery.

**Comment by kwannoel** [comment]
Any info on how to reproduce?

**Comment by StrikeW** [comment]
I found this bug by modifying the code in to return `false` to the `inited`: https://github.com/risingwavelabs/risingwave/blob/5831af86c1617d9c0509e9e19252e5b828eec918/src/connector/src/source/cdc/source/reader.rs#L150

Then execute following sql to create a cdc source job:
```
set cdc_backfill='true';
create source mysql_mydb with (
     connector = 'mysql-cdc',
     hostname = 'localhost',
     port = '8306',
     username = 'dbz',
     password = '123456',
     database.name = 'mydb',
     server.id = '5601'
);
```
