### ISSUE TITLE
alter table rename panic if there is some sinkToTable from the table.

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#14068]
```SQL
dev=> create table t (v int) append only;
NOTICE:  APPEND ONLY TABLE is currently an experimental feature.
CREATE_TABLE
dev=> create table tt (v int) append only;
NOTICE:  APPEND ONLY TABLE is currently an experimental feature.
CREATE_TABLE
dev=> create sink s from t with (connector='blackhole');
^C
dev=> create sink s into tt as select * from t;
CREATE_SINK
dev=> select definition from rw_sinks;
            definition            
----------------------------------
 CREATE SINK s AS SELECT * FROM t
(1 row)

dev=> alter table tt rename to t_re1;
ALTER_TABLE
dev=> alter table t rename to t_re2;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request failed: Unknown error
  2: transport error
  3: connection error
  4: connection reset
```

```
thread 'risingwave-main' panicked at src/meta/src/manager/catalog/utils.rs:94:45:
failed to parse relation definition: ParserError("Expected WITH, found: EOF at the end\nNear \" AS SELECT * FROM t\"")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::expect
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/result.rs:1034:23
   4: risingwave_meta::manager::catalog::utils::alter_relation_rename_refs
             at ./src/meta/src/manager/catalog/utils.rs:94:15
   5: risingwave_meta::manager::catalog::CatalogManager::alter_relation_name_refs_inner::{{closure}}
             at ./src/meta/src/manager/catalog/mod.rs:1752:35
   6: risingwave_meta::manager::catalog::CatalogManager::alter_table_name::{{closure}}
             at ./src/meta/src/manager/catalog/mod.rs:1717:10
   7: risingwave_meta::rpc::ddl_controller::DdlController::alter_name::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:1529:22
```

## the other sink do not have the issue

```SQL
dev=> create table t (v int) append only;
NOTICE:  APPEND ONLY TABLE is currently an experimental feature.
CREATE_TABLE
dev=> create sink s from t with (connector='blackhole');
CREATE_SINK
dev=> create sink ss as select * from  t with (connector='blackhole');
CREATE_SINK
dev=> select * from rw_sinks;
dev=> select definition from rw_sinks;
                            definition                            
------------------------------------------------------------------
 CREATE SINK s FROM t WITH (connector = 'blackhole')
 CREATE SINK ss AS SELECT * FROM t WITH (connector = 'blackhole')
(2 rows)

dev=> alter table t rename to t_re;
ALTER_TABLE
dev=> select definition from rw_sinks;
                                definition                                
--------------------------------------------------------------------------
 CREATE SINK s FROM t_re WITH (connector = 'blackhole')
 CREATE SINK ss AS SELECT * FROM t_re AS t WITH (connector = 'blackhole')
(2 rows)

```

**Comment by st1page** [comment]
fixed by some PR somehow....
