### ISSUE TITLE
risingwave_stream::executor::aggregation::agg_group: bad row count group=OwnedRow(...) 

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14095]
Some users recently encounter this, after cluster recovery.

```
thread 'risingwave-streaming-actor' panicked at /risingwave/src/stream/src/executor/aggregation/agg_group.rs:320:13: row count should be non-negative
```

**Comment by kwannoel** [comment]
Related https://github.com/risingwavelabs/risingwave/issues/14031

**Comment by kwannoel** [comment]
I can confirm this should probably be due to case backwards compatibility.

On `v1.4-rc`:
```
drop table t cascade;
create table t(x boolean, a int, y boolean, b int);
insert into t values (true, 1, true, 2);
create materialized view m1 as select 'abc' as v1, case when x then a when y then b end as case_col from t group by case_col;
select * from m1;
```

On `v1.5.0-rc`:
```
delete from t;
flush;
```

Agg panics with:
```
thread 'risingwave-streaming-actor' panicked at /Users/noelkwan/projects/risingwave/src/stream/src/executor/aggregation/agg_group.rs:320:13:
row count should be non-negative
stack backtrace:
   0: rust_begin_unwind
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/panicking.rs:72:14
   2: risingwave_stream::executor::aggregation::agg_group::AggGroup<S,Strtg>::curr_row_count
             at ./src/stream/src/executor/aggregation/agg_group.rs:320:13
   3: risingwave_stream::executor::aggregation::agg_group::AggGroup<S,Strtg>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/aggregation/agg_group.rs:351:12
   4: risingwave_stream::executor::hash_agg::HashAggExecutor<K,S>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/hash_agg.rs:419:18
   5: risingwave_stream::executor::hash_agg::HashAggExecutor<K,S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/hash_agg.rs:650:68
   6: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.28/src/stream.rs:120:9
   9: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
Sat Dec 23 03:00:56 UTC 2023 [risedev]: Program exited with 139

```

**Comment by stdrc** [comment]
Is this possibly caused by https://github.com/risingwavelabs/risingwave/pull/13890? Cc @wangrunji0408

**Comment by kwannoel** [comment]
> Is this possibly caused by https://github.com/risingwavelabs/risingwave/pull/13890? Cc @wangrunji0408 

Yeah, may look at bugens comment in that PR

**Comment by MrCroxx** [comment]
> > Is this possibly caused by #13890? Cc @wangrunji0408
> 
> Yeah, may look at bugens comment in that PR

FYI: https://github.com/risingwavelabs/risingwave/pull/13890#issuecomment-1853217308

**Comment by kwannoel** [comment]
One of the root cause is case expression. For the other root cause it is unclear.

For case expression, we can't really avoid the breaking change in `expr` framework.

We have to inform users of the breaking change via the release notes, and get them to recreate any MVs with case expressions. The `v1.5` release notes have been updated for `CASE` expression.
<img width="1089" alt="Screenshot 2024-01-09 at 12 17 56 PM" src="https://github.com/risingwavelabs/risingwave/assets/47273164/0d94f575-5ba3-46f5-90ce-0bdfdc7d6c8a">

https://docs.risingwave.com/release-notes/
