### ISSUE TITLE
Connector log: superfluous Java object creation

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#14291]
### Describe the bug

The `TracingSlf4jAdapter` implemented by https://github.com/risingwavelabs/risingwave/pull/14082 doesn't check whether a specific logging level is enabled before constructing the log message, which will create superfluous objects in the java side.

For example, `TRACE` level may not be enabled, but the Java object will always be created.
```rust
 @Override
    public void trace(String format, Object arg) {
        TracingSlf4jImpl.event(
                name,
                TracingSlf4jImpl.TRACE,
                new ParameterizedMessage(format, arg).getFormattedMessage());
    }
```

### Error message/log

```text
risingwave-standalone  | Caused by: java.lang.UnsupportedOperationException
risingwave-standalone  | 	at java.sql/java.sql.Date.toInstant(Date.java:316)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterFormatter.appendDate(ParameterFormatter.java:492)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterFormatter.appendSpecialTypes(ParameterFormatter.java:485)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:474)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterFormatter.recursiveDeepToString(ParameterFormatter.java:449)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterFormatter.formatMessage2(ParameterFormatter.java:192)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterizedMessage.formatTo(ParameterizedMessage.java:227)
risingwave-standalone  | 	at org.apache.logging.log4j.message.ParameterizedMessage.getFormattedMessage(ParameterizedMessage.java:203)
risingwave-standalone  | 	at com.risingwave.tracing.TracingSlf4jAdapter.trace(TracingSlf4jAdapter.java:63)
risingwave-standalone  | 	at io.debezium.connector.postgresql.connection.PostgresConnection.getColumnValue(PostgresConnection.java:740)
risingwave-standalone  | 	at io.debezium.jdbc.JdbcConnection.rowToArray(JdbcConnection.java:1553)
risingwave-standalone  | 	at io.debezium.relational.RelationalSnapshotChangeEventSource.doCreateDataEventsForTable(RelationalSnapshotChangeEventSource.java:555)
risingwave-standalone  | 	at io.debezium.relational.RelationalSnapshotChangeEventSource.lambda$createDataEventsForTableCallable$6(RelationalSnapshotChangeEventSource.java:515)
risingwave-standalone  | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
risingwave-standalone  | 	... 5 more
risingwave-standalone  |  thread="debezium-postgresconnector-RW_CDC_1002-change-event-source-coordinator" class="io.debezium.pipeline.ErrorHandler"

```

### Expected behavior

Check logging level before constructing the log message, e.g.

```java
/**
     * Log a message at level TRACE according to the specified format and
     * arguments.
     * 
     * <p>
     * This form avoids superfluous object creation when the logger is disabled
     * for the TRACE level.
     * </p>
     * 
     * @param format
     *          the format string
     * @param arg1
     *          the first argument
     * @param arg2
     *          the second argument
     */
    public void trace(String format, Object arg1, Object arg2) {
        if (isTraceEnabled()) {
            FormattingTuple ft = MessageFormatter.format(format, arg1, arg2);
            logger.log(FQCN, traceCapable ? Level.TRACE : Level.DEBUG, ft.getMessage(), ft.getThrowable());
        }
    }
```

**Comment by BugenZhao** [comment]
This is indeed a problem. However, is the exception in the log expected?

```
risingwave-standalone  | Caused by: java.lang.UnsupportedOperationException
risingwave-standalone  | 	at java.sql/java.sql.Date.toInstant(Date.java:316)
```

**Comment by StrikeW** [comment]
The log is printed in https://github.com/debezium/debezium/blob/65b25c6494995cbcfe2897f4afdb232a5cf61259/debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresConnection.java#L740, the `ParameterizedMessage` will try to format it. And we have a `Date` column in upstream, which corresponding to `java.sql.Date` in JDBC, and it doesn't support `toInstant` method. I think the exception is expected with `ParameterizedMessage`.
