### ISSUE TITLE
main-cron: end-to-end iceberg sink v2 test failed

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#14673]
```
  | Executing sql: SELECT * FROM demo_db.demo_table ORDER BY id, v1 ASC
  | Row(id=1, v1=1, v2=50, v3='1-50')
  | Row(id=1, v1=2, v2=2, v3='2-2')
  | Row(id=1, v1=5, v2=2, v3='5-2')
  | Row(id=1, v1=21, v2=2, v3='21-2')
  | Traceback (most recent call last):
  | File "/risingwave/e2e_test/iceberg/main.py", line 116, in <module>
  | verify_result(config,verify_sql,verify_schema,verify_data)
  | File "/risingwave/e2e_test/iceberg/main.py", line 65, in verify_result
  | tc.assertEqual(len(df), len(rows))
  | File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
  | assertion_func(first, second, msg=msg)
  | File "/usr/lib/python3.10/unittest/case.py", line 838, in _baseAssertEqual
  | raise self.failureException(msg)
  | AssertionError: 4 != 7


```

This frequently occurred in recent tests. Examples above taken from https://buildkite.com/risingwavelabs/main-cron/builds/1539#018d184a-ef9b-4bd3-8fb0-2e4c659e3fda.

cc @liurenjie1024 Would you help to take a look?

**Comment by liurenjie1024** [comment]
Yeah, I will fix it.
