### ISSUE TITLE
Background ddl tests failed with: `scale actors failed error=the materialized view of fragment 401008 is in state INITIAL`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#14992]
### Describe the bug

It occurs in our recovery tests:
https://buildkite.com/risingwavelabs/main-cron/builds/1778#018d74dd-0b1e-4e29-8578-39dc395dd5ee

### Error message/log

```text
2022-07-18T10:40:24.314185Z DEBUG risingwave_simulation::slt: retry count iteration=5
2022-07-18T10:40:25.325206Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:25.325206Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:28.924928Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:28.924928Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:32.702053Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:32.702053Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401009 is in state INITIAL
2022-07-18T10:40:37.381402Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:37.381402Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401009 is in state INITIAL
2022-07-18T10:40:39.165781Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:39.165781Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:40.456610Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:40.456610Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:40:42.244699Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:42.244699Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:44.470323Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:44.470323Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:40:46.658468Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:46.658468Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:47.006909Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:47.006909Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:47.073633Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:47.073633Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:40:49.112516Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:49.112516Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401008 is in state INITIAL
2022-07-18T10:40:52.450178Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:52.450178Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401009 is in state INITIAL
2022-07-18T10:40:55.598938Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:40:55.598938Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401009 is in state INITIAL
2022-07-18T10:40:56.332080Z DEBUG risingwave_simulation::slt: Record Statement { loc: Location { file: "e2e_test/streaming/rate_limit/snapshot_amplification.slt", line: 20, upper: None }, conditions: [], connection: Default, expected_error: None, sql: "CREATE SINK sink AS\n    SELECT x.i1 as i1 FROM table x\n        JOIN table s1 ON x.i1 = s1.i1\n            JOIN table s2 ON x.i1 = s2.i1\n    WITH (connector = 'blackhole');", expected_count: None } finished in 17.894836ms
thread '<unnamed>' panicked at /risingwave/src/tests/simulation/src/slt.rs:384:33:
failed to run test after retry 5 times: statement failed: db error: ERROR: Failed to run the query

Caused by these errors (recent errors listed first):
  1: gRPC request to meta service failed: Internal error
  2: The cluster is recovering

[SQL] CREATE SINK sink AS
    SELECT x.i1 as i1 FROM table x
        JOIN table s1 ON x.i1 = s1.i1
            JOIN table s2 ON x.i1 = s2.i1
    WITH (connector = 'blackhole');
at e2e_test/streaming/rate_limit/snapshot_amplification.slt:20

stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:384:33
             at ./src/tests/simulation/src/main.rs:268:84
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=14 "client", task=681 (spawned at /risingwave/src/tests/simulation/src/cluster.rs:590:21)
note: run with `MADSIM_TEST_SEED=12` environment variable to reproduce this error
```

**Comment by kwannoel** [comment]
Not sure if it's a blocking issue for 1.7 release.

**Comment by yezizp2012** [comment]
```
2022-07-18T10:39:53.645088Z DEBUG risingwave_meta::rpc::ddl_controller: starting stream job id=402010 definition="CREATE SINK sink AS SELECT x.i1 AS i1 FROM table AS x JOIN table AS s1 ON x.i1 = s1.i1 JOIN table AS s2 ON x.i1 = s2.i1 WITH (connector = 'blackhole')"
2022-07-18T10:39:53.645088Z DEBUG risingwave_meta::rpc::ddl_controller: preparing stream job id=402010
2022-07-18T10:39:53.645088Z DEBUG risingwave_meta::rpc::ddl_controller: building stream job id=402010
2022-07-18T10:39:53.786265Z  INFO risingwave_simulation::cluster: kill compute-3
2022-07-18T10:39:53.904617Z  INFO risingwave_simulation::cluster: kill meta-1
2022-07-18T10:39:53.909685Z  INFO risingwave_meta::barrier::recovery: recovery start!
2022-07-18T10:39:53.916741Z  INFO risingwave_simulation::cluster: restart compute-3
2022-07-18T10:39:53.937698Z DEBUG risingwave_meta::rpc::ddl_controller: creating stream job id=402010
2022-07-18T10:39:53.937698Z DEBUG risingwave_meta::manager::catalog: creating_tables ids: []
2022-07-18T10:39:53.947170Z DEBUG risingwave_meta::barrier::recovery: clean dirty table fragments: {}
2022-07-18T10:39:53.952062Z  INFO risingwave_meta::barrier::recovery: recovering mview progress
2022-07-18T10:39:53.961197Z  INFO risingwave_meta::barrier::recovery: recovered mview progress
2022-07-18T10:39:53.961197Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:39:53.961197Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:39:53.969957Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:39:53.969957Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:39:54.149030Z DEBUG recovery_attempt: risingwave_meta::barrier::recovery: start resetting actors distribution
2022-07-18T10:39:54.149030Z  WARN recovery_attempt: risingwave_meta::barrier::recovery: scale actors failed error=the materialized view of fragment 401007 is in state INITIAL
2022-07-18T10:39:54.166391Z  INFO risingwave_simulation::cluster: kill compute-1
```

The timeline is as follows: during the process of creating a sink, CN was killed and recovery started. During the clean dirty phase, the table fragment of the sink was retained. Before auto scaling was enabled, the sink still had the possibility of success or injecting and collecting barriers causing another recovery to be cleaned up by the thread that created it. Now that auto scaling has been enabled, it fails during assertion, leading to continuous recovery. 
Since it cannot be determined whether the DDL thread writes into table fragments during cleaning, allowing auto scaling to operate together with initializing or creating table fragments should currently be the only solution.Cc @shanicky
