### ISSUE TITLE
`hummock::event_handler::hummock_event_handler::tests::test_event_handler` FAILED

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#15118]
https://buildkite.com/risingwavelabs/main-cron/builds/1873#018dbcf2-d25c-4a91-b3c2-d3b167619410:
```
failures:
--
  |  
  | failures:
  | hummock::event_handler::hummock_event_handler::tests::test_event_handler
  |  
  | test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 135 filtered out; finished in 0.55s
  |  
  |  
  | --- STDERR:              risingwave_storage hummock::event_handler::hummock_event_handler::tests::test_event_handler ---
  | thread '<unnamed>' panicked at src/storage/src/hummock/event_handler/hummock_event_handler.rs:960:9:
  | assertion `left == right` failed
  | left: [846, 845, 844, 843, 842, 841, 840, 839, 838, 837, 836]
  | right: [846, 836]
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
  | 1: core::panicking::panic_fmt
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
  | 2: core::panicking::assert_failed_inner
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:342:17
  | 3: core::panicking::assert_failed
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:297:5
  | 4: risingwave_storage::hummock::event_handler::hummock_event_handler::tests::test_event_handler::{{closure}}::{{closure}}
  | at ./src/hummock/event_handler/hummock_event_handler.rs:960:9
  | 5: madsim::sim::task::Executor::block_on::{{closure}}::{{closure}}
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:230:32
  | 6: <core::pin::Pin<P> as core::future::future::Future>::poll
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  | 7: async_task::raw::RawTask<F,T,S,M>::run
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  | 8: async_task::runnable::Runnable<M>::run
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
  | 9: madsim::sim::task::Executor::run_all_ready::{{closure}}
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:50
  | 10: std::panicking::try::do_call
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  | 11: __rust_try
  | 12: std::panicking::try
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  | 13: std::panic::catch_unwind
  | at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  | 14: madsim::sim::task::Executor::run_all_ready
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:271:17
  | 15: madsim::sim::task::Executor::block_on
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/task/mod.rs:238:13
  | 16: madsim::sim::runtime::Runtime::block_on
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:9
  | 17: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
  | at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/builder.rs:128:35
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | context: node=0 "main", task=304 (spawned at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.22/src/sim/runtime/mod.rs:126:19)
  | note: run with `MADSIM_TEST_SEED=1708272517634405559` environment variable to reproduce this error
```

**Comment by hzxa21** [comment]
The assertion fails after imm merge finishes.
https://github.com/risingwavelabs/risingwave/blob/8323b17ff5e3e66e9f79eeba99971622c5908471/src/storage/src/hummock/event_handler/hummock_event_handler.rs#L902


Given that it happens on main-cron, I think it is related to mistakenly enable `enable_test_epoch` feature in main-cron build (details [here](https://github.com/risingwavelabs/risingwave/issues/15324#issuecomment-1970505860)), which will result in incorrect epoch being used. The issue should be fixed so let's see whether we still see this issue still happens in recent main-cron test.

**Comment by wcy-fdu** [comment]
fixed via https://github.com/risingwavelabs/risingwave/pull/14557
