### ISSUE TITLE
bug: panicked at `barrier/schedule.rs:244:18`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15848]
### Describe the bug

Failure in recovery test: https://buildkite.com/risingwavelabs/main-cron/builds/2104#018e5c98-0655-4b21-b3d1-343a8b3bf96c/99

### Error message/log

```text
thread '<unnamed>' panicked at /risingwave/src/meta/src/barrier/schedule.rs:244:18:
called `Result::unwrap()` on an `Err` value: RecvError(())
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
             at ./src/meta/src/barrier/schedule.rs:244:9
             at ./src/meta/src/barrier/schedule.rs:327:59
             at ./src/meta/service/src/stream_service.rs:72:69
             at ./src/prost/src/sim/meta.rs:2980:30
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=6 "meta-3", task=731805 (spawned at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-tonic-0.4.1+0.10.0/src/transport/server.rs:275:13)
note: run with `MADSIM_TEST_SEED=10` environment variable to reproduce this error
```

**Comment by fuyufjh** [comment]
Suspect it might be related to https://github.com/risingwavelabs/risingwave/pull/13108 

cc. @yezizp2012 Can you please take a look?
