### ISSUE TITLE
bug: thread 'rw-batch' panicked at /risingwave/src/utils/iter_util/src/lib.rs:28:9

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15899]
### Describe the bug

https://buildkite.com/risingwavelabs/main-cron/builds/2154#018e7577-bd40-4e4f-ac86-a5ff0c4d0010

### Error message/log

```text
thread 'rw-batch' panicked at /risingwave/src/utils/iter_util/src/lib.rs:28:9:
assertion `left == right` failed
  left: 1024
 right: 54
stack backtrace:
thread 'rw-batch' panicked at /risingwave/src/utils/iter_util/src/lib.rs:28:9:
assertion `left == right` failed
  left: 1024
 right: 0
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:297:5
   4: zip_eq_fast<risingwave_common::buffer::bitmap::BitmapIter, core::slice::iter::Iter<risingwave_batch::executor::join::chunked_data::RowId>>
             at ./src/utils/iter_util/src/lib.rs:28:9
   5: remove_duplicate_rows_for_full_outer_join
             at ./src/batch/src/executor/join/hash_join.rs:1766:13
   6: {async_fn#0}<risingwave_common::hash::key_v2::HashKeyImpl<risingwave_common::hash::key_v2::StackStorage<16>, risingwave_common::hash::key::StackNullBitmap>>
             at ./src/batch/src/executor/join/hash_join.rs:1441:12
   7: {coroutine#0}<risingwave_common::hash::key_v2::HashKeyImpl<risingwave_common::hash::key_v2::StackStorage<8>, risingwave_common::hash::key::StackNullBitmap>>
             at ./src/batch/src/executor/join/hash_join.rs:1196:26
   8: poll_next<risingwave_batch::executor::join::hash_join::{impl#4}::do_full_outer_join_with_non_equi_condition::{coroutine_env#0}<risingwave_common::hash::key_v2::HashKeyImpl<risingwave_common::hash::key_v2::StackStorage<8>, risingwave_common::hash::key::StackNullBitmap>>, risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
   9: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<(), risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  10: {coroutine#0}<risingwave_common::hash::key_v2::HashKeyImpl<risingwave_common::hash::key_v2::StackStorage<8>, risingwave_common::hash::key::StackNullBitmap>>
             at ./src/batch/src/executor/join/hash_join.rs:224:5
  11: poll_next<risingwave_batch::executor::join::hash_join::{impl#4}::do_execute::{coroutine_env#0}<risingwave_common::hash::key_v2::HashKeyImpl<risingwave_common::hash::key_v2::StackStorage<8>, risingwave_common::hash::key::StackNullBitmap>>, risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  12: poll_next<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  13: poll_next_unpin<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  14: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  15: poll<futures_util::stream::stream::next::Next<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  16: poll_unpin<tracing::instrument::Instrumented<futures_util::stream::stream::next::Next<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/mod.rs:558:9
  17: poll<core::pin::Pin<&mut risingwave_batch::task::task_execution::{impl#9}::cancelled::{async_fn_env#0}>, tracing::instrument::Instrumented<futures_util::stream::stream::next::Next<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/select.rs:118:35
  18: {coroutine#0}
             at ./src/batch/src/executor/managed.rs:61:82
  19: poll_next<risingwave_batch::executor::managed::{impl#1}::execute::{coroutine_env#0}, risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  20: poll<alloc::boxed::Box<(dyn core::future::future::Future<Output=core::result::Result<(), risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  21: poll_next_unpin<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  22: poll<core::pin::Pin<alloc::boxed::Box<(dyn futures_core::stream::Stream<Item=core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>> + core::marker::Send), alloc::alloc::Global>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:21
  23: {closure#3}<risingwave_batch::task::context::ComputeNodeContext>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/macros/select.rs:524:49
  24: poll<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn#0}::__tokio_select_util::Out<(), core::option::Option<core::result::Result<risingwave_common::array::data_chunk::DataChunk, risingwave_batch::error::BatchError>>>, risingwave_batch::task::task_execution::{impl#10}::run::{async_fn#0}::{closure_env#3}<risingwave_batch::task::context::ComputeNodeContext>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/future/poll_fn.rs:58:9
  25: {async_fn#0}<risingwave_batch::task::context::ComputeNodeContext>
             at ./src/batch/src/task/task_execution.rs:613:13
  26: poll<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn_env#0}<risingwave_batch::task::context::ComputeNodeContext>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  27: {closure#0}<alloc::string::String, tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  28: scope_inner<alloc::string::String, tokio::task::task_local::{impl#3}::poll::{closure_env#0}<alloc::string::String, tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>, core::option::Option<core::task::poll::Poll<()>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  29: poll<alloc::string::String, tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  30: {async_fn#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::run::{async_fn_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>
             at ./src/expr/core/src/expr_context.rs:35:65
  31: {async_block#0}<risingwave_batch::task::context::ComputeNodeContext>
             at ./src/batch/src/task/task_execution.rs:502:18
  32: call_once<fn(core::pin::Pin<&mut risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, &mut core::task::wake::Context) -> core::task::poll::Poll<()>, (core::pin::Pin<&mut risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, &mut core::task::wake::Context)>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/ops/function.rs:250:5
  33: instrument_poll<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>, (), fn(core::pin::Pin<&mut risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, &mut core::task::wake::Context) -> core::task::poll::Poll<()>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.3.0/src/task.rs:2530:15
  34: poll<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-metrics-0.3.0/src/task.rs:2430:9
  35: poll<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:297:9
  36: {closure#0}<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/catch_unwind.rs:36:42
  37: call_once<core::task::poll::Poll<()>, futures_util::future::future::catch_unwind::{impl#1}::poll::{closure_env#0}<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:272:9
  38: do_call<core::panic::unwind_safe::AssertUnwindSafe<futures_util::future::future::catch_unwind::{impl#1}::poll::{closure_env#0}<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  39: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<futures_util::future::future::catch_unwind::{impl#1}::poll::{closure_env#0}<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  40: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<futures_util::future::future::catch_unwind::{impl#1}::poll::{closure_env#0}<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  41: poll<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/catch_unwind.rs:36:9
  42: {closure#0}<(), futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:347:31
  43: scope_inner<(), tokio::task::task_local::{impl#3}::poll::{closure_env#0}<(), futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>, core::option::Option<core::task::poll::Poll<core::result::Result<(), alloc::boxed::Box<(dyn core::any::Any + core::marker::Send), alloc::alloc::Global>>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:217:19
  44: poll<(), futures_util::future::future::catch_unwind::CatchUnwind<core::panic::unwind_safe::AssertUnwindSafe<tokio_metrics::task::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block#0}::{closure#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/task/task_local.rs:343:19
  45: {async_block#0}<risingwave_batch::task::context::ComputeNodeContext>
             at ./src/batch/src/task/task_execution.rs:509:73
  46: poll<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  47: {closure#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  48: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  49: poll<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  50: {closure#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  51: call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:272:9
  52: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  53: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  54: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  55: poll_future<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  56: poll_inner<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  57: poll<tracing::instrument::Instrumented<risingwave_batch::task::task_execution::{impl#10}::async_execute::{async_fn#0}::{async_block_env#0}<risingwave_batch::task::context::ComputeNodeContext>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  58: run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  59: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:639:22
  60: with_budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  61: budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  62: run_task
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  63: run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  64: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  65: set<tokio::runtime::scheduler::Context, tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}, ()>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  66: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  67: enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::{closure_env#0}, ()>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  68: run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  69: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  70: poll<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}, ()>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  71: poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  72: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  73: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  74: poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  75: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  76: call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:272:9
  77: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  78: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  79: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  80: poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  81: poll_inner<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  82: poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  83: run<tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  84: run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  85: run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  86: {closure#0}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
```

**Comment by fuyufjh** [comment]
https://github.com/risingwavelabs/risingwave/pull/15853 seems to be the most recent change to batch hash join. @st1page  Can you pls take a look?
