### ISSUE TITLE
bug: panicked at src/storage/src/hummock/event_handler/uploader.rs:1040:26: epoch should not be empty

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#16190]
### Describe the bug

Found in the [CI run ](https://buildkite.com/risingwavelabs/pull-request/builds/46644#018eb773-21e5-4bff-8bc4-4f4f26fb8e8d) of #16163.

I suspect there is a race between stop actors and create actors.

### Error message/log

```text
2024-04-07T07:35:59.539075686Z  INFO risingwave_stream::executor::flow_control: actor starts with rate limit rate_limit=Some(1000)
thread 'rw-main' panicked at src/storage/src/hummock/event_handler/uploader.rs:1040:26:
epoch should not be empty
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:196:5
   3: core::panicking::panic_str
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:171:5
   4: core::option::expect_failed
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/option.rs:1980:5
   5: core::option::Option<T>::expect
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/option.rs:894:21
   6: risingwave_storage::hummock::event_handler::uploader::HummockUploader::update_pinned_version
             at ./src/storage/src/hummock/event_handler/uploader.rs:1037:22
   7: apply_version_update
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:714:9
   8: {async_fn#0}
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:727:21
   9: poll<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>
```

**Comment by hzxa21** [comment]
Debug with @wenym1. We think here is what happened:
1. Actors created on CN1 and CN2 on epoch1. No actors created on CN3.
2. epoch1's Inject/Collect barrier RPCs are sent to CN1 and CN2 only.
3. New actors created on CN3 on epoch2.
4. epoch2's Inject/Collect barrier RPCs are sent to CN1, CN2 and CN3
5. There is no data generated in epoch2 on CN3 so CN3 will have `syncing_tasks` with empty `epochs`.
6. epoch1 committed. MCE bumps to epoch1.
7. CN3 received version update notification and call [`update_pinned_version`](https://github.com/risingwavelabs/risingwave/blob/06451cd9acfd0756364413e68b7867260521d084/src/storage/src/hummock/event_handler/uploader.rs#L1032). CN3's `max_synced_epoch = 0` so the check is triggered. Because of 5, the assertion fails.

This is not a correctness issue. We should fix the check to handle syncing_task with empty payload.
