### ISSUE TITLE
bug(source): panic on `ALTER SOURCE` when columns added in the middle

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#16486]
### Describe the bug

Avro schema evolution allows adding fields to a record in the middle, for example:
```diff
{
  "type": "record",
  "name": "Root",
  "fields": [
+   {
+     "name": "bar",
+     "type": "int",
+     "default": 0
+   },
    {
      "name": "foo",
      "type": "string"
    }
  ]
}
```

However, `ALTER ... ADD COLUMN` via our SQL interface always add new columns to the right end. Such difference can result in schema mismatch between upstream and downstream operators when handled improperly and lead to panic.

### Error message/log

For a simple `select * from t;` the schema mismatch was undetected until very late stage - when pgwire is about to serialize (i.e. `ToText` or `ToBinary`) result columns and send to psql client. The serialization function detects a mismatch between expected `DataType` and actual `ScalarImpl`.

Ideally the mismatch shall be detected much earlier.

<details>
<summary>stack backtrace</summary>

```text
thread 'rw-main' panicked at src/common/src/types/to_text.rs:102:1:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:144:5
   3: <&str as risingwave_common::types::to_text::ToText>::write_with_type
             at ./src/common/src/types/to_text.rs:76:30
   4: <risingwave_common::types::ScalarRefImpl as risingwave_common::types::to_text::ToText>::write_with_type
             at ./src/common/src/types/to_text.rs:202:50
   5: risingwave_common::types::to_text::ToText::to_text_with_type
             at ./src/common/src/types/to_text.rs:34:9
   6: risingwave_common::types::ScalarRefImpl::text_format
             at ./src/common/src/types/mod.rs:980:9
   7: risingwave_frontend::handler::util::pg_value_format
             at ./src/frontend/src/handler/util.rs:127:20
   8: risingwave_frontend::handler::util::to_pg_rows::{{closure}}::{{closure}}
             at ./src/frontend/src/handler/util.rs:166:40
   9: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/map.rs:92:28
  10: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2462:21
  11: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/map.rs:118:9
  12: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:201:9
  13: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2524:9
  14: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:184:14
  15: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/mod.rs:2891:35
  16: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/spec_extend.rs:17:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/spec_from_iter.rs:33:9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/mod.rs:2791:9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2054:9
  21: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/result.rs:1930:51
  22: core::iter::adapters::try_process
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:170:17
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/result.rs:1930:9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2054:9
  25: itertools::Itertools::try_collect
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.12.1/src/lib.rs:2228:9
  26: risingwave_frontend::handler::util::to_pg_rows::{{closure}}
             at ./src/frontend/src/handler/util.rs:161:23
  27: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/map.rs:92:28
  28: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2462:21
  29: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/map.rs:118:9
  30: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:201:9
  31: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2524:9
  32: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:184:14
  33: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  34: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/spec_from_iter.rs:33:9
  35: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/alloc/src/vec/mod.rs:2791:9
  36: core::iter::traits::iterator::Iterator::collect
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2054:9
  37: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/result.rs:1930:51
  38: core::iter::adapters::try_process
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/adapters/mod.rs:170:17
  39: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/result.rs:1930:9
  40: core::iter::traits::iterator::Iterator::collect
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/iter/traits/iterator.rs:2054:9
  41: itertools::Itertools::try_collect
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.12.1/src/lib.rs:2228:9
  42: risingwave_frontend::handler::util::to_pg_rows
             at ./src/frontend/src/handler/util.rs:156:5
  43: <risingwave_frontend::handler::util::DataChunkToRowSetAdapter<VS> as futures_core::stream::Stream>::poll_next
             at ./src/frontend/src/handler/util.rs:102:25
  44: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  45: <risingwave_frontend::handler::PgResponseStream as futures_core::stream::Stream>::poll_next
             at ./src/frontend/src/handler/mod.rs:152:58
  46: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  47: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  48: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg_one_stmt::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:626:66
  49: pgwire::pg_protocol::PgProtocol<S,SM>::inner_process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:582:18
  50: pgwire::pg_protocol::PgProtocol<S,SM>::process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:564:14
  51: pgwire::pg_protocol::PgProtocol<S,SM>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:394:88
  52: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  53: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  54: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  55: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  56: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:251:53
  57: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:297:9
  58: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/catch_unwind.rs:36:42
  59: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:272:9
  60: std::panicking::try::do_call
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  61: ___rust_try
  62: std::panicking::try
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  63: std::panic::catch_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  64: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/catch_unwind.rs:36:9
  65: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  66: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  67: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  68: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:261:18
  69: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  70: <&mut F as core::future::future::Future>::poll
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:112:9
  71: <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/time/timeout.rs:202:33
  72: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:277:62
  73: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:294:30
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  75: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:321:19
  76: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:201:30
  77: pgwire::pg_server::handle_connection::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:298:41
  78: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/future/future.rs:124:9
  79: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  80: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  81: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  82: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:13
  83: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  84: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panic/unwind_safe.rs:272:9
  85: std::panicking::try::do_call
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:552:40
  86: ___rust_try
  87: std::panicking::try
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:516:19
  88: std::panic::catch_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panic.rs:142:14
  89: tokio::runtime::task::harness::poll_future
             at /Users/xiangjin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
```

</details>

### To Reproduce

Assuming a redpanda instance with broker on port 29092 and schema registry on port 8081:

Create the topic and first version of schema:
```
RPK_BROKERS=127.0.0.1:29092 ./rpk topic create alter-avro

echo '{"type":"record","name":"Root","fields":[{"name":"foo","type":"string"}]}' | jq '{"schema": tojson}' | curl -X POST -H 'content-type:application/json' -d @- 'http://127.0.0.1:8081/subjects/alter-avro-value/versions'
```

Then in RisingWave psql connection:
```
create source t with (properties.bootstrap.server = '127.0.0.1:29092', connector = 'kafka', topic = 'alter-avro') format plain encode avro (schema.registry = 'http://127.0.0.1:8081');
```

Next we create a new version of schema and produce a message:
```
echo '{"type":"record","name":"Root","fields":[{"name":"bar","type":"int","default":0},{"name":"foo","type":"string"}]}' | jq '{"schema": tojson}' | curl -X POST -H 'content-type:application/json' -d @- 'http://127.0.0.1:8081/subjects/alter-avro-value/versions'

echo '{"id":?}' | jq .id | python3 -c 'print("00{:08x}0406414243".format(int(input())))' | RPK_BROKERS=127.0.0.1:29092 ./rpk topic produce -f '%v{hex}\n' alter-avro
```
Note the `?` part shall be replaced by actual schema id returned by previous command. If the command above returns `{"id":26}`, the last command shall start with `echo '{"id":26}' | jq .id | python3`.

Lastly back to RisingWave psql connection:
```
alter source t format plain encode avro (schema.registry = 'http://127.0.0.1:8081'); 
select * from t;
```

To cleanup before rerunning the test again, use the following commands:
```
RPK_BROKERS=127.0.0.1:29092 ./rpk topic delete alter-avro
curl -X DELETE 'http://127.0.0.1:8081/subjects/alter-avro-value'
curl -X DELETE 'http://127.0.0.1:8081/subjects/alter-avro-value?permanent=true'
```

### Expected behavior

Not sure which of the following is preferred:

Option A:
```
dev=> select * from t;
 bar | foo 
-----+-----
   2 | ABC
(1 row)
```

Option B:
```
dev=> select * from t;
 foo | bar 
-----+-----
 ABC |   2
(1 row)
```

Option C:
```
dev=> alter source t format plain encode avro (schema.registry = 'http://127.0.0.1:8081'); 
ERROR: new columns in the middle are not supported.
```

At least it shall not panic.

**Comment by xiangjinwu** [comment]
The `BatchKafkaScan` executor is to blame:
* `schema() == [foo:Varchar, _rw_kafka_timestamp:Timestamptz, _row_id:Serial, bar:Int32]`
* `data_chunk.to_pretty()` gives:
```
+-----+-------------------------------+---+-----+
| ABC | 2024-04-25 08:22:45.779+00:00 |   | ABC |
+-----+-------------------------------+---+-----+
```

**Comment by xiangjinwu** [comment]
After fix it is better to verify protobuf as well:
```diff
message User {
+ int32 id = 4;
  string name = 7;
}
```
although in practice protobuf fields are usually added sequentially with a larger field number.

**Comment by xxchan** [comment]
Putting columns at the end of the schema is acceptable to the original user, so this is less urgent.

**Comment by BugenZhao** [comment]
> However, `ALTER ... ADD COLUMN` in SQL always add new columns to the right end.

Just to clarify, the bug described in this issue has nothing to do with our table schema change feature, right? BTW,
- MySQL supports adding column at any position through syntax `ADD COLUMN .. AFTER ..` ([ref](https://arc.net/l/quote/hqgexvvp))
- There's no blocker for us to support that as well.

**Comment by xiangjinwu** [comment]
> has nothing to do with our table schema change feature

I am not sure.
* If the underlying table schema change feature has the ability to add columns in the middle (like MySQL), we could leverage it here and achieve **Option A**.
* Without that ability, we could add the column at end and achieve **Option B**, by adjusting the column orders after decoding avro and before sending to downstream (like an addition `Project`).

**Comment by xxchan** [comment]
Note: streaming will also panic (create a new MV on the `ALTER`ed source)

```
thread 'rw-streaming' panicked at src/stream/src/executor/wrapper/schema_check.rs:48:29:
schema check failed on ExecutorInfo { schema: Schema { fields: [foo:Varchar, _rw_kafka_timestamp:Timestamptz, _row_id:Serial, bar:Int32] }, pk_indices: [2], identity: "Source 753500002727" }: column type mismatched at position 3: expected Some(Int32), found Some("Utf8")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:48:29
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1431:23
   4: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:30:9
   5: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
   6: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
   7: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
   8: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
   9: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_check.rs:31:44
  10: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  12: <S as futures_core::stream::TryStream>::try_poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:196:9
  13: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/try_stream/mod.rs:1131:9
  14: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/try_stream/try_next.rs:32:9
  15: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:391:31
  16: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:217:19
  17: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/task/task_local.rs:387:19
  18: risingwave_common::util::epoch::task_local::scope::{{closure}}
             at ./src/common/src/util/epoch.rs:244:47
  19: risingwave_stream::executor::wrapper::epoch_provide::epoch_provide::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_provide.rs:31:59
  20: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  21: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  22: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  23: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  24: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  25: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:53:69
  26: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  27: risingwave_stream::executor::wrapper::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/wrapper/update_check.rs:27:1
  28: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  29: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  30: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  31: risingwave_stream::executor::row_id_gen::RowIdGenExecutor::execute_inner::{{closure}}
             at ./src/stream/src/executor/row_id_gen.rs:83:5
  32: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-async-stream-0.2.9/src/lib.rs:506:33
  33: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9

```

**Comment by xiangjinwu** [comment]
Update:
* Even when new column is added at the end, avro still panics because the new column is still "in the middle" - before hidden `_rw_kafka_timestamp` column.
* The initial PR [#14057](https://github.com/risingwavelabs/risingwave/pull/14057) tests with protobuf. It does not panic despite also having `_rw_kafka_timestamp`.

**Comment by xxchan** [comment]
The root cause is the added column has the wrong column id.
