### ISSUE TITLE
Bug: thread 'state_store_tests::test_iter_log' panicked at src/storage/hummock_test/src/state_store_tests.rs:1619:5: assertion `left == right` failed

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#16529]
I recently started to see these bugs in the PR workflows. Looks like a regression.

```
thread 'state_store_tests::test_iter_log' panicked at src/storage/hummock_test/src/state_store_tests.rs:1619:5:
assertion `left == right` failed
  left: 9999
 right: 10000
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:342:17
   3: core::panicking::assert_failed
             at /rustc/e4c626dd9a17a23270bf8e7158e59cf2b9c04840/library/core/src/panicking.rs:297:5
   4: risingwave_hummock_test::state_store_tests::test_iter_log::{{closure}}
             at ./src/state_store_tests.rs:1619:5
```

Source: https://buildkite.com/risingwavelabs/pull-request/builds/48640#018f27b6-e81f-457c-8882-7022dd6fb022

**Comment by wenym1** [comment]
Fixed by https://github.com/risingwavelabs/risingwave/pull/16534
