### ISSUE TITLE
error in metabase: function has_any_column_privilege does not exist

### ISSUE THREAD

**Issue by DOUS3L** [risingwavelabs/risingwave#17187]
### Describe the bug

not sure if this issue categorizes as a bug, but in metabase they use `has_any_column_privilege()` for scanning a new postgresql data source but it has different parameters(data types) from the function implemented here
https://github.com/risingwavelabs/risingwave/blob/9e137fcf5784ccaf3f703196419746eb8b917308/src/frontend/src/expr/function_impl/has_privilege.rs#L53

related query from metabase repo
https://github.com/metabase/metabase/blob/7b919f8b27421f0469a566f22707f7f719025355/src/metabase/driver/postgres.clj#L963-L984

because of this error, tables are not showing up in metabase UI

### Error message/log
relevant log from metabase
```text
[4352ba0d-62ee-41fb-9bfb-03875b2d7d71] 2024-06-10T14:14:30+07:00 WARN metabase.sync.util Error in sync step Sync metadata for postgres Database 13371345 ''rw'',org.postgresql.util.PSQLException: ERROR: Failed to prepare the statement,Caused by these errors (recent errors listed first):,  
1: Failed to bind expression: pg_catalog.has_any_column_privilege(current_user, '"' || t.schemaname || '"' || '.' || '"' || t.objectname || '"', 'update'),  
2: function has_any_column_privilege(character varying, character varying, character varying) does not exist,
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725),
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412),
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371),
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502),
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419),
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194),
    at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137),
    ...
```

### To Reproduce

https://docs.risingwave.com/docs/current/metabase-integration/

### How did you deploy RisingWave?

using the helm chart

### The version of RisingWave

```
dev=> select version();
                                    version
--------------------------------------------------------------------------------
 PostgreSQL 13.14.0-RisingWave-1.8.2 (fa177a5b4ff952a50e8391ac09067f425f98f44c)
(1 row)
```

**Comment by lmatz** [comment]
implemented in https://github.com/risingwavelabs/risingwave/pull/16674
please use the latest version 1.9.1

**Comment by DOUS3L** [comment]
ah my bad, should have checked the latest version first
thank you for the fast reply @lmatz

**Comment by lmatz** [comment]
> ah my bad, should have checked the latest version first
> 
> thank you for the fast reply @lmatz 

No worries, we deliver new features fast, it is not easy to track all the updates, thanks for trying RW!
