### ISSUE TITLE
Unable to use google cloud sql postgres as source

### ISSUE THREAD

**Issue by bestmike007** [risingwavelabs/risingwave#17729]
### Describe the bug

I was trying to add a google cloud sql postgres instance as a source. I tried to follow the doc (https://docs.risingwave.com/docs/current/ingest-from-postgres-cdc/#set-up-postgresql), I was able to create table from the source, however, according to the logs, RisingWave failed to create subscription hence the table was not updating.

Note: This was originally discussed here: https://risingwave-community.slack.com/archives/C03BW71523T/p1720604180563529

### Error message/log

```text
2024-07-18T03:37:04.349019516Z ERROR ThreadId(560) risingwave_connector_node: Producer failure: org.postgresql.util.PSQLException: ERROR: publication "rw_publication" does not exist
  Where: slot "rw_test", output plugin "pgoutput", in the change callback, associated LSN 1BF/7106A428
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1264)
	at org.postgresql.core.v3.QueryExecutorImpl.readFromCopy(QueryExecutorImpl.java:1164)
	at org.postgresql.core.v3.CopyDualImpl.readFromCopy(CopyDualImpl.java:44)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.receiveNextData(V3PGReplicationStream.java:160)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.readInternal(V3PGReplicationStream.java:125)
	at org.postgresql.core.v3.replication.V3PGReplicationStream.readPending(V3PGReplicationStream.java:82)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection$1.readPending(PostgresReplicationConnection.java:617)
	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.processMessages(PostgresStreamingChangeEventSource.java:221)
	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:183)
	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.execute(PostgresStreamingChangeEventSource.java:42)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:272)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:197)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### To Reproduce

1. Following the doc to enable logical replication: https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication, specifically: set flag `cloudsql.logical_decoding` to `on`, enable replication role for the table owner: `ALTER USER the_table_creator WITH REPLICATION;`
2. Create the source
3. Create a table from the source

### How did you deploy RisingWave?

```docker-compose.yml
services:
  risingwave:
    image: risingwavelabs/risingwave:v1.9.2
    command: "standalone --meta-opts=\" \
      --listen-addr 0.0.0.0:5690 \
      --advertise-addr 0.0.0.0:5690 \
      --dashboard-host 0.0.0.0:5691 \
      --prometheus-host 0.0.0.0:1250 \
      --prometheus-endpoint http://127.0.0.1:9500 \
      --connector-rpc-endpoint 0.0.0.0:50051 \
      --backend sql \
      --sql-endpoint postgresql://postgres:${POSTGRES_PASSWORD}@127.0.0.1:${POSTGRES_PORT}/rw \
      --state-store hummock+fs:///risingwave-data \
      --data-directory hummock_001 \
      --config-path /risingwave.toml\" \
      --compute-opts=\" \
      --config-path /risingwave.toml \
      --listen-addr 0.0.0.0:5688 \
      --prometheus-listener-addr 0.0.0.0:1250 \
      --advertise-addr 0.0.0.0:5688 \
      --async-stack-trace verbose \
      --connector-rpc-endpoint 0.0.0.0:50051 \
      --role both \
      --meta-address http://0.0.0.0:5690\" \
      --frontend-opts=\" \
      --config-path /risingwave.toml \
      --listen-addr 0.0.0.0:4566 \
      --advertise-addr 0.0.0.0:4566 \
      --prometheus-listener-addr 0.0.0.0:1250 \
      --health-check-listener-addr 0.0.0.0:6786 \
      --meta-addr http://0.0.0.0:5690\" \
      --compactor-opts=\" \
      --listen-addr 0.0.0.0:6660 \
      --prometheus-listener-addr 0.0.0.0:1250 \
      --advertise-addr 0.0.0.0:6660 \
      --meta-address http://0.0.0.0:5690\""
    network_mode: host
    volumes:
      - "$PWD/risingwave/risingwave.toml:/risingwave.toml"
      - "$DATA_DIR/risingwave:/risingwave-data"
    environment:
      RUST_BACKTRACE: "full"
      # If ENABLE_TELEMETRY is not set, telemetry will start by default
      ENABLE_TELEMETRY: ${ENABLE_TELEMETRY:-true}
    container_name: risingwave-standalone
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/6660; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5688; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/4566; exit $$?;'
        - bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/5690; exit $$?;'
      interval: 1s
      timeout: 5s
    restart: always
```

### The version of RisingWave

 PostgreSQL 13.14.0-RisingWave-1.9.2 (fbf1343627e9bc018930efb7f72f7fd19c15d2d0)

### Additional context

After creating the table, the publication `rw_publication` is properly created on the postgres database: `select * from pg_publication;`.

**Comment by StrikeW** [comment]
Hi, I tested with v1.9.2 locally, and there is no problem. The configuration of gcloud sql can refer to this [link](https://aiven.io/docs/products/postgresql/howto/logical-replication-gcp-cloudsql).
<img width="800" alt="image" src="https://github.com/user-attachments/assets/c1bb1487-a9d6-4ad8-bfdb-be1490a15c41">

**Comment by bestmike007** [comment]
Thanks @StrikeW 

The permission set up is exactly the same as @StrikeW suggested in the doc, but that did not solve the problem.

The root cause is somehow we created the publication after the replication slot, so we deleted all replication slots and publications and then tried again, and it works.

Reference:

![image](https://github.com/user-attachments/assets/3bae1eaa-64dc-4d3c-a7df-674e26c9a276)
https://elephanttamer.net/?p=50

**Comment by StrikeW** [comment]
Good to know your problem has been solved. With the shared cdc source, users usually doesn't need to manage publication and replication slot by themselves.
