### ISSUE TITLE
thread 'rw-main' panicked at src/storage/src/hummock/event_handler/uploader/mod.rs:968:17: assertion `left == right` failed

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#17734]
### Describe the bug

Panic while running a high join amplification case.

### Error message/log

```text
2024-07-18T12:55:08.363683+08:00 DEBUG risingwave_storage::hummock::event_handler::hummock_event_handler: awaiting for epoch to be synced new_sync_epoch=6818577821204480 table_ids={TableId { table_id: 1 }, TableId { table_id: 5 }, TableId { table_id: 4 }, TableId { table_id: 3 }, TableId { table_id: 9 }, TableId { table_id: 8 }, TableId { table_id: 7 }, TableId { table_id: 2 }, TableId { table_id: 6 }}
2024-07-18T12:55:08.363691+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: start sync epoch epoch=6818577821204480 table_ids={TableId { table_id: 1 }, TableId { table_id: 5 }, TableId { table_id: 4 }, TableId { table_id: 3 }, TableId { table_id: 9 }, TableId { table_id: 8 }, TableId { table_id: 7 }, TableId { table_id: 2 }, TableId { table_id: 6 }}
2024-07-18T12:55:08.36375+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: start upload task: UploadTaskInfo { task_size: 48136072, epochs: [6818577821204480], imm_ids: {24: [1466, 1455], 23: [1462, 1458, 1449], 47: [1460], 19: [1465, 1454, 1450], 17: [1464, 1456], 20: [1463, 1452], 22: [1461, 1457], 18: [1468, 1459, 1451], 21: [1467, 1453]} }
thread 'rw-main' panicked at src/storage/src/hummock/event_handler/uploader/mod.rs:968:17:
assertion `left == right` failed
  left: {TableId { table_id: 3 }}
 right: {TableId { table_id: 1 }, TableId { table_id: 5 }, TableId { table_id: 4 }, TableId { table_id: 3 }, TableId { table_id: 9 }, TableId { table_id: 8 }, TableId { table_id: 7 }, TableId { table_id: 2 }, TableId { table_id: 6 }}

   0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: assert_failed<std::collections::hash::set::HashSet<risingwave_common::catalog::TableId, std::hash::random::RandomState>, std::collections::hash::set::HashSet<risingwave_common::catalog::TableId, std::hash::random::RandomState>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:298:5
   4: {closure#0}
             at ./src/storage/src/hummock/event_handler/uploader/mod.rs:968:17
   5: call_once<(&risingwave_storage::hummock::event_handler::uploader::UploadingTaskId), risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/ops/function.rs:305:13
   6: map<&risingwave_storage::hummock::event_handler::uploader::UploadingTaskId, alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, &mut risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/option.rs:1073:29
   7: next<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/iter/adapters/map.rs:108:26
   8: from_iter<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
   9: from_iter<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/vec/spec_from_iter.rs:33:9
  10: from_iter<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/vec/mod.rs:2894:9
  11: spec_from_iter<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/collections/vec_deque/spec_from_iter.rs:17:9
  12: from_iter<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/alloc/src/collections/vec_deque/mod.rs:2787:9
  13: collect<core::iter::adapters::map::Map<core::iter::adapters::rev::Rev<alloc::collections::btree::set::Iter<risingwave_storage::hummock::event_handler::uploader::UploadingTaskId>>, risingwave_storage::hummock::event_handler::uploader::{impl#12}::sync::{closure_env#0}>, alloc::collections::vec_deque::VecDeque<alloc::sync::Arc<risingwave_storage::hummock::store::version::StagingSstableInfo, alloc::alloc::Global>, alloc::alloc::Global>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/iter/traits/iterator.rs:2003:9
  14: sync
             at ./src/storage/src/hummock/event_handler/uploader/mod.rs:971:14
  15: start_sync_epoch
             at ./src/storage/src/hummock/event_handler/uploader/mod.rs:1213:9
  16: handle_sync_epoch
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:476:9
  17: handle_hummock_event
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:732:17
  18: {async_fn#0}
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:698:29
  19: poll<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  20: {closure#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  21: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle, alloc::alloc::Global>>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  22: poll<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:30
  23: {closure#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  24: call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panic/unwind_safe.rs:272:9
  25: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  26: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
  27: catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>>, core::task::poll::Poll<()>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panic.rs:146:14
  28: poll_future<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:473:18
  29: poll_inner<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:208:27
  30: poll<tracing::instrument::Instrumented<risingwave_storage::hummock::event_handler::hummock_event_handler::{impl#5}::start_hummock_event_handler_worker::{async_fn_env#0}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:153:15
  31: poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/raw.rs:201:18
  32: run<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle, alloc::alloc::Global>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/mod.rs:427:9
  33: {closure#0}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:639:22
  34: with_budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  35: budget<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core, alloc::alloc::Global>, ()>, tokio::runtime::scheduler::multi_thread::worker::{impl#1}::run_task::{closure_env#0}>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  36: run_task
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  37: run
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  38: {closure#0}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  39: set<tokio::runtime::scheduler::Context, tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}, ()>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  40: {closure#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  41: try_with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>, ()>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/local.rs:284:16
  42: with<tokio::runtime::context::Context, tokio::runtime::context::set_scheduler::{closure_env#0}<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>, ()>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/thread/local.rs:260:9
  43: set_scheduler<(), tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure_env#0}>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:17
  44: {closure#0}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  45: enter_runtime<tokio::runtime::scheduler::multi_thread::worker::run::{closure_env#0}, ()>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  46: run
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  47: {closure#0}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  48: poll<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}, ()>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/blocking/task.rs:42:21
  49: poll<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  50: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:328:17
  51: with_mut<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>>, core::task::poll::Poll<()>, tokio::runtime::task::core::{impl#6}::poll::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/loom/std/unsafe_cell.rs:16:9
  52: poll<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/core.rs:317:30
  53: {closure#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/task/harness.rs:485:19
  54: call_once<core::task::poll::Poll<()>, tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panic/unwind_safe.rs:272:9
  55: do_call<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>, core::task::poll::Poll<()>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:552:40
  56: try<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::{closure_env#0}<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<tokio::runtime::scheduler::multi_thread::worker::{impl#0}::launch::{closure_env#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>>
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:516:19
```

### To Reproduce

- This runs in `ci-release` mode, not `release` mode. See: https://github.com/risingwavelabs/risingwave/issues/17725#issuecomment-2235342412

- My machine has 10 vcpu

- Commit: 30fd4d8ab8995142eed9b185d769791e20e2bdb1 

```yml
  ci-3cn-1fe-par8:
    config-path: src/config/ci.toml
    steps:
      - use: minio
      - use: etcd
        unsafe-no-fsync: true
      - use: meta-node
        meta-backend: etcd
      - use: compute-node
        parallelism: 8
        port: 5687
        exporter-port: 1222
        enable-tiered-cache: true
      - use: compute-node
        parallelism: 8
        port: 5688
        exporter-port: 1223
        enable-tiered-cache: true
      - use: compute-node
        parallelism: 8
        port: 5689
        exporter-port: 1224
        enable-tiered-cache: true
      - use: frontend
      - use: compactor
      - use: prometheus
      - use: grafana

```

```sql
create table if not exists fact(id int, v1 varchar);
create table if not exists dim(id int, v1 varchar);
create materialized view m1 as select fact.id, fact.v1 as fact_v1, dim.v1 as dim_v1 from
  fact join dim on fact.id = dim.id
  union all
  select fact.id, fact.v1, dim.v1 from
  fact join dim on fact.id = dim.id;

insert into fact select 1, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 2, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 3, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 4, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 5, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 6, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 7, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 8, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 9, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 10, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 11, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 12, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 13, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
insert into fact select 14, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 1000000);
flush;
insert into dim select generate_series as id, 'k2jbkajbddwa2j3333333333333333333333333akdjbn2kbeui2be22' as varchar from generate_series(1, 15);
flush;
```

### Expected behavior

No panic

**Comment by Li0k** [comment]
@wenym1 PTAL

**Comment by wenym1** [comment]
What SQL did you run? Did you run any ddl or scale when the panic happened?

**Comment by BugenZhao** [comment]
> What SQL did you run? Did you run any ddl or scale when the panic happened?

It's the query in the issue body. No other actions required. Can be reproduced steadily on the latest commit.

**Comment by wenym1** [comment]
I figure out the root cause. The assertion is too strict. Will submit a PR to fix it.
