### ISSUE TITLE
bug: secret manager panic at { code: 17, kind: AlreadyExists, message: "File exists" }

### ISSUE THREAD

**Issue by wenym1** [risingwavelabs/risingwave#17740]
### Describe the bug

CI panic https://buildkite.com/risingwavelabs/main-cron/builds/3001#0190c170-0853-4319-8c86-caf972cffd9a

### Error message/log

```text
thread '<unnamed>' panicked at src/common/secret/src/secret_manager.rs:90:56:
called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/4a0cc881dcc4d800f10672747f61a94377ff6662/library/core/src/result.rs:1654:5
```

**Comment by wenym1** [comment]
cc @yuhao-su

**Comment by yuhao-su** [comment]
Is this the correct link? I didn't see such the panic in the log
