### ISSUE TITLE
Bug(ctl): "start a runtime from within a runtime."

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#17974]
```
2024-08-08T17:44:15.27620676+08:00  INFO risingwave_rt::panic_hook: coredump on panic is likely to be enabled limit=18446744073709551615
2024-08-08T17:44:15.27673965+08:00  INFO risingwave_ctl::common::meta_service: using meta addr from `RW_META_ADDR`: consul:[risingwave.rw](http://risingwave.rw/)-cn-test-cluster1.meta-node
thread 'main' panicked at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/scheduler/multi_thread/[mod.rs:86](http://mod.rs:86/):9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
stack backtrace:
   0:     0x55b49b5caf69 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h78bb173879226e7e
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/../../backtrace/src/backtrace/[libunwind.rs:105](http://libunwind.rs:105/):5
   1:     0x55b4908378eb - core::fmt::write::h84af2867d7d195ca
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/core/src/fmt/[rt.rs:142](http://rt.rs:142/):9
   2:     0x55b49b5c3edf - std::io::Write::write_fmt::h50f2bab801a3fbad
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/io/[mod.rs:1843](http://mod.rs:1843/):15
   3:     0x55b49b5cad3e - std::sys_common::backtrace::print::h5b9583e9ade67c9b
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/sys_common/[backtrace.rs:47](http://backtrace.rs:47/):5
   4:     0x55b49b5cc149 - std::panicking::default_hook::{{closure}}::hfcbfda6a0b8af12c
   5:     0x55b49b5cbe5d - std::panicking::default_hook::he4d5c9ef4fcd6b21
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/[panicking.rs:291](http://panicking.rs:291/):9
   6:     0x55b498e6355b - std::panicking::update_hook::{{closure}}::he3cffa29d96dd83c
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9
   7:     0x55b49b5cc794 - std::panicking::rust_panic_with_hook::h75c9fa15c80e870b
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/alloc/src/[boxed.rs:2032](http://boxed.rs:2032/):9
   8:     0x55b49b5cc50d - std::panicking::begin_panic_handler::{{closure}}::h0af6b83a00b058d2
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/[panicking.rs:649](http://panicking.rs:649/):13
   9:     0x55b49b5cb429 - std::sys_common::backtrace::__rust_end_short_backtrace::h5d136cf2ede03798
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/sys_common/[backtrace.rs:171](http://backtrace.rs:171/):18
  10:     0x55b49b5cc287 - rust_begin_unwind
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/[panicking.rs:645](http://panicking.rs:645/):5
  11:     0x55b490833c46 - core::panicking::panic_fmt::h6300da8ef47aad32
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/core/src/[panicking.rs:72](http://panicking.rs:72/):14
  12:     0x55b493464b6b - tokio::runtime::context::runtime::enter_runtime::h1ad34b24d7ce0f1d
                               at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/context/[runtime.rs:68](http://runtime.rs:68/):5
  13:     0x55b493447fe1 - tokio::runtime::runtime::Runtime::block_on::h1032b2166b6e00f1
                               at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/scheduler/multi_thread/[mod.rs:86](http://mod.rs:86/):9
  14:     0x55b4934699d4 - <risingwave_common::util::meta_addr::MetaAddressStrategy as core::str::traits::FromStr>::from_str::h3d929761a22708a4
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/common/src/util/meta_addr.rs:93:32](http://code.byted.org/inf/RisingWave/src/common/src/util/meta_addr.rs:93:32)
  15:     0x55b492aad09a - risingwave_ctl::common::context::CtlContext::meta_client::{{closure}}::h81c1c521f7df09d9
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/core/src/str/[mod.rs:2420](http://mod.rs:2420/):9
  16:     0x55b492ab975a - risingwave_ctl::cmd_impl::meta::reschedule::unregister_workers::{{closure}}::hdcdb1bde64c27f78
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/ctl/src/cmd_impl/meta/reschedule.rs:245:45](http://code.byted.org/inf/RisingWave/src/ctl/src/cmd_impl/meta/reschedule.rs:245:45)
  17:     0x55b492aa651b - risingwave_ctl::start_impl::{{closure}}::h6e3cd3729c2f981d
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/ctl/src/lib.rs:832:14](http://code.byted.org/inf/RisingWave/src/ctl/src/lib.rs:832:14)
  18:     0x55b492c4d793 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h75ad7eefaf44fff2
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/ctl/src/lib.rs:612:45](http://code.byted.org/inf/RisingWave/src/ctl/src/lib.rs:612:45)
  19:     0x55b492e2f217 - tokio::runtime::park::CachedParkThread::block_on::h0e4b5755d3f8b2ce
                               at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/[park.rs:281](http://park.rs:281/):63
  20:     0x55b492e30017 - tokio::runtime::context::runtime::enter_runtime::h473345d8dcdeea23
                               at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/context/[blocking.rs:66](http://blocking.rs:66/):9
  21:     0x55b492ef5a31 - tokio::runtime::runtime::Runtime::block_on::h303f4f63e9c48e5f
                               at /root/.cargo/registry/src/[rsproxy.cn](http://rsproxy.cn/)-0dccff568467c15b/tokio-1.37.0/src/runtime/scheduler/multi_thread/[mod.rs:86](http://mod.rs:86/):9
  22:     0x55b493011ba7 - risingwave_rt::main_okk::h7795e5b157298930
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/utils/runtime/src/lib.rs:76:5](http://code.byted.org/inf/RisingWave/src/utils/runtime/src/lib.rs:76:5)
  23:     0x55b49204157f - risingwave::main::ha517ab8929b603b4
                               at /opt/tiger/compile_path/src/[code.byted.org/inf/RisingWave/src/cmd/src/lib.rs:62:5](http://code.byted.org/inf/RisingWave/src/cmd/src/lib.rs:62:5)
  24:     0x55b492046333 - std::sys_common::backtrace::__rust_begin_short_backtrace::h639b7cba948e29fe
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/core/src/ops/[function.rs:250](http://function.rs:250/):5
  25:     0x55b4920483a9 - std::rt::lang_start::{{closure}}::h79a2f4841bcbbd78
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/std/src/[rt.rs:159](http://rt.rs:159/):18
  26:     0x55b49b5b9124 - std::rt::lang_start_internal::hfee626c788d7b722
                               at /rustc/ab5bda1aa70f707014e2e691e43bc37a8819252a/library/core/src/ops/[function.rs:284](http://function.rs:284/):13
  27:     0x55b492041cbc - main
  28:     0x7f9cd7ef71ca - <unknown>
  29:     0x7f9cd7ef728b - __libc_start_main
  30:     0x55b48f85602a - _start
  31:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by st1page** [comment]
```
SELECT VERSION();
PostgreSQL 13.14.0-RisingWave-1.9.0-alpha (unknown)
```

**Comment by BugenZhao** [comment]
Interesting. However I can't find how `<risingwave_common::util::meta_addr::MetaAddressStrategy as core::str::traits::FromStr>::from_str::h3d929761a22708a4` lead to `tokio::runtime::runtime::Runtime::block_on::h1032b2166b6e00f1`.
