### ISSUE TITLE
bug(postgres-sink): `delete` doesn't work for timestamp

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#18179]
### Describe the bug

When the PK of PG Sink include a timestamp column, the delete will fail

### Error message/log

```text
2024-08-22T14:49:35.676076+08:00 ERROR risingwave_connector_node: sink writer error: : io.grpc.StatusRuntimeException: INTERNAL: Error when exec 22007, message Bad value for type timestamp/date/time: 2024-08-22T06:48:50.641Z
	at io.grpc.Status.asRuntimeException(Status.java:525)
	at com.risingwave.connector.JDBCSink$JdbcStatements.prepareDelete(JDBCSink.java:298)
	at com.risingwave.connector.JDBCSink.write(JDBCSink.java:144)
	at com.risingwave.connector.SinkWriterStreamObserver.onNext(SinkWriterStreamObserver.java:132)
	at com.risingwave.connector.JniSinkWriterHandler.runJniSinkWriterThread(JniSinkWriterHandler.java:37)
 thread="Thread-754" class="com.risingwave.connector.SinkWriterStreamObserver"
2024-08-22T14:49:35.677502+08:00 ERROR risingwave_connector_node: JniSinkWriterHandler onError: : io.grpc.StatusRuntimeException: INTERNAL: Error when exec 22007, message Bad value for type timestamp/date/time: 2024-08-22T06:48:50.641Z
	at io.grpc.Status.asRuntimeException(Status.java:525)
	at com.risingwave.connector.JDBCSink$JdbcStatements.prepareDelete(JDBCSink.java:298)
	at com.risingwave.connector.JDBCSink.write(JDBCSink.java:144)
	at com.risingwave.connector.SinkWriterStreamObserver.onNext(SinkWriterStreamObserver.java:132)
	at com.risingwave.connector.JniSinkWriterHandler.runJniSinkWriterThread(JniSinkWriterHandler.java:37)
 thread="Thread-754" class="com.risingwave.connector.JniSinkWriterResponseObserver"
2024-08-22T14:49:35.94815+08:00 ERROR risingwave_connector_node: sink writer finishes with error: : java.lang.RuntimeException: fail to sendSinkWriterResponseToChannel
	at com.risingwave.connector.JniSinkWriterHandler.runJniSinkWriterThread(JniSinkWriterHandler.java:40)
 thread="Thread-754" class="com.risingwave.connector.SinkWriterStreamObserver"
```

### To Reproduce

On Postgres:

```
CREATE TABLE "request_summaries_15m" (
    "executedAt" TIMESTAMP WITH TIME ZONE,
    "userId" INT,
    "service_type" VARCHAR,
    "c1" FLOAT,
     primary key ("executedAt", "userId", "service_type")
);
```

On RisingWave:

```
CREATE TABLE request_summaries_15m (
    "executedAt" TIMESTAMP WITH TIME ZONE,
    "userId" INT,
    "service_type" VARCHAR,
    "c1" FLOAT,
     primary key ("executedAt", "userId", "service_type")
);


CREATE SINK s FROM request_summaries_15m WITH (
    connector = 'jdbc',
    jdbc.url = 'jdbc:postgresql://127.0.0.1:5432/test?user=eric&password=',
    table.name = 'request_summaries_15m',
    type = 'upsert',
    primary_key = 'executedAt,userId,service_type'
);

```

**Comment by fuyufjh** [comment]
The row passed to JDBC sink is a `LocalDateTime`, which corresponds to `timestamp with time zone`

<img width="648" alt="image" src="https://github.com/user-attachments/assets/1b532fa0-fe83-4730-8b75-9717974b6139">

https://github.com/risingwavelabs/risingwave/blob/f6892e98e7c32e323263b2886817f0a0d34c61f4/java/java-binding/src/main/java/com/risingwave/java/binding/BaseRow.java#L56-L62

However, the type passed to JDBC sink is 93 = `TIMESTAMP` (without time zone)

<img width="524" alt="image" src="https://github.com/user-attachments/assets/0f9563af-61bb-4eac-8be9-f9c01d397b27">

<img width="667" alt="image" src="https://github.com/user-attachments/assets/f1879d1c-17e2-417c-b3de-af708bf2fe48">

**Comment by StrikeW** [comment]
It is a known issue of pgjdbc, we need to work around it by our own. https://github.com/pgjdbc/pgjdbc/issues/1766
