### ISSUE TITLE
File sink can not work after enable sink_decouple

### ISSUE THREAD

**Issue by wcy-fdu** [risingwavelabs/risingwave#18502]
### Describe the bug

If we do not explicitly set set `sink_decouple = false;`, the file sink will not work properly.

### Error message/log

```text
thread 'rw-streaming' panicked at src/storage/src/monitor/traced_store.rs:393:14:
cannot access a task-local storage value without setting it first
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/panicking.rs:74:14
   2: tokio::task::task_local::LocalKey<T>::with
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/task/task_local.rs:236:23
   3: tokio::task::task_local::LocalKey<T>::get
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/task/task_local.rs:276:9
2024-09-12T12:10:20.992886+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: start epoch epoch=7135495519731712 table_ids={TableId { table_id: 3 }, TableId { table_id: 4 }, TableId { table_id: 1 }}
2024-09-12T12:10:20.992932+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: table new epoch table_id=TableId { table_id: 3 } epoch=7135495519731712
2024-09-12T12:10:20.992959+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: table new epoch table_id=TableId { table_id: 4 } epoch=7135495519731712
2024-09-12T12:10:20.992977+08:00 DEBUG risingwave_storage::hummock::event_handler::uploader: table new epoch table_id=TableId { table_id: 1 } epoch=7135495519731712
   4: risingwave_storage::monitor::traced_store::get_concurrent_id
             at ./src/storage/src/monitor/traced_store.rs:393:5
   5: risingwave_storage::monitor::traced_store::TracedStateStore<S>::new_local
             at ./src/storage/src/monitor/traced_store.rs:59:18
   6: <risingwave_storage::monitor::traced_store::TracedStateStore<S> as risingwave_storage::store::StateStore>::new_local::{{closure}}
             at ./src/storage/src/monitor/traced_store.rs:269:9
   7: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.2.1/src/future.rs:119:15
   8: <risingwave_storage::monitor::monitored_store::MonitoredStateStore<S> as risingwave_storage::store::StateStore>::new_local::{{closure}}
             at ./src/storage/src/monitor/monitored_store.rs:339:18
   9: <risingwave_stream::common::log_store_impl::kv_log_store::KvLogStoreFactory<S> as risingwave_connector::sink::log_store::LogStoreFactory>::build::{{closure}}
             at ./src/stream/src/common/log_store_impl/kv_log_store/mod.rs:409:14
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  11: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  12: <futures_util::stream::once::Once<Fut> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/once.rs:46:33
  13: <futures_util::future::future::IntoStream<F> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:102:13
  14: <futures_util::stream::stream::flatten::Flatten<St,<St as futures_core::stream::Stream>::Item> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/flatten.rs:55:44
  15: <futures_util::stream::stream::Flatten<St> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:102:13
  16: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  17: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:120:9
  18: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/mod.rs:1638:9
  19: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/next.rs:32:9
  20: <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll
             at /Users/wangcongyi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/await-tree-0.2.1/src/future.rs:119:15
```
```


### To Reproduce

First, start risingwave with minio as storage backend. `./risedev d full`
```SQL
CREATE TABLE t (v1 int, v2 int);
```
```SQL
create sink s as select v1, v2
from t
with (
    connector='s3',
    s3.path = 'test/',
    s3.region_name = 'custom',
    s3.bucket_name = 'hummock001',
    s3.credentials.access = 'hummockadmin',
    s3.credentials.secret = 'hummockadmin',
    s3.endpoint_url = 'http://hummock001.127.0.0.1:9301',
    type = 'append-only',
)FORMAT PLAIN ENCODE PARQUET(force_append_only=true);
```

**Comment by wcy-fdu** [comment]
Any update? cc @xxhZs
