### ISSUE TITLE
S3 compatible endpoints do not support the ip:port format

### ISSUE THREAD

**Issue by cnmac** [risingwavelabs/risingwave#18598]
### Describe the bug

1. Helm chart version: 0.2.0
2. Using image: docker.risingwave.com/risingwavelabs/risingwave:v2.0.0
3. s3-compatible configuration：
```
stateStore:
  dataDirectory: "prefix/data"
  s3:
    enabled: true
    endpoint: http://192.168.2.71:8878
    region: us-east-1
    bucket: risingwave
    authentication:
      useServiceAccount: false
      accessKey: xxxxxxxxxxxxxxxxxxx
      secretAccessKey: xxx
```
4. The risingwave-meta-0 pod has the following error：
```
2024-09-19T02:41:31.354160215Z  INFO risingwave_object_store::object: Using OpenDAL to access s3, bucket is risingwave
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/http_util/client.rs:92:58:
input request url must be valid: InvalidIpv4Address
stack backtrace:
   0:     0x55e9124cb609 - std::backtrace_rs::backtrace::libunwind::trace::hb2aae96f7a63ad27
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x55e9124cb609 - std::backtrace_rs::backtrace::trace_unsynchronized::h21f79cd140dff600
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e9124cb609 - std::sys_common::backtrace::_print_fmt::hc8ebdc1b64ae52ee
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55e9124cb609 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7ba491a968dfae1d
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e905d1330b - core::fmt::rt::Argument::fmt::he322040f856802e1
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/rt.rs:165:63
   5:     0x55e905d1330b - core::fmt::write::hb4f7da2a314ef133
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/mod.rs:1168:21
   6:     0x55e9124c428f - std::io::Write::write_fmt::h9e79d11af9b4686b
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/io/mod.rs:1835:15
   7:     0x55e9124cb3de - std::sys_common::backtrace::_print::h9276d72631ea2ebd
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e9124cb3de - std::sys_common::backtrace::print::h301edb80f46c58f8
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e9124cc749 - std::panicking::default_hook::{{closure}}::h08c68fc043d12d43
  10:     0x55e9124cc4f5 - std::panicking::default_hook::hdf65558cafad5039
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:298:9
  11:     0x55e90f936b8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb1bd1334e19fb4d6
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2077:9
  12:     0x55e90f936b8b - risingwave_rt::panic_hook::set_panic_hook::{{closure}}::hb127a6454381f93e
                               at /risingwave/src/utils/runtime/src/panic_hook.rs:25:9
  13:     0x55e90f936b8b - std::panicking::update_hook::{{closure}}::hb643787da43b1cda
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:233:47
  14:     0x55e9124ccd8b - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h69f90a497fd344b0
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/alloc/src/boxed.rs:2077:9
  15:     0x55e9124ccd8b - std::panicking::rust_panic_with_hook::h9576f09a7a058c94
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:799:13
  16:     0x55e9124ccb34 - std::panicking::begin_panic_handler::{{closure}}::hd8f56243f630c203
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:664:13
  17:     0x55e9124cbac9 - std::sys_common::backtrace::__rust_end_short_backtrace::h5bed6f770a09acf8
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:171:18
  18:     0x55e9124cc877 - rust_begin_unwind
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:652:5
  19:     0x55e905d0f863 - core::panicking::panic_fmt::h088f9f84f0369284
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/panicking.rs:72:14
  20:     0x55e905d0fd56 - core::result::unwrap_failed::he3619d4dec44758c
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/result.rs:1679:5
  21:     0x55e90f48afc8 - core::result::Result<T,E>::expect::h07f419005f7b8456
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/result.rs:1059:23
  22:     0x55e90f48afc8 - opendal::raw::http_util::client::HttpClient::fetch::{{closure}}::h2bd3882b12ef2823
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/http_util/client.rs:92:17
  23:     0x55e90f489669 - opendal::raw::http_util::client::HttpClient::send::{{closure}}::hfd79aca8f4b0283b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/http_util/client.rs:74:49
  24:     0x55e90f441537 - opendal::services::s3::core::S3Core::send::{{closure}}::h7c13ee920a0a7300
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/services/s3/core.rs:190:31
  25:     0x55e90f441537 - opendal::services::s3::core::S3Core::s3_head_object::{{closure}}::ha18d97134a726bda
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/services/s3/core.rs:463:24
  26:     0x55e90f441537 - <opendal::services::s3::backend::S3Backend as opendal::raw::accessor::Access>::stat::{{closure}}::h428bc765c63013ef
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/services/s3/backend.rs:1091:57
  27:     0x55e90f441537 - <F as futures_core::future::TryFuture>::try_poll::h817c0e675ec06cb4
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/future.rs:82:9
  28:     0x55e90f441537 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::h6d75c43fe05003ed
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/try_future/into_future.rs:34:9
  29:     0x55e90f441537 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h54e014eab726e4d9
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/future/map.rs:55:37
  30:     0x55e90f2be9d0 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::hcac99db79e0854ef
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  31:     0x55e90f2be9d0 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::ha026ac5309f15834
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/lib.rs:91:13
  32:     0x55e90f2be9d0 - <opendal::layers::error_context::ErrorContextAccessor<A> as opendal::raw::layer::LayeredAccess>::stat::{{closure}}::h5f28517985d6cc06
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/layers/error_context.rs:166:14
  33:     0x55e90f2be9d0 - opendal::raw::layer::<impl opendal::raw::accessor::Access for L>::stat::{{closure}}::hfea761302efa2620
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/layer.rs:274:39
  34:     0x55e90f2be9d0 - <alloc::sync::Arc<T> as opendal::raw::accessor::Access>::stat::{{closure}}::h7e1b9e6ae94bf426
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/accessor.rs:733:53
  35:     0x55e90f26a1ec - opendal::layers::complete::CompleteAccessor<A>::complete_stat::{{closure}}::h1d2823a03ec031fe
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/layers/complete.rs:216:37
  36:     0x55e90f26a1ec - <opendal::layers::complete::CompleteAccessor<A> as opendal::raw::layer::LayeredAccess>::stat::{{closure}}::h511faac5e94580c6
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/layers/complete.rs:479:40
  37:     0x55e90f3056c1 - opendal::raw::layer::<impl opendal::raw::accessor::Access for L>::stat::{{closure}}::hbb0e184163ed64a9
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/layer.rs:274:39
  38:     0x55e90f3056c1 - <opendal::layers::logging::LoggingAccessor<A> as opendal::raw::layer::LayeredAccess>::stat::{{closure}}::h4c0626387e54d319
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/layers/logging.rs:454:14
  39:     0x55e90f3056c1 - opendal::raw::layer::<impl opendal::raw::accessor::Access for L>::stat::{{closure}}::hd3675b14271aca26
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/layer.rs:274:39
  40:     0x55e90f3056c1 - opendal::raw::layer::<impl opendal::raw::accessor::Access for L>::stat::{{closure}}::hed420081afd49893
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/layer.rs:274:39
  41:     0x55e90dd90d09 - <core::pin::Pin<P> as core::future::future::Future>::poll::h4417b51ea5005492
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/future/future.rs:123:9
  42:     0x55e90dd90d09 - <dyn opendal::raw::accessor::AccessDyn as opendal::raw::accessor::Access>::stat::{{closure}}::hcb8a7f650e368077
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/accessor.rs:619:35
  43:     0x55e90dd90d09 - <alloc::sync::Arc<T> as opendal::raw::accessor::Access>::stat::{{closure}}::h0050c2601ea3e930
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/raw/accessor.rs:733:53
  44:     0x55e90dd90d09 - opendal::types::read::reader::Reader::parse_range::{{closure}}::h653c634117cdb7be
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/types/read/reader.rs:137:26
  45:     0x55e90dd90d09 - opendal::types::read::reader::Reader::into_stream::{{closure}}::hc4973d8692f5363c
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/types/read/reader.rs:243:45
  46:     0x55e90dd90d09 - opendal::types::read::reader::Reader::read::{{closure}}::he1d9cbb93adc5d88
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/types/read/reader.rs:154:60
  47:     0x55e90dd90d09 - opendal::types::operator::operator::Operator::read_with::{{closure}}::{{closure}}::h89c9b0a3aa4434af
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/types/operator/operator.rs:575:52
  48:     0x55e90dd1b31d - opendal::types::operator::operator::Operator::read::{{closure}}::h61ac42a26d0503cb
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.47.2/src/types/operator/operator.rs:427:30
  49:     0x55e90dd1b31d - <risingwave_object_store::object::opendal_engine::opendal_object_store::OpendalObjectStore as risingwave_object_store::object::ObjectStore>::read::{{closure}}::hc8b20316afe5a783
                               at /risingwave/src/object_store/src/object/opendal_engine/opendal_object_store.rs:135:32
  50:     0x55e90dd9919a - <core::pin::Pin<P> as core::future::future::Future>::poll::h9634a9ff55857579
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/future/future.rs:123:9
  51:     0x55e90dd9919a - <await_tree::future::Instrumented<F,_> as core::future::future::Future>::poll::hc3cb8ad753f6f34b
  52:     0x55e90e289074 - risingwave_object_store::object::MonitoredObjectStore<OS>::read::{{closure}}::{{closure}}::{{closure}}::hfc48ff33286c0f22
                               at /risingwave/src/object_store/src/object/mod.rs:647:18
  53:     0x55e90e289074 - <tokio::time::timeout::Timeout<T> as core::future::future::Future>::poll::h31fcd9dc81f8431a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/time/timeout.rs:202:33
  54:     0x55e90dda6846 - risingwave_object_store::object::retry_request::{{closure}}::{{closure}}::{{closure}}::h0a4485727a5a1976
                               at /risingwave/src/object_store/src/object/mod.rs:1195:18
  55:     0x55e90dda6846 - tokio_retry::future::RetryState<A>::poll::hc78342da0704a123
                               at /root/.cargo/git/checkouts/rust-tokio-retry-38aa0853644639a4-shallow/95e2fd3/src/future.rs:27:73
  56:     0x55e90dda6846 - <tokio_retry::future::RetryIf<I,A,C> as core::future::future::Future>::poll::hc09a5304dc086d71
                               at /root/.cargo/git/checkouts/rust-tokio-retry-38aa0853644639a4-shallow/95e2fd3/src/future.rs:156:15
  57:     0x55e90e059c79 - risingwave_object_store::object::retry_request::{{closure}}::h627fa48ae5c98671
                               at /risingwave/src/object_store/src/object/mod.rs:1205:62
  58:     0x55e90e059c79 - risingwave_object_store::object::MonitoredObjectStore<OS>::read::{{closure}}::hdce38c534bad3911
                               at /risingwave/src/object_store/src/object/mod.rs:657:10
  59:     0x55e90e059c79 - risingwave_object_store::object::ObjectStoreEnum<risingwave_object_store::object::MonitoredObjectStore<risingwave_object_store::object::mem::InMemObjectStore>,risingwave_object_store::object::MonitoredObjectStore<risingwave_object_store::object::opendal_engine::opendal_object_store::OpendalObjectStore>,risingwave_object_store::object::MonitoredObjectStore<risingwave_object_store::object::s3::S3ObjectStore>>::read::{{closure}}::h1ac91b570c0fcb75
                               at /risingwave/src/object_store/src/object/mod.rs:258:45
  60:     0x55e90e0198a7 - risingwave_meta::hummock::manager::write_exclusive_cluster_id::{{closure}}::hcf6c61cacbb8580e
                               at /risingwave/src/meta/src/hummock/manager/mod.rs:583:56
  61:     0x55e90e0198a7 - risingwave_meta::hummock::manager::HummockManager::new_impl::{{closure}}::h63cd17a7c17366d2
                               at /risingwave/src/meta/src/hummock/manager/mod.rs:232:14
  62:     0x55e90e0bf2dd - risingwave_meta::hummock::manager::HummockManager::new::{{closure}}::h64feb74cdc4924d2
                               at /risingwave/src/meta/src/hummock/manager/mod.rs:160:10
  63:     0x55e90e0bf2dd - risingwave_meta_node::server::start_service_as_election_leader::{{closure}}::he781416480c4bda1
                               at /risingwave/src/meta/node/src/server.rs:468:6
  64:     0x55e90e0b4684 - risingwave_meta_node::server::rpc_serve_with_store::{{closure}}::h2129a5dc593be24b
                               at /risingwave/src/meta/node/src/server.rs:335:6
  65:     0x55e90e0db34d - risingwave_meta_node::server::rpc_serve::{{closure}}::h0d58120e4e35d7f7
                               at /risingwave/src/meta/node/src/server.rs:250:14
  66:     0x55e90e0db34d - risingwave_meta_node::start::{{closure}}::h94a95e45b0b7ea7c
                               at /risingwave/src/meta/node/src/lib.rs:473:10
  67:     0x55e908967b91 - <core::pin::Pin<P> as core::future::future::Future>::poll::h06297825d9b96bf0
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/future/future.rs:123:9
  68:     0x55e908967b91 - <core::pin::Pin<P> as core::future::future::Future>::poll::h6e393132872bede7
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/future/future.rs:123:9
  69:     0x55e908967b91 - <&mut F as core::future::future::Future>::poll::h64acc7de477529f5
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/future/future.rs:111:9
  70:     0x55e908967b91 - risingwave_rt::main_okk::{{closure}}::{{closure}}::h609eee165428311b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/macros/select.rs:548:49
  71:     0x55e908967b91 - <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h4b8d7df72b0e5d46
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/future/poll_fn.rs:58:9
  72:     0x55e908967b91 - risingwave_rt::main_okk::{{closure}}::haa22de4c495b9b9b
                               at /risingwave/src/utils/runtime/src/lib.rs:107:9
  73:     0x55e908967b91 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h202b337bdf77a354
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  74:     0x55e908a97da5 - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h4f84855c26dbb952
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  75:     0x55e908a97da5 - tokio::runtime::coop::with_budget::he3a31ac340433127
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  76:     0x55e908a97da5 - tokio::runtime::coop::budget::he36905778e3d99c4
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  77:     0x55e908a97da5 - tokio::runtime::park::CachedParkThread::block_on::h729c4454abebb9e1
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  78:     0x55e908f3555f - tokio::runtime::context::blocking::BlockingRegionGuard::block_on::hd71f8c236e278f6b
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  79:     0x55e908f3555f - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}::h01c3d0e5338e16b7
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:22
  80:     0x55e908f3555f - tokio::runtime::context::runtime::enter_runtime::h7d79f42a6c699664
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  81:     0x55e908ce8aa3 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h20b4bda417336a77
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  82:     0x55e908ce8aa3 - tokio::runtime::runtime::Runtime::block_on::h487e5613bf3bb9eb
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:50
  83:     0x55e908df5d76 - risingwave_rt::main_okk::h02c6f2dad0b2ad64
                               at /risingwave/src/utils/runtime/src/lib.rs:149:5
  84:     0x55e908d0dc73 - risingwave_cmd::meta::h74185ad8fe8989e9
                               at /risingwave/src/cmd/src/lib.rs:47:5
  85:     0x55e907a13bce - risingwave::Component::start::h1cae890902d7a43d
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:121:27
  86:     0x55e907a147d4 - risingwave::main::h27be1dba45ab8d5c
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:224:5
  87:     0x55e907a175d3 - core::ops::function::FnOnce::call_once::h1c5cf827bcd43fb3
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/ops/function.rs:250:5
  88:     0x55e907a175d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3b5954736952557e
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:155:18
  89:     0x55e907a14fb9 - std::rt::lang_start::{{closure}}::h3b0d61f572d2ba3a
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/rt.rs:159:18
  90:     0x55e9124b956f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h1788e34035aefcce
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/ops/function.rs:284:13
  91:     0x55e9124b956f - std::panicking::try::do_call::hb8e771df4cfda499
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:559:40
  92:     0x55e9124b956f - std::panicking::try::h5bdf2c609cc4abd3
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:523:19
  93:     0x55e9124b956f - std::panic::catch_unwind::hfae59fa54039bbc3
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panic.rs:149:14
  94:     0x55e9124b956f - std::rt::lang_start_internal::{{closure}}::ha6372c0a3b48763e
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/rt.rs:141:48
  95:     0x55e9124b956f - std::panicking::try::do_call::hf771ef17b870d2a0
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:559:40
  96:     0x55e9124b956f - std::panicking::try::h84d9287d68560e01
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panicking.rs:523:19
  97:     0x55e9124b956f - std::panic::catch_unwind::he1757749be86c5ad
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/panic.rs:149:14
  98:     0x55e9124b956f - std::rt::lang_start_internal::h978095d8c1ffa0ac
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/rt.rs:141:20
  99:     0x55e907a14fac - main
 100:     0x7f2b7856b1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
 101:     0x7f2b7856b28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
 102:     0x55e9046d39e5 - _start
 103:                0x0 - <unknown>
```

**Comment by cnmac** [comment]
Hi @wcy-fdu, I am using the s3 interface of apache ozone. Ozone is deployed on the k8s cluster. The exposed port is s3g.ozone.svc.cluster.local:9878. When I configure stateStore.s3.endpoint to http://s3g.ozone.svc.cluster.local:9878, it reports an error that the domain name cannot be recognized: s3g.ozone.svc.cluster.local. The actual k8s environment can also access this domain name and port, so I changed http://s3g.ozone.svc.cluster.local:9878 to the specific form of http://192.168.2.71:9878. This is normal in risingwave v1.10.1, but when upgrading to risingwave v2.0.0, it reports the InvalidIpv4Address problem.

**Comment by Xuanwo** [comment]
I believe that's related to

https://github.com/risingwavelabs/risingwave/blob/bfa43091930004d008bcd0b3bd7407549e06c6d7/src/object_store/src/object/opendal_engine/opendal_s3.rs#L43-L45

risingwave will use virtual_host_style by default, so opendal will try to send requests to

- `http://risingwave.s3g.ozone.svc.cluster.local:9878/` => can't resolve.
- `http://risingwave.192.168.2.71:9878/` => invalid IPv4.

**Comment by cnmac** [comment]
Yes, I tested adding stateStore.s3.forcePathStyle = true, the problem is solved.
```
stateStore:
  dataDirectory: "prefix/data"
  s3:
    enabled: true
    endpoint: http://192.168.2.71:8878
    forcePathStyle: true
    region: us-east-1
    bucket: risingwave
    authentication:
      useServiceAccount: false
      accessKey: xxxxxxxxxxxxxxxxxxx
      secretAccessKey: xxx
```
