### ISSUE TITLE
bug: thread 'main' panicked at /risingwave/src/storage/hummock_sdk/src/version.rs:996:21: delta_type is not set

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#18650]
### Describe the bug

Panic when upgrading a cluster from v1.9.2 to latest `main` (~2.0.0). There's no issue upgrading a cluster from v1.9.2 to v1.10.x or v1.10.x to v2.0.x.

That being said, I'm not sure if we upgrade v1.9.2 to v1.10.x, then from v1.10.x to v2.0.x, the same error will surface. So we should still investigate on what type of error this is.

### Error message/log

```
thread 'main' panicked at /risingwave/src/storage/hummock_sdk/src/version.rs:996:21:
delta_type is not set
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/panicking.rs:74:14
   2: from<risingwave_hummock_sdk::sstable_info::SstableInfo>
             at ./src/storage/hummock_sdk/src/version.rs:996:21
   3: call_mut<fn(&risingwave_pb::hummock::GroupDelta) -> risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>, (&risingwave_pb::hummock::GroupDelta)>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/ops/function.rs:166:5
   4: {closure#0}<&risingwave_pb::hummock::GroupDelta, risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>, (), fn(&risingwave_pb::hummock::GroupDelta) -> risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>, core::iter::traits::iterator::Iterator::for_each::call::{closure_env#0}<risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>, alloc::vec::{impl#20}::extend_trusted::{closure_env#0}<risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>, alloc::alloc::Global, core::iter::adapters::map::Map<core::slice::iter::Iter<risingwave_pb::hummock::GroupDelta>, fn(&risingwave_pb::hummock::GroupDelta) -> risingwave_hummock_sdk::version::GroupDeltaCommon<risingwave_hummock_sdk::sstable_info::SstableInfo>>>>>
             at /rustc/5affbb17153bc69a9d5d8d2faa4e399a014a211e/library/core/src/iter/adapters/map.rs:89:28
```

### To Reproduce

Rerun https://buildkite.com/risingwavelabs/main-cron/builds/3315#01921f9d-f86b-4358-9078-cf24c47102ce.

### Expected behavior

No panic

### Additional context

https://buildkite.com/risingwavelabs/main-cron/builds/3315#01921f9d-f86b-4358-9078-cf24c47102ce

**Comment by hzxa21** [comment]
I suspect it is because we deprecate two delta types in this [PR](https://github.com/risingwavelabs/risingwave/pull/18585/files).

It will cause the panic here when the old delta containing the deprecated type is accessed by the new image:
https://github.com/risingwavelabs/risingwave/blob/d5dbc6ac1cd266140bb0740b3fedc53dbb53b07c/src/storage/hummock_sdk/src/version.rs#L996
