### ISSUE TITLE
EXCEPT panics for jsonb column

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#19278]
### Error message/log

```text
ERROR:  Panicked when handling the request: called `Result::unwrap()` on an `Err` value: function is_not_distinct_from(jsonb, jsonb) does not exist
This is a bug. We would appreciate a bug report at:
```

**Comment by xiangjinwu** [comment]
related: #7981, which may not be possible - and equality have to be supported.

On main (v2.3-alpha 1d58b407f5eb7079186661a203dbf58c1cbe962e), the `except` does not panic despite it still uses non-existent expr `is_not_distinct_from(jsonb, jsonb)` (need to examine more carefully):
```
dev=> select to_jsonb(1) except select to_jsonb(1);
 to_jsonb 
----------
(0 rows)

dev=> explain select to_jsonb(1) except select to_jsonb(1);
                                        QUERY PLAN                                         
-------------------------------------------------------------------------------------------
 BatchHashAgg { group_key: [$expr10005], aggs: [] }
 └─BatchHashJoin { type: LeftAnti, predicate: $expr10005 IS NOT DISTINCT FROM $expr10006 }
   ├─BatchValues { rows: [['1':Jsonb]] }
   └─BatchValues { rows: [['1':Jsonb]] }
(4 rows)

dev=> select to_jsonb(1) is not distinct from to_jsonb(1);
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: to_jsonb(1) IS NOT DISTINCT FROM to_jsonb(1)
  2: function is_not_distinct_from(jsonb, jsonb) does not exist
```

For the `map` type, `except`/`union`/`distinct` panics with the following error:
```
thread 'rw-batch-local' panicked at /Users/xiangjin/primary/risingwave-dev/src/common/src/hash/key.rs:630:1:
in-memory deserialize should never fail: InvalidTagEncoding(128)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/core/src/result.rs:1695:5
   3: core::result::Result<T,E>::expect
             at /Users/xiangjin/.rustup/toolchains/nightly-2024-10-11-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:1060:23
   4: <risingwave_common::array::map_array::scalar::MapValue as risingwave_common::hash::key::HashKeyDe>::deserialize
             at ./src/common/src/hash/key.rs:385:30
   5: risingwave_common::hash::key_v2::Deserializer<S,N>::deserialize
             at ./src/common/src/hash/key_v2.rs:199:18
   6: <risingwave_common::hash::key_v2::HashKeyImpl<S,N> as risingwave_common::hash::key_v2::HashKey>::deserialize_to_builders
             at ./src/common/src/hash/key_v2.rs:353:29
   7: risingwave_batch_executors::executor::hash_agg::HashAggExecutor<K>::do_execute::{{closure}}
             at ./src/batch/executors/src/executor/hash_agg.rs:716:21
```

**Comment by xiangjinwu** [comment]
panic will be fixed by #22390 but would like to keep this open to fix/avoid similar problems (missing implementations)

**Comment by xxchan** [comment]
User's context for `=`/`except` for `jsonb`/`map`: for dbt tests
https://risingwave-labs.slack.com/archives/C0881T5531D/p1750487735004049?thread_ts=1750478278.388169&cid=C0881T5531D

> I think mainly around testing use cases where we may want to assert whether two values are the same.  That said, existing dbt test mechanisms don't directly use = operator:
1. dbt unit tests compare row values in Python rather than SQL.  That is, they read both actual/expected values and then compare them there.  So it turns out we don't need = operator for dbt unit tests when checking against expected output.  (But if they implemented with SQL, then it would have been necessary.)
2. dbt data tests might use `equality` test to compare two tables, [but that uses](https://github.com/dbt-labs/dbt-utils/blob/22855099135cd4de445bed45601f11cb1caabb24/macros/generic_tests/equality.sql#L143) `EXCEPT` [to do the comparison instead](https://github.com/dbt-labs/dbt-utils/blob/22855099135cd4de445bed45601f11cb1caabb24/macros/generic_tests/equality.sql#L143), which is also broken.
