### ISSUE TITLE
Backfill test failed: attempt to subtract with overflow

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#19586]
### Describe the bug

Failed in `main-cron` https://buildkite.com/risingwavelabs/main-cron/builds/3953#01936934-335a-497c-8b74-78c23e75345c.

### Error message/log

```text
thread 'rw-main' panicked at src/meta/src/hummock/compaction/selector/level_selector.rs:208:31:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_const::panic_const_sub_overflow
             at /rustc/52fd9983996d9fcfb719749838336be66dee68f9/library/core/src/panicking.rs:181:21
   3: get_priority_levels
             at ./src/meta/src/hummock/compaction/selector/level_selector.rs:208:31
   4: pick_compaction
             at ./src/meta/src/hummock/compaction/selector/level_selector.rs:427:19
   5: get_compact_task
             at ./src/meta/src/hummock/compaction/mod.rs:123:29
   6: {async_fn#0}
             at ./src/meta/src/hummock/manager/compaction/mod.rs:730:44
   7: {async_fn#0}
             at ./src/meta/src/hummock/manager/compaction/mod.rs:1032:14
   8: {async_fn#0}
             at ./src/meta/src/hummock/manager/compaction/mod.rs:282:26
   9: {async_block#0}
             at ./src/meta/src/hummock/manager/compaction/mod.rs:568:184
```

**Comment by kwannoel** [comment]
Don't see it anymore
