### ISSUE TITLE
bug: panic when adding to a table a column as the primary key

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#19609]
### Describe the bug

```
dev=> create table t(v1 int, v2 int);
CREATE_TABLE

dev=> drop table tmp2;
DROP_TABLE

dev=> create table tmp2 as select * except (v1) from t;
INSERT 0 0

dev=> alter table tmp2 add column employee_id int primary key;
ERROR:  Panicked when handling the request: called `Result::unwrap()` on an `Err` value: []
This is a bug. We would appreciate a bug report at:
  https://github.com/risingwavelabs/risingwave/issues/new?labels=type%2Fbug&template=bug_report.yml
SSL connection has been closed unexpectedly

```

### Error message/log

```text
2024-11-29 10:56:04.860	
thread 'rw-standalone-frontend' panicked at src/frontend/src/handler/alter_table_column.rs:322:10:
2024-11-29 10:56:04.860	
called `Result::unwrap()` on an `Err` value: []
2024-11-29 10:56:04.860	
stack backtrace:
2024-11-29 10:56:04.978	
   0:     0xaaaad2dc7c74 - std::backtrace_rs::backtrace::libunwind::trace::h22abe6941b6c364e
2024-11-29 10:56:04.978	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
2024-11-29 10:56:04.978	
   1:     0xaaaad2dc7c74 - std::backtrace_rs::backtrace::trace_unsynchronized::h09825ba824b25c03
2024-11-29 10:56:04.978	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
2024-11-29 10:56:04.978	
   2:     0xaaaad2dc7c74 - std::sys_common::backtrace::_print_fmt::h8edb2ed98e6d043e
2024-11-29 10:56:04.978	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:68:5
2024-11-29 10:56:04.978	
   3:     0xaaaad2dc7c74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h59fe19f00e808c0f
2024-11-29 10:56:04.978	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/sys_common/backtrace.rs:44:22
2024-11-29 10:56:04.979	
   4:     0xaaaac82db660 - core::fmt::rt::Argument::fmt::h97fcedd5c989dd8e
2024-11-29 10:56:04.979	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/rt.rs:165:63
2024-11-29 10:56:04.979	
   5:     0xaaaac82db660 - core::fmt::write::h2ab4a0f6cb1c47e2
2024-11-29 10:56:04.979	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/core/src/fmt/mod.rs:1168:21
2024-11-29 10:56:04.979	
   6:     0xaaaad2dc135c - std::io::Write::write_fmt::h92c5bdbd600095f4
2024-11-29 10:56:04.979	
                               at /rustc/72fdf913c53dd0e75313ba83e4aa80df3f6e2871/library/std/src/io/mod.rs:1835:15
2024-11-29 10:56:04.979	
   7:     0xaaaad2dc7abc - std::sys_common::backtrace::_print::ha084ca3dc112f7ce
```

### To Reproduce

Please use the SQL statements above

### Additional context

This pattern is useful when we want to create a table with a primary key but without manually specifying the schema.

**Comment by BugenZhao** [comment]
I believe this issue arises because you're performing a schema change on a `CREATE TABLE AS` (CTAS). The table's definition isn't properly maintained, which is necessary for replacing the table plan.

Similar issue: https://github.com/risingwavelabs/risingwave/issues/15334#issuecomment-1968532255

Adding a primary key to a normal table should be rejected gracefully.

**Comment by lmatz** [comment]
Always reject or reject under some conditions?

The doc includes "primary key" clause in the syntax:
https://docs.risingwave.com/sql/commands/sql-alter-table#clauses
but does not mention under what condition it can be used

**Comment by BugenZhao** [comment]
> Always reject or reject under some conditions?

Always rejected. Primary key affects the physical distribution of the table data thus cannot be changed with instant schema change.

**Comment by BugenZhao** [comment]
Fixed in https://github.com/risingwavelabs/risingwave/pull/20174.
