### ISSUE TITLE
Recovery failure on source manager (I believe there are also  bugs in other components).

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#3746]
**Describe the bug**

I encountered this panic when I restarted a meta node that had set up a source.

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError(())', src/meta/src/barrier/mod.rs:754:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/result.rs:1098:23
   4: risingwave_meta::barrier::GlobalBarrierManager<S>::run_command::{{closure}}
             at ./risingwave/src/meta/src/barrier/mod.rs:754:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/future/mod.rs:91:19
   6: risingwave_meta::stream::source_manager::SourceManager<S>::tick::{{closure}}::{{closure}}::{{closure}}
             at ./risingwave/src/meta/src/stream/source_manager.rs:722:58
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/future/mod.rs:91:19
   8: tokio_retry::future::RetryState<A>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.3.0/src/future.rs:27:73
   9: <tokio_retry::future::RetryIf<I,A,C> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.3.0/src/future.rs:156:15
  10: <tokio_retry::future::Retry<I,A> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-retry-0.3.0/src/future.rs:76:9
  11: risingwave_meta::stream::source_manager::SourceManager<S>::tick::{{closure}}
             at ./risingwave/src/meta/src/stream/source_manager.rs:723:15
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/future/mod.rs:91:19
  13: risingwave_meta::stream::source_manager::SourceManager<S>::run::{{closure}}
             at ./risingwave/src/meta/src/stream/source_manager.rs:740:40
```

**To Reproduce**
Steps to reproduce the behavior.

1. `docker compose up -d`. You can use the config file here: https://github.com/singularity-data/risingwave-demo/blob/main/docker/docker-compose.yml (v0.10.0)
2. Create a source:
    ```
    create source ad_source (
        user_id bigint,
        ad_id bigint,
        click_timestamp timestamp,
        impression_timestamp timestamp
    ) with (
        'connector' = 'kafka',
        'kafka.topic' = 'ad_clicks',
        'kafka.brokers' = '...',
        'kafka.scan.startup.mode' = 'earliest'
    ) row format json;
    ```
3. `docker compose stop`
4. `docker compose start`

**Expected behavior**

**Additional context**

**Comment by tabVersion** [comment]
thanks for reporting. I will work on it.
