### ISSUE TITLE
storage/streaming: Materialize state table sanity check failed for `Update`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4861]
```
thread 'risingwave-streaming-actor' panicked at 'value mismatch when updating row: Some(b"\x01\xe8\x03\0\0\0\0\0\0\x01\x02\0\0\0\0\0\0\0\x01\x90\xa2\xa5U\0\0\0\0\0\0\0\0\x01\x90\xa2\xa5U\0\0\0\0\0\0\0\0") != [1, 232, 3, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 1, 144, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0, 1, 144, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0]', /risingwave/src/storage/src/streaming_table/state_table.rs:473:25
stack backtrace:
thread 'risingwave-streaming-actor' panicked at 'value mismatch when updating row: Some(b"\x01\xe8\x03\0\0\0\0\0\0\x01\x04\0\0\0\0\0\0\0\x01\x82\xa2\xa5U\0\0\0\0\0\0\0\0\x01\x82\xa2\xa5U\0\0\0\0\0\0\0\0") != [1, 232, 3, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 0, 0, 0, 0, 1, 130, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0, 1, 130, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0]', /risingwave/src/storage/src/streaming_table/state_table.rs:473:25
thread 'risingwave-streaming-actor' panicked at 'value mismatch when updating row: Some(b"\x01\xe8\x03\0\0\0\0\0\0\x01\x02\0\0\0\0\0\0\0\x01z\xa2\xa5U\0\0\0\0\0\0\0\0\x01z\xa2\xa5U\0\0\0\0\0\0\0\0") != [1, 232, 3, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0, 0, 0, 0, 1, 122, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0, 1, 122, 162, 165, 85, 0, 0, 0, 0, 0, 0, 0, 0]', /risingwave/src/storage/src/streaming_table/state_table.rs:473:25
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::streaming_table::state_table::StateTable<S>::batch_write_rows::{{closure}}
             at ./src/storage/src/streaming_table/state_table.rs:473:25
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: risingwave_storage::streaming_table::state_table::StateTable<S>::commit::{{closure}}
             at ./src/storage/src/streaming_table/state_table.rs:401:52
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:155:59
```

Full logs [here](https://buildkite.com/singularity-data/pull-request/builds/6758#0182cf63-acce-48ab-be9f-0ed76e67e7f9).

May related: #4857 #4774

cc @hzxa21

**Comment by wcy-fdu** [comment]
May related: https://github.com/singularity-data/risingwave/pull/4854

**Comment by hzxa21** [comment]
Relevant to #4813

**Comment by BugenZhao** [comment]
Seems not resolved yet. `inconsistent deletion` at https://buildkite.com/singularity-data/pull-request/builds/6976#0182d880-32cf-4dd0-b743-d01bbfaf8503

**Comment by fuyufjh** [comment]
maybe related #4894

**Comment by zwang28** [comment]
Another failure for update
https://buildkite.com/singularity-data/pull-request/builds/7059#0182e7cf-5446-44e9-86ff-126e87fe1b0b

**Comment by zwang28** [comment]
Another [overwriting an existing row](https://buildkite.com/singularity-data/pull-request/builds/7111#0182e8bf-b55a-4c97-9bf6-6c30f4637fe5)

**Comment by BugenZhao** [comment]
Could this be an issue related to the project set executor?

**Comment by xxhZs** [comment]
Relevant to https://github.com/risingwavelabs/risingwave/pull/4996

**Comment by hzxa21** [comment]
#4996 didn't fix the issue completely. Another occurrence: 
```
thread 'risingwave-streaming-actor' panicked at 'value mismatch when updating row: Some(b"\x01\0\0\x04\0bt\xa6\x05\0\0\0\0\0\0\0\0") != [1, 0, 0, 4, 0, 100, 34, 148, 49, 0, 0, 0, 0, 0, 0, 0, 0]', /risingwave/src/storage/src/table/streaming_table/state_table.rs:484:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::state_table::StateTable<S>::batch_write_rows::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:484:25
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: risingwave_storage::table::streaming_table::state_table::StateTable<S>::commit::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:412:52
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:155:59
   7: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
``` 

https://buildkite.com/singularity-data/pull-request/builds/7281#0182ee4d-4df7-4ed6-845a-514539c98cd2




> Could this be an issue related to the project set executor?

Fix for project set has been merged but the issue still continues so I think it is not related.

**Comment by hzxa21** [comment]
> Another [overwriting an existing row](https://buildkite.com/singularity-data/pull-request/builds/7111#0182e8bf-b55a-4c97-9bf6-6c30f4637fe5)



> Another failure for update https://buildkite.com/singularity-data/pull-request/builds/7059#0182e7cf-5446-44e9-86ff-126e87fe1b0b



> Seems not resolved yet. `inconsistent deletion` at https://buildkite.com/singularity-data/pull-request/builds/6976#0182d880-32cf-4dd0-b743-d01bbfaf8503

These occurrences are all related to ProjectSet so I believe they are not related to this bug.

**Comment by wcy-fdu** [comment]
It seems that this bug has become more frequent in CI...

**Comment by hzxa21** [comment]
Another occurrence on join executor after #5020. Reproduced steps:
```
./risedev dev ci-3cn-3fe

sqllogictest -h localhost -p 4565 -h localhost -p 4566 -h localhost -p 4567 -d dev './e2e_test/streaming/**/*.slt' -j 16
```

commit_id: `df00ff4e0`

```
thread 'risingwave-streaming-actor' panicked at 'value mismatch when updating row: Some(b"\x01\xa1\x03\0\0\0\0\0\0\x01S\0\0\0\x01\x01\0\0\0\0\0\0\0") != [1, 161, 3, 0, 0, 0, 0, 0, 0, 1, 83, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0]', /home/patrick/projs/risingwave-dev/src/storage/src/table/streaming_table/state_table.rs:449:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::state_table::StateTable<S>::batch_write_rows::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:449:25
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: risingwave_storage::table::streaming_table::state_table::StateTable<S>::commit::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:378:52
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::flush::{{closure}}
             at ./src/stream/src/executor/managed_state/join/mod.rs:340:52
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::flush_data::{{closure}}
             at ./src/stream/src/executor/hash_join.rs:614:31
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
``` 
[compute-node-5689.log](https://github.com/risingwavelabs/risingwave/files/9467255/compute-node-5689.log)
[compute-node-5687.log](https://github.com/risingwavelabs/risingwave/files/9467256/compute-node-5687.log)
[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/9467257/compute-node-5688.log)

**Comment by MrCroxx** [comment]
And another one: https://buildkite.com/risingwavelabs/pull-request/builds/7486#0182fc53-596e-420c-9c22-f5845e09e94e

**Comment by BugenZhao** [comment]
Reproduced on the release profile: https://buildkite.com/risingwavelabs/main/builds/1467#01830ba4-fad0-4ea0-8217-067585370994

**Comment by hzxa21** [comment]
#5065 is the potential cause of this issue. PR is merged now. Let's wait a few days to see whether this issue still happens.

**Comment by fuyufjh** [comment]
> #5065 is the potential cause of this issue. PR is merged now. Let's wait a few days to see whether this issue still happens.

So the bug still exists

**Comment by nanderstabel** [comment]
Another occurrence when receiving a debezium/kafka `UPDATE` message.

To reproduce:
```
// start cluster
$ ./risedev kafka

// start kafka topic and kafka producer with this specific (UPDATE) message
$ ./.risingwave/bin/kafka/bin/kafka-topics.sh --create --topic my-topic --bootstrap-server 127.0.0.1:29092
$ ./.risingwave/bin/kafka/bin/kafka-console-producer.sh --topic my-topic --bootstrap-server 127.0.0.1:29092
>{"schema":{},"payload":{"before":{"id":1,"status":null},"after":{"id":1,"status":"COMPLETED"},"source":{"version":"1.4.2.Final","connector":"postgresql","name":"postgres","ts_ms":1662716476390,"snapshot":"false","db":"simple_db","schema":"public","table":"t","txId":490,"lsn":23871176,"xmin":null},"op":"u","ts_ms":1662716476717,"transaction":null}}

// connect to postgres
$ psql -h localhost -p 4566 -d dev -U root

// Create materialized source from my-topic
dev=> create materialized source simple (id int, status varchar, primary key (id)) with ( connector = 'kafka', topic = 'my-topic', properties.bootstrap.server = '127.0.0.1:29092', scan.startup.mode = 'earliest' ) row format DEBEZIUM_JSON;
```

This results in the following panic:
```
thread 'risingwave-streaming-actor' panicked at 'update a non-existing row: [1, 1, 0, 0, 0, 0]', /home/nstabel/Workspace/risingwave-dev/src/storage/src/table/streaming_table/state_table.rs:522:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::state_table::StateTable<S>::batch_write_rows::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:522:25
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: risingwave_storage::table::streaming_table::state_table::StateTable<S>::commit::{{closure}}
             at ./src/storage/src/table/streaming_table/state_table.rs:456:52
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:124:59
   7: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  11: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  12: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  13: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:57:60
  14: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  16: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  17: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  18: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:140:36
  19: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  20: risingwave_stream::executor::wrapper::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:120:70
  21: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  22: risingwave_stream::executor::wrapper::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/wrapper/schema_check.rs:24:1
  23: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  24: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  25: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  26: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  27: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/wrapper/epoch_check.rs:31:44
  28: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  29: risingwave_stream::executor::wrapper::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/wrapper/update_check.rs:27:1
  30: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  31: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  32: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  33: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./src/stream/src/executor/dispatch.rs:255:9
  34: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  35: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  36: <&mut S as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:104:9
  37: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.9/src/stream_ext/next.rs:42:9
  38: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  39: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:140:36
  40: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  41: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:111:16
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  43: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:608:32
  44: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  45: <risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::__Enum15994158506141524639<__Variant0,__Variant1> as core::future::future::Future>::poll
             at ./src/stream/src/task/stream_manager.rs:610:17
  46: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  47: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  48: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  50: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  51: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  52: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  53: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  54: __rust_try
  55: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  56: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  57: tokio::runtime::task::harness::poll_future
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  58: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  59: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  60: tokio::runtime::task::raw::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
  61: tokio::runtime::task::raw::RawTask::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  62: tokio::runtime::task::LocalNotified<S>::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:381:9
  63: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:435:13
  64: tokio::coop::with_budget::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  65: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  66: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  67: tokio::coop::with_budget
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:95:5
  68: tokio::coop::budget
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  69: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
  70: tokio::runtime::thread_pool::worker::Context::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:408:24
  71: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:386:17
  72: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  73: tokio::runtime::thread_pool::worker::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:383:5
  74: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:362:45
  75: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/task.rs:42:21
  76: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  77: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  78: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  79: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  80: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  81: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  82: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  83: __rust_try
  84: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  85: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  86: tokio::runtime::task::harness::poll_future
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  87: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  88: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  89: tokio::runtime::task::raw::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
  90: tokio::runtime::task::raw::RawTask::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  91: tokio::runtime::task::UnownedTask<S>::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:418:9
  92: tokio::runtime::blocking::pool::Task::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:91:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
