### ISSUE TITLE
bug(recovery): panicked at 'no table reader exists'

### ISSUE THREAD

**Issue by wangrunji0408** [risingwavelabs/risingwave#4875]
### Describe the bug

https://buildkite.com/singularity-data/pull-request/builds/6818#0182d35d-042e-42ec-8b57-dcdebd0ce81c/2450-5881
```
thread '<unnamed>' panicked at 'no table reader exists', src/source/src/table_v2.rs:66:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at ./src/source/src/table_v2.rs:66:13
   6: risingwave_source::table_v2::TableSourceV2::write_chunk
             at ./src/source/src/table_v2.rs:66:13
   7: risingwave_batch::executor::insert::InsertExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/insert.rs:102:28
   8: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  11: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  12: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  13: risingwave_batch::executor::trace::TraceExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/trace.rs:67:69
  14: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  16: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  17: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  18: risingwave_batch::task::task_execution::BatchTaskExecution<C>::try_execute::{{closure}}::{{closure}}
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/select.rs:507:49
  19: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/future/poll_fn.rs:38:9
  20: risingwave_batch::task::task_execution::BatchTaskExecution<C>::try_execute::{{closure}}
             at ./src/batch/src/task/task_execution.rs:335:13
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  22: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  23: risingwave_batch::task::task_execution::BatchTaskExecution<C>::async_execute::{{closure}}::{{closure}}::{{closure}}
             at ./src/batch/src/task/task_execution.rs:274:23
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  25: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  26: async_task::raw::RawTask<F,T,S>::run
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
  27: madsim::sim::task::Executor::run_all_ready::{{closure}}
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.3/src/sim/task.rs:179:53
  28: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  29: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  30: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  31: madsim::sim::task::Executor::run_all_ready
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.3/src/sim/task.rs:179:20
  32: madsim::sim::task::Executor::block_on
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.3/src/sim/task.rs:147:13
  33: madsim::sim::runtime::Runtime::block_on
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.3/src/sim/runtime/mod.rs:124:9
  34: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at /Users/wangrunji/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.3/src/sim/runtime/builder.rs:128:35
```

### To Reproduce

On M1 Macbook Pro, checkout 4850abc and run:
```
MADSIM_TEST_SEED=3 ./risedev sslt -- --kill-node './e2e_test/batch/**/*.slt'
```

On Linux: (not sure whether this works)
```
MADSIM_TEST_SEED=1661404148 ./risedev sslt -- --kill-node './e2e_test/batch/**/*.slt'
```

**Comment by BugenZhao** [comment]
Inserting into a table will first try to find a running `SourceExecutor` ("table reader"), then send the chunks to it. In the normal `create table` procedure, we ensure that the table is visible only after the streaming tasks (including the `SourceExecutor`s) ready so we assert there's must be one table reader.

With recovery, we may update and build actors. Before the building completes, if a frontend issues a batch query of `Insert`, it may find no table reader available. Easy to reproduce if we insert a delay before `self.update_actors`.

https://github.com/singularity-data/risingwave/blob/7065ef109aeadc11d582d184ff0d7f2cb9c8ca2f/src/meta/src/barrier/recovery.rs#L96-L104

A quick fix can be changing the `expect` to `or_else`, as the actors will be built and the `Insert` query will succeed eventually (after some retries). However, I'm not sure whether the recovery test requires that there should be no error during the whole tests. If so, should we block all queries in the frontend until the meta finally recovered the whole cluster? cc @yezizp2012

**Comment by fuyufjh** [comment]
Any updates?

**Comment by BugenZhao** [comment]
> Any updates?

We won't panic after #4967, but return error if the cluster is recovering and DML is temporarily unavailable. IIRC, the simulator will retry in these cases now, so there should be no problem.
