### ISSUE TITLE
bug: streaming jobs (NexMark) didn't recover after cluster restarts

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4918]
### Describe the bug

As title.

### To Reproduce

1. `./risedev d full`
2. Create NexMark sources and `create materialized view nexmark_q7`
3. `./risedev d full` again to restart cluster
4. Watch Grafana and no throughput

### Expected behavior

Streaming jobs should recover after restart

**Comment by BugenZhao** [comment]
I think we've not implemented meta service recovery?

**Comment by TennyZhuang** [comment]
In `InnerConnectorSourceReader::new`, when the source is first created:

```
&split = Some(
    [
        Nexmark(
            NexmarkSplit {
                split_index: 0,
                split_num: 4,
                start_offset: None,
            },
        ),
    ],
```

When it's recovered:

```
&split = None
```

cc @tabVersion

**Comment by tabVersion** [comment]
after some investigation, I believe it is a left todo: source executor should maintain its split assignment and write to state store. 
I prefer to use source_id as the prefix in state_store, is it okay when migrating or scaling? @shanicky

**Comment by fuyufjh** [comment]
> after some investigation, I believe it is a left todo: source executor should maintain its split assignment and write to state store. I prefer to use source_id as the prefix in state_store, is it okay when migrating or scaling? @shanicky

Will it cause the problem similar to #4817 if using source_id?

**Comment by tabVersion** [comment]
> > after some investigation, I believe it is a left todo: source executor should maintain its split assignment and write to state store. I prefer to use source_id as the prefix in state_store, is it okay when migrating or scaling? @shanicky
> 
> Will it cause the problem similar to #4817 if using source_id?

I think it won't. I use internal_table_id as source_id for actors in each fragment and this will make the prefix unique.

**Comment by fuyufjh** [comment]
Any progress on this? @tabVersion

**Comment by tabVersion** [comment]
> Any progress on this?

#5004 has proven executors can handle state restoring from the state store but it can not handle crashes on migration. After discussion @shanicky and @yezizp2012 , a solution is that meta pushes split assignments to executors again by recovery (#5160). This solution requires some refractory on meta source manager and barrier manager, still in design stage.

**Comment by cyliu0** [comment]
The compute node panicked after restarting the cluster w/ 3 compute nodes.
```
  full-3cn:
    - use: minio
    - use: etcd
    - use: meta-node
    - use: compute-node
      port: 5687
      exporter-port: 1222
    - use: compute-node
      port: 5688
      exporter-port: 1223
    - use: compute-node
      port: 5689
      exporter-port: 1224
    - use: frontend
    - use: compactor
    - use: prometheus
    - use: grafana
    - use: zookeeper
      persist-data: true
    - use: kafka
      persist-data: true
```
Part of the compute note panic stack
```
thread 'risingwave-main' panicked at 'assertion failed: `(left == right)`
  left: `14`,
 right: `15`', src/storage/src/hummock/local_version/local_version_manager.rs:168:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:181:5
   4: risingwave_storage::hummock::local_version::local_version_manager::LocalVersionManager::try_update_pinned_version
             at ./src/storage/src/hummock/local_version/local_version_manager.rs:168:21
   5: risingwave_storage::hummock::event_handler::hummock_event_handler::HummockEventHandler::start_hummock_event_handler_worker::{{closure}}
             at ./src/storage/src/hummock/event_handler/hummock_event_handler.rs:323:25
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   7: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
   8: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
   9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  10: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  11: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  13: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  14: ___rust_try
  15: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  16: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  17: tokio::runtime::task::harness::poll_future
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
```
So reopen this one.

**Comment by tabVersion** [comment]
> This seems a bug of Hummock storage and is not relavant to this issue. Could you please help to open a new issue for this?

I think it is related and I am looking into this. Source executor recovery failure can result in hummock panic. 
Taking a rough look, meta behaves abnormally since I does not push down split assignments down as expected in #5160

**Comment by tabVersion** [comment]
```
INFO risingwave_meta::barrier::recovery: meta push down {63: [Nexmark(NexmarkSplit { split_index: 2, split_num: 4, start_offset: None })], 16: [Nexmark(NexmarkSplit { split_index: 1, spli
t_num: 4, start_offset: None })], 15: [Nexmark(NexmarkSplit { split_index: 2, split_num: 4, start_offset: None })], 64: [Nexmark(NexmarkSplit { split_index: 3, split_num: 4, start_offset: None })], 39: [Nexmark(Nexma
rkSplit { split_index: 0, split_num: 4, start_offset: None })], 14: [Nexmark(NexmarkSplit { split_index: 3, split_num: 4, start_offset: None })], 61: [Nexmark(NexmarkSplit { split_index: 1, split_num: 4, start_offset
: None })], 37: [Nexmark(NexmarkSplit { split_index: 1, split_num: 4, start_offset: None })], 38: [Nexmark(NexmarkSplit { split_index: 2, split_num: 4, start_offset: None })], 13: [Nexmark(NexmarkSplit { split_index:
 0, split_num: 4, start_offset: None })], 40: [Nexmark(NexmarkSplit { split_index: 3, split_num: 4, start_offset: None })], 62: [Nexmark(NexmarkSplit { split_index: 0, split_num: 4, start_offset: None })]}
```

nexmark Q7 involves 36 actors but meta pushes down only 12 of them where all of the recovered actors are on the same node.

**Comment by tabVersion** [comment]
Validate with the [latest main](https://github.com/risingwavelabs/risingwave/commit/8a650e533cf5dd404bd6fce4e964692806ea297b), the problem seems fixed.
