### ISSUE TITLE
bug: meta: crash on "etcdserver: request timed out"

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#4919]
### Describe the bug

```log
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Internal(grpc request error: status: Unavailable, message: "etcdserver: request timed out", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1107:23
   4: risingwave_meta::barrier::GlobalBarrierManager<S>::run::{{closure}}
             at ./src/meta/src/barrier/mod.rs:595:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_meta::barrier::GlobalBarrierManager<S>::start::{{closure}}::{{closure}}
             at ./src/meta/src/barrier/mod.rs:507:45
   ... omitted ...
```

### To Reproduce

1. `./risedev d full`
2. Create NexMark sources and `create materialized view nexmark_q7`
3. waiting for 30min

### Expected behavior

don't crash

**Comment by fuyufjh** [comment]
It seems to be caused by this `unwrap`. Looks incorrect.

https://github.com/singularity-data/risingwave/blob/fe08fc5cf0f816334bfa1e96d52cc42d0aa19c7a/src/meta/src/barrier/mod.rs#L590-L593
