### ISSUE TITLE
file cache fail to limit it's total size

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#5009]
### Describe the bug

When running nexmark q20 on aws 3 node deploy. The compute nodes panic:
```
thread 'risingwave-main' panicked at 'error raised within file cache buffer flusher: nix error: ENOSPC: No space left on device', /ebs/risingwave/src/storage/src/hummock/file_cache/cache.rs:215:17
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::file_cache::cache::FileCache<K,V,S>::open_with_hasher::{{closure}}::{{closure}}
             at ./ebs/risingwave/src/storage/src/hummock/file_cache/cache.rs:215:17
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
   5: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
   6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
   7: tokio::runtime::task::core::CoreStage<T>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
   8: tokio::runtime::task::harness::poll_future::{{closure}}
error from daemon in stream: Error grabbing logs: unexpected EOF
```

The configuration of CNs are c5.2xlarge with 20G root disk space. I think 20G should be enough since:

 `df -T` shows a CN consumes more than 20G disk
```
Filesystem      Type  1K-blocks     Used Available Use% Mounted on
/dev/root       ext4   20134592 20118208         0 100% /
```
while a meta only consumes less than 10G disk
```
Filesystem      Type  1K-blocks    Used Available Use% Mounted on
/dev/root       ext4  101430960 9619244  91795332  10% /
```

### To Reproduce

Run nexmark q20 using three-easy-steps. The cn will panic within 10 min.

### Expected behavior

Limit the space file cache uses.

**Comment by MrCroxx** [comment]
Have you check the disk occupation? The default config has limited file cache to 1 GiB. 🤔

**Comment by yuhao-su** [comment]
> Have you check the disk occupation? The default config has limited file cache to 1 GiB. 🤔

Yes. But the CN still uses more than 10GB than Meta
