### ISSUE TITLE
bug: streaming top-n cannot do state recovery

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5196]
When testing with actor migration in #4956, I find that streaming top-n cannot do state recovery.

```
dev=> create table t (v int);
CREATE_TABLE
dev=> insert into t values (1), (2), (3);
INSERT 0 3
dev=> create materialized view mv as select v from t order by v limit 2;
CREATE_MATERIALIZED_VIEW
dev=> select * from t;
 v 
---
 1
 3
 2
(3 rows)

dev=> select * from mv;
 v 
---
 1
 2
(2 rows)

====> Migrate global top-n to a new compute node.

dev=> delete from t where v = 3;
DELETE 1

====> PANIC!

thread 'risingwave-streaming-actor' panicked at 'attempt to subtract with overflow', src/stream/src/executor/managed_state/top_n/top_n_state.rs:79:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:48:5
   3: risingwave_stream::executor::managed_state::top_n::top_n_state::ManagedTopNState<S>::delete
             at ./src/stream/src/executor/managed_state/top_n/top_n_state.rs:79:9
   4: <risingwave_stream::executor::top_n::InnerTopNExecutorNew<S> as risingwave_stream::executor::top_n_executor::TopNExecutorBase>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/top_n.rs:371:21
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
   7: risingwave_stream::executor::top_n_executor::TopNExecutorWrapper<E>::top_n_executor_execute::{{closure}}
             at ./src/stream/src/executor/top_n_executor.rs:109:79
```

The problem is, when initializing a Top-N executor, we always set the `total_count` to 0.

https://github.com/risingwavelabs/risingwave/blob/3e0d4d2873c47c1bd141ccd90d286c75fff06e6f/src/stream/src/from_proto/top_n.rs#L48-L58

Do we really need to maintain such a field? 👀

**Comment by st1page** [comment]
fixed in #5202
