### ISSUE TITLE
panic: meta: transport error

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5197]
### Describe the bug

```
thread 'risingwave-main' panicked at 'called `Result::unwrap()` on an `Err` value: Internal(grpc request error: status: Unknown, message: "transport error", details: [], metadata: MetadataMap { headers: {} }

   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1107:23
   4: risingwave_meta::barrier::GlobalBarrierManager<S>::run::{{closure}}
             at ./src/meta/src/barrier/mod.rs:679:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_meta::barrier::GlobalBarrierManager<S>::start::{{closure}}::{{closure}}
             at ./src/meta/src/barrier/mod.rs:591:45
```

Full logs: [risingwave-logs.zip](https://github.com/risingwavelabs/risingwave/files/9507878/risingwave-logs.zip)

### To Reproduce

See https://github.com/risingwavelabs/risingwave/issues/5157#issue-1364002749

**Comment by fuyufjh** [comment]
@xxhZs Please take a look. Feel free to reassign it to others

**Comment by BugenZhao** [comment]
The same as #4919. I think we still use `unwrap` here as the timeout should already be handled by the retry client. Is there something wrong with the connection to the etcd server?

**Comment by fuyufjh** [comment]
Yes, perhaps. My EC2 instance went into some weird state after running benchmark for a while - it even does not respond to my SSH login. I'll investigate it today.

**Comment by fuyufjh** [comment]
Duplicated #4919
