### ISSUE TITLE
bug(storage): panicked: when sync an epoch, there should not be any uploading task

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5209]
### Describe the bug

```
thread 'risingwave-main' panicked at 'when sync an epoch, there should not be any uploading task', src/storage/src/hummock/shared_buffer/mod.rs:290:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::shared_buffer::SharedBuffer::into_uncommitted_data
             at ./src/storage/src/hummock/shared_buffer/mod.rs:290:9
   3: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer_le_epoch::{{closure}}::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:545:61
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/ops/function.rs:301:13
   5: core::option::Option<T>::map
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/option.rs:929:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/map.rs:103:9
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter.rs:33:9
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/mod.rs:2648:9
  10: core::iter::traits::iterator::Iterator::collect
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/traits/iterator.rs:1836:9
  11: itertools::Itertools::collect_vec
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/lib.rs:1985:9
  12: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer_le_epoch::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:541:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  14: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:521:48
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  16: risingwave_storage::hummock::state_store::<impl risingwave_storage::store::StateStore for risingwave_storage::hummock::HummockStorage>::sync::{{closure}}
             at ./src/storage/src/hummock/state_store.rs:648:43
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  18: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  19: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  20: <risingwave_storage::monitor::monitored_store::MonitoredStateStore<S> as risingwave_storage::store::StateStore>::sync::{{closure}}
             at ./src/storage/src/monitor/monitored_store.rs:251:43
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  22: risingwave_stream::task::stream_manager::LocalStreamManager::sync_epoch::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:239:36
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  24: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  25: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  26: <risingwave_compute::rpc::service::stream_service::StreamServiceImpl as risingwave_pb::stream_service::stream_service_server::StreamService>::barrier_complete::{{closure}}
             at ./src/compute/src/rpc/service/stream_service.rs:166:75
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  29: <<risingwave_pb::stream_service::stream_service_server::StreamServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::BarrierCompleteSvc<T> as tonic::server::service::UnaryService<risingwave_pb::stream_service::BarrierCompleteRequest>>::call::{{closure}}
             at ./src/prost/src/stream_service.rs:941:67
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  31: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  32: tonic::server::grpc::Grpc<T>::unary::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.8.0/src/server/grpc.rs:166:27
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  34: <risingwave_pb::stream_service::stream_service_server::StreamServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
             at ./src/prost/src/stream_service.rs:958:58
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
 ... omitted ...
```

Full logs here: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9524115/risingwave-log.tgz)

### To Reproduce

1. Start the cluster with `./risedev d full`
2. Create sources:

```sql
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

3. Create MView:

```sql
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

4. Wait for 1 hour

### Additional context

Full logs here: [risingwave-log.tgz](https://github.com/risingwavelabs/risingwave/files/9524115/risingwave-log.tgz)

**Comment by fuyufjh** [comment]
@xxhZs Please take a look and feel free to reassign to others

**Comment by hzxa21** [comment]
```
2022-09-08T03:58:44.429081Z  INFO risingwave_storage::hummock::local_version_manager: running flush task in epoch 2973640643510272 of size 3518221568
thread 'risingwave-main' panicked at 'when sync an epoch, there should not be any uploading task', src/storage/src/hummock/shared_buffer/mod.rs:290:9
stack backtrace:
```

We have accumulated 3518221568B = 3.27GB data within one epoch which triggers spill to disk. @wenym1 please also take a look.

The log shows that checkpoint interval is 250ms so I wonder how we get to this state...

**Comment by wenym1** [comment]
The error seems to be caused by `sync_shared_buffer_le_epoch` introduced for supporting checkpoint barrier decouple.

Our current sync logic is 
```
fn sync(epoch) {
    let epochs = ... // all epochs less then `epoch` in shared buffer
    let flush_join_handle = ... // get all join handles of flush task for `epochs`
    flush_join_handle.await;
    
    // Panics here
    sync_shared_buffer_le_epoch(epoch) // move all data in shared buffers whose epoch are less than `epoch` to 
    sync_uncommitted_data and starts sync
}
```

Let's say we have ten epochs 1 to 10, and we call sync at 5 and 10 concurrently, and we have a flush task for data in epoch 3.

`sync(5)` will take the flush_join_handle of epoch 1 to 5, and wait for the flush join handle of epoch 3. `sync(10)` only takes the flush_join_handle of epoch 6 to 10, and have nothing to wait and will progress to `sync_shared_buffer_le_epoch(10)`, which turns the shared buffer of all epochs less than 10, which are all epochs from 1 to 10. However, the data in epoch 3 is still in a flush task, which is unexpected and makes our code panic.

The bug will happen when we have an ongoing flush task and concurrent sync. Therefore, it can be more easily reproduced if we turn the flush threshold to a extremely small value (e.g. 1MB).

I will fix the bug by turning `sync_shared_buffer_le_epoch` into syncing some specified epochs
