### ISSUE TITLE
bug: `Materialize` double insert in tpch q15

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5277]
https://buildkite.com/risingwavelabs/main/builds/1574#01832fbc-fe3e-41ae-8e95-fd685fe09fd1

```
thread 'risingwave-streaming-actor' panicked at 'invalid flush status: double insert [75, 0, 128, 0, 0, 4, 0, 128, 0, 0, 4] -> [1, 4, 0, 0, 0, 1, 18, 0, 0, 0, 83, 117, 112, 112, 108, 105, 101, 114, 35, 48, 48, 48, 48, 48, 48, 48, 48, 52, 1, 25, 0, 0, 0, 66, 107, 55, 97, 104, 52, 67, 75, 56, 83, 89, 81, 84, 101, 112, 69, 109, 118, 77, 107, 107, 103, 77, 119, 103, 1, 15, 0, 0, 0, 50, 53, 45, 56, 52, 51, 45, 55, 56, 55, 45, 55, 52, 55, 57, 1, 0, 0, 4, 0, 98, 25, 56, 25, 2, 0, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0]', src/storage/src/table/streaming_table/mem_table.rs:69:21
stack backtrace:
2022-09-12T03:42:38.947750Z DEBUG risingwave_stream::task::stream_manager: drop actors actors=[6510, 6511, 6512, 6513, 6522, 6523, 6524, 6525, 6534, 6535, 6536, 6537, 6546, 6547, 6548, 6549]
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::mem_table::MemTable::insert
             at ./src/storage/src/table/streaming_table/mem_table.rs:69:21
   3: risingwave_storage::table::streaming_table::state_table::StateTable<S>::write_chunk
             at ./src/storage/src/table/streaming_table/state_table.rs:446:58
   4: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:119:21
   5: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   6: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
   9: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  10: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  11: risingwave_stream::executor::wrapper::trace::trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:57:60
  12: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  13: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  14: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  15: risingwave_stream::executor::wrapper::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/wrapper/trace.rs:120:70
```

```
b"\x01\x04\0\0\0\x01\x12\0\0\0Supplier#000000004\x01\x19\0\0\0Bk7ah4CK8SYQTepEmvMkkgMwg\x01\x0f\0\0\025-843-787-7479\x01\0\0\x04\0b\x198\x19\x02\0\0\0\0\0\0\0\x01\x04\0\0\0"
```

**Comment by fuyufjh** [comment]
The most special part of Q15 is that the (original) query uses CTE:

```sql
with revenue0 (supplier_no, total_revenue) as (
  select
    l_suppkey,
    sum(l_extendedprice * (1 - l_discount))
  from
    lineitem
  where
    l_shipdate >= date '1993-01-01'
    and l_shipdate < date '1993-01-01' + interval '3' month
  group by
    l_suppkey
)
select
  s_suppkey,
  s_name,
  s_address,
  s_phone,
  total_revenue
from
  supplier,
  revenue0
where
  s_suppkey = supplier_no
  and total_revenue = (
    select
      max(total_revenue)
    from
      revenue0
  )
order by
  s_suppkey;
```

While, very interesting, our e2e test case was adapted by rewriting CTE into normal subquery:

https://github.com/risingwavelabs/risingwave/blob/1a0fb0287174ac0565db45e23fb8f03fea642ba1/e2e_test/streaming/tpch/views/q15.slt.part#L3-L43

And the plan is:

```
StreamMaterialize { columns: [s_suppkey, s_name, s_address, s_phone, total_revenue, lineitem.l_suppkey(hidden)], pk_columns: [lineitem.l_suppkey], order_descs: [s_suppkey, lineitem.l_suppkey] }
  StreamExchange { dist: HashShard(lineitem.l_suppkey) }
    StreamHashJoin { type: Inner, predicate: sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))) = max(max(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))))), output: [supplier.s_suppkey, supplier.s_name, supplier.s_address, supplier.s_phone, sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))), lineitem.l_suppkey] }
      StreamExchange { dist: HashShard(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))) }
        StreamHashJoin { type: Inner, predicate: supplier.s_suppkey = lineitem.l_suppkey, output: [supplier.s_suppkey, supplier.s_name, supplier.s_address, supplier.s_phone, sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))), lineitem.l_suppkey] }
          StreamExchange { dist: HashShard(supplier.s_suppkey) }
            StreamTableScan { table: supplier, columns: [supplier.s_suppkey, supplier.s_name, supplier.s_address, supplier.s_phone], pk: [supplier.s_suppkey], distribution: UpstreamHashShard(supplier.s_suppkey) }
          StreamProject { exprs: [lineitem.l_suppkey, sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))] }
            StreamHashAgg { group_key: [lineitem.l_suppkey], aggs: [count, sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))] }
              StreamExchange { dist: HashShard(lineitem.l_suppkey) }
                StreamProject { exprs: [lineitem.l_suppkey, (lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)), lineitem.l_orderkey, lineitem.l_linenumber] }
                  StreamFilter { predicate: (lineitem.l_shipdate >= '1993-01-01':Varchar::Date) AND (lineitem.l_shipdate < ('1993-01-01':Varchar::Date + '3 mons 00:00:00':Interval)) }
                    StreamTableScan { table: lineitem, columns: [lineitem.l_suppkey, lineitem.l_extendedprice, lineitem.l_discount, lineitem.l_orderkey, lineitem.l_linenumber, lineitem.l_shipdate], pk: [lineitem.l_orderkey, lineitem.l_linenumber], distribution: UpstreamHashShard(lineitem.l_orderkey, lineitem.l_linenumber) }
      StreamExchange { dist: HashShard(max(max(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))))) }
        StreamProject { exprs: [max(max(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))))] }
          StreamGlobalSimpleAgg { aggs: [sum(count), max(max(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))))] }
            StreamExchange { dist: Single }
              StreamHashAgg { group_key: [Vnode(lineitem.l_suppkey)], aggs: [count, max(sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))))] }
                StreamProject { exprs: [sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))), lineitem.l_suppkey, Vnode(lineitem.l_suppkey)] }
                  StreamProject { exprs: [sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount))), lineitem.l_suppkey] }
                    StreamHashAgg { group_key: [lineitem.l_suppkey], aggs: [count, sum((lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)))] }
                      StreamExchange { dist: HashShard(lineitem.l_suppkey) }
                        StreamProject { exprs: [lineitem.l_suppkey, (lineitem.l_extendedprice * (1:Int32 - lineitem.l_discount)), lineitem.l_orderkey, lineitem.l_linenumber] }
                          StreamFilter { predicate: (lineitem.l_shipdate >= '1993-01-01':Varchar::Date) AND (lineitem.l_shipdate < ('1993-01-01':Varchar::Date + '3 mons 00:00:00':Interval)) }
                            StreamTableScan { table: lineitem, columns: [lineitem.l_suppkey, lineitem.l_extendedprice, lineitem.l_discount, lineitem.l_orderkey, lineitem.l_linenumber, lineitem.l_shipdate], pk: [lineitem.l_orderkey, lineitem.l_linenumber], distribution: UpstreamHashShard(lineitem.l_orderkey, lineitem.l_linenumber) }
```

Just my guess, could it be related to https://github.com/risingwavelabs/risingwave/issues/4618 ?

**Comment by BugenZhao** [comment]
> Just my guess, could it be related to https://github.com/risingwavelabs/risingwave/issues/4618 ?

I think the Join operator (at least under the current implementation) is unaware of the relationship or synchronization of the two sides, or self-join with rearranged barrier may also lead to some problems.

**Comment by BugenZhao** [comment]
Another occurrence:
https://buildkite.com/risingwavelabs/pull-request/builds/8351#0183377a-2214-4640-baf8-00380d7971bd

**Comment by BugenZhao** [comment]
```
thread 'risingwave-streaming-actor' panicked at 
'mem-table operation conflicts! 
table_id: 2354, 
vnode: 75, 
key: Row([Some(Int32(4)), Some(Int32(4))]), 
prev: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(647416.3417))), Some(Int32(4))])), 
 new: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(901304.1506))), Some(Int32(4))]))', 

/risingwave/src/storage/src/table/streaming_table/state_table.rs:412:17
```

https://buildkite.com/risingwavelabs/main/builds/1607#01833a4d-c45f-4a7d-a990-96aaf072cb5d

**Comment by fuyufjh** [comment]
> ```
> thread 'risingwave-streaming-actor' panicked at 
> 'mem-table operation conflicts! 
> table_id: 2354, 
> vnode: 75, 
> key: Row([Some(Int32(4)), Some(Int32(4))]), 
> prev: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(647416.3417))), Some(Int32(4))])), 
>  new: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(901304.1506))), Some(Int32(4))]))', 
> 
> /risingwave/src/storage/src/table/streaming_table/state_table.rs:412:17
> ```
> 
> https://buildkite.com/risingwavelabs/main/builds/1607#01833a4d-c45f-4a7d-a990-96aaf072cb5d


```
prev: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(647416.3417))), Some(Int32(4))])), 
 new: Insert(Row([Some(Int32(4)), Some(Utf8("Supplier#000000004")), Some(Utf8("Bk7ah4CK8SYQTepEmvMkkgMwg")), Some(Utf8("25-843-787-7479")), Some(Decimal(Normalized(901304.1506))), Some(Int32(4))]))', 
```
Interesting. The prev row is incorrect: the total revenue should be `901304.1506`

**Comment by fuyufjh** [comment]
Could it be caused by the tricky problem of Join's stream key? https://singularity-data.quip.com/3lUJAQMthect/RFC-Streamkey-instead-pk  cc. @st1page
