### ISSUE TITLE
bug(storage): panic: assertion failed: `(left matches right)`

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5353]
### Describe the bug

```
thread 'risingwave-main' panicked at 'assertion failed: `(left matches right)`
  left: `Synced([(2, SstableInfo { id: 16672, key_range: Some(KeyRange { left: [116, 0, 0, 3, 239, 0, 0, 128, 0, 0, 0, 1, 19, 189, 139, 0, 130, 173, 59, 174, 92, 128, 0, 69, 255, 245, 75, 17, 70, 212, 255, 255], right: [116, 0, 0, 3, 247, 56, 45, 54, 255, 245, 75, 17, 70, 212, 255, 255], inf: false }), file_size: 639273, table_ids: [1007, 1015], meta_offset: 627473 }), (3, SstableInfo { id: 16671, key_range: Some(KeyRange { left: [116, 0, 0, 3, 236, 0, 0, 130, 173, 59, 99, 78, 140, 0, 52, 0, 130, 173, 59, 110, 1, 76, 0, 52, 0, 130, 173, 59, 174, 92, 128, 0, 52, 255, 245, 75, 17, 70, 212, 255, 255], right: [116, 0, 0, 3, 236, 255, 0, 130, 173, 59, 117, 131, 192, 3, 251, 0, 130, 173, 59, 111, 114, 64, 3, 251, 0, 130, 173, 59, 174, 86, 128, 3, 251, 255, 245, 75, 17, 70, 212, 255, 255], inf: false }), file_size: 362313, table_ids: [1004], meta_offset: 357645 })])`,
 right: `SyncUncommittedData::Syncing(_)`', src/storage/src/hummock/local_version.rs:206:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_matches_failed
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:200:5
   4: risingwave_storage::hummock::local_version::LocalVersion::add_sync_state
             at ./src/storage/src/hummock/local_version.rs:206:17
   5: risingwave_storage::hummock::local_version_manager::LocalVersionManager::run_sync_upload_task::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:610:9
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   7: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer_le_epoch::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:585:71
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   9: risingwave_storage::hummock::local_version_manager::LocalVersionManager::sync_shared_buffer::{{closure}}
             at ./src/storage/src/hummock/local_version_manager.rs:514:69
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  11: risingwave_storage::hummock::state_store::<impl risingwave_storage::store::StateStore for risingwave_storage::hummock::HummockStorage>::sync::{{closure}}
             at ./src/storage/src/hummock/state_store.rs:604:43
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  13: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  14: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  15: <risingwave_storage::monitor::monitored_store::MonitoredStateStore<S> as risingwave_storage::store::StateStore>::sync::{{closure}}
             at ./src/storage/src/monitor/monitored_store.rs:251:43
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  17: risingwave_stream::task::stream_manager::LocalStreamManager::sync_epoch::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:242:36
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  19: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  20: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  21: <risingwave_compute::rpc::service::stream_service::StreamServiceImpl as risingwave_pb::stream_service::stream_service_server::StreamService>::barrier_complete::{{closure}}
             at ./src/compute/src/rpc/service/stream_service.rs:174:75
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  24: <<risingwave_pb::stream_service::stream_service_server::StreamServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::BarrierCompleteSvc<T> as tonic::server::service::UnaryService<risingwave_pb::stream_service::BarrierCompleteRequest>>::call::{{closure}}
             at ./src/prost/src/stream_service.rs:943:67

```

### To Reproduce

Deploy a full cluster and run

```
CREATE SOURCE person (
    “id” BIGINT,
    “name” VARCHAR,
    “email_address” VARCHAR,
    “credit_card” VARCHAR,
    “city” VARCHAR,
    “state” VARCHAR,
    “date_time” TIMESTAMP,
    “extra” VARCHAR
) with (
    connector = ‘nexmark’,
    nexmark.table.type = ‘Person’,
    nexmark.split.num = ‘8’,
    nexmark.min.event.gap.in.ns = ‘0’
) ROW FORMAT JSON;
CREATE SOURCE auction (
    “id” BIGINT,
    “item_name” VARCHAR,
    “description” VARCHAR,
    “initial_bid” BIGINT,
    “reserve” BIGINT,
    “date_time” TIMESTAMP,
    “expires” TIMESTAMP,
    “seller” BIGINT,
    “category” BIGINT,
    “extra” VARCHAR
) with (
    connector = ‘nexmark’,
    nexmark.table.type = ‘Auction’,
    nexmark.split.num = ‘8’,
    nexmark.min.event.gap.in.ns = ‘0’
) ROW FORMAT JSON;
CREATE SOURCE bid (
    “auction” BIGINT,
    “bidder” BIGINT,
    “price” BIGINT,
    “channel” VARCHAR,
    “url” VARCHAR,
    “date_time” TIMESTAMP,
    “extra” VARCHAR
) with (
    connector = ‘nexmark’,
    nexmark.table.type = ‘Bid’,
    nexmark.split.num = ‘8’,
    nexmark.min.event.gap.in.ns = ‘0’
) ROW FORMAT JSON;

create materialized view mv1 as select 1 c from auction a1, auction a2, auction a3 where a1.id = a2.id and a1.id = a3.id;
```

### Additional context

[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/9572220/compute-node-5688.log)

**Comment by fuyufjh** [comment]
@xxhZs  Please take a look.

**Comment by xxhZs** [comment]
do we have the meta logs?

**Comment by fuyufjh** [comment]
> do we have the meta logs?

Sorry, it was cleaned...

**Comment by wenym1** [comment]
Seems that the SQL text in the issue description has something wrong with the single and double quote and does not work on my Mac.

The following SQL will work
```
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

create materialized view mv1 as select 1 c from auction a1, auction a2, auction a3 where a1.id = a2.id and a1.id = a3.id;
```

**Comment by wenym1** [comment]
The bug seems to happen when recovery happened.

I randomly injected some object store error in the sync task to trigger the recovery. The following error happened.
```
thread 'risingwave-streaming-actor' panicked at 'write epoch must greater than max current epoch, write epoch3014222016741376, sealed epoch3014222016741376', src/storage/src/hummock/local_version_manager.rs:424:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::local_version_manager::LocalVersionManager::write_shared_buffer_inner
             at ./src/storage/src/hummock/local_version_manager.rs:424:9
```

Seems that we didn't reset the max_sync_epoch and sealed_epoch when we reset the local version.

**Comment by xxhZs** [comment]
> The bug seems to happen when recovery happened.
> 
> I randomly injected some object store error in the sync task to trigger the recovery. The following error happened.
> 
> ```
> thread 'risingwave-streaming-actor' panicked at 'write epoch must greater than max current epoch, write epoch3014222016741376, sealed epoch3014222016741376', src/storage/src/hummock/local_version_manager.rs:424:9
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
>    2: risingwave_storage::hummock::local_version_manager::LocalVersionManager::write_shared_buffer_inner
>              at ./src/storage/src/hummock/local_version_manager.rs:424:9
> ```
> 
> Seems that we didn't reset the max_sync_epoch and sealed_epoch when we reset the local version.

maybe our stop actor epoch is wrong. And this bug: we clear_shred_buffer will remove all sync_uncommitted_data, If we have a sync task, we will err

**Comment by wenym1** [comment]
The problems seems to be caused by that we didn't wait for the on-flight sync request to finish before we send the stop all actor request. When we have an on-flight unfinished sync, and we then clear the shared buffer, the on-flight sync will panic the same way as the issue description when it finished local compaction and try to report the `Synced` data.

**Comment by wenym1** [comment]
> The bug seems to happen when recovery happened.

> I randomly injected some object store error in the sync task to trigger the recovery. The following error happened.
```
thread 'risingwave-streaming-actor' panicked at 'write epoch must greater than max current epoch, write epoch3014222016741376, sealed epoch3014222016741376', src/storage/src/hummock/local_version_manager.rs:424:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::hummock::local_version_manager::LocalVersionManager::write_shared_buffer_inner
             at ./src/storage/src/hummock/local_version_manager.rs:424:9
```

> Seems that we didn't reset the max_sync_epoch and sealed_epoch when we reset the local version.
