### ISSUE TITLE
bug: panicked at 'index out of bounds: the len is 1 but the index is 1', src/meta/src/barrier/recovery.rs:191:50

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#5366]
### Describe the bug

After killing all CNs and starting them up again, meta node panicked:
```
thread 'risingwave-main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/meta/src/barrier/recovery.rs:191:50
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/slice/index.rs:242:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/mod.rs:2627:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/mod.rs:2627:9
   6: risingwave_meta::barrier::recovery::<impl risingwave_meta::barrier::GlobalBarrierManager<S>>::get_migrate_map_plan::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/recovery.rs:191:50
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: risingwave_meta::barrier::recovery::<impl risingwave_meta::barrier::GlobalBarrierManager<S>>::migrate_actors::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/recovery.rs:225:88
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: risingwave_meta::barrier::recovery::<impl risingwave_meta::barrier::GlobalBarrierManager<S>>::recovery::{{closure}}::{{closure}}::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/recovery.rs:85:54
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: tokio_retry::future::RetryState<A>::poll
             at ./home/ubuntu/.cargo/git/checkouts/rust-tokio-retry-38aa0853644639a4/95e2fd3/src/future.rs:27:73
  13: <tokio_retry::future::RetryIf<I,A,C> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/git/checkouts/rust-tokio-retry-38aa0853644639a4/95e2fd3/src/future.rs:156:15
  14: <tokio_retry::future::Retry<I,A> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/git/checkouts/rust-tokio-retry-38aa0853644639a4/95e2fd3/src/future.rs:76:9
  15: risingwave_meta::barrier::recovery::<impl risingwave_meta::barrier::GlobalBarrierManager<S>>::recovery::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/recovery.rs:151:11
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  17: risingwave_meta::barrier::GlobalBarrierManager<S>::do_recovery::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/mod.rs:792:41
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  19: risingwave_meta::barrier::GlobalBarrierManager<S>::barrier_complete_and_commit::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/mod.rs:741:73
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  21: risingwave_meta::barrier::GlobalBarrierManager<S>::run::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/mod.rs:552:22
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  23: risingwave_meta::barrier::GlobalBarrierManager<S>::start::{{closure}}::{{closure}}
             at ./ebs/risingwave/src/meta/src/barrier/mod.rs:500:45
  24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  25: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  26: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  27: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  28: tokio::runtime::task::core::CoreStage<T>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  29: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  30: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  31: std::panicking::try::do_call
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  32: std::panicking::try
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  33: std::panic::catch_unwind
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  34: tokio::runtime::task::harness::poll_future
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  35: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  36: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  37: tokio::runtime::task::raw::RawTask::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  38: tokio::runtime::task::LocalNotified<S>::run
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:381:9
  39: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:435:13
  40: tokio::coop::with_budget::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
  41: std::thread::local::LocalKey<T>::try_with
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  42: std::thread::local::LocalKey<T>::with
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  43: tokio::coop::with_budget
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
  44: tokio::coop::budget
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
  45: tokio::runtime::thread_pool::worker::Context::run_task
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
  46: tokio::runtime::thread_pool::worker::Context::run
  47: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:386:17
  48: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
  49: tokio::runtime::thread_pool::worker::run
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:383:5
  50: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:362:45
  51: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/task.rs:42:21
  52: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  53: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  54: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  55: tokio::runtime::task::core::CoreStage<T>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  56: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  57: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  58: std::panicking::try::do_call
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  59: std::panicking::try
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  60: std::panic::catch_unwind
             at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  61: tokio::runtime::task::harness::poll_future
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  62: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  63: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  64: tokio::runtime::task::raw::RawTask::poll
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  65: tokio::runtime::task::UnownedTask<S>::run
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:418:9
  66: tokio::runtime::blocking::pool::Task::run
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:91:9
  67: tokio::runtime::blocking::pool::Inner::run
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:325:17
  68: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

0. Use risedev-bench to start a 3-cn cluster.
1. Create sources:

```sql
CREATE SOURCE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;

CREATE SOURCE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

2. Create MView:

```sql
CREATE MATERIALIZED VIEW nexmark_q7
AS
SELECT
    B.auction,
    B.price,
    B.bidder,
    B.date_time
from
    bid B
    JOIN (
        SELECT
            MAX(price) AS maxprice,
            window_end as date_time
        FROM
            TUMBLE(bid, date_time, INTERVAL '10' SECOND)
        GROUP BY
            window_end
    ) B1 ON B.price = B1.maxprice
WHERE
    B.date_time BETWEEN B1.date_time - INTERVAL '10' SECOND
    AND B1.date_time;
```

3. Wait for 40mins

4. Log onto the CN ec2 instances and run the following command to kill the CN container on the corresponding ec2 instance:
```
docker container stop compute-node-0
docker container stop compute-node-1
docker container stop compute-node-2
```

5. Wait for 5mins and run the following commands to restart the CN container on the corresponding ec2 instance:
```
docker container start compute-node-0
docker container start compute-node-1
docker container start compute-node-2
```

### Additional context

commit: `812775fada572db6b7b061420d31e2eca7509540`

[meta.log](https://github.com/risingwavelabs/risingwave/files/9574132/meta.log)

Meta log is too large so I only include the last 200 lines here.

Just ping me if full log is needed.

**Comment by BugenZhao** [comment]
Looks like we should also early exit in the inner loop if compute nodes are sufficient for recovery.

https://github.com/risingwavelabs/risingwave/blob/6a18a947ea8101a12725f65a9e41f0f28091cdc9/src/meta/src/barrier/recovery.rs#L190-L197
