### ISSUE TITLE
bug(frontend): panic when calculating with different data types

### ISSUE THREAD

**Issue by nanderstabel** [risingwavelabs/risingwave#5563]
### Describe the bug

Panic when calculating with more than 2 different datatypes.

This results in a panic: `select 100.00 + 1.0::float + 1;`

These do not:
```
dev=> select 100.00 + 1.0::float;
 ?column? 
----------
   101.00
(1 row)

dev=> select 1.0::float + 1;
 ?column? 
----------
        2
(1 row)
```

### To Reproduce

```
select 100.00 + 1.0::float + 1;
```

results in:

```
2022-09-26T15:04:02.779316Z ERROR pgwire::pg_protocol: Error: ReadMsgError: unexpected end of file
thread 'risingwave-main' panicked at 'cannot convert ArrayImpl::Decimal to concrete type Float64', src/common/src/array/mod.rs:398:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_common::array::<impl core::convert::From<&risingwave_common::array::ArrayImpl> for &risingwave_common::array::primitive_array::PrimitiveArray<risingwave_common::types::ordered_float::OrderedFloat<f64>>>::from
             at ./src/common/src/array/mod.rs:374:44
   3: <T as core::convert::Into<U>>::into
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/convert/mod.rs:550:9
   4: <risingwave_expr::expr::template::BinaryExpression<IA1,IA2,OA,F> as risingwave_expr::expr::Expression>::eval
             at ./src/expr/src/expr/template.rs:36:54
   5: risingwave_batch::executor::project::ProjectExecutor::do_execute::{{closure}}::{{closure}}
             at ./src/batch/src/executor/project.rs:60:29
   6: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/map.rs:91:28
   7: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/traits/iterator.rs:2238:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/map.rs:117:9
   9: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/mod.rs:191:9
  10: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/mod.rs:174:9
  11: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/mod.rs:174:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/spec_from_iter.rs:33:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/vec/mod.rs:2648:9
  15: core::iter::traits::iterator::Iterator::collect
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:2101:49
  16: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:2101:49
  17: core::iter::adapters::try_process
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/adapters/mod.rs:160:17
  18: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:2101:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/iter/traits/iterator.rs:1836:9
  20: itertools::Itertools::try_collect
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/lib.rs:2014:9
  21: risingwave_batch::executor::project::ProjectExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/project.rs:57:39
  22: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  23: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  24: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  25: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  26: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  27: risingwave_batch::executor::trace::TraceExecutor::do_execute::{{closure}}
             at ./src/batch/src/executor/trace.rs:67:69
  28: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  29: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  30: risingwave_frontend::scheduler::local::LocalQueryExecution::run_inner::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:71:5
  31: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  32: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  33: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  34: <&mut S as futures_core::stream::Stream>::poll_next
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:104:9
  35: <futures_async_stream::stream::next::Next<S> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:386:17
  36: risingwave_frontend::scheduler::local::LocalQueryExecution::collect_rows::{{closure}}
             at ./src/frontend/src/scheduler/local.rs:105:9
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  38: risingwave_frontend::handler::query::local_execute::{{closure}}
             at ./src/frontend/src/handler/query.rs:198:53
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  40: risingwave_frontend::handler::query::handle_query::{{closure}}
             at ./src/frontend/src/handler/query.rs:64:54
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  42: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:161:81
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  44: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session>::run_statement::{{closure}}
             at ./src/frontend/src/session.rs:671:50
  45: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  46: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  47: pgwire::pg_protocol::PgProtocol<S,SM>::process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:287:39
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  49: pgwire::pg_protocol::PgProtocol<S,SM>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:171:87
  50: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  51: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:105:38
  52: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  53: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:101:26
  54: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  55: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:99:46
  56: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  57: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  58: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  59: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  60: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  61: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  62: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  63: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  64: __rust_try
  65: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  66: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  67: tokio::runtime::task::harness::poll_future
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  68: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  69: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  70: tokio::runtime::task::raw::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:194:5
  71: tokio::runtime::task::raw::RawTask::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  72: tokio::runtime::task::LocalNotified<S>::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:385:9
  73: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:444:21
  74: tokio::coop::with_budget::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:102:9
  75: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  76: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  77: tokio::coop::with_budget
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:95:5
  78: tokio::coop::budget
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:72:5
  79: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:420:9
  80: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:387:24
  81: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:372:17
  82: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/macros/scoped_tls.rs:61:9
  83: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:369:5
  84: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:348:45
  85: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/task.rs:42:21
  86: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  87: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  88: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  89: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  90: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/nstabel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  91: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  92: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  93: __rust_try
  94: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
```

### Expected behavior

```
dev=> select 100.00 + 1.0::float + 1;
 ?column? 
----------
   102.00
(1 row)

```

**Comment by neverchanje** [comment]
A little surprised that sqlsmith didn't ever find this bug.
