### ISSUE TITLE
bug: access wrong vnode

### ISSUE THREAD

**Issue by zwang28** [risingwavelabs/risingwave#5614]
### Describe the bug

```
compute-node-0  | thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'vnode 147 should not be accessed by this tablevnode 147 should not be accessed by this table', ', src/storage/src/table/mod.rssrc/storage/src/table/mod.rs::152152::55
compute-node-0  | 
compute-node-0  | stack backtrace:
compute-node-0  |    0: rust_begin_unwind
compute-node-0  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
compute-node-0  |    1: core::panicking::panic_fmt
compute-node-0  |              at ./rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
compute-node-0  |    2: risingwave_storage::table::check_vnode_is_set
compute-node-0  |              at ./ebs/risingwave/src/storage/src/table/mod.rs:152:5
compute-node-0  |    3: risingwave_storage::table::compute_vnode
compute-node-0  |              at ./ebs/risingwave/src/storage/src/table/mod.rs:119:9
compute-node-0  |    4: risingwave_storage::table::streaming_table::state_table::StateTable<S>::update
compute-node-0  |              at ./ebs/risingwave/src/storage/src/table/streaming_table/state_table.rs:491:67
compute-node-0  |    5: risingwave_stream::executor::managed_state::join::JoinHashMap<K,S>::inc_degree
compute-node-0  |              at ./ebs/risingwave/src/stream/src/executor/managed_state/join/mod.rs:517:9
compute-node-0  |    6: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::eq_join_oneside::{{closure}}
compute-node-0  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:832:37
compute-node-0  |    7: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
compute-node-0  |              at ./home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
compute-node-0  |    8: risingwave_stream::executor::hash_join::HashJoinExecutor<K,S,_>::into_stream::{{closure}}
compute-node-0  |              at ./ebs/risingwave/src/stream/src/executor/hash_join.rs:600:5
```

### To Reproduce

./bin/bench --type=tpch-std --qps=800000 --scale 80.0 --query 20 --partition 12
$(cat ~/risingwave-deploy/tpch-bench-args-kafka)
$(cat ~/risingwave-deploy/tpch-bench-args-frontend)
--prepare-sql ./assets/data/create_materialized_source.sql

I use commit 9a4ac60d and it can be reproduced every time.

### Expected behavior

No panic.

### Additional context
[compute-0.log](https://github.com/risingwavelabs/risingwave/files/9662913/compute-0.log)
[compute-1.log](https://github.com/risingwavelabs/risingwave/files/9662914/compute-1.log)
[compute-2.log](https://github.com/risingwavelabs/risingwave/files/9662915/compute-2.log)
[meta.log](https://github.com/risingwavelabs/risingwave/files/9662916/meta.log)

**Comment by zwang28** [comment]
Caused by tiered cached, see https://github.com/risingwavelabs/risingwave/issues/5587#issuecomment-1263486972
