### ISSUE TITLE
Kernel crashes on connect

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#5953]
### Describe the bug

**Stack trace:** 

```
2022-10-20T13:36:11.959923Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    2,
).
2022-10-20T13:36:11.960046Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    3,
).
2022-10-20T13:36:11.960098Z  WARN risingwave_meta::hummock::compaction_scheduler: Failed to get compaction task: InvalidCompactionGroup(
    2,
).
2022-10-20T13:36:11.960139Z  INFO risingwave_common_service::metrics_manager: Prometheus listener for Prometheus is set up on http://127.0.0.1:1222
thread 'risingwave-main' panicked at 'Unable to set up a ssl connection, reason: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:1544:SSL alert number 48', /Users/janmensch/Documents/github/risingwave/src/utils/pgwire/src/pg_protocol.rs:631:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: pgwire::pg_protocol::PgStream<S>::ssl::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:631:13
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: pgwire::pg_protocol::Conn<S>::ssl::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:693:51
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process_ssl_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:233:54
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:203:53
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:157:38
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:153:26
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  14: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:116:46
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  17: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  18: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  19: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  20: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  23: ___rust_try
  24: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  25: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  26: tokio::runtime::task::harness::poll_future
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  27: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  28: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  29: tokio::runtime::task::raw::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:194:5
  30: tokio::runtime::task::raw::RawTask::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  31: tokio::runtime::task::LocalNotified<S>::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:385:9
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:421:13
  33: tokio::coop::with_budget::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:102:9
  34: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  35: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  36: tokio::coop::with_budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:95:5
  37: tokio::coop::budget
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:72:5
  38: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:420:9
  39: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:387:24
  40: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:372:17
  41: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/macros/scoped_tls.rs:61:9
  42: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:369:5
  43: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:348:45
  44: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/task.rs:42:21
  45: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  46: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  47: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  48: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  49: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  50: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  51: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  52: ___rust_try
  53: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  54: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  55: tokio::runtime::task::harness::poll_future
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  56: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  57: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  58: tokio::runtime::task::raw::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:194:5
  59: tokio::runtime::task::raw::RawTask::poll
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  60: tokio::runtime::task::UnownedTask<S>::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:422:9
  61: tokio::runtime::blocking::pool::Task::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:111:9
  62: tokio::runtime::blocking::pool::Inner::run
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:346:17
  63: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/janmensch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:321:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/var/folders/fj/dmw16z3n01l9dj2bmx_zc0hc0000gn/T/fsio_8bqcN3ZCuU.sh: line 9: 10080 Abort trap: 6           RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin risingwave --profile "${RISINGWAVE_BUILD_PROFILE}"
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
```

### To Reproduce

I am using the latest `main` at commit `58f07ccb7645e2f0328d4b395f78e8a63fc4155c`

Run `risedev p` and then connect via `psql -h localhost -p 4566 -d dev -U root`

### Additional context

```
cargo --version 
cargo 1.64.0-nightly (85b500cca 2022-07-24)

openssl version
LibreSSL 2.8.3

psql -V
psql (PostgreSQL) 14.5 (Homebrew)
# problem persists after upgrading to 14.5.5
```

Connecting against a prod instance also fails. Seems to be connected to my SSL setup? 

```
psql "postgresql://Jan:@canary-useast2-eks-a.risingwave.cloud:4566/dev?sslmode=require&options=--tenant%3Drwc-998-test"
psql: error: connection to server at "canary-useast2-eks-a.risingwave.cloud" (3.142.128.2), port 4566 failed: SSL error: certificate verify failed
```

**Comment by BowenXiao1999** [comment]
Ported some conclusions from slack to end this thread:

1. Use `psql "port=4566 host=localhost user=root dbname=dev sslmode=disable"` 
2. remove ~/.postgresql/root.crt. With this, the sql client may require verify-ca, which will reject a self-signed CA. Discovered by @mikechesterwang.
3. We should not panic here but reject this connection here. But still, user can not login to pg session and start querying. Reject the request forever is expected.

**Comment by BowenXiao1999** [comment]
If we do not encounter the same issue, we may temporailly close this after #5920
