### ISSUE TITLE
Duplicate primary keys cause panic.

### ISSUE THREAD

**Issue by iswade** [risingwavelabs/risingwave#6239]
### Describe the bug

Create a table with primary key, then insert duplicate tuples with duplicate keys.
```sql
create table seq(a int, b int primary key);
insert into seq values(1, 1), (1, 2), (2, 1), (2, 2), (2, 3);
```

cause the server panic:
```
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'mem-table operation conflicts! table_id: 1008, vnode: 121, key: Row([Some(Int32(1))]), prev: Insert(Ok(Row([Some(Int32(1)), Some(Int32(1))]))), new: Insert(Ok(Row([Some(Int32(1)), Some(Int32(2))])))mem-table operation conflicts! table_id: 1008, vnode: 151, key: Row([Some(Int32(2))]), prev: Insert(Ok(Row([Some(Int32(2)), Some(Int32(3))]))), new: Insert(Ok(Row([Some(Int32(2)), Some(Int32(4))])))', ', /mnt/src/storage/src/table/streaming_table/state_table.rs/mnt/src/storage/src/table/streaming_table/state_table.rs::440440::1717

stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::streaming_table::state_table::StateTable<S>::handle_mem_table_error
             at /mnt/src/storage/src/table/streaming_table/state_table.rs:440:17
   3: risingwave_storage::table::streaming_table::state_table::StateTable<S>::write_chunk::{{closure}}
             at /mnt/src/storage/src/table/streaming_table/state_table.rs:526:45
   4: core::result::Result<T,E>::unwrap_or_else
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:1493:23
   5: risingwave_storage::table::streaming_table::state_table::StateTable<S>::write_chunk
             at /mnt/src/storage/src/table/streaming_table/state_table.rs:522:25
   6: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at /mnt/src/stream/src/executor/mview/materialize.rs:131:21
   7: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/mod.rs:1626:9
  11: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/next.rs:32:9
  12: risingwave_stream::executor::wrapper::trace::metrics::{{closure}}
             at /mnt/src/stream/src/executor/wrapper/trace.rs:83:44
  13: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  14: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  15: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/future/future/fuse.rs:86:37
  16: risingwave_stream::executor::wrapper::trace::stack_trace::{{closure}}
             at /mnt/src/stream/src/executor/wrapper/trace.rs:117:70
  17: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  18: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
  19: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/mod.rs:1626:9
  20: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/next.rs:32:9
  21: risingwave_stream::executor::wrapper::epoch_check::epoch_check::{{closure}}
             at /mnt/src/stream/src/executor/wrapper/epoch_check.rs:31:44
  22: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  24: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
  25: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at /mnt/src/stream/src/executor/dispatch.rs:259:9
  26: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  27: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
  28: <&mut S as futures_core::stream::Stream>::poll_next
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:104:9
  29: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.9/src/stream_ext/next.rs:42:9
  30: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  31: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
  32: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/future/future/fuse.rs:86:37
  33: risingwave_stream::executor::actor::Actor<C>::run_consumer::{{closure}}
             at /mnt/src/stream/src/executor/actor.rs:129:16
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  35: <tokio::future::maybe_done::MaybeDone<Fut> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/future/maybe_done.rs:68:48
  36: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/macros/join.rs:116:24
  37: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/future/poll_fn.rs:38:9
  38: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at /mnt/src/stream/src/executor/actor.rs:99:9
  39: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  40: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}
             at /mnt/src/stream/src/task/stream_manager.rs:610:40
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  42: <risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::__Enum15994158506141524639<__Variant0,__Variant1> as core::future::future::Future>::poll
             at /mnt/src/stream/src/task/stream_manager.rs:615:17
  43: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  44: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  45: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  46: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  47: tokio::runtime::task::core::CoreStage<T>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  48: tokio::runtime::task::harness::poll_future::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  49: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  50: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  51: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  52: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  53: tokio::runtime::task::harness::poll_future
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  54: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  55: tokio::runtime::task::harness::Harness<T,S>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  56: tokio::runtime::task::raw::RawTask::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  57: tokio::runtime::task::LocalNotified<S>::run
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:385:9
  58: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:421:13
  59: tokio::coop::with_budget::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:102:9
  60: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
  61: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
  62: tokio::coop::with_budget
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:420:9
  63: tokio::coop::budget
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/coop.rs:72:5
  64: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:420:9
  65: tokio::runtime::scheduler::multi_thread::worker::Context::run
  66: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:372:17
  67: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/macros/scoped_tls.rs:61:9
  68: tokio::runtime::scheduler::multi_thread::worker::run
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:369:5
  69: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs:348:45
  70: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/task.rs:42:21
  71: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  72: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:184:17
  73: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/loom/std/unsafe_cell.rs:14:9
  74: tokio::runtime::task::core::CoreStage<T>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/core.rs:174:13
  75: tokio::runtime::task::harness::poll_future::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:480:19
  76: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  77: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  78: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  79: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  80: tokio::runtime::task::harness::poll_future
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:468:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:104:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/harness.rs:57:15
  83: tokio::runtime::task::raw::RawTask::poll
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/raw.rs:134:18
  84: tokio::runtime::task::UnownedTask<S>::run
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/task/mod.rs:422:9
  85: tokio::runtime::blocking::pool::Task::run
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:111:9
  86: tokio::runtime::blocking::pool::Inner::run
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:346:17
  87: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /risingwave/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.1/src/runtime/blocking/pool.rs:321:13
```

### To Reproduce

run server
`RUST_BACKTRACE=1 ./risingwave playground`

run client
```
bash $ psql -h localhost -p 4566 -d dev -U root
psql (15.0, server 9.5.0)
Type "help" for help.
dev=> create table seq(a int, b int primary key);                 
CREATE_TABLE
dev=> insert into seq values(1, 1), (1, 2), (2, 1), (2, 2), (2, 3);
INSERT 0 5
dev=> 
dev=> select * from seq;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

**Comment by skyzh** [comment]
It's expected to ignore the values instead panic. Need fix.

**Comment by BugenZhao** [comment]
Thanks for your feedback. We're currently working on the fix. Since the checkpointing of RisingWave is asynchronous and periodical, we plan to support validation for duplicated keys, and user can specify the strategy of first-win or last-win.

**Comment by fuyufjh** [comment]
Thanks for your feedback. We will fix it ASAP. (est. 2 weeks)

**Comment by wcy-fdu** [comment]
Thanks for your feedback, we have fix it, and feel free to try it again.

**Comment by wcy-fdu** [comment]
Thanks for your feedback, we have fix it, and feel free to try it again.
