### ISSUE TITLE
Failed to run `explain` using JDBC

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#6336]
### To Reproduce

Run the following java codes with [pgJDBC](https://jdbc.postgresql.org/download/) driver.

```java
import java.sql.*;
import java.util.Properties;

public class App {
    public static void main(String[] args) {
        var url = "jdbc:postgresql://localhost:4566/dev";
        var props = new Properties();
        props.setProperty("user", "root");
        try (var conn = DriverManager.getConnection(url, props)) {
            try (var stmt = conn.createStatement()) {
                stmt.execute("explain select 1");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

Exception:

```plain
java -cp ./postgresql-42.5.0.jar App.java
java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2301)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at App.main(App.java:11)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:434)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:205)
        at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:132)
```

And it works well on a standard pg server.

**Comment by TennyZhuang** [comment]
The bug may also affect some pg GUI client written in Java.

**Comment by BowenXiao1999** [comment]
Is this driver using extended query mode? 

Maybe not classified as is_query... Try add starts_with explain in?
https://github.com/risingwavelabs/risingwave/blob/21e2861087d10aa6cfc1c04c28eaa4ed5145e371/src/utils/pgwire/src/pg_protocol.rs#L380

**Comment by TennyZhuang** [comment]
> Is this driver using extended query mode?
> 
> Maybe not classified as is_query... Try add starts_with explain in?

Not sure, you can try to reproduce it easily.

1. install a JAVA 18 JDK.
2. Download the jar.
3. Run the file using `java -cp ./postgresql-42.5.0.jar App.java`.

At least the standard pg works well, so I think it's a bug :(

**Comment by TennyZhuang** [comment]
It's fixed after adding the line.

Is it reasonable to do such string comparison in the wire layer?

**Comment by BowenXiao1999** [comment]
Yes I was also thinking about how to refactor these code to be more robust. cc @ZENOTME, Do you have some ideas?

**Comment by TennyZhuang** [comment]
Oh it get panicked after adding the line

**Comment by TennyZhuang** [comment]
Ok, I also need to add `infer_return_type` implementation for explain.

**Comment by BowenXiao1999** [comment]
> Ok, I also need to add infer_return_type implementation for explain.

Yes I think it's very similar to Query
