### ISSUE TITLE
Compute node panicked in cloud.

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#6561]
### Describe the bug

A node will be panicked when a multi-node cluster starts in the cloud.

### To Reproduce

image-tag:latest(nightly-20221124, git-30d7d784c69420bdf5191f2c22049fff10e80b18)

1. Cloud deploys a three-node risingwave cluster, and one of the CN cannot be ready:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/29391315/203710962-12d32985-1242-4560-a3a6-da3b61f94abd.png">

2. CN logs:
```
launching compute node
2022-11-24T06:26:21.146786Z  INFO risingwave_rt: setting tokio worker threads to 8
2022-11-24T06:26:21.147222Z  INFO risingwave_compute: Compute node options: ComputeNodeOpts { host: "10.0.10.143:5688", client_address: Some("risingwave-compute-2.risingwave-compute:5688"), state_store: "hummock+s3://rls-apse1-mgmt-bucket", prometheus_listener_addr: "0.0.0.0:1222", metrics_level: 1, meta_address: "http://risingwave-meta:5690", config_path: "/risingwave/config/risingwave.toml", enable_jaeger_tracing: false, async_stack_trace: Off, file_cache_dir: "", connector_source_endpoint: "127.0.0.1:60061" }
2022-11-24T06:26:21.147253Z  INFO risingwave_compute: Server Listening at 10.0.10.143:5688
2022-11-24T06:26:21.147290Z  INFO risingwave_compute: Client address is risingwave-compute-2.risingwave-compute:5688
2022-11-24T06:26:21.147548Z  INFO risingwave_compute::server: Starting compute node with config ComputeNodeConfig { server: ServerConfig { heartbeat_interval_ms: 1000, max_heartbeat_interval_secs: 600, connection_pool_size: 16 }, batch: BatchConfig { worker_threads_num: None, developer: DeveloperConfig { batch_output_channel_size: 64, batch_chunk_size: 1024, stream_enable_executor_row_count: false, stream_enable_managed_cache: true, stream_connector_message_buffer_size: 16, unsafe_stream_hash_agg_cache_size: 65536, unsafe_stream_join_cache_size: 65536, unsafe_stream_extreme_cache_size: 1024, stream_chunk_size: 1024 } }, streaming: StreamingConfig { barrier_interval_ms: 250, in_flight_barrier_nums: 40, checkpoint_frequency: 10, minimal_scheduling: false, worker_node_parallelism: 8, actor_runtime_worker_threads_num: None, total_memory_available_bytes: 66716327936, developer: DeveloperConfig { batch_output_channel_size: 64, batch_chunk_size: 1024, stream_enable_executor_row_count: false, stream_enable_managed_cache: true, stream_connector_message_buffer_size: 16, unsafe_stream_hash_agg_cache_size: 65536, unsafe_stream_join_cache_size: 65536, unsafe_stream_extreme_cache_size: 1024, stream_chunk_size: 1024 } }, storage: StorageConfig { sstable_size_mb: 256, block_size_kb: 1024, bloom_false_positive: 0.01, share_buffers_sync_parallelism: 1, share_buffer_compaction_worker_threads_number: 4, shared_buffer_capacity_mb: 1024, data_directory: "rls-apse1-eks-a-rwc-3-tpchbench-nightly-20221124", write_conflict_detection_enabled: false, block_cache_capacity_mb: 256, meta_cache_capacity_mb: 64, disable_remote_compactor: false, enable_local_spill: true, local_object_store: "tempdisk", share_buffer_upload_concurrency: 8, compactor_memory_limit_mb: 512, sstable_id_remote_fetch_number: 10, file_cache: FileCacheConfig { capacity_mb: 1024, total_buffer_capacity_mb: 128, cache_file_fallocate_unit_mb: 512, cache_meta_fallocate_unit_mb: 16, cache_file_max_write_size_mb: 4 }, min_sst_size_for_streaming_upload: 33554432, max_sub_compaction: 4, object_store_use_batch_delete: true, enable_state_store_v1: false } } with debug assertions off
2022-11-24T06:26:21.151078Z  INFO risingwave_compute::server: Assigned worker node id 3
2022-11-24T06:26:21.235144Z  INFO risingwave_object_store::object::s3: S3 bucket rls-apse1-mgmt-bucket has already configured AbortIncompleteMultipartUpload: [LifecycleRule { expiration: None, id: Some("abort-incomplete-multipart-upload"), prefix: None, filter: Some(Prefix("")), status: Some(Enabled), transitions: None, noncurrent_version_transitions: None, noncurrent_version_expiration: None, abort_incomplete_multipart_upload: Some(AbortIncompleteMultipartUpload { days_after_initiation: 1 }) }]
thread 'main' panicked at 'should be able to start the observer manager: internal error: the first notify should be compute snapshot, but get SubscribeResponse { status: None, operation: Snapshot, version: 0, info: None }
   0: <risingwave_common::error::RwError as core::convert::From<risingwave_common::error::ErrorCode>>::from
             at ./risingwave/src/common/src/error.rs:173:33
   1: <T as core::convert::Into<U>>::into
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/convert/mod.rs:726:9
   2: <risingwave_storage::hummock::observer_manager::HummockObserverNode as risingwave_common_service::observer_manager::ObserverState>::handle_initialization_notification
             at ./risingwave/src/storage/src/hummock/observer_manager.rs:97:28
   3: risingwave_common_service::observer_manager::ObserverManager<T,S>::start::{{closure}}
             at ./risingwave/src/common/common_service/src/observer_manager.rs:100:9
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
   5: risingwave_storage::hummock::HummockStorage::new::{{closure}}
             at ./risingwave/src/storage/src/hummock/mod.rs:164:13
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
   7: risingwave_storage::store_impl::StateStoreImpl::new::{{closure}}
             at ./risingwave/src/storage/src/store_impl.rs:261:21
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
   9: risingwave_compute::server::compute_node_serve::{{closure}}
             at ./risingwave/src/compute/src/server.rs:123:5
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  11: risingwave_compute::start::{{closure}}
             at ./risingwave/src/compute/src/lib.rs:116:69
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/future.rs:124:9
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:54
  16: tokio::coop::with_budget::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  17: std::thread::local::LocalKey<T>::try_with
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:446:16
  18: std::thread::local::LocalKey<T>::with
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:422:9
  19: tokio::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  20: tokio::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  21: tokio::park::thread::CachedParkThread::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  22: tokio::runtime::enter::Enter::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/enter.rs:152:13
  23: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/mod.rs:79:9
  24: tokio::runtime::Runtime::block_on
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/mod.rs:492:44
  25: risingwave_rt::main_okk
             at ./risingwave/src/utils/runtime/src/lib.rs:264:5
  26: risingwave::main::{{closure}}
             at ./risingwave/src/cmd_all/src/bin/risingwave.rs:50:17
  27: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  28: risingwave::main
             at ./risingwave/src/cmd_all/src/bin/risingwave.rs:163:13
  29: core::ops::function::FnOnce::call_once
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:251:5
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:122:18
  31: std::rt::lang_start::{{closure}}
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:166:18
  32: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:286:13
  33: std::panicking::try::do_call
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  34: std::panicking::try
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  35: std::panic::catch_unwind
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  36: std::rt::lang_start_internal::{{closure}}
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:48
  37: std::panicking::try::do_call
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  38: std::panicking::try
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  39: std::panic::catch_unwind
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  40: std::rt::lang_start_internal
             at ./rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:20
  41: main
  42: <unknown>
  43: __libc_start_main
  44: _start
', /risingwave/src/storage/src/hummock/mod.rs:165:14
stack backtrace:
   0:     0x55b0199da710 - std::backtrace_rs::backtrace::libunwind::trace::hf9eede5a9d6c67b2
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x55b0199da710 - std::backtrace_rs::backtrace::trace_unsynchronized::h0c91910fa04f4df9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b0199da710 - std::sys_common::backtrace::_print_fmt::he2b25433ad3bf420
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55b0199da710 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hef18c387f5407d06
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55b019a06a0e - core::fmt::write::h0a37462e5afa8d15
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/fmt/mod.rs:1209:17
   5:     0x55b0199d2a05 - std::io::Write::write_fmt::hc60ebc8a0cd9d3df
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/io/mod.rs:1682:15
   6:     0x55b0199dbd93 - std::sys_common::backtrace::_print::he3d440518a780bd7
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55b0199dbd93 - std::sys_common::backtrace::print::ha90d39b5839b2415
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55b0199dbd93 - std::panicking::default_hook::{{closure}}::h3448dcb19bce1d74
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:267:22
   9:     0x55b0199dba6a - std::panicking::default_hook::hd0a73ed3ba68d845
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:286:9
  10:     0x55b0155dabf2 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6add681223999f58
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  11:     0x55b0155dabf2 - risingwave_rt::set_panic_hook::{{closure}}::h332cbc02a12bb36d
                               at /risingwave/src/utils/runtime/src/lib.rs:81:9
  12:     0x55b0155dabf2 - std::panicking::update_hook::{{closure}}::h37ad3eecf6248393
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:232:47
  13:     0x55b0199dc619 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h789be6fd9a4af450
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  14:     0x55b0199dc619 - std::panicking::rust_panic_with_hook::h5e710c30b3aa952e
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:692:13
  15:     0x55b0199dc397 - std::panicking::begin_panic_handler::{{closure}}::h88a18397eefe7379
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:579:13
  16:     0x55b0199dabbc - std::sys_common::backtrace::__rust_end_short_backtrace::hfe085dbc16a7edcb
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x55b0199dc0b2 - rust_begin_unwind
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
  18:     0x55b019a03c23 - core::panicking::panic_fmt::ha20927ebca9f6d14
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
  19:     0x55b019a04153 - core::result::unwrap_failed::hef7de851e99192f8
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1791:5
  20:     0x55b0161b5167 - core::result::Result<T,E>::expect::hc12e995a71893c4e
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1070:23
  21:     0x55b0161b5167 - risingwave_storage::hummock::HummockStorage::new::{{closure}}::hdee495a7fd536194
                               at /risingwave/src/storage/src/hummock/mod.rs:162:17
  22:     0x55b0161b5167 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h43181d7b66f84d96
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  23:     0x55b0161b5167 - risingwave_storage::store_impl::StateStoreImpl::new::{{closure}}::h12778fa7fd41dacb
                               at /risingwave/src/storage/src/store_impl.rs:261:21
  24:     0x55b0163fe65e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf3a0160e32868f3f
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  25:     0x55b0163fe65e - risingwave_compute::server::compute_node_serve::{{closure}}::h9f707379505eab36
                               at /risingwave/src/compute/src/server.rs:123:5
  26:     0x55b01624da3c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h86c7ed2ad91847fc
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  27:     0x55b01624da3c - risingwave_compute::start::{{closure}}::hc49a120923e6f03c
                               at /risingwave/src/compute/src/lib.rs:116:69
  28:     0x55b01624da3c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0805370180dab0c7
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  29:     0x55b0153f4642 - <core::pin::Pin<P> as core::future::future::Future>::poll::he73ac3b991054c27
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/future.rs:124:9
  30:     0x55b0153f4642 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h2524e200c0982822
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  31:     0x55b0153f4642 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h96a9f4943b2af5f2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:54
  32:     0x55b0153f4642 - tokio::coop::with_budget::{{closure}}::h326f9df77da37022
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:102:9
  33:     0x55b0153f4642 - std::thread::local::LocalKey<T>::try_with::h7635b3d6defa152b
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:446:16
  34:     0x55b0153f4642 - std::thread::local::LocalKey<T>::with::hbaef71032d9b89bd
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/thread/local.rs:422:9
  35:     0x55b01525817d - tokio::coop::with_budget::h7ce9c528e2add43e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  36:     0x55b01525817d - tokio::coop::budget::h9b5b69495e057623
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/coop.rs:72:5
  37:     0x55b01525817d - tokio::park::thread::CachedParkThread::block_on::he4cb2a278ab5c167
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/park/thread.rs:267:31
  38:     0x55b0154c7604 - tokio::runtime::enter::Enter::block_on::hb24b8d8bca7140e3
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/enter.rs:152:13
  39:     0x55b0154c7604 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hf8db4f8dd3206b40
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/scheduler/multi_thread/mod.rs:79:9
  40:     0x55b01541fa97 - tokio::runtime::Runtime::block_on::h5d891618b7a2d679
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/mod.rs:492:44
  41:     0x55b01545a66c - risingwave_rt::main_okk::h2ec6654abac90294
                               at /risingwave/src/utils/runtime/src/lib.rs:264:5
  42:     0x55b015537db8 - risingwave::main::{{closure}}::haefd0a46efc174b8
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:50:17
  43:     0x55b0155378c6 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hc28c712b01c676bf
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  44:     0x55b0155378c6 - risingwave::main::h390fc44bdeb3edaa
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:163:13
  45:     0x55b01522c243 - core::ops::function::FnOnce::call_once::h309cbb32c9d024e4
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:251:5
  46:     0x55b01522c243 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e22a958637294cd
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:122:18
  47:     0x55b0153323cd - std::rt::lang_start::{{closure}}::h30e7c37cc26dc771
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:166:18
  48:     0x55b0199c9f4b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf105ddd1169c173a
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:286:13
  49:     0x55b0199c9f4b - std::panicking::try::do_call::he5d8f4184990e3bb
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  50:     0x55b0199c9f4b - std::panicking::try::h3fd4bce8ca12f40a
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  51:     0x55b0199c9f4b - std::panic::catch_unwind::hbc34baf325dba023
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  52:     0x55b0199c9f4b - std::rt::lang_start_internal::{{closure}}::hd38e0e16beb6e1a4
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:48
  53:     0x55b0199c9f4b - std::panicking::try::do_call::h9204340ea5cb9cf9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  54:     0x55b0199c9f4b - std::panicking::try::h96892eb3cbae8cf8
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  55:     0x55b0199c9f4b - std::panic::catch_unwind::h1595c408747ffa84
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  56:     0x55b0199c9f4b - std::rt::lang_start_internal::h294cac284b8f9297
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:20
  57:     0x55b01553849f - main
  58:     0x7fc01b276d90 - <unknown>
  59:     0x7fc01b276e40 - __libc_start_main
  60:     0x55b0151f6025 - _start
  61:                0x0 - <unknown>
```

**Comment by hzxa21** [comment]
Based on the log, CN binary is not built upon `30d7d784c69420bdf5191f2c22049fff10e80b18`

The relevant log is removed in https://github.com/risingwavelabs/risingwave/pull/6378/files#diff-58cb969ac9fcd7308ff9e1255a2bbc8f5e4c11a0dabb753e12cae051fe24c1c1L97

**Comment by yezizp2012** [comment]
The CN and meta binaries should have been compiled with different versions. They are incompatible after #6378 . Cc @HuaHuaY

**Comment by fuyufjh** [comment]
Looks like this should be closed?

**Comment by huangjw806** [comment]
This should be an issue of cloud image inconsistency. I will try to solve this issue at the cloud level.
