### ISSUE TITLE
Node panicked when a multi-node cluster starts in the cloud

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#6811]
### Describe the bug

node panicked when a multi-node cluster starts in the cloud.

### To Reproduce

image-tag:latest(nightly-20221208, git-62e49bfa45848af98e6d3424ff50f0202f85fc52)

1. Cloud deploys a three-node risingwave cluster,  some nodes cannot be ready:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/29391315/206609615-85d8e2e6-193b-40c5-8459-58151c0bcc66.png">

2. failed node logs:
```
2022-12-09T02:17:00.459072Z  INFO risingwave_rt: setting tokio worker threads to 8
2022-12-09T02:17:00.459912Z  INFO risingwave_compute: Compute node options: ComputeNodeOpts { host: "10.0.121.29:5688", client_address: Some("benchmark-risingwave-compute-2.benchmark-risingwave-compute:5688"), state_store: "hummock+s3://sysbench-test-1723", prometheus_listener_addr: "0.0.0.0:1222", metrics_level: 1, meta_address: "http://benchmark-risingwave-meta:5690", enable_jaeger_tracing: false, async_stack_trace: On, file_cache_dir: "", connector_rpc_endpoint: None, config_path: "/risingwave/config/risingwave.toml", total_memory_bytes: 66716327936, parallelism: 8 }
2022-12-09T02:17:00.459936Z  INFO risingwave_compute: Server Listening at 10.0.121.29:5688
2022-12-09T02:17:00.459992Z  INFO risingwave_compute: Client address is benchmark-risingwave-compute-2.benchmark-risingwave-compute:5688
thread 'main' panicked at 'parse error unknown field `worker_node_parallelism`, expected one of `barrier_interval_ms`, `in_flight_barrier_nums`, `checkpoint_frequency`, `minimal_scheduling`, `actor_runtime_worker_threads_num`, `developer` for key `streaming` at line 4 column 1', src/common/src/config.rs:40:60
stack backtrace:
   0:     0x56125aa02520 - std::backtrace_rs::backtrace::libunwind::trace::hf9eede5a9d6c67b2
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x56125aa02520 - std::backtrace_rs::backtrace::trace_unsynchronized::h0c91910fa04f4df9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56125aa02520 - std::sys_common::backtrace::_print_fmt::he2b25433ad3bf420
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x56125aa02520 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hef18c387f5407d06
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x56125aa2ec2e - core::fmt::write::h0a37462e5afa8d15
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/fmt/mod.rs:1209:17
   5:     0x56125a9fa185 - std::io::Write::write_fmt::hc60ebc8a0cd9d3df
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/io/mod.rs:1682:15
   6:     0x56125aa03ba3 - std::sys_common::backtrace::_print::he3d440518a780bd7
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x56125aa03ba3 - std::sys_common::backtrace::print::ha90d39b5839b2415
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x56125aa03ba3 - std::panicking::default_hook::{{closure}}::h3448dcb19bce1d74
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:267:22
   9:     0x56125aa0387a - std::panicking::default_hook::hd0a73ed3ba68d845
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:286:9
  10:     0x5612562fb912 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h12af999eee983af9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  11:     0x5612562fb912 - risingwave_rt::set_panic_hook::{{closure}}::h0959199c434db8eb
                               at /risingwave/src/utils/runtime/src/lib.rs:78:9
  12:     0x5612562fb912 - std::panicking::update_hook::{{closure}}::hbd78333c86dd73f9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:232:47
  13:     0x56125aa04429 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h789be6fd9a4af450
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  14:     0x56125aa04429 - std::panicking::rust_panic_with_hook::h5e710c30b3aa952e
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:692:13
  15:     0x56125aa041a7 - std::panicking::begin_panic_handler::{{closure}}::h88a18397eefe7379
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:579:13
  16:     0x56125aa029cc - std::sys_common::backtrace::__rust_end_short_backtrace::hfe085dbc16a7edcb
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x56125aa03ec2 - rust_begin_unwind
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:575:5
  18:     0x56125aa2be43 - core::panicking::panic_fmt::ha20927ebca9f6d14
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/panicking.rs:65:14
  19:     0x56125a1c14e8 - risingwave_common::config::load_config::{{closure}}::ha1f481f1388598f0
                               at /risingwave/src/common/src/config.rs:40:60
  20:     0x56125a1c14e8 - core::result::Result<T,E>::unwrap_or_else::hcb1717d29e089d53
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/result.rs:1504:23
  21:     0x56125a1c14e8 - risingwave_common::config::load_config::h8b8da2de13d469e1
                               at /risingwave/src/common/src/config.rs:40:5
  22:     0x5612573c56d4 - risingwave_compute::server::compute_node_serve::{{closure}}::h1ba13696bd8e77f7
                               at /risingwave/src/compute/src/server.rs:72:18
  23:     0x56125731899b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h180e4f784e9e41dd
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  24:     0x56125731899b - risingwave_compute::start::{{closure}}::h9f61d7c1a5fa6c45
                               at /risingwave/src/compute/src/lib.rs:126:69
  25:     0x56125731899b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha6da822bbc9e882d
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/mod.rs:91:19
  26:     0x5612561093ab - <core::pin::Pin<P> as core::future::future::Future>::poll::hf238f4f4c786f706
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/future/future.rs:124:9
  27:     0x5612561093ab - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h5536e846af058a2e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  28:     0x5612561093ab - tokio::runtime::park::CachedParkThread::block_on::{{closure}}::h36be935f9c462f1f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  29:     0x5612561093ab - tokio::runtime::coop::with_budget::hebea45097bbbe0ef
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  30:     0x5612561093ab - tokio::runtime::coop::budget::h2978e6a7563c30be
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  31:     0x5612561093ab - tokio::runtime::park::CachedParkThread::block_on::he81480ee2b4afad6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  32:     0x56125622f90a - tokio::runtime::context::BlockingRegionGuard::block_on::hf2c926e4fd28aa66
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  33:     0x56125622f90a - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h5160f2299cd0c0e6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  34:     0x56125604d6a8 - tokio::runtime::runtime::Runtime::block_on::h780faf0da6f88608
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/runtime.rs:281:45
  35:     0x5612561def8c - risingwave_rt::main_okk::hd87fac5edac54bd1
                               at /risingwave/src/utils/runtime/src/lib.rs:258:5
  36:     0x561255fa94cb - risingwave::main::{{closure}}::hf4da45465fd5b9db
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:47:17
  37:     0x561255fa8fe0 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h06c1f69b52293609
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/alloc/src/boxed.rs:1952:9
  38:     0x561255fa8fe0 - risingwave::main::h0ea6787d4e8d83e4
                               at /risingwave/src/cmd_all/src/bin/risingwave.rs:160:13
  39:     0x561255ff66a3 - core::ops::function::FnOnce::call_once::h99c8adc0af9b46a6
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:251:5
  40:     0x561255ff66a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8ddb5ca4268ff1a2
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/sys_common/backtrace.rs:122:18
  41:     0x5612560c963d - std::rt::lang_start::{{closure}}::h07dbfdd285b8f059
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:166:18
  42:     0x56125a9f11db - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf105ddd1169c173a
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/core/src/ops/function.rs:286:13
  43:     0x56125a9f11db - std::panicking::try::do_call::he5d8f4184990e3bb
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  44:     0x56125a9f11db - std::panicking::try::h3fd4bce8ca12f40a
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  45:     0x56125a9f11db - std::panic::catch_unwind::hbc34baf325dba023
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  46:     0x56125a9f11db - std::rt::lang_start_internal::{{closure}}::hd38e0e16beb6e1a4
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:48
  47:     0x56125a9f11db - std::panicking::try::do_call::h9204340ea5cb9cf9
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:483:40
  48:     0x56125a9f11db - std::panicking::try::h96892eb3cbae8cf8
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panicking.rs:447:19
  49:     0x56125a9f11db - std::panic::catch_unwind::h1595c408747ffa84
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/panic.rs:137:14
  50:     0x56125a9f11db - std::rt::lang_start_internal::h294cac284b8f9297
                               at /rustc/b8c35ca26b191bb9a9ac669a4b3f4d3d52d97fb1/library/std/src/rt.rs:148:20
  51:     0x561255fa9c3f - main
  52:     0x7f254f0f8d90 - <unknown>
  53:     0x7f254f0f8e40 - __libc_start_main
  54:     0x561255f7e025 - _start
  55:                0x0 - <unknown>
```

**Comment by hzxa21** [comment]
maybe related: #6767

**Comment by fuyufjh** [comment]
See https://github.com/risingwavelabs/risingwave/pull/6767. `worker_node_parallelism` was moved to CLI argument.

**Comment by huangjw806** [comment]
> See #6767. `worker_node_parallelism` was moved to CLI argument.

It seems that the operator needs to synchronize this change. cc @arkbriar

**Comment by arkbriar** [comment]
Do you know which nodes support the `worker_node_parallelism` argument? It seems the operator needs to set this when starting the RisingWave. BTW, what's the recommended value for this? Shall we make it configurable or just set it to the CPU size? @huangjw806 @fuyufjh

**Comment by arkbriar** [comment]
Besides, shall we support ignoring those unrecognized parameters in the config file to avoid crashes? Like what MySQL does. 🤔 Looks like it's a common issue when upgrading the versions.

**Comment by fuyufjh** [comment]
> Besides, shall we support ignoring those unrecognized parameters in the config file to avoid crashes? Like what MySQL does. 🤔 Looks like it's a common issue when upgrading the versions.

Agree. I think it's better to print warning instead of crashing.
