### ISSUE TITLE
kafka sink: panicked at `itertools: .zip_eq()`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7072]
### Describe the bug

commit: 21e12ea2878e5597f05ee14aace56f84b67bdca5

```
CREATE SOURCE nexmark (
  event_type BIGINT,
  person STRUCT<"id" BIGINT,
                "name" VARCHAR,
                "email_address" VARCHAR,
                "credit_card" VARCHAR,
                "city" VARCHAR,
                "state" VARCHAR,
                "date_time" TIMESTAMP,
                "extra" VARCHAR>,
  auction STRUCT<"id" BIGINT,
                 "item_name" VARCHAR,
                 "description" VARCHAR,
                 "initial_bid" BIGINT,
                 "reserve" BIGINT,
                 "date_time" TIMESTAMP,
                 "expires" TIMESTAMP,
                 "seller" BIGINT,
                 "category" BIGINT,
                 "extra" VARCHAR>,
  bid STRUCT<"auction" BIGINT,
             "bidder" BIGINT,
             "price" BIGINT,
             "channel" VARCHAR,
             "url" VARCHAR,
             "date_time" TIMESTAMP,
             "extra" VARCHAR>
) WITH (
    connector = 'nexmark',
    nexmark.split.num = '8',
    nexmark.min.event.gap.in.ns = '0'
) ROW FORMAT JSON;
```

```
create sink nexmark_sink
as select * from nexmark with (
    kafka.brokers = '127.0.0.1:9092',
    kafka.topic = 'nexmark',
    format = 'append_only',
    connector = 'kafka'
);
```

LOG:
```
   0: std::panicking::begin_panic
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:607:12
   1: <itertools::zip_eq_impl::ZipEq<I,J> as core::iter::traits::iterator::Iterator>::next
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs:48:13
   2: risingwave_connector::sink::kafka::datum_to_json_object
             at ./src/connector/src/sink/kafka.rs:374:47
   3: risingwave_connector::sink::kafka::record_to_json
             at ./src/connector/src/sink/kafka.rs:398:21
```

[compute-node-5688.log](https://github.com/risingwavelabs/risingwave/files/10306501/compute-node-5688.log)

### Additional context
enable DEBUG LOG: 
```
2022-12-27T07:13:15.681606Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(2)
2022-12-27T07:13:15.681606Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(1)
2022-12-27T07:13:15.681618Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Struct(StructType { fields: [Int64, Int64, Int64, Varchar, Varchar, Timestamp, Varchar], field_names: ["auction", "bidder", "price", "channel", "url", "date_time", "extra"] }), Struct(Some(Int64(1000)), Some(Int64(1001)), Some(Int64(461574)), Some(Utf8("channel-1315")), Some(Utf8("https://www.nexmark.com/wwwv/sxm/hikr/item.htm?query=1&channel_id=996147200")), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:14.860))), Some(Utf8("iugddyabokogelsfvrrroebiavelhnnxdxbefjnktsbsgvxcnhpsvqcpq")))
2022-12-27T07:13:15.681623Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Struct(StructType { fields: [Int64, Varchar, Varchar, Int64, Int64, Timestamp, Timestamp, Int64, Int64, Varchar], field_names: ["id", "item_name", "description", "initial_bid", "reserve", "date_time", "expires", "seller", "category", "extra"] }), Struct(Some(Int64(1000)), Some(Utf8("sbeimyckhspxpmpeeuqm")), Some(Utf8("gvseirycizmyesblucotqllwnexpjnmleygtxdduleovagzygzgleacqfvawalfwlfaimlzupsxpmexeufltsibzopargshhlkpp")), Some(Int64(595843)), Some(Int64(691876)), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:14.853))), Some(NaiveDateTime(NaiveDateTimeWrapper(2022-12-27T07:13:15.185))), Some(Int64(1000)), Some(Int64(12)), Some(Utf8("uamacidfvaipnenhviwwavjfvbpbucvfkxqygfeowbwtosrufnpiznlnvdyxjugfkolqozsatlutklowfvzbhyfzzywptzehmmwjtmmssqrheaubbyogocydtzvhcqrdebvgzpgdbnfrgfgpeekmimaasrosvnhjafwzjzsiisiojknnuwmiedvlhsbfmnmbgceohwobbxagbtucgaelkohpksyktwgdqdlunjkvghuencafwgauxmoetfcyttjsxcrpvqlmuapiyewovcxldrnaybyxgbnptzkuugubkhihhbyreysolqguhxuruxafdmwwecypdlhrazsnox")))
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'itertools: .zip_eq() reached end of one iterator before the otheritertools: .zip_eq() reached end of one iterator before the other', ', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/zip_eq_impl.rs::2022-12-27T07:13:15.681652Z DEBUG risingwave_connector::sink::kafka: datum_to_json_object: Int64, Int64(2)
```

**Comment by lmatz** [comment]
```
dev=> create source s1 ( s1 struct<v1 int, v2 int> ) with ( connector = 'datagen' ) ROW FORMAT JSON;
CREATE_SOURCE
dev=> create sink s1_sink                                                                
as select * from s1 with (
    kafka.brokers = '127.0.0.1:9092',
    kafka.topic = 'test',
    format = 'append_only',
    connector = 'kafka'
);
CREATE_SINK
```
Panic too

**Comment by lmatz** [comment]
https://github.com/risingwavelabs/risingwave/blob/main/src/connector/src/sink/kafka.rs#L377

`sub_fields` is empty.
