### ISSUE TITLE
Ban `now()` in `create materialized view` until it is fully supported

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7226]
### Describe the bug

See below

### To Reproduce

See below

### Expected behavior

If it will panic, then don't allow it to be created.

### Additional context

**Comment by fuyufjh** [comment]
Is that where you need? https://github.com/risingwavelabs/risingwave/pull/7167

If not, please give an example?

**Comment by lmatz** [comment]
I see, then we may need to convince the user to use the latest image/binary

**Comment by lmatz** [comment]
> Is that what you need? #7167
> 
> If not, please give an example?

```
dev=> create table t(v1 int, t1 timestamp);
CREATE_TABLE
dev=> create materialized view mv as select * from t where t1 < now() - interval '1 day';
CREATE_MATERIALIZED_VIEW
dev=> create materialized view mv2 as select * from t where t1 > now() - interval '1 day';
ERROR:  QueryError: internal error: error trying to connect: tcp connect error: Connection refused (os error 61)
dev=> 
```

Log:
```
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'not yet implemented: https://github.com/risingwavelabs/risingwave/issues/6042thread 'risingwave-streaming-actor' panicked at 'not yet implemented: https://github.com/risingwavelabs/risingwave/issues/6042', ', /Users/martin/Code/risingwave/src/stream/src/executor/simple.rs/Users/martin/Code/risingwave/src/stream/src/executor/simple.rs::7777::not yet implemented: https://github.com/risingwavelabs/risingwave/issues/604221', 21
/Users/martin/Code/risingwave/src/stream/src/executor/simple.rs
:77:21
thread 'risingwave-streaming-actor' panicked at 'not yet implemented: https://github.com/risingwavelabs/risingwave/issues/6042', /Users/martin/Code/risingwave/src/stream/src/executor/simple.rs:77:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
   2: risingwave_stream::executor::simple::SimpleExecutorWrapper<E>::execute_inner::{{closure}}
             at ./src/stream/src/executor/simple.rs:77:21
```

**Comment by fuyufjh** [comment]
@jon-chuang Please take a look

**Comment by soundOfDestiny** [comment]
> @jon-chuang Please take a look

after discussion with bugen we decided to implement as #7229
