### ISSUE TITLE
bug: failed to set container resource spec in playground mode

### ISSUE THREAD

**Issue by mikechesterwang** [risingwavelabs/risingwave#7236]
### Describe the bug

The playground mode cannot correctly set the `total_memory_bytes` and `parallelism` params.

### To Reproduce

**Failed to set CPU limit**
```bash
docker run --entrypoint "/usr/bin/bash" \
--cpu-period 100000 \
--cpu-quota 100000 \
risingwavelabs/risingwave:v0.1.15 \
-c "mkdir -p /src/config && touch /src/config/default.toml && /risingwave/bin/risingwave playground"
```
got
```
2023-01-06T07:42:30.088105Z ERROR services: risingwave_compute: error_msg="parallelism 4 is larger than the total cpu available 1 that can be acquired."
thread 'risingwave-main' panicked at 'parallelism 4 is larger than the total cpu available 1 that can be acquired.', src/compute/src/lib.rs:118:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Failed to set memory limit**
```bash
docker run --entrypoint "/usr/bin/bash" \
--memory 4294967296 \
risingwavelabs/risingwave:v0.1.15 \
-c "mkdir -p /src/config && touch /src/config/default.toml && /usr/bin/timeout --signal=SIGKILL 120s /risingwave/bin/risingwave playground"
```
got
```
2023-01-06T07:43:35.732923Z ERROR risingwave_compute: error_msg="total_memory_bytes 8589934592 is larger than the total memory available bytes 4294967296 that can be acquired."
thread 'risingwave-main' panicked at 'total_memory_bytes 8589934592 is larger than the total memory available bytes 4294967296 that can be acquired.', src/compute/src/lib.rs:109:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

allow setting these two values in playgound mode

**Comment by fuyufjh** [comment]
Is this solved? @mikechesterwang

**Comment by fuyufjh** [comment]
Ping

**Comment by mikechesterwang** [comment]
this is solved.
