### ISSUE TITLE
bug: crashed when select from internal tables

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#7303]
### Describe the bug

```
thread 'risingwave-main' panicked at 'output_indices must be a subset of value_indices', /Users/eric/Workspace/risingwave-dev/src/storage/src/table/batch_table/storage_table.rs:180:9
stack backtrace:
   0: rust_begin_unwind
             at /Users/eric/.rustup/toolchains/nightly-2022-12-12-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /Users/eric/.rustup/toolchains/nightly-2022-12-12-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:64:14
   2: risingwave_storage::table::batch_table::storage_table::StorageTable<S>::new_inner
             at ./src/storage/src/table/batch_table/storage_table.rs:180:9
   3: risingwave_storage::table::batch_table::storage_table::StorageTable<S>::new_partial
             at ./src/storage/src/table/batch_table/storage_table.rs:122:9
   4: <risingwave_batch::executor::row_seq_scan::RowSeqScanExecutorBuilder as risingwave_batch::executor::BoxedExecutorBuilder>::new_boxed_executor::{{closure}}
             at ./src/batch/src/executor/row_seq_scan.rs:248:25
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/eric/.rustup/toolchains/nightly-2022-12-12-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
   6: risingwave_batch::executor::ExecutorBuilder<C>::try_build::{{closure}}
             at ./src/batch/src/executor/mod.rs:195:29
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/eric/.rustup/toolchains/nightly-2022-12-12-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:124:9
   8: risingwave_batch::executor::ExecutorBuilder<C>::build::{{closure}}
             at ./src/batch/src/executor/mod.rs:179:25
   9: risingwave_batch::task::task_execution::BatchTaskExecution<C>::async_execute::{{closure}}
             at ./src/batch/src/task/task_execution.rs:316:9
  10: <risingwave_batch::rpc::service::task_service::BatchServiceImpl as risingwave_pb::task_service::task_service_server::TaskService>::execute::{{closure}}
             at ./src/batch/src/rpc/service/task_service.rs:124:53
```

### To Reproduce

Create tables and insert some data:

```sql
create table t2 (k int, v varchar, primary key(k));
create table t1 (k int, v varchar, primary key(k));
create materialized view mv1 as select t1.k as k, t1.v as v1, t2.v as v2 from t1, t2 where t1.k=t2.k;
insert into t1 values (1,2), (3,4);
insert into t2 values (1,200), (3,400);
FLUSH;
```

Then,

```
dev=> select * from mv1;
 k | v1 | v2
---+----+-----
 3 | 4  | 400
 1 | 2  | 200
(2 rows)

dev=> select * from __internal_mv1_5_hashjoindegreeleft_1005;
ERROR:  QueryError: internal error: transport error
```

Note that the internal table name `__internal_mv1_5_hashjoindegreeleft_1005` can be inspected via command `./risedev ctl table list`

**Comment by fuyufjh** [comment]
I am also considering to expose internal tables to users/developers in SQL besides the little-known `./risedev ctl table list`. Let me open another issue for that.

**Comment by fuyufjh** [comment]
Oops, @Enter-tainer has leaved. @chenzl25 can you help to take a look?

**Comment by chenzl25** [comment]
> Oops, @Enter-tainer has leaved. @chenzl25 can you help to take a look?

OK, I will take a look.

**Comment by st1page** [comment]
I think that is because we do not implement batch scan on the table after introducing the `value_indices` in the state table. c.c. @wcy-fdu

**Comment by BugenZhao** [comment]
BTW, should we add some e2e tests for querying the internal tables, if we can decide the table name by querying the system tables.
