### ISSUE TITLE
stream group topn panics when order_by contains group_by columns

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7322]
### To Reproduce

```sql
CREATE TABLE t (
        x int,
        y int
    );

    create materialized view mv as SELECT
      1 as x
    FROM (
      SELECT
        row_number() over (partition by x order by x) as rank
      FROM
        t
    )
    WHERE rank <=1;

```

### Additional context

```
thread 'risingwave-main' panicked at 'assertion failed: `(left == right)`
  left: `OrderPair { column_idx: 2, order_type: Ascending }`,
 right: `OrderPair { column_idx: 0, order_type: Ascending }`', src/stream/src/executor/top_n/utils.rs:201:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:199:5
   4: risingwave_stream::executor::top_n::utils::create_cache_key_serde
             at ./src/stream/src/executor/top_n/utils.rs:201:13
   5: risingwave_stream::executor::top_n::group_top_n::InnerGroupTopNExecutorNew<K,S,_>::new
             at ./src/stream/src/executor/top_n/group_top_n.rs:113:13
```

**Comment by xxchan** [comment]
The assertion is `order_key = group_by + order_by + additional_pk`, but the `order_by` is actually de-duped 🤔

https://github.com/risingwavelabs/risingwave/blob/2ac5bad5ccb282a82ce9cc5cafd73272af59be35/src/frontend/src/optimizer/plan_node/generic/top_n.rs#L55-L78

**Comment by xxchan** [comment]
There's a chance for optimization (although it's a little bit silly): e.g., `partition by x,y,x,y order by x,y,x,y,z` is equivalent to `partition by x,y order by z` 🤪

**Comment by xxchan** [comment]
Found a different problem while doing the optimization... https://github.com/risingwavelabs/risingwave/issues/7332
