### ISSUE TITLE
panicked at `capacity overflow`, library/alloc/src/raw_vec.rs

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7345]
### Describe the bug

version = 0.1.15

```
thread ‘risingwave-main’ panicked at ‘capacity overflow’, library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
   2: alloc::raw_vec::capacity_overflow
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/raw_vec.rs:518:5
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/raw_vec.rs:178:27
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_zeroed_in
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/raw_vec.rs:139:9
   5: <u8 as alloc::vec::spec_from_elem::SpecFromElem>::from_elem
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_elem.rs:52:31
   6: alloc::vec::from_elem
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2557:5
   7: pgwire::pg_message::FeStartupMessage::read::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_message.rs:336:27
   8: pgwire::pg_protocol::PgStream<S>::read_startup::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:567:46
   9: pgwire::pg_protocol::Conn<S>::read_startup::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:650:53
  10: pgwire::pg_protocol::PgProtocol<S,SM,VS>::read_message::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_protocol.rs:225:67
  11: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:145:46
  12: pgwire::pg_server::handle_connection::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:131:1
  13: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./risingwave/src/utils/pgwire/src/pg_server.rs:118:40
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:208:17
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/loom/std/unsafe_cell.rs:14:9
  17: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:197:13
  18: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:483:19
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:483:40
  21: std::panicking::try
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:447:19
  22: std::panic::catch_unwind
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panic.rs:137:14
  23: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:471:18
  24: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:107:27
  25: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:61:15
  26: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:134:18
  27: tokio::runtime::task::LocalNotified<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/mod.rs:430:9
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:439:13
  29: tokio::runtime::coop::with_budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  30: tokio::runtime::coop::budget
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:438:9
  32: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:405:24
  33: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:390:17
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/macros/scoped_tls.rs:61:9
  35: tokio::runtime::scheduler::multi_thread::worker::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:387:5
  36: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  37: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/blocking/task.rs:42:21
  38: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  39: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:208:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::Core<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/core.rs:197:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:483:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:483:40
  45: std::panicking::try
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:447:19
  46: std::panic::catch_unwind
             at ./rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panic.rs:137:14
  47: tokio::runtime::task::harness::poll_future
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:471:18
  48: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:107:27
  49: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/harness.rs:61:15
  50: tokio::runtime::task::raw::RawTask::poll
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/raw.rs:134:18
  51: tokio::runtime::task::UnownedTask<S>::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/task/mod.rs:467:9
  52: tokio::runtime::blocking::pool::Task::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/blocking/pool.rs:159:9
  53: tokio::runtime::blocking::pool::Inner::run
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/blocking/pool.rs:510:17
  54: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/blocking/pool.rs:468:13
```

### Additional context

From the slack community: https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1673502585719499

**Comment by liurenjie1024** [comment]
I think this is caused by some attack:
https://github.com/risingwavelabs/risingwave/blob/aff23a192c76e80b351802afeecaac417524a329/src/utils/pgwire/src/pg_message.rs#L336

We need to check payload len before do true allocating.

**Comment by lmatz** [comment]
feel free to reassign it

**Comment by fuyufjh** [comment]
See the context at https://risingwave-community.slack.com/archives/C02T3F7UYM6/p1673502585719499

**Comment by BowenXiao1999** [comment]
IIUC, is this because we allocate too much memory in this vector and cause OOM? This may not be so easy to fix cuz we do not know which capacity is ok. 🤔

**Comment by fuyufjh** [comment]
> IIUC, is this because we allocate too much memory in this vector and cause OOM? This may not be so easy to fix cuz we do not know which capacity is ok. 🤔

🤔 Seems not. IIUC, "capacity overflow" was thrown when allocation size > `isize::MAX` which is definitely unreasonable.

- https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#176-182
- https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#505
- https://doc.rust-lang.org/stable/src/core/alloc/layout.rs.html#426

**Comment by liurenjie1024** [comment]
> Seems not. IIUC, "capacity overflow" was thrown when allocation size > isize::MAX which is definitely unreasonable.

I think the payload length is user input? If so, this is not unreasonable since it's quite easy to be attacked.

**Comment by BowenXiao1999** [comment]
> I think the payload length is user input? If so, this is not unreasonable since it's quite easy to be attacked.

It was constructed as network packet by psql, so it's not normal user input. Usually there is no attack so I was also curious why it happens..
