### ISSUE TITLE
bug(frontend): type mismatch when substituting $0 with $0

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#7473]
### Describe the bug

[frontend-4566.log](https://github.com/risingwavelabs/risingwave/files/10453037/frontend-4566.log)
```sh
thread 'risingwave-main' panicked at 'assertion failed: `(left == right)`
  left: `Int32`,
 right: `Varchar`: Type mismatch when substituting $0 with $0', src/frontend/src/utils/mod.rs:37:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:199:5
   4: <risingwave_frontend::utils::Substitute as risingwave_frontend::expr::expr_rewriter::ExprRewriter>::rewrite_input_ref
             at ./src/frontend/src/utils/mod.rs:37:9
   5: risingwave_frontend::expr::expr_rewriter::ExprRewriter::rewrite_expr
             at ./src/frontend/src/expr/expr_rewriter.rs:26:42
   6: <risingwave_frontend::optimizer::rule::project_merge_rule::ProjectMergeRule as risingwave_frontend::optimizer::rule::Rule>::apply::{{closure}}
             at ./src/frontend/src/optimizer/rule/project_merge_rule.rs:35:25
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:84:21
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:2414:21
  10: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:124:9
  11: <core::iter::adapters::cloned::Cloned<I> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/cloned.rs:60:9
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:124:9
  13: core::iter::traits::iterator::Iterator::for_each
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:831:9
  14: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2880:17
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_extend.rs:26:9
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  20: <risingwave_frontend::optimizer::rule::project_merge_rule::ProjectMergeRule as risingwave_frontend::optimizer::rule::Rule>::apply
             at ./src/frontend/src/optimizer/rule/project_merge_rule.rs:31:21
  21: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_node
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:51:36
  22: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:76:17
  23: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  24: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  25: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  26: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  28: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  29: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  30: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  31: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  32: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  33: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  34: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  35: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  36: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  37: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  38: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2848:35
  39: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_extend.rs:17:9
  40: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  41: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  42: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  43: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  44: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  45: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  46: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  47: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  48: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  49: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  50: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  51: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  52: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  53: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  54: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  55: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  56: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  57: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  58: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  59: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  60: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  61: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  62: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  63: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  64: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  65: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  66: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  67: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  68: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  69: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  70: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  71: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  72: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  73: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  74: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  75: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  76: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  77: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  78: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  79: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  80: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  81: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  82: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  83: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  84: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  85: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  86: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  87: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  88: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
  89: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
  90: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
  91: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
  92: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
  93: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
  94: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
  95: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  96: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
  97: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
  98: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
  99: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
 100: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
 101: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
 102: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
 103: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
 104: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
 105: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
 106: alloc::vec::Vec<T,A>::extend_desugared
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2848:35
 107: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_extend.rs:17:9
 108: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
 109: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
 110: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
 111: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
 112: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
 113: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
 114: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
 115: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
 116: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
 117: core::option::Option<T>::map
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:925:29
 118: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/adapters/map.rs:103:9
 119: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
 120: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/spec_from_iter.rs:33:9
 121: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/alloc/src/vec/mod.rs:2748:9
 122: core::iter::traits::iterator::Iterator::collect
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/iter/traits/iterator.rs:1836:9
 123: itertools::Itertools::collect_vec
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5/src/lib.rs:1985:9
 124: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:60:22
 125: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:75:24
 126: risingwave_frontend::optimizer::heuristic_optimizer::HeuristicOptimizer::optimize_inputs::{{closure}}
             at ./src/frontend/src/optimizer/heuristic_optimizer.rs:63:29
 127: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/ops/function.rs:629:13
 128: core::option::Option<T>::map
```

### To Reproduce

TODO

### Additional context

https://buildkite.com/risingwavelabs/main-cron/builds/314#0185c75d-6497-4d3f-a1b3-f3f6120b0366

**Comment by jon-chuang** [comment]
ddl now fails on main with
```
Not supported: streaming nested-loop join
HINT: The non-equal join in the query requires a nested-loop join executor, which could be very expensive to run. Consider rewriting the query to use dynamic filter as a substitute if possible.
See also: https://github.com/risingwavelabs/rfcs/blob/main/rfcs/0033-dynamic-filter.md
```

**Comment by kwannoel** [comment]
> ddl now fails on main with
> 
> ```
> Not supported: streaming nested-loop join
> HINT: The non-equal join in the query requires a nested-loop join executor, which could be very expensive to run. Consider rewriting the query to use dynamic filter as a substitute if possible.
> See also: https://github.com/risingwavelabs/rfcs/blob/main/rfcs/0033-dynamic-filter.md
> ```

Only one mview triggers that, and we don't actually reference that in the query. It works for me on latest main still.
Have removed the failing ddl statement to make it less confusing.

**Comment by kwannoel** [comment]
Fixed #7507
