### ISSUE TITLE
test: recovery test failed with `Catalog error: table with name .. exists`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7578]
Full logs [here](https://buildkite.com/risingwavelabs/pull-request/builds/16390#0185fcbf-d49d-401f-91f7-62d11fafe9ab). Another occurrence [here](https://github.com/risingwavelabs/risingwave/pull/7483#issuecomment-1398330622).

I guess this is caused by broken atomicity for `create table` or `drop table`. 🤨 cc @yezizp2012 
```
2022-11-11T23:37:32.587224Z ERROR node{id=4 name="frontend-1"}:task{id=2889601}: risingwave_frontend::session: failed to handle sql:
create table st (v1 int, v2 struct<v1 int, v2 struct<v1 int, v2 int>>);:
Catalog error: table with name st exists
2022-11-11T23:37:32.596302Z ERROR node{id=11 name="client"}:task{id=995}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: Catalog error: table with name st exists
[SQL] create table st (v1 int, v2 struct<v1 int, v2 struct<v1 int, v2 int>>);
at e2e_test/batch/./types/struct/struct.slt.part:4
at e2e_test/batch/./types/struct.slt.part:1
at e2e_test/batch/local_mode.slt:14

retry after 1s
2022-11-11T23:37:33.596302Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./types/struct/struct.slt.part", line: 4, upper: Some(Location { file: "e2e_test/batch/./types/struct.slt.part", line: 1, upper: Some(Location { file: "e2e_test/batch/local_mode.slt", line: 14, upper: None }) }) }, conditions: [], expected_error: None, sql: "create table st (v1 int, v2 struct<v1 int, v2 struct<v1 int, v2 int>>);", expected_count: None }
2022-11-11T23:37:33.599936Z ERROR node{id=4 name="frontend-1"}:task{id=2889601}: risingwave_frontend::session: failed to handle sql:
create table st (v1 int, v2 struct<v1 int, v2 struct<v1 int, v2 int>>);:
Catalog error: table with name st exists
2022-11-11T23:37:33.608987Z  INFO node{id=11 name="client"}:task{id=995}: sqllogictest::runner: testing record=Statement { loc: Location { file: "e2e_test/batch/./types/struct/struct.slt.part", line: 7, upper: Some(Location { file: "e2e_test/batch/./types/struct.slt.part", line: 1, upper: Some(Location { file: "e2e_test/batch/local_mode.slt", line: 14, upper: None }) }) }, conditions: [], expected_error: None, sql: "insert into st values(1,(1,(1,2)));", expected_count: None }
2022-11-11T23:37:33.621580Z ERROR node{id=4 name="frontend-1"}:task{id=2889601}: risingwave_frontend::session: failed to handle sql:
insert into st values(1,(1,(1,2)));:
Bind error: INSERT has more target columns than expressions
thread '<unnamed>' panicked at 'failed to run test after retry 0 times: statement failed: db error: ERROR: QueryError: Bind error: INSERT has more target columns than expressions
[SQL] insert into st values(1,(1,(1,2)));
at e2e_test/batch/./types/struct/struct.slt.part:7
at e2e_test/batch/./types/struct.slt.part:1
at e2e_test/batch/local_mode.slt:14
', /risingwave/src/tests/simulation/src/slt.rs:116:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:116:33
   3: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/tests/simulation/src/main.rs:182:57
   4: async_task::raw::RawTask<F,T,S>::run
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
   5: madsim::sim::task::Executor::run_all_ready
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:209:17
   6: madsim::sim::task::Executor::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/task.rs:159:13
   7: madsim::sim::runtime::Runtime::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/mod.rs:124:9
   8: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.13/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: run with `MADSIM_TEST_SEED=6` environment variable to reproduce this error
      and make sure `MADSIM_CONFIG_HASH=1AD2E4ABC41F3553`
```

**Comment by yezizp2012** [comment]
The root cause is that meta was restarting during running `drop table` for previous table `st`, and meta didn't finished starting leader RPC services. The frontend will receive error message `internal error: service not found: /ddl_service.DdlService/DropTable` and simulation test ignored it because it contains keywords `not found` 😢 .
```
2022-11-11T17:21:05.562399Z  INFO node{id=3 name="meta"}:task{id=1225359}: risingwave_meta: Meta server listening at 0.0.0.0:5690
2022-11-11T17:21:05.562406Z  INFO node{id=3 name="meta"}:task{id=1225360}: risingwave_meta::rpc::election_client: client 192.168.1.1:5690 start election
2022-11-11T17:21:05.562406Z  WARN node{id=3 name="meta"}:task{id=1225362}: madsim_tonic::sim::transport::server: layer is unimplemented and ignored
2022-11-11T17:21:05.573853Z  INFO node{id=3 name="meta"}:task{id=1225360}: risingwave_meta::rpc::election_client: restoring leader from lease 949780487911284656
2022-11-11T17:21:05.573853Z  INFO node{id=3 name="meta"}:task{id=1225360}: risingwave_meta::rpc::election_client: use lease id 949780487911284656
2022-11-11T17:21:05.576942Z ERROR node{id=4 name="frontend-1"}:task{id=1225357}: risingwave_frontend::session: failed to handle sql:
drop table st;:
internal error: service not found: /ddl_service.DdlService/DropTable
2022-11-11T17:21:05.599878Z  INFO node{id=3 name="meta"}:task{id=1225362}:server{addr=0.0.0.0:5690}: risingwave_meta::rpc::follower_svc: Shutting down follower services
2022-11-11T17:21:05.611276Z  INFO node{id=3 name="meta"}:task{id=1225361}: risingwave_meta::rpc::leader_svc: Defining leader services
```
