### ISSUE TITLE
DBeaver-> create database is failing 

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#7925]
### Describe the bug

Workflow:
1) Login to DBeaver
2) perform the database dev->right click->create database
3) DBeaver throw an error after clicking on create database.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/7961084/218676742-5d798c34-2d29-4ade-a645-a2fbf7226d98.png">

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/7961084/218677210-38ad527b-6b58-4297-ad56-c1e66029e4a3.png">

logs:
```
2023-02-14 16:04:56.409 - Error during job 'Load users' execution
org.postgresql.util.PSQLException: ERROR: ParseError: Feature is not yet implemented: pg_catalog.pg_conversion is not supported, please use `SHOW` commands for now.
`SHOW TABLES`,
`SHOW MATERIALIZED VIEWS`,
`DESCRIBE <table>`,
`SHOW COLUMNS FROM [table]`

Tracking issue: https://github.com/risingwavelabs/risingwave/issues/1695
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.execute(JDBCPreparedStatementImpl.java:261)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCPreparedStatementImpl.executeStatement(JDBCPreparedStatementImpl.java:205)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.loadObjects(JDBCObjectCache.java:109)
	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache.getAllObjects(JDBCObjectCache.java:73)
	at org.jkiss.dbeaver.ext.postgresql.model.PostgreDatabase.getEncodings(PostgreDatabase.java:476)
	at org.jkiss.dbeaver.ext.postgresql.ui.PostgreCreateDatabaseDialog$5.run(PostgreCreateDatabaseDialog.java:139)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by yezizp2012** [comment]
Resolved by #7964
