### ISSUE TITLE
bug: deterministic fuzzing test panicked at `not yet implemented` in `to_binary.rs`

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#7946]
### Describe the bug

```
2022-09-19T15:27:29.618542Z  INFO node{id=14 name="client"}:task{id=1339}: risingwave_sqlsmith::runner: Executing: SELECT ((REAL '506') * (REAL '330')) AS col_0, (133) AS col_1 FROM m4 AS t_0, hop(m8, m8.col_1, INTERVAL '3600', INTERVAL '842173200') AS hop_1 WHERE (true) GROUP BY t_0.col_2, hop_1.col_2, t_0.col_0 HAVING true
2022-09-19T15:27:29.757714Z  INFO node{id=14 name="client"}:task{id=1339}: risingwave_sqlsmith::runner: Executing: SELECT t_0.c7 AS col_0, TIME '14:27:29' AS col_1, TIME '07:28:03' AS col_2 FROM alltypes2 AS t_0, alltypes2 AS t_1, person AS t_2, partsupp AS t_3, alltypes1 AS t_4 GROUP BY t_0.c7, t_4.c15, t_0.c14, t_2.id ORDER BY t_0.c14 DESC
2022-09-19T15:27:29.973576Z  INFO node{id=14 name="client"}:task{id=1339}: risingwave_sqlsmith::runner: Executing: WITH with_0 AS (SELECT t_4.c5 AS col_0, TIME '15:27:28' AS col_1 FROM nation AS t_1 CROSS JOIN m1 AS t_2, lineitem AS t_3, alltypes1 AS t_4, person AS t_5 JOIN alltypes2 AS t_6 ON t_5.name = t_6.c9 GROUP BY t_3.l_discount, t_3.l_quantity, t_4.c10, t_3.l_returnflag, t_5.name, t_5.id, t_3.l_linenumber, t_4.c3, t_6.c2, t_3.l_extendedprice, t_3.l_suppkey, t_2.col_0, t_4.c5, t_4.c15 HAVING (t_6.c2 = ((812) / (94)))) SELECT ARRAY[(INTERVAL '-3600'), (INTERVAL '0'), (INTERVAL '604800'), (INTERVAL '86400')] AS col_0, (134) AS col_1, (INT '277') AS col_2, max(DATE '2022-09-14') FILTER(WHERE (true)) AS col_3 FROM with_0 WHERE false LIMIT 8
thread '<unnamed>' panicked at 'not yet implemented', src/common/src/types/to_binary.rs:97:39
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:114:5
   3: <risingwave_common::types::ScalarRefImpl as risingwave_common::types::to_binary::ToBinary>::to_binary_with_type
   4: risingwave_common::types::ScalarRefImpl::binary_format
             at ./src/common/src/types/mod.rs:825:9
   5: risingwave_frontend::handler::util::pg_value_format
             at ./src/frontend/src/handler/util.rs:124:27
   6: risingwave_frontend::handler::util::to_pg_rows::{{closure}}::{{closure}}
             at ./src/frontend/src/handler/util.rs:160:40
   7: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/adapters/map.rs:91:28
   8: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/traits/iterator.rs:2262:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/adapters/map.rs:117:9
  10: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/adapters/mod.rs:195:9
  11: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/traits/iterator.rs:2323:9
  12: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/iter/adapters/mod.rs:178:14
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/vec/spec_from_iter.rs:33:9
```

More details can be found here: https://buildkite.com/risingwavelabs/pull-request/builds/17491#_

**Comment by kwannoel** [comment]
This is happening with `struct` and `list`, since those currently don't have `to_binary_with_type` implemented.

**Comment by yezizp2012** [comment]
any updates? @jon-chuang @kwannoel

**Comment by kwannoel** [comment]
> any updates? @jon-chuang @kwannoel

No updates, duplicate from https://github.com/risingwavelabs/risingwave/issues/7949. Let's track it there instead.

**Comment by kwannoel** [comment]
> any updates? @jon-chuang @kwannoel

Is it urgent fix? Any features depending on it?

**Comment by yezizp2012** [comment]
> > any updates? @jon-chuang @kwannoel
> 
> Is it urgent fix? Any features depending on it?

Nope, let's just track it in #7949 . 😄
