### ISSUE TITLE
deterministic e2e failed for issue_7324.slt

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7975]
### Describe the bug

https://buildkite.com/risingwavelabs/main/builds/3097#018659a5-cb68-4a6a-b243-10fae3d89327

[risedev-logs/batch-19.log](https://buildkite.com/organizations/risingwavelabs/pipelines/main/builds/3097/jobs/018659a5-cb68-4a6a-b243-10fae3d89327/artifacts/018659b0-5fe5-44b9-8169-0cceb0cc7d5e)

```
000504f600819491439282b000000652450dec0000"], size=0KB

2022-02-09T05:41:01.667027Z ERROR node{id=9 name="compute-1"}:task{id=186660}: risingwave_batch::task::task_execution: Execution failed [TaskId { task_id: 0, stage_id: 1, query_id: "e91cb5bf-247f-4dcc-8e47-39464f4b475f" }]: Expr error: Numeric out of range
2022-02-09T05:41:01.667027Z ERROR node{id=9 name="compute-1"}:task{id=186675}: risingwave_batch::task::task_execution: Execution failed [TaskId { task_id: 5, stage_id: 1, query_id: "e91cb5bf-247f-4dcc-8e47-39464f4b475f" }]: Expr error: Numeric out of range
2022-02-09T05:41:01.671619Z ERROR node{id=7 name="frontend-1"}:task{id=186642}: risingwave_frontend::scheduler::distributed::stage: Stage QueryId { id: "e91cb5bf-247f-4dcc-8e47-39464f4b475f" }-1 failed to schedule tasks, error: TaskExecutionError("Expr error: Numeric out of range")
2022-02-09T05:41:01.671619Z ERROR node{id=7 name="frontend-1"}:task{id=186641}: risingwave_frontend::scheduler::distributed::query: Query stage QueryId { id: "e91cb5bf-247f-4dcc-8e47-39464f4b475f" }-1 failed: TaskExecutionError("Expr error: Numeric out of range").
thread '<unnamed>' panicked at 'statement is expected to fail, but actually succeed:
[SQL] SELECT i.f1, i.f1 * smallint '2' AS x FROM INT2_TBL i;
at e2e_test/batch/issue_7324.slt:27
', /risingwave/src/tests/simulation/src/slt.rs:114:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:147:5
   3: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:114:31
   4: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/tests/simulation/src/main.rs:188:57
   5: async_task::raw::RawTask<F,T,S>::run
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
   6: madsim::sim::task::Executor::run_all_ready
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.16/src/sim/task.rs:227:17
   7: madsim::sim::task::Executor::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.16/src/sim/task.rs:178:13
   8: madsim::sim::runtime::Runtime::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.16/src/sim/runtime/mod.rs:124:9
   9: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.16/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: run with `MADSIM_TEST_SEED=19` environment variable to reproduce this error
      and make sure `MADSIM_CONFIG_HASH=1AD2E4ABC41F3553`
```

**Comment by xxchan** [comment]
BTW, why I can't reproduce that locally?  🥵

```
MADSIM_TEST_SEED=19 risedev sslt './e2e_test/batch/issue_7324.slt'
```

**Comment by kwannoel** [comment]
Known issue: https://github.com/risingwavelabs/risingwave/issues/7901#issuecomment-1429113045

**Comment by kwannoel** [comment]
> BTW, why I can't reproduce that locally? 🥵
> 
> ```
> MADSIM_TEST_SEED=19 risedev sslt './e2e_test/batch/issue_7324.slt'
> ```

Known issue: https://github.com/risingwavelabs/risingwave/issues/7901#issuecomment-1429113045

**Comment by xxchan** [comment]
I'm testing that on Linux EC2 🥵

**Comment by liurenjie1024** [comment]
Fixed.
