### ISSUE TITLE
bug: `repeat` cause capacity overflow

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#8003]
### Describe the bug

```
thread 'risingwave-streaming-actor' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/raw_vec.rs:518:5
   3: alloc::raw_vec::handle_reserve
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/raw_vec.rs:489:34
   4: alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/raw_vec.rs:285:13
   5: alloc::raw_vec::RawVec<T,A>::reserve
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/raw_vec.rs:289:13
   6: alloc::vec::Vec<T,A>::reserve
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/alloc/src/vec/mod.rs:912:9
   7: bytes::bytes_mut::BytesMut::reserve_inner
             at /Users/noelkwan/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/bytes_mut.rs:630:21
   8: bytes::bytes_mut::BytesMut::reserve
             at /Users/noelkwan/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/bytes_mut.rs:576:9
   9: bytes::bytes_mut::BytesMut::extend_from_slice
             at /Users/noelkwan/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/bytes_mut.rs:766:9
  10: <bytes::bytes_mut::BytesMut as bytes::buf::buf_mut::BufMut>::put_slice
             at /Users/noelkwan/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/bytes_mut.rs:1123:9
  11: risingwave_common::util::value_encoding::serialize_str
             at ./src/common/src/util/value_encoding/mod.rs:117:5
  12: risingwave_common::util::value_encoding::serialize_scalar
             at ./src/common/src/util/value_encoding/mod.rs:75:35
  13: risingwave_common::util::value_encoding::serialize_datum_into
             at ./src/common/src/util/value_encoding/mod.rs:46:9
  14: risingwave_common::array::data_chunk::DataChunk::serialize
             at ./src/common/src/array/data_chunk.rs:411:29
  15: risingwave_stream::common::table::state_table::StateTable<S>::write_chunk
             at ./src/stream/src/common/table/state_table.rs:663:22
  16: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:200:29
```

### To Reproduce

```sql
-- Setup
CREATE TABLE orders (o_orderkey BIGINT, o_custkey INT, o_orderstatus CHARACTER VARYING, o_totalprice NUMERIC, o_orderdate DATE, o_orderpriority CHARACTER VARYING, o_clerk CHARACTER VARYING, o_shippriority INT, o_comment CHARACTER VARYING, PRIMARY KEY (o_orderkey));
INSERT INTO orders VALUES ((5395448908257897696), (INT '-2147483648'), 'fuwUX8EYn3', (787), DATE '2023-02-10', 'OxjXosVC6U', 'nUQWIrIn5j', (INT '98'), 'zHUhaEKf8b'), ((511), (INT '-2147483648'), 'vfblCTZLCY', (961), DATE '2023-02-17', 'BPq3KkNM1X', 'NeIXYbpNSt', (INT '934'), 'keYPv97N63'), ((782), (INT '-2147483648'), 'oP1YHzyzVH', (715), DATE '2023-02-17', 'mwRMyTbVkV', 'ignsmVQKsQ', (INT '68240333'), 'iY8DwsiWLF'), ((0), (INT '1753117740'), 'gbYCXcYVRk', (828), DATE '2023-02-17', 'AjBHe8Mk1G', 'Qxjas6VbNE', (INT '846'), 'BL7XGMDBaZ'), ((5617999432514889701), (INT '1266801000'), 'WqoVmRIptR', (755), DATE '2023-02-07', 'IUOBgwzhtM', 'ZzCHYwfXee', (INT '-712760904'), 'yAmnVWlkKY'), ((841), (INT '2147483647'), 'NjQqwlre0l', (831), DATE '2023-02-17', '76G6r6jRry', 'DxdnTqt3LM', (INT '497'), 'nYb3rk5GhJ'), ((326), (INT '907'), '2tB0jM14Xb', (625046401), DATE '2023-02-17', 'VxeTfgvfuS', 'HxXFyhrvDV', (INT '364'), 'L6Z4C7AwT3'), ((-3341712993507031047), (INT '875'), '7TnmrkgrGF', (0), DATE '2023-02-17', '7WwIphxRGx', 'd5BBPfwNjy', (INT '968'), 'YEUfIbnlL9'), ((5), (INT '298'), 'Kskdt1iMgX', (-797448337), DATE '2023-02-17', 'DyRPfBaaOa', 'NDx8szDE1u', (INT '655'), '7QGmOGQQn5'), ((251), (INT '-2147483648'), 'Sx4nvytgh3', (105), DATE '2023-02-17', 'AbNJm54yXM', 'u2GocQEwEW', (INT '504'), 'tV8droAs9C');

-- Query
CREATE MATERIALIZED VIEW stream_query AS SELECT DATE '2023-02-07' AS col_0, (repeat(t_0.o_comment, (t_0.o_custkey >> (t_0.o_custkey & (~ t_0.o_custkey))))) AS col_1 FROM orders AS t_0 WHERE true GROUP BY t_0.o_comment, t_0.o_clerk, t_0.o_orderkey, t_0.o_orderdate, t_0.o_custkey;
---- END


```

### Expected behavior

It is probably caused by `repeat` with a large repeat number... Should we truncate string? What is limit of string size 🤔

**Comment by kwannoel** [comment]
I don't think users will write such a large string... Mark as priority low for now.
