### ISSUE TITLE
flaky test: thread 'risingwave-streaming-actor' panicked at 'assertion failed: !next_serialized_key.is_empty()'

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8024]
### Describe the bug

```
thread 'risingwave-streaming-actor' panicked at 'assertion failed: !next_serialized_key.is_empty()', /risingwave/src/storage/src/table/batch_table/storage_table.rs:502:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/panicking.rs:114:5
   3: risingwave_storage::table::batch_table::storage_table::StorageTable<S>::iter_with_pk_bounds::{{closure}}::serialize_pk_bound
             at ./src/storage/src/table/batch_table/storage_table.rs:502:25
   4: risingwave_storage::table::batch_table::storage_table::StorageTable<S>::iter_with_pk_bounds::{{closure}}
             at ./src/storage/src/table/batch_table/storage_table.rs:522:25
   5: risingwave_storage::table::batch_table::storage_table::StorageTable<S>::batch_iter_with_pk_bounds::{{closure}}
             at ./src/storage/src/table/batch_table/storage_table.rs:594:13
   6: risingwave_stream::executor::backfill::BackfillExecutor<S>::snapshot_read::{{closure}}
             at ./src/stream/src/executor/backfill.rs:329:14
   7: <futures_async_stream::try_stream::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.6/src/lib.rs:463:33
   8: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/stream/map.rs:58:26
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.26/src/stream.rs:120:9
  10: futures_util::stream::select_with_strategy::poll_side
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/select_with_strategy.rs:220:28
  11: futures_util::stream::select_with_strategy::poll_inner
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/select_with_strategy.rs:243:11
  12: <futures_util::stream::select_with_strategy::SelectWithStrategy<St1,St2,Clos,State> as futures_core::stream::Stream>::poll_next
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.26/src/stream/select_with_strategy.rs:270:17
  13: risingwave_stream::executor::backfill::BackfillExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/backfill.rs:104:5
```

Met this on a PR https://buildkite.com/risingwavelabs/pull-request/builds/17667
and on main https://buildkite.com/risingwavelabs/main/builds/3117

**Comment by xxchan** [comment]
cc @chenzl25

**Comment by chenzl25** [comment]
```
create materialized view mv1 as select array_agg(c) as res from t;
create materialized view mv3 as select * from (select unnest(res) as u from mv1) where u>2; // panic
```

The root cause is when `current_pos` is an empty row, backfill `snapshot_read` will panic. The only way to make `current_pos` be an empty row is that the upstream mv primary key is empty. The chances of this corner case happening are very low. It happens only when a new mv on an existing mv with empty pk and there is a barrier between the only one row and `None` of the `snapshot_read`. I will fix it later.
