### ISSUE TITLE
bug: recovery test failed at `internal error: index already in creating procedure`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#8086]
```
2022-09-30T10:39:26.468164Z ERROR node{id=8 name="frontend-2"}:task{id=2134752}: risingwave_frontend::session: failed to handle sql:
CREATE INDEX idx1 ON t1(v1) INCLUDE(v2):
internal error: index already in creating procedure
2022-09-30T10:39:26.475830Z ERROR node{id=14 name="client"}:task{id=1339}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: internal error: index already in creating procedure
[SQL] create index idx1 on t1(v1) include(v2);
at e2e_test/batch/./basic/index.slt.part:7
at e2e_test/batch/local_mode.slt:7

retry after 4s
2022-09-30T10:39:30.488436Z ERROR node{id=8 name="frontend-2"}:task{id=2134752}: risingwave_frontend::session: failed to handle sql:
CREATE INDEX idx1 ON t1(v1) INCLUDE(v2):
internal error: index already in creating procedure
2022-09-30T10:39:30.491962Z ERROR node{id=14 name="client"}:task{id=1339}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: internal error: index already in creating procedure
[SQL] create index idx1 on t1(v1) include(v2);
at e2e_test/batch/./basic/index.slt.part:7
at e2e_test/batch/local_mode.slt:7

retry after 8s
2022-09-30T10:39:34.141529Z  INFO node{id=8 name="frontend-2"}:task{id=2135204}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 3099796785725440 with RPC
2022-09-30T10:39:34.606501Z  INFO node{id=7 name="frontend-1"}:task{id=2135264}: risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 3099796785725440 with RPC
2022-09-30T10:39:38.508064Z ERROR node{id=8 name="frontend-2"}:task{id=2134752}: risingwave_frontend::session: failed to handle sql:
CREATE INDEX idx1 ON t1(v1) INCLUDE(v2):
internal error: index already in creating procedure
2022-09-30T10:39:38.516188Z ERROR node{id=14 name="client"}:task{id=1339}: risingwave_simulation::slt: failed to run test: statement failed: db error: ERROR: QueryError: internal error: index already in creating procedure
[SQL] create index idx1 on t1(v1) include(v2);
at e2e_test/batch/./basic/index.slt.part:7
at e2e_test/batch/local_mode.slt:7

retry after 16s
2022-09-30T10:39:49.546489Z  INFO node{id=6 name="meta-3"}:task{id=2136143}: risingwave_meta::hummock::compactor_manager: Added compactor session 2
2022-09-30T10:39:54.522749Z ERROR node{id=8 name="frontend-2"}:task{id=2134752}: risingwave_frontend::session: failed to handle sql:
CREATE INDEX idx1 ON t1(v1) INCLUDE(v2):
internal error: index already in creating procedure
thread '<unnamed>' panicked at 'failed to run test after retry 5 times: statement failed: db error: ERROR: QueryError: internal error: index already in creating procedure
[SQL] create index idx1 on t1(v1) include(v2);
at e2e_test/batch/./basic/index.slt.part:7
at e2e_test/batch/local_mode.slt:7
', /risingwave/src/tests/simulation/src/slt.rs:192:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:64:14
   2: risingwave_simulation::slt::run_slt_task::{{closure}}
             at ./src/tests/simulation/src/slt.rs:192:41
   3: risingwave_simulation::main::{{closure}}::{{closure}}::{{closure}}
             at ./src/tests/simulation/src/main.rs:191:57
   4: async_task::raw::RawTask<F,T,S>::run
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.3.0/src/raw.rs:511:20
   5: madsim::sim::task::Executor::run_all_ready
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.17/src/sim/task.rs:236:17
   6: madsim::sim::task::Executor::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.17/src/sim/task.rs:187:13
   7: madsim::sim::runtime::Runtime::block_on
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.17/src/sim/runtime/mod.rs:124:9
   8: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.17/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
note: run with `MADSIM_TEST_SEED=13` environment variable to reproduce this error
```

https://buildkite.com/risingwavelabs/main/builds/3152#018672d1-e028-42cc-a565-988b3b7d5240

**Comment by yezizp2012** [comment]
I have reproduced it locally, will fix. 🥵
