### ISSUE TITLE
please trim the sql statement before processing it - e.g. `<space>select 1` fails

### ISSUE THREAD

**Issue by cameronbraid** [risingwavelabs/risingwave#8089]
### Describe the bug

Example in java

standalone repro : (uses testcontainers)
```
git clone https://github.com/cameronbraid/risingwave-java-received-resultset-tuples-but-no-field-structure-for-them-reproduction
cd risingwave-java-received-resultset-tuples-but-no-field-structure-for-them-reproduction
mvn test
```

example code : 

```
var list = handle.createQuery(" select 1").mapToMap().list();
```

```
java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
 at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2301)
 at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
 at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
 at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
 at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
 at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
 at org.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
 at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1787)
 at org.jdbi.v3.core.result.ResultProducers.lambda$createResultBearing$3(ResultProducers.java:94)
 at org.jdbi.v3.core.result.ResultIterable.lambda$of$0(ResultIterable.java:58)
 at org.jdbi.v3.core.result.ResultIterable.stream(ResultIterable.java:269)
 at org.jdbi.v3.core.result.ResultIterable.collect(ResultIterable.java:325)
 at org.jdbi.v3.core.result.ResultIterable.list(ResultIterable.java:314)
 at risingwave.TestCase.testCase(TestCase.java:60)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
```

**Comment by xiangjinwu** [comment]
https://github.com/risingwavelabs/risingwave/blob/b429e9c2966a88c47f71ea0e05f4dc3589801448/src/utils/pgwire/src/pg_protocol.rs#L395-L409

The query is actually executed correctly, but our pgwire extend query protocol is falsely telling the client "this is not a query and do not expect any output".

@ZENOTME Do you recall why it was designed to use naive string comparison rather than invoke the parser?

**Comment by ZENOTME** [comment]
Before #6849, we parse in frontend. I currently try to move parser to pgwire in extended query mode, it may more complex than simple query mode because we need to replace the parameter in parse tree.
