### ISSUE TITLE
bug: handling of panic when sinking into a  non-existed iceberg table

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8129]
### Describe the bug

connector-node

```
2023-02-22 15:07:00,876 ERROR [grpc-default-executor-1] connector.IcebergSinkFactory:70 - load table error: {}
org.apache.iceberg.exceptions.NoSuchTableException: Table does not exist: demo_db.demo_table
	at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:49)
	at com.risingwave.connector.IcebergSinkFactory.create(IcebergSinkFactory.java:68)
	at com.risingwave.connector.SinkStreamObserver.bindSink(SinkStreamObserver.java:200)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:52)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:21)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

compute-node

```
ERROR:  QueryError: internal error: Rpc error: gRPC error (Internal error): Actor 17 exit unexpectedly: Executor error: Sink error: Remote sink error: failed to start sink: Status { code: FailedPrecondition, message: "failed to load iceberg table", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
```

### To Reproduce

1. Clone this branch: https://github.com/risingwavelabs/risingwave-demo/pull/83
2. Start the cluster: `docker compose up -d`
3. Run create_source.sql, create_mv.sql and create_sink.sql. It will finally fail in the create_sink step.

### Expected behavior

Throwing an error instead of causing panic.

**Comment by wenym1** [comment]
May I ask what is the expected behavior? 

IIUC, neither compute-node nor connector-node panics in the given log. The logs are only errors that is caught during create sink, and both nodes are not panicked.

Since the iceberg table does not exists, the error is inevitable.

**Comment by liurenjie1024** [comment]
What's the response to psql client?

**Comment by wenym1** [comment]
From my side,
```
dev=> CREATE SINK bhv_iceberg_sink
FROM
    bhv_mv WITH (
    connector = 'iceberg',
    sink.mode='upsert',
    location.type='minio',
    warehouse.path='minio://hummockadmin:hummockadmin@minio-0:9301/hummock001/iceberg-data',
    database.name='demo_db',
    table.name='demo_table'
);
ERROR:  QueryError: internal error: Rpc error: gRPC error (Internal error): Actor 20 exit unexpectedly: Executor error: Sink error: Remote sink error: failed to start sink: Status { code: FailedPrecondition, message: "failed to load iceberg table", metadata: MetadataMap { headers: {"content-type": "application/grpc"} }, source: None }
  backtrace of `StreamError`:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/std/src/backtrace.rs:332:13
   3: <risingwave_stream::error::StreamError as core::convert::From<risingwave_stream::error::Inner>>::from
             at ./risingwave/src/stream/src/error.rs:47:10
   4: <T as core::convert::Into<U>>::into
             at ./rustc/3984bc5833db8bfb0acc522c9775383e4171f3de/library/core/src/convert/mod.rs:726:9
   5: <risingwave_stream::error::StreamError as core::convert::From<risingwave_stream::executor::error::StreamExecutorError>>::from
             at ./risingwave/src/stream/src/error.rs:94:9
```

**Comment by xx01cyx** [comment]
After #8417, the error message will be:

```SQL
dev=> CREATE SINK bhv_iceberg_sink
FROM
    bhv_mv WITH (
    connector = 'iceberg',
    sink.mode='upsert',
    location.type='minio',
    warehouse.path='minio://hummockadmin:hummockadmin@minio-0:9301/hummock001/iceberg-data',
    database.name='demo_db',
    table.name='demo_table'
);
ERROR:  QueryError: internal error: Remote sink error: sink cannot pass validation: FAILED_PRECONDITION: failed to load iceberg table
```

which is a lot clearer!
