### ISSUE TITLE
XorFilter panicked

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#8150]
### Describe the bug

```
thread 'risingwave-streaming-actor' panicked at 'assertion failed: self.remaining() >= dst.len()', /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:254:9
stack backtrace:
thread 'risingwave-streaming-actor' panicked at 'assertion failed: self.remaining() >= dst.len()', /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:254:9
   0: rust_begin_unwind
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:114:5
   3: bytes::buf::buf_impl::Buf::copy_to_slice
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:254:9
   4: bytes::buf::buf_impl::Buf::get_u32_le
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/bytes-1.4.0/src/buf/buf_impl.rs:481:9
   5: risingwave_storage::hummock::sstable::xor_filter::XorFilterReader::new
             at ./src/storage/src/hummock/sstable/xor_filter.rs:90:39
   6: risingwave_storage::hummock::sstable::Sstable::new
             at ./src/storage/src/hummock/sstable/mod.rs:145:29
   7: risingwave_storage::hummock::sstable_store::SstableStore::sstable_syncable::{{closure}}::{{closure}}::{{closure}}
             at ./src/storage/src/hummock/sstable_store.rs:348:31
   8: risingwave_common::cache::LruCache<K,T>::lookup_with_request_dedup::{{closure}}
             at ./src/common/src/cache.rs:875:54
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  10: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  12: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  13: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panic/unwind_safe.rs:271:9
  15: std::panicking::try::do_call
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:483:40
  16: ___rust_try
  17: std::panicking::try
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:447:19
  18: std::panic::catch_unwind
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panic.rs:140:14
  19: tokio::runtime::task::harness::poll_future
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  21: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  22: tokio::runtime::task::raw::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  23: tokio::runtime::task::raw::RawTask::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  24: tokio::runtime::task::LocalNotified<S>::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  26: tokio::runtime::coop::with_budget
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  27: tokio::runtime::coop::budget
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  30: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  32: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  33: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  34: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
  35: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  36: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  38: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  39: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panic/unwind_safe.rs:271:9
  41: std::panicking::try::do_call
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:483:40
  42: ___rust_try
  43: std::panicking::try
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:447:19
  44: std::panic::catch_unwind
             at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panic.rs:140:14
  45: tokio::runtime::task::harness::poll_future
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  46: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  47: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  48: tokio::runtime::task::raw::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  49: tokio::runtime::task::raw::RawTask::poll
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  50: tokio::runtime::task::UnownedTask<S>::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
  51: tokio::runtime::blocking::pool::Task::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
  52: tokio::runtime::blocking::pool::Inner::run
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/tianyizhuang/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Thu Feb 23 09:22:19 UTC 2023 [risedev]: Program exited with 134
```

### To Reproduce

After some recovery

**Comment by hzxa21** [comment]
cc @soundOfDestiny 
https://github.com/risingwavelabs/risingwave/blob/438825b3e8b7d8a6787f78eb63b428183877698d/src/storage/src/hummock/sstable/xor_filter.rs#L90

**Comment by hzxa21** [comment]
> > cc @soundOfDestiny
> > https://github.com/risingwavelabs/risingwave/blob/438825b3e8b7d8a6787f78eb63b428183877698d/src/storage/src/hummock/sstable/xor_filter.rs#L90
> 
> I think it is not from an xor filter, but from a bloom filter

You are right. I confirmed with @TennyZhuang offline. This happens when running new codes on old data.
