### ISSUE TITLE
pr-fuzz-test triggered `unreachable code: suspicious distribution` in StreamHashJoin plan node

### ISSUE THREAD

**Issue by xiangjinwu** [risingwavelabs/risingwave#8176]
### Describe the bug

```
thread 'main' panicked at 'internal error: entered unreachable code: suspicious distribution: left: HashShard([0, 1]), right: UpstreamHashShard([0], TableId { table_id: 7 })', src/frontend/src/optimizer/plan_node/stream_hash_join.rs:137:23
stack backtrace:
  0: rust_begin_unwind
      at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/std/src/panicking.rs:575:5
  1: core::panicking::panic_fmt
      at /rustc/5ce39f42bd2c8bca9c570f0560ebe1fce4eddb14/library/core/src/panicking.rs:64:14
  2: risingwave_frontend::optimizer::plan_node::stream_hash_join::StreamHashJoin::derive_dist
      at /risingwave/src/frontend/src/optimizer/plan_node/stream_hash_join.rs:137:23
  3: risingwave_frontend::optimizer::plan_node::stream_hash_join::StreamHashJoin::new
      at /risingwave/src/frontend/src/optimizer/plan_node/stream_hash_join.rs:61:20
  4: risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin::to_stream_hash_join
      at /risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:1091:16
  5: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::convert::ToStream>::to_stream
      at /risingwave/src/frontend/src/optimizer/plan_node/logical_join.rs:1302:13
  6: <risingwave_frontend::optimizer::plan_node::logical_filter::LogicalFilter as risingwave_frontend::optimizer::plan_node::convert::ToStream>::to_stream
      at /risingwave/src/frontend/src/optimizer/plan_node/logical_filter.rs:215:25
... (more in log below)
```

### To Reproduce

See failing SQL setup code from log:
https://buildkite.com/risingwavelabs/pull-request/builds/18189#01868216-c30e-45ce-baa0-53dd24d2a46d

Failing SQL query:
```
CREATE MATERIALIZED VIEW m6 AS
SELECT
  ARRAY[(INT '68'),
  (INT '2147483647')] AS col_0,
  sq_2.col_1 AS col_1,
  (INT '84') AS col_2
FROM
  (
    SELECT t_1.o_orderdate AS col_0, (INT '60') AS col_1
    FROM
      m1 AS t_0 FULL JOIN orders AS t_1
      ON t_0.col_0 = t_1.o_orderkey AND ((SMALLINT '48') = t_1.o_orderkey)
    GROUP BY t_1.o_orderdate, t_1.o_custkey HAVING false
  ) AS sq_2
GROUP BY sq_2.col_1;
```

**Comment by xiangjinwu** [comment]
Ran the same queries from log on latest main, and there are no more panic.
