### ISSUE TITLE
NoClassDefFoundError for connector started by risedev

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8407]
### Describe the bug

Meet this when using downloaded connector. Using built connector is fine.

```
Exception in thread "grpc-default-executor-3" Exception in thread "grpc-default-executor-2" Exception in thread "grpc-default-executor-0" java.lang.NoClassDefFoundError: com/risingwave/connector/
	at com.risingwave.connector.SinkStreamObserver.getSinkFactory(SinkStreamObserver.java:212)
	at com.risingwave.connector.SinkStreamObserver.bindSink(SinkStreamObserver.java:199)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:52)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:21)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.NoClassDefFoundError: com/risingwave/connector/JDBCSinkFactory
	at com.risingwave.connector.SinkStreamObserver.getSinkFactory(SinkStreamObserver.java:212)
	at com.risingwave.connector.SinkStreamObserver.bindSink(SinkStreamObserver.java:199)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:52)
	at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:21)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:332)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:315)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by StrikeW** [comment]
> Meet this when using downloaded connector

Where are you download the connector? If you download from https://github.com/risingwavelabs/risingwave-connector-release, then this is expected. Because the package in the repo only contains features of CDC source.

**Comment by xxchan** [comment]
I download from connector-release by risedev. 

> the package in the repo only contains features of CDC source

This sounds a little bit wierd, especially when we already make connector's source code public.. So currently in what cases is this release repo used? Only for risedev?

**Comment by StrikeW** [comment]
The repo is created to hold the binary of the connector node to let community users to try the CDC features. Now, the connector node is open-sourced, I think the repo should be deprecated and risedev should not download from it.

**Comment by fuyufjh** [comment]
> The repo is created to hold the binary of the connector node to let community users to try the CDC features. Now, the connector node is open-sourced, I think the repo should be deprecated and risedev should not download from it.

@StrikeW Can you help to work this out?

**Comment by StrikeW** [comment]
I will fix it in next release.
