### ISSUE TITLE
bug: metabase query crashed the frontend node.

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#8530]
### Describe the bug

metabase query crashed the frontend node.
```
thread 'risingwave-main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/liuchengyou/working/risingwave-labs/risingwave/src/utils/pgwire/src/pg_protocol.rs:410:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:159:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/slice/index.rs:260:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2703:9
   6: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process_parse_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:410:50
   7: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:221:61
   8: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:160:41
   9: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:156:29
  10: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:156:44
  11: pgwire::pg_server::handle_connection::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:140:1
  12: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:127:40
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/future/future.rs:125:9
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  17: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  18: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  21: ___rust_try
  22: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  23: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  24: tokio::runtime::task::harness::poll_future
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  25: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  26: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  27: tokio::runtime::task::raw::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  28: tokio::runtime::task::raw::RawTask::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  29: tokio::runtime::task::LocalNotified<S>::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:394:9
  30: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  31: tokio::runtime::coop::with_budget
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
  32: tokio::runtime::coop::budget
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
  33: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  34: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  35: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  36: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/macros/scoped_tls.rs:61:9
  37: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  38: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  39: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/task.rs:42:21
  40: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  41: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:223:17
  42: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/loom/std/unsafe_cell.rs:14:9
  43: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/core.rs:212:13
  44: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:476:19
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  47: ___rust_try
  48: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  49: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  50: tokio::runtime::task::harness::poll_future
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:464:18
  51: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:198:27
  52: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/harness.rs:152:15
  53: tokio::runtime::task::raw::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:255:5
  54: tokio::runtime::task::raw::RawTask::poll
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/raw.rs:200:18
  55: tokio::runtime::task::UnownedTask<S>::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/task/mod.rs:431:9
  56: tokio::runtime::blocking::pool::Task::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:159:9
  57: tokio::runtime::blocking::pool::Inner::run
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:511:17
  58: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/liuchengyou/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/blocking/pool.rs:469:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/Users/liuchengyou/working/risingwave-labs/risingwave/.risingwave/bin/run_command.sh: line 12: /var/folders/v0/ywg4jttx7qn__323w39m_g1r0000gn/T/.tmpyOZUSz/frontend-4566.status: No such file or directory
Program exited with 134, press Ctrl+C to continue.
```

### To Reproduce

1. Connect to RW on Metabase with risingwave-metabase-driver.
2. Execute `show tables;` or `select * from t;` in a metabase query

**Comment by liurenjie1024** [comment]
cc @ZENOTME
