### ISSUE TITLE
feat(JDBCSink): supported TIMESTAMP type

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8647]
### Describe the bug

```
2023-03-20 08:48:38,584 ERROR [grpc-default-executor-6] connector.SinkStreamObserver:168 - sink task error: 
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: unsupported type TIMESTAMP
        at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-api-1.49.0.jar:1.49.0]
        at com.risingwave.connector.JsonDeserializer.validateJsonDataTypes(JsonDeserializer.java:145) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.JsonDeserializer.lambda$deserialize$0(JsonDeserializer.java:62) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[?:?]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[?:?]
        at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161) ~[?:?]
        at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[?:?]
        at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681) ~[?:?]
        at com.risingwave.connector.api.sink.TrivialCloseIterator.hasNext(TrivialCloseIterator.java:34) ~[connector-api-1.0-SNAPSHOT.jar:?]
        at com.risingwave.metrics.MonitoredRowIterator.hasNext(MonitoredRowIterator.java:29) ~[risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.JDBCSink.write(JDBCSink.java:229) ~[risingwave-sink-jdbc-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:125) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
        at com.risingwave.connector.SinkStreamObserver.onNext(SinkStreamObserver.java:33) [risingwave-connector-service-1.0-SNAPSHOT.jar:?]
```

**Comment by fuyufjh** [comment]
Need to test more data types https://github.com/risingwavelabs/risingwave/pull/6631/files

**Comment by fuyufjh** [comment]
@tabVersion Have you started working on this? I just made some preliminary work: https://github.com/risingwavelabs/risingwave/compare/eric/fix_8647
