### ISSUE TITLE
bug: entered unreachable code: suspicious distribution

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#8673]
### Describe the bug

```
2022-03-30T09:32:37.029389Z  INFO node{id=14 name="client"}:task{id=1411}: risingwave_sqlsmith::runner: [EXECUTING STATEMENT]: 
CREATE MATERIALIZED VIEW m1 AS SELECT 'DZnTz1UrAn' AS col_0, ((INTERVAL '17') + TIME '09:32:37') AS col_1, (INTERVAL '85') AS col_2, 'IVufrFXpen' AS col_3 FROM (customer AS t_0 RIGHT JOIN region AS t_1 ON t_0.c_address = t_1.r_comment AND true AND t_0.c_name = t_1.r_name AND t_0.c_mktsegment = t_1.r_name AND t_0.c_mktsegment = t_1.r_comment AND t_0.c_nationkey = t_1.r_regionkey AND t_0.c_comment = t_1.r_comment AND t_0.c_comment = t_1.r_name AND t_0.c_phone = t_1.r_name AND t_0.c_address = t_1.r_name AND t_0.c_name = t_1.r_comment) FULL JOIN partsupp AS t_2 ON t_0.c_custkey = t_2.ps_partkey AND true AND t_0.c_acctbal = t_2.ps_supplycost AND t_0.c_address = t_2.ps_comment AND t_1.r_regionkey = t_2.ps_availqty AND t_0.c_nationkey = t_2.ps_partkey AND t_1.r_name = t_2.ps_comment AND t_0.c_comment = t_2.ps_comment AND t_0.c_custkey = t_2.ps_suppkey AND t_0.c_nationkey = t_2.ps_suppkey AND t_0.c_custkey = t_2.ps_availqty GROUP BY t_0.c_address, t_0.c_mktsegment

thread '<unnamed>' panicked at 'internal error: entered unreachable code: suspicious distribution: left: HashShard([0, 1, 2, 3, 5, 6, 7]), right: UpstreamHashShard([0, 1], TableId { table_id: 1003 })', src/frontend/src/optimizer/plan_node/[stream_hash_join.rs:137](http://stream_hash_join.rs:137/):23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
   2: risingwave_frontend::optimizer::plan_node::stream_hash_join::StreamHashJoin::derive_dist
             at ./src/frontend/src/optimizer/plan_node/[stream_hash_join.rs:137](http://stream_hash_join.rs:137/):23
   3: risingwave_frontend::optimizer::plan_node::stream_hash_join::StreamHashJoin::new
             at ./src/frontend/src/optimizer/plan_node/[stream_hash_join.rs:61](http://stream_hash_join.rs:61/):20
   4: risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin::to_stream_hash_join
             at ./src/frontend/src/optimizer/plan_node/[logical_join.rs:1098](http://logical_join.rs:1098/):16
   5: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::convert::ToStream>::to_stream
             at ./src/frontend/src/optimizer/plan_node/[logical_join.rs:1283](http://logical_join.rs:1283/):13
   6: <risingwave_frontend::optimizer::plan_node::logical_agg::LogicalAgg as risingwave_frontend::optimizer::plan_node::convert::ToStream>::to_stream
             at ./src/frontend/src/optimizer/plan_node/[logical_agg.rs:1266](http://logical_agg.rs:1266/):56
   7: risingwave_frontend::optimizer::plan_node::convert::ToStream::to_stream_with_dist_required
             at ./src/frontend/src/optimizer/plan_node/convert.rs:56:19
   8: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::convert::ToStream>::to_stream_with_dist_required
             at ./src/frontend/src/optimizer/plan_node/[logical_project.rs:291](http://logical_project.rs:291/):25
   9: risingwave_frontend::optimizer::PlanRoot::gen_stream_plan
             at ./src/frontend/src/optimizer/mod.rs:307:17
  10: risingwave_frontend::optimizer::PlanRoot::gen_materialize_plan
             at ./src/frontend/src/optimizer/mod.rs:410:27
  11: risingwave_frontend::handler::create_mv::gen_create_mv_plan
             at ./src/frontend/src/handler/[create_mv.rs:99](http://create_mv.rs:99/):23
  12: risingwave_frontend::handler::create_mv::handle_create_mv::{{closure}}
             at ./src/frontend/src/handler/[create_mv.rs:135](http://create_mv.rs:135/):29
  13: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:341:81
```

**Comment by lmatz** [comment]
https://buildkite.com/risingwavelabs/pull-request/builds/19885#0187029d-0200-489b-a818-7c324f87527d
