### ISSUE TITLE
panics when hit tab after `SHOW`

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#8791]
### To Reproduce

Use `psql` to connect to rw
```
dev=> show 
```
hit tab

rw panics with

```
thread 'risingwave-main' panicked at 'internal error: entered unreachable code', src/frontend/src/scheduler/distributed/stage.rs:914:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:114:5
   3: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:914:21
   4: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:949:25
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
   6: core::iter::traits::iterator::Iterator::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
   9: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
  15: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:945:32
  16: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:949:25
  17: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
  18: core::iter::traits::iterator::Iterator::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
  19: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
  20: core::iter::traits::iterator::Iterator::for_each
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
  21: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
  22: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
  23: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  24: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
  25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
  26: core::iter::traits::iterator::Iterator::collect
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
  27: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:945:32
  28: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:949:25
  29: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
  30: core::iter::traits::iterator::Iterator::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
  31: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
  32: core::iter::traits::iterator::Iterator::for_each
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
  33: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
  34: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
  35: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  36: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
  37: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
  38: core::iter::traits::iterator::Iterator::collect
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
  39: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:945:32
  40: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:949:25
  41: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
  42: core::iter::traits::iterator::Iterator::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
  43: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
  44: core::iter::traits::iterator::Iterator::for_each
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
  45: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
  46: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
  47: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  48: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
  49: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
  50: core::iter::traits::iterator::Iterator::collect
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
  51: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:945:32
  52: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:949:25
  53: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:84:28
  54: core::iter::traits::iterator::Iterator::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:2477:21
  55: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/adapters/map.rs:124:9
  56: core::iter::traits::iterator::Iterator::for_each
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:852:9
  57: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2856:17
  58: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_extend.rs:26:9
  59: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  60: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/spec_from_iter.rs:33:9
  61: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/vec/mod.rs:2724:9
  62: core::iter::traits::iterator::Iterator::collect
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/iter/traits/iterator.rs:1891:9
  63: risingwave_frontend::scheduler::distributed::stage::StageRunner::convert_plan_node
             at ./src/frontend/src/scheduler/distributed/stage.rs:945:32
  64: risingwave_frontend::scheduler::distributed::stage::StageRunner::create_plan_fragment
             at ./src/frontend/src/scheduler/distributed/stage.rs:852:13
  65: risingwave_frontend::scheduler::distributed::stage::StageRunner::schedule_tasks_for_root::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:556:29
  66: risingwave_frontend::scheduler::distributed::stage::StageRunner::schedule_tasks_for_all::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:636:54
  67: risingwave_frontend::scheduler::distributed::stage::StageRunner::run::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:306:65
  68: risingwave_frontend::scheduler::distributed::stage::StageExecution::start::{{closure}}::{{closure}}
             at ./src/frontend/src/scheduler/distributed/stage.rs:221:56
  69: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/future/future.rs:125:9
  70: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:223:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/core.rs:212:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:476:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  77: ___rust_try
  78: std::panicking::try
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  79: std::panic::catch_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  80: tokio::runtime::task::harness::poll_future
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:464:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:198:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/harness.rs:152:15
  83: tokio::runtime::task::raw::poll
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:255:5 nity_check: false, node_num_monitor_interval_sec: 10, backend: Mem, periodic_space_reclaim_compaction_interval_sec: 3600, periodic_ttl_reclaim_comin benchmarks and production environment.
  84: tokio::runtime::task::raw::RawTask::poll
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/raw.rs:200:18
  85: tokio::runtime::task::LocalNotified<S>::run
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/task/mod.rs:394:9
  86: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:487:21
  87: tokio::runtime::coop::with_budget
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:107:5
  88: tokio::runtime::coop::budget
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/coop.rs:73:5
  89: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/xxchan/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.26.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/var/folders/ck/2ms8pxqd15xc91xlcv_lcbrh0000gn/T/fsio_b584wXnem6.sh: line 5: 20571 Abort trap: 6           RUST_BACKTRACE=1 RW_NODE=playground cargo run --bin risingwave --profile "${RISINGWAVE_BUILD_PROFILE}"
[cargo-make] ERROR - Unable to execute script.
[cargo-make] WARN - Build Failed.
```

**Comment by xxchan** [comment]
in query log (so useful 🙏):
```sql
(simple query)receive query: SELECT name FROM  (SELECT pg_catalog.lower(name) AS name FROM pg_catalog.pg_settings   UNION ALL SELECT 'session authorization'   UNION ALL SELECT 'all') ss  WHERE substring(name,1,0)=''
LIMIT 1000
```
