### ISSUE TITLE
Bug: crash when the columns are not fully written in nexmark source

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#8812]
### Describe the bug

When columns of the nexmark source are not written completely, it will panic in [schema_check](https://github.com/risingwavelabs/risingwave/blob/a1d084d50ef845b1a566b9e6c5ab733c2ad40509/src/stream/src/executor/wrapper/schema_check.rs#L25)

If this is the expected behavior, please close this issue.

### To Reproduce

```
dev=> create table bid (auction INTEGER, bidder INTEGER, price INTEGER, "date_time" TIMESTAMP)
with (
  connector = 'nexmark',
  nexmark.table.type = 'Bid',
  nexmark.split.num = '12',
  nexmark.min.event.gap.in.ns = '100000'
) ;

```

then 

```
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 4800002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
stack backtrace:
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 3000002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
thread 'risingwave-streaming-actor' panicked at 'schema check failed on SourceExecutor 2D00002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', src/stream/src/executor/wrapper/schema_check.rs:48:29
thread 'thread 'risingwave-streaming-actorrisingwave-streaming-actor' panicked at '' panicked at 'schema check failed on SourceExecutor 3F00002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")schema check failed on SourceExecutor 2900002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")', thread '', src/stream/src/executor/wrapper/schema_check.rsrisingwave-streaming-actorsrc/stream/src/executor/wrapper/schema_check.rs:' panicked at ':48schema check failed on SourceExecutor 4500002718: column type mismatched at position 0: expected Some(Int32), found Some("Int64")48:', :29src/stream/src/executor/wrapper/schema_check.rs29

```

**Comment by BugenZhao** [comment]
The panic is intended to expose this as earlier as possible, introduced in #8711.

I think it's better to gracefully report an error when creating.
