### ISSUE TITLE
Modifying the `max_heartbeat_interval_secs` configuration of meta can cause simulation tests nexmark_q4_materialize_agg to fail.

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#8823]
### Describe the bug

Adding the
```
[meta]
max_heartbeat_interval_secs = 10
```
configuration to `/src/tests/simulation/src/risingwave.toml` can cause simulation tests for `nexmark_q4::nexmark_q4_materialize_agg` to panic.

### To Reproduce

update the config then 

```
./risedev sscale-test nexmark_q4::nexmark_q4_materialize_agg
```

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', src/meta/src/barrier/mod.rs:397:9
stack backtrace:
   0:        0x110b663b6 - std::backtrace_rs::backtrace::libunwind::trace::he32b094fcf0f5cf2
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x110b663b6 - std::backtrace_rs::backtrace::trace_unsynchronized::h01e5feb323ee775f
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x110b663b6 - std::sys_common::backtrace::_print_fmt::hdbeadd8ffbdcda5e
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x110b663b6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4d81d14243f5c699
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x110b8cffa - core::fmt::write::h26a8189c9d399096
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/fmt/mod.rs:1232:17
   5:        0x110b611cc - std::io::Write::write_fmt::h9caf243c87159177
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/io/mod.rs:1684:15
   6:        0x110b6619a - std::sys_common::backtrace::_print::haca6445e74ffacf0
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:47:5
   7:        0x110b6619a - std::sys_common::backtrace::print::h1959c72d84d59aa0
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:34:9
   8:        0x110b68333 - std::panicking::default_hook::{{closure}}::h0e4333c2c6d9c845
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:271:22
   9:        0x110b68088 - std::panicking::default_hook::h72b1a628247e1147
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:290:9
  10:        0x110b6891b - std::panicking::rust_panic_with_hook::hb89ecd355360e7c6
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:692:13
  11:        0x110b68834 - std::panicking::begin_panic_handler::{{closure}}::he48dd6edeb14ce88
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:583:13
  12:        0x110b667f9 - std::sys_common::backtrace::__rust_end_short_backtrace::hb8e39e23acf3139a
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:137:18
  13:        0x110b684fd - rust_begin_unwind
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
  14:        0x110cad1a3 - core::panicking::panic_fmt::hcf87cff77af8fbf9
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
  15:        0x110cad4cb - core::panicking::assert_failed_inner::he510d8fb7d43e1ff
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:257:17
  16:        0x110c72600 - core::panicking::assert_failed::h1049cfd68d8053bc
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:211:5
  17:        0x10b9a4a06 - risingwave_meta::barrier::CheckpointControl<S>::can_inject_barrier::hfed3c64fdb7872da
                               at /Users/shanicky/Workspace/singularity/risingwave/src/meta/src/barrier/mod.rs:397:9
  18:        0x10b9b1d5e - risingwave_meta::barrier::GlobalBarrierManager<S>::run::{{closure}}::hefc5def5715660ad
                               at /Users/shanicky/Workspace/singularity/risingwave/src/meta/src/barrier/mod.rs:617:60
  19:        0x10b9aa224 - risingwave_meta::barrier::GlobalBarrierManager<S>::start::{{closure}}::{{closure}}::hb0f37132ec0339f3
                               at /Users/shanicky/Workspace/singularity/risingwave/src/meta/src/barrier/mod.rs:517:45
  20:        0x10b7fbf06 - <core::pin::Pin<P> as core::future::future::Future>::poll::h2370fd4d785601a0
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/future/future.rs:125:9
  21:        0x10c799c81 - async_task::raw::RawTask<F,T,S>::run::hf1b4545ce58cb1e9
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/raw.rs:511:20
  22:        0x1108e4351 - async_task::runnable::Runnable::run::h435fc1e85e793c8a
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.3.0/src/runnable.rs:309:18
  23:        0x110572efc - madsim::sim::task::Executor::run_all_ready::h4bb48a9483325428
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.18/src/sim/task.rs:236:17
  24:        0x1083cbeff - madsim::sim::task::Executor::block_on::h5c8fe229d526bdb9
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.18/src/sim/task.rs:187:13
  25:        0x10831a763 - madsim::sim::runtime::Runtime::block_on::heeb2cdb85e830947
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.18/src/sim/runtime/mod.rs:124:9
  26:        0x108010216 - madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}::h8d91779da436397b
                               at /Users/shanicky/.cargo/registry/src/github.com-1ecc6299db9ec823/madsim-0.2.18/src/sim/runtime/builder.rs:128:35
  27:        0x1084e824d - std::sys_common::backtrace::__rust_begin_short_backtrace::hc1193721162f5c1b
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys_common/backtrace.rs:121:18
  28:        0x107fa60a2 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h04cc5c38ee02a5e0
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/thread/mod.rs:560:17
  29:        0x107f07155 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc8914c60ce377569
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panic/unwind_safe.rs:271:9
  30:        0x108592db9 - std::panicking::try::do_call::h24aa3bf75f42a5b6
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:487:40
  31:        0x10859f5ed - ___rust_try
  32:        0x1085886d7 - std::panicking::try::h10c8ccef17b13d28
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:451:19
  33:        0x10834bce4 - std::panic::catch_unwind::h27c7ff4de16480b6
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panic.rs:140:14
  34:        0x107f983e4 - std::thread::Builder::spawn_unchecked_::{{closure}}::h9f01ff75963df05d
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/thread/mod.rs:559:30
  35:        0x108107b21 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd85f64e604397944
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/ops/function.rs:250:5
  36:        0x110b6e817 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h964e763f256649a9
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/boxed.rs:1988:9
  37:        0x110b6e817 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1ff1dae955a7a18e
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/alloc/src/boxed.rs:1988:9
  38:        0x110b6e817 - std::sys::unix::thread::Thread::new::thread_start::hc25d6f2006bded68
                               at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7fff204eb8fc - __pthread_start
note: run with `MADSIM_TEST_SEED=6` environment variable to reproduce this error
test nexmark_q4::nexmark_q4_materialize_agg ... FAILED

failures:

failures:
    nexmark_q4::nexmark_q4_materialize_agg

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 57 filtered out; finished in 19.68s
```

Printing the commands in the queue shows that Pause is not at the end of the queue, which can cause a debug assert to fail.

```
command #0 Plain(Some(Pause(PauseMutation)))
command #1 RescheduleFragment({1: Reschedule { added_actors: [25, 26], removed_actors: [3, 4], vnode_bitmap_updates: {25: 0000000000000000000000000000000000000000000000000000000000000000111111111111111111111000000000000000000000000000000000000000000001111111111111111111111111111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000000000000, 26: 0000000000000000000000000000000000000000000111111111111111111111000000000000000000000011111111111111111111111111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, upstream_fragment_dispatcher_ids: [(2, 1)], upstream_dispatcher_mapping: Some(VnodeMapping { original_indices: [20, 42, 63, 84, 85, 128, 171, 213, 255], data: [5, 6, 26, 25, 5, 26, 25, 5, 6] }), downstream_fragment_ids: [], actor_splits: {} }})
```

**Comment by shanicky** [comment]
The issue has been identified. There was a missing `continue` statement [here](https://github.com/risingwavelabs/risingwave/blob/9d5ff78bddf2ba615e9bc3cb687611ac1c9b9251/src/meta/src/barrier/mod.rs#L587), causing `risedev` to not heartbeat and causing meta to kick the risedev node used for simulation testing after 10 seconds, resulting in the issue.
