### ISSUE TITLE
bug: Drop table with watermark panic

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#8922]
### Describe the bug

```sql
create table t1 (ts1 timestamp with time zone, id int, watermark for ts1 as ts1 - INTERVAL '5' SECOND) append only;
drop table t1; // panic
```

**Comment by BugenZhao** [comment]
Seems related to #8336.

```
thread 'risingwave-main' panicked at 'assertion failed: internal_table_ids.is_empty()', src/meta/src/rpc/ddl_controller.rs:535:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/31f858d9a511f24fedb8ed997b28304fec809630/library/core/src/panicking.rs:114:5
   3: risingwave_meta::rpc::ddl_controller::DdlController<S>::drop_table_inner::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:535:13
   4: risingwave_meta::rpc::ddl_controller::DdlController<S>::drop_streaming_job::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:306:21
   5: risingwave_meta::rpc::ddl_controller::DdlController<S>::run_command::{{closure}}::{{closure}}
             at ./src/meta/src/rpc/ddl_controller.rs:143:88
```
