### ISSUE TITLE
deterministic test failed with `there is no reactor running`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#9661]
### Describe the bug

<details closed>
<summary> Log </summary>

```
seed = 1
Configuration {
    config_path: Regular(
        "",
    ),
    frontend_nodes: 2,
    compute_nodes: 3,
    meta_nodes: 3,
    compactor_nodes: 2,
    compute_node_cores: 2,
    etcd_timeout_rate: 0.0,
    etcd_data_path: None,
}
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/dns.rs:121:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
context: node=5 "meta-2", task=129 (spawned at /Users/noelkwan/projects/risingwave/src/common/src/telemetry/report.rs:55:23)
note: run with `MADSIM_TEST_SEED=1` environment variable to reproduce this error
noelkwan@Noels-MacBook-Pro risingwave % RUST_BACKTRACE=1 MADSIM_TEST_SEED=1 ./target/sim/ci-sim/risingwave_simulation --sqlsmith 100 ./src/tests/sqlsmith/tests/testdata
seed = 1
Configuration {
    config_path: Regular(
        "",
    ),
    frontend_nodes: 2,
    compute_nodes: 3,
    meta_nodes: 3,
    compactor_nodes: 2,
    compute_node_cores: 2,
    etcd_timeout_rate: 0.0,
    etcd_data_path: None,
}
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/dns.rs:121:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/panicking.rs:150:5
   3: tokio::runtime::scheduler::Handle::current
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/panic.rs:54:9
   4: tokio::runtime::blocking::pool::spawn_blocking
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/pool.rs:182:14
   5: <reqwest::dns::gai::GaiResolver as reqwest::dns::resolve::Resolve>::resolve
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.17/src/dns/gai.rs:26:18
   6: hyper::client::connect::dns::resolve::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/dns.rs:360:5
   7: hyper::client::connect::http::HttpConnector<R>::call_async::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/http.rs:338:17
   8: <hyper::client::connect::http::HttpConnector<R> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/connect/http.rs:271:61
   9: <hyper_tls::client::HttpsConnector<T> as tower_service::Service<http::uri::Uri>>::call::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-tls-0.5.0/src/client.rs:136:33
  10: <hyper_tls::client::HttpsConnecting<T> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-tls-0.5.0/src/client.rs:162:9
  11: reqwest::connect::Connector::connect_with_maybe_proxy::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.17/src/connect.rs:247:40
  12: reqwest::connect::with_timeout::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.17/src/connect.rs:415:10
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/future/future.rs:125:9
  14: <hyper::service::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/service/oneshot.rs:60:28
  15: <F as futures_core::future::TryFuture>::try_poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.27/src/future.rs:82:9
  16: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/try_future/into_future.rs:34:9
  17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/future/map.rs:55:37
  18: <F as futures_core::future::TryFuture>::try_poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.27/src/future.rs:82:9
  19: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/try_future/into_future.rs:34:9
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/future/map.rs:55:37
  21: <F as futures_core::future::TryFuture>::try_poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.27/src/future.rs:82:9
  22: <futures_util::future::try_future::try_flatten::TryFlatten<Fut,<Fut as futures_core::future::TryFuture>::Ok> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/try_future/try_flatten.rs:49:61
  23: <hyper::common::lazy::Lazy<F,R> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/common/lazy.rs:69:28
  24: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/select.rs:118:35
  25: hyper::client::client::Client<C,B>::connection_for::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/client.rs:368:48
  26: hyper::client::client::Client<C,B>::send_request::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/client.rs:236:61
  27: hyper::client::client::Client<C,B>::retryably_send_request::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/client.rs:206:65
  28: <hyper::client::client::ResponseFuture as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-0.14.26/src/client/client.rs:623:9
  29: <reqwest::async_impl::client::PendingRequest as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.17/src/async_impl/client.rs:2126:53
  30: risingwave_common::telemetry::post_telemetry_report::{{closure}}
             at ./src/common/src/telemetry/mod.rs:136:9
  31: risingwave_common::telemetry::report::start_telemetry_reporting::{{closure}}::{{closure}}
             at ./src/common/src/telemetry/report.rs:111:59
  32: madsim::sim::task::Spawner::spawn_inner::{{closure}}::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/task/mod.rs:626:27
  33: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:455:26
  34: async_task::raw::RawTask<F,T,S,M>::run
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  35: madsim::sim::task::Executor::run_all_ready::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/task/mod.rs:268:50
  36: std::panicking::try::do_call
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/panicking.rs:485:40
  37: std::panicking::try
             at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/panicking.rs:449:19
  38: madsim::sim::task::Executor::run_all_ready
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/task/mod.rs:268:17
  39: madsim::sim::task::Executor::block_on
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/task/mod.rs:235:13
  40: madsim::sim::runtime::Runtime::block_on
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/runtime/mod.rs:126:9
  41: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at /Users/noelkwan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/madsim-0.2.21/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=5 "meta-2", task=129 (spawned at /Users/noelkwan/projects/risingwave/src/common/src/telemetry/report.rs:55:23)
note: run with `MADSIM_TEST_SEED=1` environment variable to reproduce this error
```

</details>

### To Reproduce

```
cargo make sslt-build-all --profile ci-sim
MADSIM_TEST_SEED=1 ./target/sim/ci-sim/risingwave_simulation --sqlsmith 100 ./src/tests/sqlsmith/tests/testdata
```

### Expected behavior

No error

**Comment by kwannoel** [comment]
Need to disable telemetry

**Comment by BugenZhao** [comment]
Can we disable telemetry by default if `debug_assertions` in on (while keeping the ability to enable it back)?
