### ISSUE TITLE
panicked at `distribution key [2] must be a subset of primary key []`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9815]
### Describe the bug

```
dev=> describe business_user_event;
       Name       |            Type             
------------------+-----------------------------
 XXX_user_id    | varchar
 event_type_id    | integer
 event_created_at | timestamp without time zone
 event_date       | varchar
 event_id         | varchar
 dw_creation_date | timestamp with time zone
 primary key      | _row_id
(7 rows)
```

```
dev=> select definition from pg_views where viewname = 'business_user_event_view';
definition                                                                                                                                                           
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
  DISTINCT ON (event_id) event_id, 
  XXX_user_id, 
  CAST((split_part(event_date, '/', 1) || '-' || split_part(event_date, '/', 2) || '-' || split_part(event_date, '/', 3)) AS TIMESTAMP) AS event_date, 
  event_type_id, 
  event_created_at, 
  dw_creation_date 
FROM business_user_event 
ORDER BY 
event_id, 
dw_creation_date ASC
```

```
dev=> describe completed_user_info;
dev-> 
         Name         |                  Type                   
----------------------+-----------------------------------------
 email                | varchar
 user_id              | varchar
 first_name           | varchar
 last_name            | varchar
 country              | varchar
 telegram             | varchar
 role                 | varchar
 company              | varchar
 company_size         | varchar
 company_homepage     | varchar
 category             | varchar
 title                | varchar
 subscribe_newsletter | boolean
 status               | varchar
 primary key          | email, business_user_info.XXX_user_id
(15 rows)
```

```
CREATE MATERIALIZED VIEW completed_user_info  AS
WITH user_table as (
    SELECT   
          XXX_user_id as user_id,
          email as user_email
    FROM business_user_info  
    WHERE lower(SPLIT_PART(SPLIT_PART(email, '@', 2), '.', 1)) != 'XXX'
),
applicant_table as (
    SELECT   
          XXX_user_id as applicant_id,
          email,
          first_name,
          last_name,
          country,
          telegram,
          role,
          company,
          company_size,
          company_homepage,
          category,
          title,
          subscribe_newsletter,
          status
    FROM business_applicant_info   
    WHERE lower(SPLIT_PART(SPLIT_PART(email, '@', 2), '.', 1)) != 'XXX'
)
SELECT email,
      COALESCE(user_id, applicant_id) as user_id,
      first_name,
      last_name,
      country,
      telegram,
      role,
      company,
      company_size,
      company_homepage,
      category,
      title,
      subscribe_newsletter,
      status
FROM applicant_table
LEFT JOIN user_table ON email = user_email
```

Panic when:
```
CREATE MATERIALIZED VIEW YYY as
SELECT event_date, 
      event_type_id, 
      XXX_user_id,
      email,
      first_name,
      last_name,
      country,
      telegram,
      role,
      company,
      company_size,
      company_homepage,
      category,
      title,
      subscribe_newsletter,
      status
FROM business_user_event_view 
LEFT JOIN completed_user_info ON XXX_user_id = user_id
```

```
thread 'risingwave-main' panicked at 'distribution key [2] must be a subset of primary key []', src/common/src/catalog/internal_table.rs:51:21
stack backtrace:
   0:     0x55737bc2156f - std::backtrace_rs::backtrace::libunwind::trace::h2ae08ac77e721453
                               at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55737bc2156f - std::backtrace_rs::backtrace::trace_unsynchronized::hb7d3015d68fe20ce
                               at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55737bc2156f - std::sys_common::backtrace::_print_fmt::h60e26e0e8c18d6ce
                               at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55737bc2156f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3b0d15c01f4c6ce1
                               at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5573768a420f - core::fmt::write::h53efc8feba3ef479
                               at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/fmt/mod.rs:1254:17
   5:     0x55737bc1bd93 - std::io::Write::write_fmt::h36688c4bf2bf4993
```

**Comment by st1page** [comment]
What does the SQL want to express with the `ORDER BY` clause? Does the writer want the view always maintain the Record with the topest `(event_id, dw_creation_date ASC)` value for each distinct `event_id`? 
```SQL
dev=> select definition from pg_views where viewname = 'business_user_event_view';
definition                                                                                                                                                           
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT 
  DISTINCT ON (event_id) event_id, 
  XXX_user_id, 
  CAST((split_part(event_date, '/', 1) || '-' || split_part(event_date, '/', 2) || '-' || split_part(event_date, '/', 3)) AS TIMESTAMP) AS event_date, 
  event_type_id, 
  event_created_at, 
  dw_creation_date 
FROM business_user_event 
ORDER BY 
event_id, 
dw_creation_date ASC
```

**Comment by lmatz** [comment]
i guess he used this SQL as a batch query to view the results on superset first, and then directly copy paste it as a view/MV.
